-- ============================================================
-- seed-industry-content-garden-services.sql
-- Industry content for Garden Services across all 11 services
-- Safe to re-run: uses ON CONFLICT ... DO UPDATE
-- ============================================================

-- 1. Garden Services x Web Design
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'garden-services',
  'web-design',
  'Garden service businesses operate across a spectrum from weekly lawn mowing rounds to full garden maintenance packages including hedge trimming, border work, leaf clearance, and seasonal planting. Your website needs to communicate this range while making it effortless for homeowners to book the specific services they need. Unlike one-off project trades, garden maintenance is a recurring relationship business. Your website must convert first-time visitors into regular customers by clearly presenting your service packages, pricing structure, and the areas you cover. It needs to showcase the difference between a neglected garden and one maintained by your team through seasonal photography showing spring lawn treatments, summer border displays, autumn clearances, and winter pruning results. Most garden service websites are basic one-page affairs with a phone number and a vague list of services. We build garden maintenance websites that let homeowners select their garden size, choose from clearly defined service packages, see indicative pricing, and book their first visit online, converting browsing homeowners into recurring monthly clients without a single phone call.',
  'Homeowners searching for garden maintenance want to know three things immediately: do you cover their area, what services do you offer, and roughly how much will it cost. A website that fails to answer these questions forces them to phone, and most will not bother. They will book with the competitor whose website provides clear service packages, transparent pricing, and an online booking option. For a recurring revenue business like garden maintenance, every lost website visitor represents months or years of ongoing revenue.',
  'We design garden service websites around the recurring booking model. Service package pages clearly outline what is included in weekly, fortnightly, and monthly maintenance visits. An interactive garden size estimator provides indicative pricing. Online booking captures garden details, access information, and preferred visit frequency. Seasonal galleries show your work across all four seasons.',
  '[{"title": "No clear service packages or pricing guidance", "description": "Homeowners considering regular garden maintenance want to understand what they will receive and approximately how much it will cost before making contact. A website listing lawn mowing, hedge trimming, and weeding without explaining how these combine into maintenance packages or providing any pricing indication loses visitors to competitors who present structured, transparent offerings."}, {"title": "No online booking for the modern homeowner", "description": "Busy professionals who want a gardener do not want to play phone tag. They research garden services in the evening, compare options, and want to book online. Without an online booking system that captures their garden size, required services, access details, and preferred schedule, you miss the growing segment of homeowners who expect to arrange services digitally."}, {"title": "No seasonal showcase demonstrating year-round capability", "description": "Garden maintenance is a year-round service, but most garden company websites show only summer photos. Without seasonal galleries demonstrating spring lawn treatments, summer border management, autumn leaf clearance, and winter pruning, homeowners assume your service is limited to grass cutting and do not consider you for the comprehensive maintenance package they actually need."}]',
  '[{"title": "Service package pages with clear inclusions and pricing", "description": "Structured pages presenting your maintenance packages: what is included in a basic lawn care visit versus a comprehensive garden maintenance package, how often each service is performed, and what seasonal work is covered. Indicative pricing based on garden size gives homeowners the cost transparency they need to make a decision. Each package page is designed to convert browsers into booking enquiries."}, {"title": "Online booking system with garden detail capture", "description": "A step-by-step booking form that captures garden size using a simple small, medium, or large selector with visual examples, required services, access arrangements including side gate codes and key safe details, preferred visit day and frequency, and any specific requirements. Homeowners book their first maintenance visit without a phone call, and you receive a complete brief before arriving."}, {"title": "Four-season portfolio showcasing year-round maintenance", "description": "Galleries organised by season showing the breadth of your maintenance work: spring lawn scarification and overseeding results, summer border planting and hedge shaping, autumn leaf clearance and garden tidying, and winter structural pruning and hard landscaping maintenance. This positions your business as a year-round garden partner rather than just a grass-cutting service."}]',
  '[{"question": "Should I show my pricing on the website?", "answer": "For garden maintenance services, indicative pricing significantly increases conversion rates. Homeowners expect transparency from recurring service providers. We recommend showing starting-from prices based on garden size categories rather than fixed quotes. This pre-qualifies visitors and ensures enquiries come from homeowners whose budget aligns with your rates."}, {"question": "Can the website handle recurring booking management?", "answer": "The booking system captures initial visit details and preferred schedule. For ongoing management, we integrate with scheduling tools that handle recurring appointments, route planning, and customer communication. The website serves as the entry point that converts new customers, while your operational systems manage the ongoing relationship."}, {"question": "How do I showcase seasonal work when I only have photos from summer?", "answer": "We start with your existing photography and build the seasonal gallery progressively. We provide a simple photo capture guide so your team photographs key seasonal work throughout the year: scarification in spring, hedge trimming in summer, leaf clearance in autumn, and pruning in winter. Within twelve months you have a comprehensive seasonal portfolio."}, {"question": "How long does a garden services website take to build?", "answer": "Most garden service websites launch within three to four weeks. The service package structure and booking system are prioritised for early launch. Seasonal galleries build over time as you capture work across different seasons. We launch with your strongest current photography and add seasonal content as it becomes available."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 2. Garden Services x SEO
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'garden-services',
  'seo',
  'When a homeowner searches for gardener near me or garden maintenance services in their local town, the results they see determine which companies receive their enquiry. For garden service businesses, SEO is particularly valuable because each new organic enquiry represents not a one-off job but potentially years of recurring monthly revenue. A single first-page ranking for lawn care services Maidstone could generate dozens of new regular customers annually, each worth hundreds of pounds per year in ongoing maintenance fees. The challenge is that garden services is a fragmented market where dozens of sole traders and small businesses compete locally, while national franchise operations like Fantastic Services and GreenThumb target the same keywords with substantial marketing budgets. Our SEO campaigns for garden maintenance companies target the full range of services homeowners search for: regular garden maintenance, lawn care and treatment, hedge trimming, seasonal clearances, and one-off garden tidying. Every keyword is mapped to location-specific pages covering the towns and villages where you operate, building a web of local relevance that Google rewards with consistent search visibility.',
  'Garden maintenance customers have high lifetime value. A homeowner who books a fortnightly maintenance visit at eighty pounds per visit represents nearly two thousand pounds in annual revenue, and the average garden maintenance customer stays for three to five years. Every first-page ranking position that generates a new recurring customer compounds in value over time. SEO is the highest-return marketing investment for any garden maintenance business because each lead generates ongoing revenue rather than a single project fee.',
  'Garden service SEO requires seasonal keyword planning because search demand shifts dramatically through the year. Lawn care searches peak in spring, hedge trimming in summer, leaf clearance in autumn, and garden tidying before Christmas. We build content and optimisation calendars aligned to these seasonal patterns, ensuring your pages rank in time for each demand surge rather than trailing behind.',
  '[{"title": "Invisible for garden maintenance searches in your service area", "description": "Homeowners searching for gardener near me, lawn mowing service, or garden maintenance in their specific town will contact the companies they find on the first page of results. If your website does not appear for these searches in every town you serve, potential long-term customers, each worth thousands in lifetime revenue, are booking with competitors who invested in local search visibility."}, {"title": "National franchise brands outranking local garden services", "description": "GreenThumb, Fantastic Services, and other national operators invest heavily in SEO to dominate garden service search results. These brands often charge premium prices and deliver impersonal service, yet they appear above local independents who provide better value and more personalised care. Without SEO investment, your website cannot compete with these corporate marketing budgets."}, {"title": "No seasonal content capturing cyclical search demand", "description": "Garden service searches follow strong seasonal patterns: lawn care peaks in March and April, hedge trimming in June and July, leaf clearance in October and November, and garden tidying before Christmas. Without content targeting these seasonal terms in advance, your website misses the surges in demand that drive new customer acquisition at the most opportune times of year."}]',
  '[{"title": "Service-specific pages targeting garden maintenance search terms", "description": "Dedicated, optimised pages for every service you offer: regular garden maintenance, lawn mowing and treatment, hedge trimming and reduction, border maintenance and seasonal planting, leaf and garden clearance, tree and shrub pruning, and one-off garden tidying. Each page targets the specific terms homeowners search for and includes your seasonal scheduling, service area, and indicative pricing to convert visitors into enquiries."}, {"title": "Location pages covering every town in your maintenance rounds", "description": "Individual pages for every town and village in your service area, each featuring the specific services available in that location and any completed project references. Garden maintenance Tonbridge, lawn care Sevenoaks, hedge trimming Maidstone: each combination captures local searches and builds your reputation as the established garden service provider in that area."}, {"title": "Seasonal content calendar aligned to search demand peaks", "description": "We plan and publish content months ahead of seasonal demand surges. Lawn care content is optimised and ranking by February for March search peaks. Hedge trimming content peaks in May for June demand. Autumn clearance pages are ready by September. This proactive approach ensures your website captures seasonal traffic when it matters most for new customer acquisition."}]',
  '[{"question": "How valuable is a single garden maintenance SEO lead?", "answer": "Extremely valuable because of recurring revenue. A homeowner who finds you through a Google search for gardener near me and books fortnightly maintenance at eighty to one hundred pounds per visit represents nearly two thousand pounds in first-year revenue and potentially eight to ten thousand pounds over a typical customer lifetime. Even a modest number of monthly organic leads translates to significant compounding revenue."}, {"question": "How long before SEO generates new garden maintenance customers?", "answer": "Most garden services see ranking improvements for specific town-plus-service terms within eight to twelve weeks. Terms like garden maintenance Faversham or lawn mowing Whitstable are typically less competitive than broader terms and deliver results faster. We focus on your core service area towns first to generate early results while building authority for more competitive broader terms."}, {"question": "Should I target lawn care and garden maintenance separately?", "answer": "Yes. Homeowners searching for lawn care and those searching for garden maintenance have different needs and intent. Lawn care searchers may want treatment services like scarification, overseeding, and fertilisation. Garden maintenance searchers typically want comprehensive ongoing care. Separate content strategies for each capture both audiences and their distinct service requirements."}, {"question": "How does seasonal SEO work for a garden services business?", "answer": "We plan content around the predictable seasonal search patterns. Lawn care and spring garden content is published in January and February to rank before March demand peaks. Summer hedge and border content is ready by April. Autumn clearance content publishes in August. This lead time ensures your pages are ranking when homeowners start searching for each seasonal service."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 3. Garden Services x Lead Capture
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'garden-services',
  'lead-capture',
  'Garden maintenance businesses have a unique lead capture advantage: every new customer represents recurring monthly revenue rather than a one-off project. This makes lead capture systems extraordinarily valuable because converting a single website visitor into a regular maintenance customer generates revenue that compounds over years. Yet most garden service websites offer nothing more than a phone number and a generic contact form. A homeowner browsing at nine in the evening, comparing garden maintenance companies, has no way to get an indicative price, understand what is included in your service packages, or book a consultation visit. Purpose-built lead capture for garden services guides homeowners through a garden assessment that captures their property size, current garden condition, required services, preferred visit frequency, and access arrangements. An indicative price calculator based on garden size and service level converts browsing into commitment. For one-off services like clearances and autumn tidying, separate lead paths capture the specific scope and timeline. Every enquiry arrives with the detail needed to schedule efficiently and quote accurately.',
  'Garden maintenance customers typically research several providers before choosing one. The decision is significant because they are committing to a recurring expense and regular access to their property. Without lead capture that provides immediate value through pricing guidance and service clarity, you rely on phone calls to convert interest into bookings. Most homeowners will not call three gardeners to compare. They will engage with the one whose website answers their questions and captures their requirements automatically.',
  'We build lead capture around the recurring service model. Maintenance enquiry forms capture garden size, condition, required services, and preferred frequency, then calculate indicative pricing. One-off service forms for clearances and tidying capture scope and photos. Seasonal prompt campaigns re-engage previous enquirers who did not convert, targeting the specific service period they originally searched for.',
  '[{"title": "Evening browsers leaving without any engagement", "description": "Most homeowners research garden services in the evening when they are not working. Without an interactive tool that provides immediate value, such as a garden maintenance price estimator or a service package comparison tool, these evening visitors compare your basic website against a competitor who provides instant pricing and online booking, and choose the path of least resistance."}, {"title": "No differentiation between maintenance and one-off service enquiries", "description": "A homeowner wanting ongoing weekly maintenance and someone needing a one-off garden clearance have completely different needs. A generic contact form treats both identically, capturing insufficient detail for either. The maintenance prospect needs to specify garden size and service frequency. The clearance customer needs to describe the scope and timeline. Without separate paths, both are underserved."}, {"title": "No system to re-engage enquiries that did not convert", "description": "A homeowner who enquired about garden maintenance in March but did not book may have been put off by the initial commitment or wanted to wait for better weather. Without a system to re-engage these warm leads when the season changes or when they are most likely to reconsider, this earlier interest is wasted entirely."}]',
  '[{"title": "Garden maintenance price estimator with service package selection", "description": "An interactive calculator where homeowners select their garden size from visual examples, choose their preferred service level from basic lawn care to comprehensive maintenance, indicate their preferred visit frequency, and receive an indicative monthly cost. This transparent pricing builds trust and converts browsers into enquiries with realistic budget expectations already set."}, {"title": "Separate lead paths for maintenance and one-off services", "description": "Maintenance enquiries capture garden size, current condition with optional photos, required services, preferred visit day and frequency, and access arrangements. One-off service enquiries for clearances, hedge reductions, and seasonal tidying capture the specific scope, urgency, and any access or waste removal considerations. Each path provides the information your team needs to schedule and price efficiently."}, {"title": "Seasonal re-engagement campaigns for unconverted leads", "description": "Homeowners who enquired but did not book receive targeted emails aligned to seasonal service periods. A spring email highlights lawn revival services. A summer email promotes hedge trimming and border maintenance. An autumn email offers garden clearance packages. These seasonal touchpoints re-engage prospects at the moment they are most likely to recognise the need for your services."}]',
  '[{"question": "How does the garden maintenance price estimator work?", "answer": "Homeowners select their garden size from visual categories showing typical small, medium, and large gardens. They choose their service level: basic lawn care only, standard maintenance including hedges and borders, or comprehensive care including seasonal planting and treatment. They select their preferred visit frequency. The estimator provides an indicative monthly cost based on your actual pricing structure while capturing their contact details and garden information."}, {"question": "Can lead capture help convert one-off customers into regular maintenance clients?", "answer": "Yes. When a homeowner books a one-off clearance or tidy-up, the system sends a follow-up sequence after the work is completed, offering a discounted first month of regular maintenance. This converts customers who have already experienced your quality into recurring clients, which is significantly easier than acquiring entirely new maintenance customers."}, {"question": "What information should a maintenance enquiry form capture?", "answer": "Garden size and type, current condition, required services such as lawn care, hedges, borders, and seasonal work, preferred visit frequency and day of week, access arrangements including gate codes or key safes, any specific requirements like pet safety or areas to avoid, and preferred contact method. This detail allows you to assess the enquiry, route plan efficiently, and provide an accurate quote."}, {"question": "How effective are seasonal re-engagement emails?", "answer": "Highly effective because they reach homeowners at the exact moment the need for your specific service is most apparent. A March email about spring lawn revival arrives when homeowners are looking at their patchy, moss-covered grass. An October email about leaf clearance arrives when gutters are blocking and lawns are disappearing under fallen leaves. This timing converts previous interest into current bookings."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 4. Garden Services x Business Automation
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'garden-services',
  'business-automation',
  'Garden maintenance businesses manage dozens or hundreds of recurring customer visits per week across a complex schedule that shifts with the seasons, the weather, and customer requests. A typical garden service running forty regular maintenance customers involves coordinating weekly and fortnightly visit schedules, adjusting routes when weather cancels a day''s work, communicating postponements and rescheduled visits, tracking which seasonal services are due at each property, invoicing monthly or per-visit, and chasing late payments. Most garden businesses manage all of this through a combination of a paper diary, WhatsApp messages, and memory, which breaks down as the customer base grows beyond what one person can track mentally. Business automation for garden services systematises the recurring operational complexity: automated visit confirmations sent to customers the day before, weather-triggered rescheduling notifications when rain cancels a maintenance day, seasonal service reminders when autumn clearance or spring lawn treatment is due, monthly invoicing generated automatically from completed visits, and payment chasing sequences that maintain cash flow without awkward conversations.',
  'The operational complexity of a garden maintenance business increases exponentially as customer numbers grow. Moving from thirty to sixty regular customers does not simply double the admin. It quadruples it because of the scheduling conflicts, weather rescheduling, seasonal service additions, and communication volume involved. Without automation, growth hits a ceiling where the business owner spends more time managing admin than actually maintaining gardens.',
  'Garden service automation is built around the recurring visit model and weather dependency. Visit scheduling syncs with weather forecasts, automatically flagging days likely to require rescheduling. Route optimisation groups customers geographically. Seasonal triggers prompt additional service offerings at appropriate times. Monthly invoicing calculates from completed visits with automatic adjustments for skipped or rescheduled appointments.',
  '[{"title": "Weather cancellations creating communication chaos", "description": "When rain cancels a day''s garden visits, you need to notify six to eight customers individually, reschedule their visits into an already packed week, and remember who has been pushed back and who is still waiting. Without automation, this weather rescheduling involves dozens of individual messages, constantly shifting diary entries, and the inevitable customer who gets missed and calls to complain about an overgrown lawn."}, {"title": "Seasonal service tracking across dozens of properties", "description": "Each customer''s garden needs different seasonal attention: lawn scarification in spring, hedge trimming at specific intervals, autumn leaf clearance, winter pruning of specific shrubs. Tracking which seasonal services are due at which property across forty or sixty customers is impossible manually. Services get missed, customers are disappointed, and upsell opportunities for additional seasonal work are lost."}, {"title": "Monthly invoicing consuming entire evenings", "description": "At the end of each month, you need to calculate what work was completed for each customer, adjust for any skipped visits due to weather or holidays, generate and send individual invoices, and then chase the ones that go unpaid. This invoicing process can take an entire evening or more for a business with fifty-plus regular customers, and delays mean delayed cash flow."}]',
  '[{"title": "Weather-aware scheduling and automatic rescheduling", "description": "The system monitors weather forecasts for your service area and flags days with high rainfall probability. When you confirm a weather cancellation, automated messages notify all affected customers with their rescheduled visit date based on the next available slot in your route. Customers receive professional communication within minutes, and your diary automatically adjusts without manual intervention for each individual customer."}, {"title": "Seasonal service triggers and upsell prompts", "description": "The system tracks each property''s seasonal service calendar and sends you reminders when specific work is due: lawn scarification windows in March, hedge trimming schedules from May, autumn clearance periods from October, and winter pruning from November. Customer-facing messages offer these seasonal services at the appropriate time, generating additional revenue from your existing maintenance base without manual sales effort."}, {"title": "Automated monthly invoicing from completed visit records", "description": "When you log a completed visit via a simple mobile action, the system records the work done. At month end, invoices are automatically generated for each customer reflecting their actual completed visits, adjusted for any weather cancellations or holiday skips. Invoices are sent automatically, and payment chasing sequences follow for any that remain unpaid, keeping your cash flow steady without manual administration."}]',
  '[{"question": "Can automation handle my complex weekly and fortnightly schedules?", "answer": "Yes. The system manages customers on different visit frequencies: weekly, fortnightly, and monthly. It handles the scheduling complexity where fortnightly customers alternate weeks, routes are optimised geographically, and visit days flex when weather or bank holidays disrupt the normal schedule. You see a clear daily work list with optimised routing rather than managing a complex diary manually."}, {"question": "How does weather rescheduling work in practice?", "answer": "You check the forecast and decide to cancel a day''s visits. With one action, the system notifies all affected customers with a professional message explaining the weather postponement, assigns their rescheduled visit to the next available day in your route for their area, and updates your diary automatically. Customers appreciate the proactive communication, and you avoid the chaos of individually messaging each one."}, {"question": "Can the system handle different service packages for different customers?", "answer": "Absolutely. Each customer profile records their specific service package: lawn only, lawn and hedges, comprehensive maintenance, or a custom combination. Visit records track which services were performed, and invoicing reflects the agreed package price. When a customer upgrades from basic to comprehensive maintenance, the system updates their pricing and service checklist accordingly."}, {"question": "How does automated invoicing handle skipped visits?", "answer": "When a visit is skipped due to weather, customer holiday, or any other reason, the system logs the skip. Monthly invoices automatically adjust to reflect only completed visits. If you charge a fixed monthly rate regardless of visit count, the system tracks this too. Customers see transparent, accurate invoices that build trust in your billing process."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 5. Garden Services x Branding
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'garden-services',
  'branding',
  'Garden service businesses visit the same residential streets week after week, with branded vehicles, uniformed teams, and equipment trailers visible to every neighbour for the duration of each visit. This repeated local visibility makes branding exceptionally powerful for garden maintenance companies. Your van parked outside a well-maintained garden is an endorsement of your work that every passing homeowner sees. Your team trimming hedges or mowing lawns in branded workwear signals a professional operation to everyone on the street. A garden gate sign reading Maintained by Your Company Name turns every customer''s garden into a permanent advertisement. Professional branding for garden services creates a visual identity system that maximises this inherent visibility: vehicle graphics that communicate garden care professionalism, crew uniforms that look smart while being practical for physical outdoor work, customer garden signs that generate neighbour enquiries, and printed materials including seasonal service flyers and maintenance tips cards that keep your name on the kitchen noticeboard. For a business that operates in public view every working day, branding investment pays for itself through the sheer volume of impressions it generates.',
  'Garden maintenance is one of the most visible recurring trades. Unlike a plumber who visits once, your team appears on residential streets weekly or fortnightly for years. Every visit is seen by neighbours, dog walkers, and passing drivers. Unbranded teams in random clothing look like casual labourers, which undermines homeowner confidence and fails to generate the neighbour referrals that drive garden service growth. Professional branding transforms your routine visibility into a continuous marketing presence.',
  'We design garden service brands for maximum outdoor visibility and durability. Vehicle graphics use nature-inspired colour palettes with bold, readable company names. Crew workwear is designed for comfort during physical garden work while maintaining a smart, professional appearance. Customer garden signs are weather-resistant and designed with subtle branding that homeowners are happy to display.',
  '[{"title": "Vehicles and crews generating zero brand awareness despite weekly visibility", "description": "Your van and team are visible on residential streets five or six days per week, yet if they carry no branding, this enormous marketing opportunity is completely wasted. A plain van and unbranded crew maintaining a beautiful garden generate no recognition, no enquiries, and no competitive advantage. Neighbours who might enquire have no idea who is responsible for the excellent work they see weekly."}, {"title": "No customer garden signs converting neighbour interest into enquiries", "description": "Every garden you maintain is a living advertisement for your services. Neighbours walking past a beautifully maintained garden notice and admire the work, but without a subtle branded sign at the garden boundary, they have no way to identify or contact your company. This simple branding touchpoint converts passive admiration into active enquiries more effectively than any digital marketing."}, {"title": "Crew appearance undermining the quality of garden work", "description": "A beautifully maintained garden paired with a scruffy crew in mismatched clothing creates a contradictory impression. The homeowner whose garden you maintain and the neighbours who observe your team both form judgements based on appearance. Branded, smart workwear that is practical for mowing, hedging, and planting reinforces the quality and professionalism of your garden maintenance."}]',
  '[{"title": "Vehicle branding designed for residential street impact", "description": "Van and trailer graphics using fresh, nature-inspired colour palettes with your company name in bold, readable typography. Vehicle graphics are designed for visibility at street-parking distance, featuring your service types and phone number. For businesses with multiple vehicles, consistent fleet branding creates the impression of an established, scaled operation that homeowners trust with ongoing garden care."}, {"title": "Customer garden signs generating passive referrals", "description": "Discrete, weather-resistant signs designed for garden gate posts or border edges reading Maintained by Your Company Name with your phone number or website. These signs are offered free to customers and generate a steady stream of neighbour enquiries from homeowners who see the quality of your maintenance and want the same for their garden. Each sign is a permanent, zero-cost lead generation tool."}, {"title": "Practical branded workwear for outdoor garden work", "description": "Branded polo shirts, softshell jackets, and waterproof layers designed for the physical demands of garden maintenance: comfortable during mowing and hedge trimming, breathable during summer work, and waterproof for the days you work through drizzle. Embroidered branding withstands daily wear, mud, and grass staining while maintaining a professional appearance that customers and neighbours notice."}]',
  '[{"question": "How effective are garden maintenance customer signs for generating referrals?", "answer": "Extremely effective. Garden service businesses consistently report that customer garden signs are their single most cost-effective marketing tool. A well-maintained garden with a branded sign is seen by neighbours daily, and the quality of your work does the selling. Many garden services attribute thirty to fifty percent of their new customer enquiries to neighbours seeing their signs and calling directly."}, {"question": "What kind of workwear is practical for garden maintenance crews?", "answer": "We supply branded polo shirts in breathable fabrics for summer, softshell jackets for spring and autumn, and waterproof layers for wet weather work. All items are embroidered rather than printed, ensuring branding survives repeated washing. Colours are chosen to look professional on residential streets while being practical for the inevitable grass stains, mud, and hedge clippings of daily garden work."}, {"question": "Can you brand equipment trailers as well as vans?", "answer": "Yes. For garden services with equipment trailers, branded graphics on trailer sides represent significant additional advertising as the trailer is visible from both sides when parked on residential streets. Trailer branding typically includes your company name, phone number, website, and a visual element that communicates professional garden care. The trailer becomes a large advertising board positioned on your customers'' streets."}, {"question": "How do I convince customers to display a garden sign?", "answer": "Most customers are happy to display a small, tasteful sign acknowledging your work, especially when framed as a compliment to their garden. We design signs that are attractive enough that homeowners see them as an enhancement rather than an advertisement. Offering a modest discount or a free seasonal treatment in exchange for sign placement increases uptake further."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 6. Garden Services x Social Media Setup
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'garden-services',
  'social-media-setup',
  'Garden maintenance is one of the most naturally social media-friendly trades. Beautiful lawns with crisp striped mowing patterns, neatly trimmed box hedges, colourful seasonal borders, and dramatic before-and-after garden clearances are exactly the visual content that generates engagement on Facebook and Instagram. The seasonal nature of garden work provides a natural content rhythm: spring lawn revival posts, summer border displays, satisfying autumn leaf clearance transformations, and winter structural pruning results. Yet most garden service businesses either have no social presence or post irregularly with low-quality photos and no strategy. We set up and optimise your Facebook and Instagram profiles specifically for the garden maintenance industry, create content templates for the types of posts that drive engagement and enquiries, establish a seasonal content calendar aligned to the gardening year, and build a simple capture system so your team photographs their best work during every maintenance round without disrupting the working day.',
  'Homeowners follow local garden service pages on Facebook because they enjoy seeing beautiful gardens and seasonal transformations. This passive following becomes active enquiry when they realise their own garden needs attention and your company is already familiar and trusted through consistent social content. Garden service social media builds a local audience of homeowners who become customers when the need arises, creating a pipeline of warm leads that costs almost nothing to maintain.',
  'We set up garden service profiles with seasonal content structures. Profile highlights are organised by season and service type. Content templates cover stripe-pattern lawn showcases, hedge trimming reveals, before-and-after clearance transformations, and seasonal gardening tips. A simple crew photo guide ensures your team captures content during routine visits without slowing down their work.',
  '[{"title": "Beautiful garden work going unseen beyond the customer''s street", "description": "Every week your team creates beautiful results: striped lawns, shaped hedges, colourful borders, and cleared gardens. Without social media, these results are seen only by the homeowner and their immediate neighbours. The hundreds of local homeowners who might become customers never see your work, never build familiarity with your brand, and never think of you when they need garden maintenance."}, {"title": "No seasonal content strategy despite naturally seasonal work", "description": "Garden maintenance follows a perfect seasonal content rhythm that most businesses fail to exploit. Spring lawn revival, summer flowering borders, autumn colour and clearance, winter structural gardens: each season offers compelling visual content that resonates with homeowners experiencing the same seasonal changes in their own gardens. Without a seasonal strategy, this natural content advantage is wasted."}, {"title": "Inability to capture consistent content during busy working days", "description": "Your team visits ten to fifteen gardens per day during peak season. Without a simple system for photographing their best work as they go, content creation becomes an additional burden that never gets done. By the end of a busy day, the crew is tired and the beautifully maintained gardens have been left behind. Your phone gallery fills with personal photos instead of marketing assets."}]',
  '[{"title": "Seasonal profile setup with garden service optimisation", "description": "We configure your Facebook and Instagram profiles as local garden service discovery tools: business category set to garden maintenance, service area defined, bio text targeting local garden care searches, and cover images rotating seasonally to showcase your current best work. Highlight categories organise your portfolio by service type: lawn care, hedge work, border planting, clearances, and seasonal transformations."}, {"title": "Before-and-after and seasonal content templates", "description": "Branded templates for your highest-performing content types: dramatic before-and-after clearance transformations, satisfying lawn stripe showcases, hedge trimming precision posts, seasonal border displays, and customer garden features. Each template requires only a crew phone photo to produce a professional, branded social post that drives engagement and positions your business as the local garden care authority."}, {"title": "Crew photo capture system and seasonal content calendar", "description": "A simple guide for your maintenance team to capture one or two photos per day of their best work using their phones. Photos are sent to a shared album and turned into posts using your branded templates. A seasonal content calendar ensures regular posting aligned to the gardening year: lawn care content in spring, hedge and border content in summer, clearance content in autumn, and planning content in winter."}]',
  '[{"question": "What garden service content gets the most engagement on social media?", "answer": "Before-and-after clearance transformations consistently generate the highest engagement because the contrast is dramatic and relatable. Satisfying lawn stripe photos perform well, especially in spring when homeowners are looking at their own patchy grass. Hedge trimming precision posts attract admiration. Seasonal flower border displays generate shares from gardening enthusiasts. All of this content is produced naturally during your routine maintenance work."}, {"question": "Which social media platforms work best for garden services?", "answer": "Facebook is primary because it reaches the homeowner demographic, supports local community group engagement, and allows neighbourhood-level targeting. Instagram is excellent for visual garden content and attracts a slightly younger homeowner audience. We set up both platforms but focus Facebook for local lead generation and Instagram for portfolio building and brand awareness."}, {"question": "How do I get my crew to take photos during maintenance visits?", "answer": "We design a minimal-effort system. One quick before photo when arriving at a garden that looks particularly impressive once maintained, and one after photo from a similar angle when the work is done. The photos are sent to a shared folder. We turn the best ones into branded posts. The entire process adds less than thirty seconds per property to the crew''s routine."}, {"question": "How often should a garden service post on social media?", "answer": "Three to four posts per week is ideal during peak growing season when content is abundant from daily maintenance rounds. During winter, two posts per week using pruning work, planning content, and throwback seasonal photos maintains visibility. The seasonal nature of garden work naturally provides more content during the periods when homeowners are most likely to be searching for garden maintenance."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 7. Garden Services x Digital Marketing
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'garden-services',
  'digital-marketing',
  'Digital marketing for garden services must account for the seasonal demand cycles that define the industry. Enquiries for regular maintenance surge in March and April as homeowners emerge from winter and face overgrown gardens. Hedge trimming demand peaks in early summer. Autumn clearance requests spike in October and November. One-off tidying requests increase before Christmas and Easter when visitors are expected. A digital marketing strategy that treats all months equally wastes budget in quiet periods and underspends during peak acquisition windows. Our approach aligns every marketing channel to the garden maintenance calendar: Google Ads campaigns targeting garden maintenance near me with increased budgets during spring surge, Facebook campaigns showcasing seasonal before-and-after transformations to local homeowner audiences, email nurture sequences re-engaging previous enquiries at the seasonal moment they are most likely to convert, and retargeting campaigns keeping your brand visible to website visitors who compared garden services but did not yet commit to a provider.',
  'Garden maintenance is a recurring revenue business where the cost of customer acquisition is justified by years of ongoing monthly payments. This makes digital marketing uniquely cost-effective for garden services because each conversion generates compounding revenue. A Google Ads campaign that spends fifty pounds to acquire a new regular maintenance customer generating one hundred pounds per month has paid for itself within the first visit and continues generating revenue for years.',
  'We structure garden service marketing campaigns around the seasonal acquisition calendar. Spring campaigns target new maintenance sign-ups when motivation is highest. Summer campaigns promote additional services to existing and prospective customers. Autumn campaigns target clearance and tidying services. Winter campaigns nurture warm leads for spring commencement. Each seasonal phase has specific channel strategies and budget allocations.',
  '[{"title": "Flat marketing spend ignoring seasonal demand surges", "description": "Most garden service businesses spend the same amount on marketing every month, missing the opportunity to capture significantly more customers during peak demand periods. March and April represent the golden acquisition window when homeowners are most motivated to sign up for regular maintenance. Without concentrated marketing during these weeks, you lose the year''s best acquisition opportunity to competitors who surge their spend."}, {"title": "No retargeting for comparison shoppers who did not convert", "description": "Homeowners considering regular garden maintenance often visit multiple websites before committing. Without retargeting, a visitor who spent five minutes on your service packages page and left to check a competitor has no reason to return. Retargeting keeps your brand, your garden photos, and your service packages visible during their comparison process."}, {"title": "One-off service marketing disconnected from maintenance upselling", "description": "Many homeowners first engage with a garden service for a one-off clearance or autumn tidy-up. Without a marketing system that converts these one-off customers into regular maintenance clients, you repeatedly acquire the same customer for individual jobs rather than converting them into the recurring revenue stream that builds a sustainable business."}]',
  '[{"title": "Seasonal Google Ads with budget surge for spring acquisition", "description": "Google Ads campaigns targeting garden maintenance, gardener near me, and lawn care services with budgets that increase fifty to one hundred percent during March and April to capture peak spring demand. Ad copy shifts seasonally: spring emphasises new maintenance packages, summer promotes hedge and border services, autumn focuses on clearance packages. Each seasonal campaign has dedicated landing pages aligned to the current service offering."}, {"title": "Social media seasonal showcasing and retargeting", "description": "Facebook and Instagram campaigns showcasing your best seasonal work to homeowner audiences in your service area. Spring posts feature lawn revival transformations. Summer content shows border displays and hedge precision. Autumn campaigns showcase dramatic clearance transformations. Retargeting ensures homeowners who visited your website without booking continue seeing your work throughout their decision process."}, {"title": "One-off to maintenance conversion campaigns", "description": "Customers who book one-off clearances, autumn tidying, or spring garden preparation receive targeted follow-up campaigns offering a discounted first month of regular maintenance. These campaigns convert single-transaction customers into recurring revenue clients at a fraction of the cost of acquiring a completely new maintenance customer, dramatically improving lifetime customer value."}]',
  '[{"question": "How much should a garden service spend on digital marketing?", "answer": "Most garden services see strong returns from five hundred to twelve hundred pounds per month, with budget concentrated during the spring acquisition surge. The recurring revenue model means a single new maintenance customer can justify the entire month''s marketing spend within two or three visits. We recommend front-loading annual marketing budget into March and April when customer acquisition rates are highest."}, {"question": "Is Google Ads cost-effective for garden maintenance leads?", "answer": "Extremely, because of the recurring revenue model. A garden maintenance click might cost two to five pounds, and you might need ten clicks to generate one enquiry. Even at fifty pounds per lead, a regular maintenance customer paying one hundred pounds per month represents a return on investment that compounds over years. Few other trades enjoy this acquisition cost to lifetime value ratio."}, {"question": "How do you convert one-off clearance customers into regular clients?", "answer": "After completing a one-off service, automated follow-up sequences showcase the benefits of regular maintenance: consistently beautiful results, seasonal care handled automatically, and preferential scheduling for existing clients. A discounted first month of regular maintenance provides the incentive to commit. This approach typically converts fifteen to twenty-five percent of one-off customers into recurring maintenance clients."}, {"question": "When is the best time to advertise garden maintenance services?", "answer": "Late February through April is the primary acquisition window. Homeowners look at their gardens after winter, realise they need help, and actively search for maintenance providers. A secondary window opens in September and October as autumn clearance demand creates opportunities to convert seasonal customers into year-round maintenance clients. Summer and winter are lower-intensity maintenance periods for your existing client base."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 8. Garden Services x Workwear & Print
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'garden-services',
  'workwear-print',
  'Garden maintenance crews are the most visible recurring trade presence on residential streets. Unlike tradespeople who visit once, your team appears on the same streets every week, year after year, working outdoors where everyone can see them. The impression they create determines whether neighbours enquire about your services or assume you are a casual cash-in-hand operation. Branded workwear that is practical enough for mowing, hedge trimming, and border work while maintaining a professional appearance turns your crew into walking advertisements on every street they serve. Printed materials amplify this presence: professional business cards handed to curious neighbours, seasonal service flyers dropped through letterboxes during maintenance rounds, customer garden maintenance tip cards that keep your brand on the kitchen noticeboard, and property signs that identify your work to passers-by. For a garden service visiting forty to sixty properties per week across multiple residential streets, the cumulative marketing impact of branded teams and print materials is enormous.',
  'Your crew is visible on residential streets for hours every day, five or six days per week. This is more sustained public visibility than almost any other trade. Unbranded crews generate zero marketing value from this exposure. Branded crews create recognition, familiarity, and trust across every neighbourhood you serve. The compound effect of weekly branded visibility drives a steady stream of referral enquiries from homeowners who have watched your team working to a high standard.',
  'We supply workwear designed for the physical demands of garden maintenance: fabrics that resist grass stains, mud, and thorns while remaining presentable on residential streets. Embroidered branding withstands industrial washing. Print materials include seasonal service flyers for letterbox drops during rounds, customer tip cards, and property maintenance signs.',
  '[{"title": "Crews visible on streets weekly but generating no brand recognition", "description": "Your team visits the same streets every week, working outdoors in full view of neighbours and passers-by. In plain clothing, they are invisible as a brand. Neighbours watch someone mow a lawn and trim a hedge but have no idea which company they work for. This weekly visibility, potentially seen by hundreds of local homeowners, generates precisely zero marketing value without branded workwear."}, {"title": "No printed materials to capitalise on neighbour curiosity during visits", "description": "When your team is working on a garden, neighbours notice and sometimes approach to ask about your services. Without professional business cards to hand over and seasonal flyers to leave through nearby letterboxes, these casual enquiries rely on memory and verbal information sharing, and most are forgotten by the time the homeowner reaches their phone."}, {"title": "Seasonal service promotions not reaching your existing customer base", "description": "Your existing maintenance customers are the easiest audience to sell additional seasonal services: autumn clearance packages, spring lawn treatment, hedge reduction, and one-off deep garden tidying. Without printed seasonal service flyers or cards left with customers during visits, these upsell opportunities depend on verbal conversations that get interrupted by the demands of the working day."}]',
  '[{"title": "Durable branded workwear for outdoor garden maintenance", "description": "Branded polo shirts in breathable, quick-drying fabrics for summer work, softshell jackets for spring and autumn, and waterproof layers for wet weather maintenance. All items are embroidered for maximum durability through repeated washing. Colours are selected to look professional against garden backgrounds while being practical for the inevitable grass stains, soil, and hedge clippings of daily work."}, {"title": "Seasonal service flyers and neighbour introduction cards", "description": "Professional flyers designed for letterbox drops during maintenance rounds, featuring seasonal service highlights: spring lawn revival packages, summer hedge and border services, autumn clearance deals, and winter garden preparation. Neighbour introduction cards for streets where you have existing customers, highlighting your local presence and offering a new customer discount. These turn every maintenance round into a targeted marketing campaign."}, {"title": "Customer maintenance tip cards and service reminder materials", "description": "Branded cards left with customers containing seasonal garden care tips, watering guidance, and reminders about upcoming seasonal services. These practical materials keep your brand on the kitchen noticeboard or in the garden shed, reinforce your expertise, and prompt customers to book additional services as each season approaches."}]',
  '[{"question": "What workwear fabric works best for garden maintenance?", "answer": "We supply polyester-cotton blends that resist grass staining, dry quickly after rain exposure, and maintain colour through industrial washing. For summer work, lightweight moisture-wicking polo shirts keep crews comfortable during physical mowing and hedging. For cooler months, softshell jackets provide warmth and wind resistance while allowing free movement for operating equipment."}, {"question": "How effective are neighbour flyer drops during maintenance rounds?", "answer": "Extremely effective because they reach homeowners on streets where you are already visibly working. The neighbour sees your branded team maintaining a beautiful garden, then finds a professional flyer through their letterbox offering the same service with a local customer reference. This combination of visual evidence and targeted marketing consistently generates the highest quality garden maintenance enquiries."}, {"question": "How many sets of workwear does a garden maintenance crew member need?", "answer": "We recommend five sets of branded polo shirts per crew member for daily rotation, plus three softshell jackets and two waterproof outer layers. Garden maintenance is physically demanding and workwear gets dirty daily, so sufficient rotation ensures your crew always looks professional. We provide volume pricing for crew outfitting and maintain your embroidery design on file for easy reordering."}, {"question": "Can you produce property signs identifying our maintenance work?", "answer": "Yes. We produce weather-resistant garden signs in various sizes, from small border-edge signs to larger gate-post signs. Designs include your company name, contact details, and an optional QR code linking to your website. Signs are offered to customers as a value-add, and most homeowners are happy to display a tasteful sign acknowledging the professional care their garden receives."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 9. Garden Services x AI Chatbots
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'garden-services',
  'ai-chatbots',
  'Garden maintenance enquiries are typically straightforward but time-consuming to handle personally: homeowners want to know if you cover their area, what is included in your service packages, how much regular maintenance costs for their garden size, and when you can start. These same five or six questions are asked by every new prospect, consuming hours of phone time each week. An AI chatbot trained on your garden maintenance business handles these enquiries instantly, walking homeowners through your service area coverage, package options, and pricing based on their garden size and requirements. It captures their property details, preferred visit frequency, and access arrangements, creating a qualified lead that you can follow up with a specific proposal rather than starting from scratch on a phone call. For existing customers, the chatbot handles visit rescheduling requests, seasonal service enquiries, and communication about upcoming maintenance, reducing the back-and-forth messaging that accumulates as your customer base grows.',
  'Garden maintenance businesses lose enquiries because the owner is operating a mower, strimmer, or hedge trimmer for most of the working day and cannot answer the phone. By the time you return calls in the evening, the homeowner has booked with a competitor who answered immediately. An AI chatbot engages every visitor instantly, provides the service and pricing information they need, and captures their details while you are focused on the maintenance work that generates your current revenue.',
  'We train your chatbot on your service area, maintenance packages, pricing structure by garden size, availability, and seasonal service calendar. It knows which towns and postcodes you cover, what is included in each service level, how your pricing scales with garden size, and which seasonal services are currently available. For existing customers, it can handle rescheduling requests and seasonal booking enquiries.',
  '[{"title": "Missing enquiries while operating garden equipment all day", "description": "You cannot answer your phone while operating a mower, hedge trimmer, or leaf blower. During peak season, you might miss six to ten calls per day from potential new customers and existing clients. By evening, half of the new enquiries have already booked elsewhere, and you face an hour of return calls to handle questions that could have been answered instantly by an AI assistant."}, {"title": "Same service and pricing questions consuming hours weekly", "description": "Every prospective customer asks: do you cover my area, what services are included, how much does it cost for a medium garden, and when can you start. Answering these identical questions fifteen to twenty times per week by phone consumes significant time that could be spent on billable maintenance work. The information is entirely predictable and could be delivered instantly by a trained chatbot."}, {"title": "Existing customer communication growing unmanageable", "description": "As your customer base grows beyond thirty or forty regulars, the volume of routine communication becomes overwhelming: visit rescheduling requests, holiday notifications, seasonal service queries, and billing questions. Each message requires a personal response, and the accumulated communication burden threatens to consume every evening."}]',
  '[{"title": "Service and pricing chatbot for new customer enquiries", "description": "The chatbot checks postcode coverage, walks prospects through your service packages from basic lawn care to comprehensive maintenance, calculates indicative monthly pricing based on garden size and visit frequency, and captures their property details, access arrangements, and preferred start date. You receive a complete new customer brief ready for scheduling rather than a vague enquiry requiring a lengthy phone conversation."}, {"title": "Existing customer communication assistant", "description": "Current customers can request visit rescheduling, notify you of upcoming holidays when they do not need service, enquire about additional seasonal services, and ask about their upcoming visit schedule. The chatbot handles these routine interactions, updates your scheduling system, and only escalates unusual requests to you personally. This dramatically reduces the evening communication burden as your customer base grows."}, {"title": "Seasonal service promotion through chatbot conversations", "description": "During seasonal transitions, the chatbot proactively suggests relevant additional services to visiting prospects and existing customers. In spring, it highlights lawn scarification and treatment. In summer, it promotes hedge trimming packages. In autumn, it offers clearance services. This conversational upselling generates additional revenue from enquiries you are already handling."}]',
  '[{"question": "Can the chatbot handle different pricing for different garden sizes?", "answer": "Yes. The chatbot asks homeowners to describe or estimate their garden size using visual examples or approximate dimensions. Based on their response, it calculates indicative pricing from your rate card, distinguishing between small urban gardens, medium suburban gardens, and larger properties. Pricing is presented as indicative and subject to a visit assessment, managing expectations while giving prospects the cost information they need to proceed."}, {"question": "How does the chatbot handle existing customer rescheduling?", "answer": "Existing customers can identify themselves by name or address and request that their upcoming visit be rescheduled due to garden parties, building work, holidays, or other reasons. The chatbot logs the request, confirms the next available slot based on your route schedule, and notifies you of the change. This eliminates the back-and-forth messaging that would otherwise require your personal attention."}, {"question": "Will the chatbot know my exact service area and coverage?", "answer": "We configure the chatbot with your precise service area boundaries by postcode. When a homeowner provides their location, the chatbot immediately confirms whether you cover their area. If they are outside your range, it politely explains your geographic limitations. This prevents wasted time on enquiries from areas you do not serve."}, {"question": "Can the chatbot capture enough detail for me to schedule a new customer efficiently?", "answer": "The chatbot captures property address, garden size estimate, required services, preferred visit day and frequency, access arrangements including gate codes or key safe locations, any specific requirements like pet awareness or restricted areas, and the homeowner''s preferred contact method. This level of detail allows you to assess the property, plan routing, and provide a proposal without a preliminary phone call."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 10. Garden Services x AI Content
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'garden-services',
  'ai-content',
  'Content marketing for garden services has natural advantages because homeowners constantly search for seasonal gardening advice, lawn care tips, and maintenance guidance. Searches like when to scarify a lawn, how often should hedges be trimmed, best time to plant spring bulbs, and how to get rid of moss in grass represent thousands of monthly queries from homeowners who are either potential maintenance customers or existing customers who might benefit from additional services. AI-powered content creation generates the seasonal guides, lawn care articles, planting calendars, and maintenance tip pieces that capture this organic search traffic and position your company as the local gardening authority. Each piece is trained on your specific services, the garden conditions typical in your Kent service area, and the seasonal calendar that governs your maintenance schedule. The content reads like practical advice from an experienced gardener, not like a generic home improvement article, and every piece naturally connects to the services you provide.',
  'Garden-related searches peak seasonally with predictable patterns: lawn care in spring, hedge and border content in summer, clearance and tidying in autumn, and planning content in winter. A steady stream of published content aligned to these patterns captures organic traffic year-round from homeowners who need exactly the services you provide. Each article builds your website''s authority for garden maintenance keywords and drives prospects toward your booking system.',
  'We train AI content on your specific services, the growing conditions and soil types typical of Kent gardens, and the seasonal maintenance calendar you follow. Content targets the practical questions homeowners ask throughout the gardening year, from when to first mow in spring to how to prepare borders for winter. Every article connects naturally to the relevant maintenance service you offer.',
  '[{"title": "No time to create content between daily maintenance rounds", "description": "You know more about lawn care schedules, hedge trimming timing, and seasonal border management than any content writer, but you spend your days operating mowers, strimmers, and hedge cutters across a packed maintenance schedule. The seasonal guides, lawn care tips, and maintenance articles that would drive organic traffic to your website simply never get written because content creation cannot compete with the daily demands of serving forty or sixty customers."}, {"title": "Generic gardening websites capturing your local search traffic", "description": "When a homeowner in your area searches for when to scarify a lawn in Kent, national gardening sites and generic advice platforms capture that traffic. Without your own locally relevant content addressing the specific growing conditions, soil types, and climate of your service area, these searches drive visitors to websites that have no connection to the maintenance services you provide."}, {"title": "Seasonal content opportunities missed year after year", "description": "Every season presents content opportunities perfectly aligned to your services: spring lawn revival guides when homeowners notice their tired grass, summer border care when gardens are in full view, autumn garden preparation when leaves are falling, and winter planning content when homeowners are thinking ahead. Without consistent seasonal publishing, these recurring opportunities to attract new customers are wasted annually."}]',
  '[{"title": "Seasonal garden care guides targeting homeowner searches", "description": "AI-generated comprehensive guides for every season: spring lawn revival including scarification timing and overseeding advice, summer hedge trimming schedules and border maintenance, autumn garden clearance checklists and lawn preparation, and winter pruning guides for common Kent garden shrubs and trees. Each guide targets specific search terms homeowners use and naturally connects to the relevant maintenance services you offer."}, {"title": "Lawn care content capturing high-volume search traffic", "description": "Dedicated lawn care content targeting the most searched gardening topics: how to get rid of moss in grass, when to start mowing in spring, lawn scarification timing and techniques, dealing with dry patches in summer, and autumn lawn preparation. These high-volume search terms drive significant traffic from homeowners who are ideal candidates for regular lawn maintenance services."}, {"title": "Local gardening content specific to Kent growing conditions", "description": "AI generates content addressing the specific gardening conditions of your service area: clay soil management in the Weald, coastal garden challenges in Thanet and Dover, chalk grassland maintenance in the North Downs, and drought-resistant planting for Kent''s changing climate. This locally specific content outperforms generic national gardening advice for local searches and positions you as the expert who understands gardens in your area."}]',
  '[{"question": "Will AI-generated gardening content be accurate for my local area?", "answer": "We train the AI on the specific growing conditions of your Kent service area, including soil types, typical rainfall patterns, coastal influences where relevant, and the seasonal timing that affects your maintenance schedule. Content is reviewed before publishing for horticultural accuracy and local relevance. The articles reflect practical experience with gardens like those you actually maintain."}, {"question": "What types of garden content generate the most enquiries?", "answer": "Seasonal timing guides generate the highest enquiry conversion because they reach homeowners at the exact moment they are thinking about garden maintenance. A homeowner reading your guide on when to scarify a lawn in Kent who realises they lack the time or equipment to do it themselves is a highly qualified prospect for your lawn care service. Problem-solving content like dealing with moss or patchy grass also converts well."}, {"question": "How many pieces of garden content should I publish per month?", "answer": "We recommend four to six pieces monthly aligned to the current and upcoming season. During spring, content focuses on lawn care, border preparation, and maintenance package promotion. Summer content covers hedge timing, border maintenance, and drought management. Autumn and winter content shifts to clearance, pruning, and planning. This seasonal rhythm matches homeowner search patterns naturally."}, {"question": "Can content help me sell additional seasonal services to existing customers?", "answer": "Yes. Content shared with your existing customer base through email or social media educates them about seasonal services they may not have considered. An autumn scarification article sent to your lawn care customers generates requests for the service. A spring hedge shaping guide prompts customers to add hedge trimming to their maintenance package. Content becomes a natural upselling tool."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 11. Garden Services x AI Automation
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'garden-services',
  'ai-automation',
  'AI automation for garden services introduces intelligent decision-making into the operational complexity of managing a recurring maintenance business with seasonal variability and weather dependency. Traditional automation handles predictable sequences, but AI automation analyses patterns and makes recommendations: which days to reschedule based on weather forecast confidence levels rather than simply flagging rain, how to optimally route maintenance rounds as new customers join and others leave, when to proactively offer seasonal services based on garden-specific factors like hedge growth rates and lawn condition scores, and which prospective customers are most likely to commit to long-term maintenance based on enquiry characteristics. For garden service businesses managing forty to one hundred recurring customers across fluctuating weather conditions and seasonal service demands, AI automation transforms the constant operational juggling into intelligent, data-driven business management that improves efficiency and profitability simultaneously.',
  'Garden maintenance businesses face compounding operational complexity: recurring schedules that shift weekly based on weather, customer numbers that fluctuate seasonally, routes that need constant optimisation as the customer base changes, and seasonal service timing that varies by garden microclimate and growing conditions. Managing all of these variables manually limits business growth and creates operational fragility where one disrupted day cascades through the entire week.',
  'We implement AI systems that learn from your specific business patterns. Weather-confidence scheduling uses forecast reliability data to make smarter rescheduling decisions rather than reacting to every rain icon. Dynamic route optimisation recalculates as customers join or leave. Seasonal service intelligence predicts when specific gardens need attention based on growth patterns and historical maintenance data.',
  '[{"title": "Weather rescheduling based on unreliable forecasts causing unnecessary disruption", "description": "You cancel a day''s maintenance because the forecast shows rain, only for the weather to stay dry while you have already messaged eight customers and rescheduled their visits into an already packed week. Without intelligent weather analysis that considers forecast confidence levels, you either reschedule too aggressively and waste productive days, or not aggressively enough and get caught in downpours."}, {"title": "Route inefficiency growing as customer base changes", "description": "When you started with fifteen customers, routing was simple. Now with fifty customers across different visit frequencies, your routes contain inefficiencies that waste fuel and time. Every new customer added and every customer lost changes the optimal route, but manually recalculating routes across weekly and fortnightly schedules is practically impossible."}, {"title": "Seasonal service timing based on calendar dates rather than actual garden conditions", "description": "You scarify all lawns in March because that is when you always have. But some gardens need scarification in early March while others are not ready until April, depending on soil temperature, shade coverage, and grass variety. Without intelligent scheduling based on actual conditions, you either treat too early for some gardens or too late for others."}]',
  '[{"title": "Weather-confidence scheduling intelligence", "description": "AI analyses weather forecasts using confidence intervals rather than simple rain or dry predictions. A seventy percent chance of afternoon showers might mean proceeding with morning lawn work but postponing hedge trimming. A ninety percent chance of all-day rain triggers full rescheduling. The system makes nuanced decisions that maximise productive working days rather than cancelling entire days based on uncertain forecasts."}, {"title": "Dynamic route optimisation for changing customer bases", "description": "AI continuously recalculates optimal routes as customers join, leave, or change their visit frequency. The system groups customers geographically, balances daily workloads, accounts for different visit durations based on garden size and service level, and minimises travel time between properties. Route efficiency improves automatically without manual recalculation."}, {"title": "Condition-based seasonal service scheduling", "description": "AI tracks maintenance data for each property and identifies optimal timing for seasonal services based on historical patterns rather than fixed calendar dates. If a particular customer''s lawn consistently needs its first scarification in early March while another in a shadier location is not ready until mid-April, the system schedules accordingly. This precision improves results and customer satisfaction."}]',
  '[{"question": "How does weather-confidence scheduling work in practice?", "answer": "The AI analyses multiple weather forecast sources, historical accuracy of those forecasts for your area, and the sensitivity of each scheduled job to weather conditions. Lawn mowing can proceed in light drizzle but not heavy rain. Hedge trimming is less weather-sensitive than leaf blowing. The system makes job-by-job decisions about which visits to proceed with and which to reschedule, rather than cancelling entire days based on a generic rain forecast."}, {"question": "Can AI really optimise my maintenance routes?", "answer": "Yes. The system considers customer locations, visit frequencies, garden sizes affecting visit duration, and day-of-week constraints to generate optimised daily routes. When a new customer joins, the system recalculates which day and position in your route they best fit. When a customer leaves, the freed capacity is identified and offered to new enquiries in that geographic area."}, {"question": "How does condition-based seasonal service scheduling improve results?", "answer": "By tracking when you performed seasonal services at each property and the results achieved, the AI builds a profile of each garden''s optimal timing. Instead of scarifying all lawns in week twelve because that is your annual schedule, the system recommends property-specific timing based on the factors that actually determine readiness: soil temperature trends, shade patterns, and historical growth data."}, {"question": "How much data does the AI need before it starts improving my operations?", "answer": "Basic route optimisation and weather-confidence scheduling deliver value immediately using your customer locations and standard weather data. Condition-based seasonal intelligence improves over time as the system builds property-specific profiles. After one full seasonal cycle, the AI has enough data to make meaningfully better timing recommendations. Each subsequent year refines the predictions further."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;