-- ============================================================
-- seed-local-content-rochester.sql
-- Local content for Rochester across all 11 services
-- Safe to re-run: uses ON CONFLICT ... DO UPDATE
-- ============================================================

-- ==========================================================
-- ROCHESTER (11 services)
-- ==========================================================

-- 1. Rochester × Web Design
INSERT INTO public.local_content (service_slug, town_slug, intro_paragraph, local_context, competition_landscape, success_approach, local_stats, pain_points, solutions, faqs, layout_variant)
VALUES (
  'web-design',
  'rochester',
  'Rochester is a city whose character is defined by layers of history, from the Norman castle and England''s second oldest cathedral to the Dickensian streetscapes that draw visitors year-round, and your website must communicate that depth without feeling like a museum exhibit. The High Street''s independent shops, the creative quarter''s antique dealers and galleries, and the growing food and drink scene all serve a diverse audience: heritage tourists exploring the castle and cathedral, Dickens Festival visitors, Chatham Dockyard day-trippers extending their visit, and the Medway Towns resident population who form your year-round customer base. A website that speaks only to tourists misses the locals who sustain you through winter. One that speaks only to locals misses the heritage visitors who discover you on a castle visit. We build Rochester websites that balance these audiences, creating fast, modern, mobile-first sites that honour the city''s historic character while driving the enquiries, bookings, and sales that keep independent Rochester businesses thriving.',
  'Rochester''s commercial activity concentrates along the High Street, one of the finest preserved historic high streets in England, running from the castle at the southern end past the cathedral and Guildhall Museum toward the Corn Exchange. The independent shops, antique dealers, and eateries lining this stretch serve both the tourist trade and local residents. Rochester Cathedral, the second oldest in England, and Rochester Castle anchor the heritage tourism economy. The Dickens connection runs deep, with several novels set in and around the city and the annual Dickens Festival drawing thousands. Chatham Dockyard sits nearby, creating an extended heritage visitor catchment. Rochester forms part of the Medway Towns, with a local population of approximately 30,000 and the wider Medway area providing a substantial residential catchment.',
  'Rochester''s web design market is divided between the heritage tourism sector, where businesses sometimes benefit from VisitKent or Medway Council digital resources, and the independent business community, where website quality varies enormously. Several High Street businesses have invested in quality sites, but many others operate on templates or outdated builds that fail to capture the city''s character or convert visitors effectively. The proximity to London means some businesses use London agencies, paying premium rates for sites that lack genuine Rochester local knowledge.',
  'We approach Rochester web projects by understanding the dual audience every city-centre business serves. For heritage-adjacent businesses near the castle and cathedral, we build sites with structured data that captures tourism searches while creating compelling direct-visit experiences. For High Street independents, we create sites that reflect the artisan and antique character of Rochester''s shopping scene. For wider Medway service businesses, we build conversion-focused sites with strong local SEO targeting the entire Medway Towns area.',
  '{"population": 30000, "wider_area": "Medway Towns", "key_areas": ["High Street", "Castle area", "Cathedral precinct", "Corn Exchange", "Creative quarter"], "notable_landmarks": ["Rochester Castle", "Rochester Cathedral", "Guildhall Museum", "Corn Exchange"]}',
  '[{"title": "Rochester tourism businesses losing direct visitors to third-party platforms", "description": "A business near Rochester Castle or the Cathedral invests in a physical presence that attracts tourists, but those tourists book through TripAdvisor, Google Maps, or Visit Kent rather than directly. Without a website that ranks independently and converts visitors, Rochester heritage businesses pay commissions or lose attribution entirely."}, {"title": "Historic High Street businesses with websites that undermine their physical charm", "description": "Rochester''s High Street is one of the most attractive in Kent, yet many of its independent shops and eateries have websites that look nothing like the curated, characterful businesses they represent. A beautiful antique shop with a template website creates a jarring disconnect that loses online browsers before they ever visit in person."}, {"title": "No mobile experience for visitors exploring Rochester on foot", "description": "Tourists walking from Rochester Castle along the High Street to the Cathedral search on their phones for somewhere to eat, a gift shop, or an antique dealer. Rochester business websites that are not mobile-optimised lose these walk-in discovery moments to competitors who look better on a phone screen."}]',
  '[{"title": "Heritage-aware Rochester web design that drives modern results", "description": "We create websites that honour Rochester''s historic character while delivering contemporary commercial performance. For businesses near the castle and cathedral, this means design that feels premium and appropriate to the heritage setting, paired with booking tools, clear calls to action, and mobile-first performance."}, {"title": "Mobile-first builds for Rochester''s on-foot visitor economy", "description": "Every Rochester site we build loads in under two seconds on mobile with thumb-friendly navigation. Visitors exploring the High Street, castle grounds, or cathedral precinct can discover your business, check your offerings, and take action before they walk past your door."}, {"title": "Medway-wide SEO foundations in every Rochester website", "description": "We structure every Rochester site for visibility across the Medway Towns and wider Kent heritage tourism searches. Location-specific schema markup, content targeting Rochester, Chatham, and Strood, and structured data that feeds into Google''s tourism and local business results."}]',
  '[{"question": "Can you build a Rochester website that serves both tourists and locals?", "answer": "Yes, this dual-audience approach is central to our Rochester web design strategy. We create distinct user pathways so heritage tourists and Medway residents both find relevant content quickly. Tourism visitors see seasonal information and booking tools. Local customers see service details and clear contact options."}, {"question": "How much does a Rochester business website cost?", "answer": "Rochester projects range from focused sites for High Street independents through to complex heritage tourism builds with booking integration. We provide fixed quotes after understanding your specific needs. Every project includes mobile optimisation, on-page SEO, and content written for the Rochester and Medway market."}, {"question": "Will my Rochester website rank for heritage tourism searches?", "answer": "We build structured data and content strategies specifically designed to compete in Rochester''s heritage tourism search landscape. While Rochester Castle and Cathedral sites carry enormous authority, we target the commercial searches that these institutional sites cannot serve, such as dining, shopping, and accommodation near Rochester Castle."}, {"question": "How long does a Rochester web design project take?", "answer": "Most Rochester projects launch within four to six weeks. Heritage tourism businesses with booking requirements may need six to eight weeks. We schedule around the Dickens Festival and peak tourism periods to ensure your site is live before the busiest seasons."}]',
  'lead-gen'
)
ON CONFLICT (service_slug, town_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  local_context = EXCLUDED.local_context,
  competition_landscape = EXCLUDED.competition_landscape,
  success_approach = EXCLUDED.success_approach,
  local_stats = EXCLUDED.local_stats,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs,
  layout_variant = EXCLUDED.layout_variant;

-- 2. Rochester × SEO
INSERT INTO public.local_content (service_slug, town_slug, intro_paragraph, local_context, competition_landscape, success_approach, local_stats, pain_points, solutions, faqs, layout_variant)
VALUES (
  'seo',
  'rochester',
  'Rochester''s SEO landscape is dominated by the immovable presence of its two most famous landmarks. Search for almost anything related to Rochester and the castle and cathedral occupy the top positions alongside English Heritage, Wikipedia, and Visit Kent. For a local business trying to rank for commercial terms, this institutional dominance creates a wall of authority that generic SEO strategies cannot breach. Add in the Dickens connection generating literary tourism searches, Chatham Dockyard capturing heritage day-trip traffic, and the Guildhall Museum appearing in cultural results, and the space for commercial businesses on page one shrinks further. Yet within this challenging landscape lie genuine opportunities. The Medway Towns residential population generates substantial service search volume that heritage sites cannot serve. Specific commercial intent queries around dining, shopping, and professional services in Rochester are underserved and achievable. We build SEO strategies that navigate Rochester''s heritage-dominated search results to find and own the commercial terms that generate actual business.',
  'Rochester''s search ecosystem is shaped by institutional authority. Rochester Castle and Rochester Cathedral generate millions of annual searches, with English Heritage, the Church of England, and major tourism sites claiming the top positions. The Dickens Festival creates seasonal search spikes. Chatham Dockyard draws heritage searches that overlap with Rochester. The Guildhall Museum and Corn Exchange appear in cultural queries. Behind this tourism layer, the Medway Towns population of over 270,000 generates substantial commercial search demand for everyday services. The High Street, creative quarter, and surrounding residential areas produce consistent local search activity.',
  'SEO competition for Rochester commercial terms is moderate. Tourism and heritage searches are extremely competitive due to institutional dominance, but local service and commercial terms are more accessible. Some High Street businesses have invested in basic SEO, while the broader Medway business community has lower SEO adoption. London agencies occasionally work with Rochester heritage businesses but rarely target the local service market. National chains in nearby retail parks invest in localised SEO that competes for some Medway-wide terms.',
  'Our Rochester SEO strategy works around the heritage content wall rather than attempting to breach it. We target the commercial-intent searches that English Heritage, Wikipedia, and Rochester Cathedral cannot serve: specific service queries, local business categories, and buying-intent terms from Medway residents. We build topical authority around Rochester''s commercial zones and extend reach into the wider Medway Towns population.',
  '{"population": 30000, "wider_area": "Medway Towns (270,000+)", "key_areas": ["High Street", "Castle area", "Cathedral precinct", "Creative quarter", "Corn Exchange area"], "search_competition": "heritage terms very competitive, commercial terms moderate"}',
  '[{"title": "Rochester businesses invisible behind castle and cathedral search results", "description": "A Rochester restaurant searches for dining in Rochester and finds English Heritage, TripAdvisor, Visit Kent, and Time Out occupying every first-page position. A High Street shop searches for their product category plus Rochester and finds the Guildhall Museum gift shop and national chains ranking above them. The heritage sector absorbs the search visibility that commercial businesses need."}, {"title": "Medway residents searching for services and finding businesses in other towns", "description": "A resident of the Medway Towns searches for a local service provider and Google returns businesses in Maidstone, Gravesend, or London before showing Rochester options. Without SEO investment, Rochester businesses lose their own residential market to geographically distant competitors who simply rank better."}, {"title": "Dickens Festival and event traffic generating awareness but no lasting SEO benefit", "description": "Rochester experiences significant search spikes during the Dickens Festival and other heritage events. Local businesses enjoy temporary footfall but capture no lasting search benefit because they have no optimised content for these event-related searches to discover. When the event ends, the digital trace disappears entirely."}]',
  '[{"title": "Commercial-intent SEO that navigates Rochester''s heritage dominance", "description": "We target the Rochester searches that English Heritage, Rochester Cathedral, and Visit Kent cannot serve: specific commercial queries from Medway residents and visitors with buying intent. These are the terms that generate phone calls, bookings, and walk-ins rather than information-seeking page views from distant browsers."}, {"title": "Medway-wide content strategy anchored from Rochester", "description": "We build content targeting both Rochester-specific terms and broader Medway Towns searches. Location pages for Rochester High Street, the creative quarter, and surrounding Medway areas capture searches that competitors focused on a single location miss, extending your visibility across the 270,000-strong residential catchment."}, {"title": "Heritage event SEO that captures lasting value from Rochester''s cultural calendar", "description": "We create optimised content around the Dickens Festival, castle events, and cathedral programmes that captures search traffic during peaks and maintains ranking value afterward. This content positions your Rochester business within the heritage context visitors are searching for while driving commercial outcomes."}]',
  '[{"question": "How do I rank against Rochester Castle and Cathedral in search results?", "answer": "You target different searches. Institutional sites dominate informational heritage queries, but cannot compete for commercial searches like where to eat near Rochester Castle or gift shops Rochester High Street. We focus your SEO on the buying-intent terms that tourism sites leave open."}, {"question": "How long does SEO take to show results in Rochester?", "answer": "Commercial service terms in Rochester typically show ranking improvements within six to ten weeks. Heritage-adjacent hospitality and retail terms may take three to four months due to institutional competition. We prioritise the highest-value achievable terms first so you see returns early."}, {"question": "Should I target Rochester specifically or the wider Medway area?", "answer": "Both. Rochester-specific terms capture the heritage tourism audience and immediate local traffic. Medway-wide terms reach the 270,000-plus residential population across Chatham, Strood, Gillingham, and beyond. We build both layers simultaneously for maximum commercial impact."}, {"question": "Can SEO help me benefit from the Dickens Festival search traffic?", "answer": "Yes. We create content that ranks for Dickens Festival-related commercial searches, such as dining during the festival or shopping near festival events. This captures visitors during the peak while building content that ranks for Rochester heritage searches year-round."}]',
  'authority'
)
ON CONFLICT (service_slug, town_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  local_context = EXCLUDED.local_context,
  competition_landscape = EXCLUDED.competition_landscape,
  success_approach = EXCLUDED.success_approach,
  local_stats = EXCLUDED.local_stats,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs,
  layout_variant = EXCLUDED.layout_variant;

-- 3. Rochester × Lead Capture
INSERT INTO public.local_content (service_slug, town_slug, intro_paragraph, local_context, competition_landscape, success_approach, local_stats, pain_points, solutions, faqs, layout_variant)
VALUES (
  'lead-capture',
  'rochester',
  'Rochester generates impressive footfall through its heritage attractions. Visitors pour through the castle grounds, walk the cathedral precinct, browse the High Street''s antique shops and independent retailers, and photograph the Dickensian streetscape. During the Dickens Festival, the city is packed. On any given weekend, the castle-to-cathedral corridor is busy with tourists exploring one of England''s best-preserved historic centres. Yet the vast majority of these visitors interact with Rochester businesses without leaving any contact details. They buy a coffee, browse an antique shop, photograph a restaurant menu, and drive back to London without the business capturing a single email address. This is Rochester''s lead capture challenge: converting heritage footfall into lasting customer relationships. We build systems that capture visitor details at the moment of engagement and nurture them into repeat customers who return long after the castle visit is forgotten.',
  'Rochester''s lead capture geography follows the heritage visitor pathway. The castle at the southern end of the High Street draws visitors who then walk northward past the Guildhall Museum, through the antique and creative quarter, past the cathedral, and toward the Corn Exchange. This linear visitor flow creates predictable engagement points where capture can occur. Chatham Dockyard visitors extending their day into Rochester represent a secondary capture opportunity. The Medway Towns residential population generates a different capture pattern: browsing online before deciding to visit, where website-based capture tools are most relevant.',
  'Lead capture in Rochester is rudimentary. Most businesses rely on a phone number and a basic contact form. Heritage-adjacent hospitality uses booking platforms that own the customer data. High Street retailers have no digital capture mechanism. The antique quarter, where high-value purchases and collector relationships could sustain a thriving email marketing programme, captures virtually no visitor contact details. The opportunity cost is enormous.',
  'We build Rochester lead capture systems designed for the heritage visitor journey. For castle and cathedral-adjacent businesses, we create capture tools that work within the brief tourist interaction window. For High Street independents and the antique quarter, we build collector and enthusiast email programmes that turn one-time browsers into ongoing customers. For Medway-wide service businesses, we design qualification-focused forms that generate serious enquiries from the residential catchment.',
  '{"population": 30000, "wider_area": "Medway Towns (270,000+)", "key_areas": ["High Street", "Castle area", "Cathedral precinct", "Creative quarter", "Corn Exchange"], "visitor_economy": "strong heritage tourism plus Chatham Dockyard overflow"}',
  '[{"title": "Heritage tourists enjoying Rochester but never returning because no follow-up exists", "description": "A family visits Rochester Castle, walks the High Street, has lunch at an independent restaurant, and buys a gift from an antique shop. They had a wonderful day but no Rochester business captured their email. Without follow-up, that family''s next heritage day trip goes to Canterbury or Leeds Castle because Rochester did not stay in touch."}, {"title": "Dickens Festival visitors arriving once and disappearing", "description": "The Dickens Festival brings thousands of visitors to Rochester who spend generously across High Street businesses over a single weekend. Yet almost none of these visitors are captured into databases for year-round marketing. The festival generates a revenue spike but no lasting customer relationships."}, {"title": "Antique quarter browsers who would become collectors with the right follow-up", "description": "Rochester''s creative quarter draws antique enthusiasts who browse multiple shops during a visit. Many would become regular buyers if they received updates about new stock. But without email capture, these potential long-term relationships end when the visitor walks out the door."}]',
  '[{"title": "Heritage visitor capture tools for Rochester''s castle-to-cathedral corridor", "description": "We build capture mechanisms for the specific moments when Rochester visitors are most engaged: in-venue QR codes, post-purchase email sign-ups, and digital loyalty tools along the High Street. Each touchpoint offers genuine value like an insider guide to Rochester or exclusive event notifications in exchange for an email address."}, {"title": "Collector and enthusiast programmes for Rochester''s antique and creative quarter", "description": "For Rochester''s antique dealers and galleries, we build email capture and nurture systems designed for the collector mindset. New stock alerts, specialist event invitations, and curated content keep your Rochester shop in the minds of enthusiasts who visit once but could become lifelong customers."}, {"title": "Post-visit conversion sequences for Rochester''s heritage tourist audience", "description": "Every captured visitor enters an automated sequence designed for the heritage day-trip cycle. Thank you messages after their Rochester visit, seasonal event invitations including the Dickens Festival, and exclusive offers timed to encourage return trips build ongoing relationships from single heritage visits."}]',
  '[{"question": "How do I capture leads from Rochester Castle and cathedral visitors?", "answer": "We implement a combination of in-venue QR codes, post-purchase email capture, and digital tools that offer genuine value in exchange for contact details. A visitor guide to Rochester''s hidden gems, a discount for a return visit, or a notification about upcoming events all provide compelling reasons for heritage visitors to share their email address."}, {"question": "Can lead capture help my Rochester antique business build a collector base?", "answer": "Absolutely. We build email programmes specifically designed for collector relationships: new stock alerts tailored to interests, specialist event invitations, and behind-the-scenes content about acquisitions. Rochester''s antique quarter has ideal conditions for building a national collector database through proper email capture."}, {"question": "How do I follow up with Dickens Festival visitors year-round?", "answer": "We create automated sequences that engage Festival visitors throughout the year: exclusive early access to next year''s Festival details, invitations to other Rochester events, and seasonal offers timed to encourage off-peak visits. The Festival becomes the beginning of a year-round relationship rather than a once-annual encounter."}, {"question": "What lead capture conversion rate should a Rochester business expect?", "answer": "Heritage businesses on the High Street typically see three to eight percent of visitors convert to email contacts with properly designed capture tools. Website-based capture for Medway service businesses achieves ten to fifteen percent. Even at lower rates, Rochester''s strong heritage footfall means significant monthly list growth."}]',
  'lead-gen'
)
ON CONFLICT (service_slug, town_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  local_context = EXCLUDED.local_context,
  competition_landscape = EXCLUDED.competition_landscape,
  success_approach = EXCLUDED.success_approach,
  local_stats = EXCLUDED.local_stats,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs,
  layout_variant = EXCLUDED.layout_variant;

-- 4. Rochester × Business Automation
INSERT INTO public.local_content (service_slug, town_slug, intro_paragraph, local_context, competition_landscape, success_approach, local_stats, pain_points, solutions, faqs, layout_variant)
VALUES (
  'business-automation',
  'rochester',
  'Rochester''s business community blends heritage-sector operators with contemporary independents, and both face the same operational challenge: too much manual administration consuming time that should go toward serving customers and growing the business. A High Street restaurant near the castle manages bookings across multiple platforms during peak tourist season while simultaneously trying to maintain quality for regular Medway diners. An antique dealer in the creative quarter manually updates stock across their shop, website, and collector mailing list. A service provider covering the Medway Towns juggles quoting, scheduling, invoicing, and follow-up between completing actual work. Rochester''s compact, high-footfall High Street amplifies these pressures: businesses in the castle-to-cathedral corridor cannot afford to drop a booking or miss an enquiry during the busy periods that drive annual revenue. We build automation that handles the operational mechanics so Rochester business owners can focus on the craft, service, and customer relationships that make their businesses worth visiting.',
  'Rochester''s business operations span several distinct environments. The High Street hosts independent retail, hospitality, and the antique and creative quarter, all experiencing peak demand during heritage tourism seasons and events like the Dickens Festival. The Corn Exchange and surrounding area provides a secondary commercial cluster. Service businesses operate across the broader Medway Towns, requiring scheduling and communication systems that cover Rochester, Chatham, Strood, and beyond. Chatham Dockyard''s proximity means some Rochester businesses serve an extended visitor market that creates additional operational complexity.',
  'Automation adoption among Rochester businesses is low. Heritage hospitality venues use basic booking tools but rarely integrate them with other systems. High Street retailers manage inventory manually. The antique quarter operates almost entirely through personal knowledge and manual processes. Service businesses across Medway use phone and email for scheduling. A few forward-thinking Rochester businesses have implemented partial automation, but connected end-to-end workflows are virtually non-existent.',
  'We focus Rochester automation on the operational bottlenecks specific to a heritage town''s business rhythm. For High Street hospitality, we automate multi-platform booking management and post-visit follow-up that captures tourist relationships. For antique and creative quarter businesses, we connect inventory, communications, and collector databases. For Medway service businesses, we build scheduling, quoting, and invoicing workflows that work across the wider area.',
  '{"population": 30000, "wider_area": "Medway Towns (270,000+)", "key_areas": ["High Street", "Castle area", "Cathedral precinct", "Creative quarter", "Corn Exchange"], "business_profile": "heritage hospitality, independent retail, antiques, Medway services"}',
  '[{"title": "Rochester heritage tourism surges overwhelming manual booking systems", "description": "During the Dickens Festival, bank holidays, and summer peaks, Rochester High Street businesses experience booking volumes that manual systems cannot handle efficiently. A restaurant near the castle takes reservations by phone while simultaneously serving a full house, inevitably missing calls and double-booking tables."}, {"title": "Antique dealers managing stock knowledge in their heads rather than systems", "description": "A Rochester antique dealer knows their entire inventory from memory, which works until they are away, ill, or want to sell to online buyers. Without automated inventory management, the business cannot operate without the owner''s personal presence, creating a fragile single point of failure."}, {"title": "Medway service businesses losing revenue through delayed invoicing and follow-up", "description": "A tradesperson completes a job in Chatham, drives to the next in Strood, and arrives home to Rochester with three invoices to write, two reviews to request, and a quote to follow up. Exhaustion wins, and the admin slips to the next day, or the next. Late invoicing and missed follow-up quietly erode revenue month after month."}]',
  '[{"title": "Heritage-season booking automation for Rochester hospitality", "description": "We unify all booking channels into a single system with automated confirmations, reminders, and no-show management. During Dickens Festival weekends and summer peaks, your Rochester restaurant or venue handles surge demand without additional staff. Post-visit follow-up captures tourist relationships automatically."}, {"title": "Digital inventory management for Rochester''s antique and creative quarter", "description": "We build inventory systems that connect your Rochester shop floor, website, and collector communications. New acquisitions are catalogued once and appear across all channels. Interested collectors receive automatic notifications. The business operates systematically whether the owner is present or not."}, {"title": "End-to-end service automation for Medway Towns businesses", "description": "We connect quoting, scheduling, job management, invoicing, and follow-up into a single automated workflow. A completed job in Chatham triggers an invoice, a review request, and a follow-up scheduling prompt without requiring any manual intervention. For Rochester-based businesses serving the wider Medway area, this reclaims hours every week."}]',
  '[{"question": "What should a Rochester business automate first?", "answer": "Start with the process that costs you the most time or revenue. For High Street hospitality, booking management delivers the fastest return during heritage tourism peaks. For antique dealers, inventory digitisation protects business continuity. For Medway service businesses, invoicing and follow-up automation recovers revenue immediately."}, {"question": "Will automation handle the Dickens Festival booking surge?", "answer": "Yes. Automated booking systems scale effortlessly from quiet weekdays to packed Festival weekends. Confirmations, reminders, and waitlist management all happen automatically, so your Rochester team can focus on delivering excellent service rather than processing reservations during the busiest period of the year."}, {"question": "How long does automation setup take for a Rochester business?", "answer": "Most Rochester automation projects are operational within two to four weeks. We prioritise your highest-impact workflow and get it running first, then add additional automations. Heritage businesses should ideally begin setup well before their peak seasons to be fully operational when demand surges."}, {"question": "Can automation help my antique business reach collectors nationwide?", "answer": "Yes. By connecting your inventory management with email communication systems, we enable automated new stock alerts to collectors across the country. When you catalogue a new piece in your Rochester shop, interested collectors receive personalised notifications automatically, turning your physical shop into a national sales channel."}]',
  'operational'
)
ON CONFLICT (service_slug, town_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  local_context = EXCLUDED.local_context,
  competition_landscape = EXCLUDED.competition_landscape,
  success_approach = EXCLUDED.success_approach,
  local_stats = EXCLUDED.local_stats,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs,
  layout_variant = EXCLUDED.layout_variant;

-- 5. Rochester × Branding
INSERT INTO public.local_content (service_slug, town_slug, intro_paragraph, local_context, competition_landscape, success_approach, local_stats, pain_points, solutions, faqs, layout_variant)
VALUES (
  'branding',
  'rochester',
  'Rochester demands branding that respects its heritage without being trapped by it. The city''s visual landscape is extraordinary: a Norman castle looming above the High Street, England''s second oldest cathedral a few hundred yards away, the Guildhall Museum''s timber-framed facade, and the Dickensian shop fronts that make the High Street feel like a living period drama. Your brand exists within this rich visual context, and it must feel appropriate to the setting while being distinctly contemporary enough to attract the modern consumer. A High Street restaurant with branding that looks Victorian when it serves contemporary food sends confusing signals. An antique dealer whose identity is so modern it feels disconnected from their stock creates a credibility gap. The best Rochester brands find the balance: rooted in the city''s character, confident in their own identity, and distinctive enough to stand out on a High Street full of character. We create brand identities that navigate Rochester''s visual heritage with intelligence and craft.',
  'Rochester''s visual environment is defined by the dramatic contrast between Norman military architecture at the castle, medieval ecclesiastical grandeur at the cathedral, and the intimate timber-framed and Georgian commercial buildings along the High Street. The Guildhall Museum, Corn Exchange, and Rochester Bridge provide additional architectural reference points. The Dickens Festival transforms the streetscape annually, reinforcing the Victorian literary associations. The creative quarter''s antique shops add layers of visual history. This environment demands branding that demonstrates visual sophistication and contextual awareness.',
  'Branding quality among Rochester businesses varies widely. Some High Street businesses have invested in professional identities that complement the historic streetscape beautifully. Others use generic designs that could belong to any town. The antique quarter has a few strongly branded dealers alongside many with no consistent visual identity. Beyond the High Street, branding quality drops significantly across the wider Medway business community. The heritage context means poor branding is more noticeable in Rochester than in less visually distinctive towns.',
  'We create Rochester brand identities that respond intelligently to the city''s architectural and cultural context. Rather than imitating the heritage aesthetic, we find the design language that sits confidently alongside it. Every brand comes with comprehensive guidelines covering High Street signage, digital applications, print materials, and vehicle livery, ensuring consistency across every touchpoint within and beyond Rochester.',
  '{"population": 30000, "wider_area": "Medway Towns (270,000+)", "key_areas": ["High Street", "Castle area", "Cathedral precinct", "Creative quarter", "Corn Exchange"], "visual_context": "Norman castle, medieval cathedral, Dickensian High Street, timber-framed and Georgian architecture"}',
  '[{"title": "Rochester businesses with branding that clashes with the historic High Street", "description": "A modern business on Rochester High Street uses a brand identity designed without any awareness of the surrounding architecture. Bright neon signage next to a timber-framed building. A logo style that screams retail park rather than heritage high street. The visual clash communicates poor judgement to every tourist and local walking past."}, {"title": "Generic heritage branding that fails to distinguish Rochester businesses from each other", "description": "Several Rochester businesses adopt similar pseudo-historical design elements: serif fonts, muted colours, and illustrations of the castle or cathedral. The result is a cluster of businesses that look thematically similar but individually unmemorable. Visitors walking the High Street cannot distinguish one from another at a glance."}, {"title": "Antique quarter businesses with no brand identity undermining credibility", "description": "A Rochester antique dealer with rare and valuable stock presents themselves with no consistent visual identity. No logo, no branded packaging, no professional stationery. When a collector is deciding where to spend thousands of pounds, the absence of professional branding creates doubt about the operation''s legitimacy and permanence."}]',
  '[{"title": "Heritage-contextual Rochester brand identity design", "description": "We create brands that sit confidently alongside Rochester''s extraordinary architectural landscape without imitating it. Your identity will feel appropriate on the High Street between the castle and cathedral while being distinctly contemporary and memorable. We research your specific position within Rochester''s visual environment before designing a single element."}, {"title": "Complete brand system for Rochester''s multi-context businesses", "description": "Every brand includes guidelines for High Street signage that respects the conservation area, digital applications that work across web and social media, print materials from business cards to packaging, and vehicle livery for wider Medway area visibility. Consistency across all contexts is ensured through comprehensive brand documentation."}, {"title": "Brand positioning for Rochester''s antique and creative quarter", "description": "For antique dealers, galleries, and creative businesses, we develop brand identities that communicate expertise, trustworthiness, and the specific character of your offerings. Your brand becomes a mark of quality that collectors and enthusiasts recognise and trust, supporting higher-value transactions and repeat relationships."}]',
  '[{"question": "How do you create branding that works on Rochester''s historic High Street?", "answer": "We research the specific visual context of your location: surrounding architecture, neighbouring businesses, conservation area guidelines, and the overall streetscape character. The resulting brand is designed to complement this environment rather than clash with it, feeling appropriate to Rochester''s heritage while being clearly contemporary."}, {"question": "Can you rebrand my Rochester business without alienating existing customers?", "answer": "Yes. We specialise in brand evolution that retains the elements your customers recognise while elevating quality and consistency. For established Rochester businesses, this means a professional upgrade that feels like natural growth rather than a sudden change that confuses loyal customers."}, {"question": "How long does a Rochester branding project take?", "answer": "A complete brand identity takes four to five weeks from discovery through to final delivery. This includes research into your Rochester context, concept development, refinement rounds, and production of all brand assets with comprehensive guidelines. The heritage context research adds depth that benefits the final result."}, {"question": "Will my brand work on Rochester High Street signage and online?", "answer": "Every brand is designed for multi-environment application from the outset. We test designs against the specific Rochester High Street context, conservation area requirements, and digital platform requirements simultaneously. You receive assets in all formats needed for physical and digital applications."}]',
  'trust'
)
ON CONFLICT (service_slug, town_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  local_context = EXCLUDED.local_context,
  competition_landscape = EXCLUDED.competition_landscape,
  success_approach = EXCLUDED.success_approach,
  local_stats = EXCLUDED.local_stats,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs,
  layout_variant = EXCLUDED.layout_variant;

-- 6. Rochester × Social Media Setup
INSERT INTO public.local_content (service_slug, town_slug, intro_paragraph, local_context, competition_landscape, success_approach, local_stats, pain_points, solutions, faqs, layout_variant)
VALUES (
  'social-media-setup',
  'rochester',
  'Rochester is one of the most photographed towns in Kent. The castle against a sunset sky, the cathedral interior, the Dickens Festival in full costume, the High Street''s timber-framed shop fronts: this content circulates widely on social media, creating organic awareness that most towns would envy. Yet the majority of Rochester businesses fail to capture any value from this visual economy. Their social profiles are afterthoughts: blurry logo images, outdated information, inconsistent branding, and no strategy for engaging the audience that discovers Rochester through these shared images. When a potential customer sees a stunning photograph of the High Street and clicks through to find a local business, they encounter a Facebook page with incorrect opening hours and an Instagram profile with three posts from last year. Rochester''s visual appeal is doing the marketing work for free; your social profiles just need to be ready to receive the traffic.',
  'Rochester''s social media landscape benefits from the city''s photogenic qualities. Instagram content featuring the castle, cathedral, and High Street generates strong organic engagement. Facebook remains important for the Medway residential community and local event promotion. The Dickens Festival creates annual social media spikes with costumed attendees sharing thousands of posts. Heritage tourism accounts regularly feature Rochester, creating discovery opportunities for local businesses. The creative quarter and antique shops generate interest from specialist collector communities on social media.',
  'Social media quality among Rochester businesses is inconsistent. A few High Street venues maintain strong Instagram accounts that leverage the heritage setting effectively. Some antique dealers have built specialist followings. But the majority of Rochester businesses have underdeveloped profiles that miss the organic discovery traffic the city''s visual appeal generates. Google Business Profile adoption is particularly poor, with many businesses unclaimed or displaying inaccurate information.',
  'We set up Rochester social media profiles to capitalise on the city''s extraordinary visual appeal. Every profile receives professional imagery that leverages the castle, cathedral, and High Street setting, optimised descriptions targeting Rochester and Medway searches, and a content framework aligned with the heritage tourism calendar including the Dickens Festival and seasonal events.',
  '{"population": 30000, "wider_area": "Medway Towns (270,000+)", "key_areas": ["High Street", "Castle area", "Cathedral precinct", "Creative quarter", "Corn Exchange"], "social_landscape": "highly photogenic, strong organic content generation around castle, cathedral, and Dickens Festival"}',
  '[{"title": "Rochester''s photogenic heritage generating social media traffic that businesses cannot capture", "description": "Thousands of Instagram posts featuring Rochester Castle and the High Street circulate weekly. Potential customers discover Rochester through these images and search for local businesses to visit. Those businesses with poor or absent social profiles are invisible at the exact moment interest peaks."}, {"title": "Dickens Festival social media surge with no commercial capture", "description": "The Dickens Festival generates enormous social media activity with costumed attendees sharing photos across platforms. Rochester businesses could ride this wave of attention, but most have profiles too poorly set up to benefit. The festival''s social media impact passes without creating any lasting commercial connection."}, {"title": "Unclaimed Google Business Profiles costing Rochester businesses walk-in trade", "description": "Heritage visitors searching for businesses near Rochester Castle on Google find a map peppered with unclaimed or poorly maintained listings. Without photos, reviews, and accurate hours, these listings do more harm than good, suggesting businesses that are inactive or unreliable."}]',
  '[{"title": "Heritage-leveraging social media setup for Rochester businesses", "description": "We set up your Instagram, Facebook, and Google Business profiles with professional imagery that uses Rochester''s castle, cathedral, and High Street setting as a brand asset. Your profiles are designed to capture the organic discovery traffic that the city''s visual appeal generates, converting heritage tourism interest into business engagement."}, {"title": "Dickens Festival and event-ready social profiles", "description": "We prepare your social profiles with content strategies and templates designed for Rochester''s event calendar. When the Dickens Festival, heritage weekends, or seasonal events drive social media surges, your business is positioned to capture attention with prepared, branded content that converts interest into visits and bookings."}, {"title": "Google Business Profile optimisation for Rochester walk-in discovery", "description": "We claim, verify, and fully optimise your Google Business Profile with professional imagery, comprehensive business information, and structured review generation. For High Street businesses in the castle-to-cathedral corridor, an optimised listing is the difference between capturing walk-in visitors and being invisible to them."}]',
  '[{"question": "Which social media platforms matter most for a Rochester business?", "answer": "Instagram is essential for leveraging Rochester''s visual heritage appeal. Facebook reaches the Medway residential community and local event audience. Google Business Profile is critical for walk-in discovery around the castle and High Street. We assess your business type to prioritise platforms correctly."}, {"question": "Can social media help my Rochester business benefit from the Dickens Festival?", "answer": "Yes. We create Festival-specific content strategies and templates so your business is ready when the social media surge hits. Hashtagged, location-tagged, and visually compelling content during the Festival connects your business to the thousands of posts and searches the event generates."}, {"question": "How long does social media setup take for a Rochester business?", "answer": "Complete setup covering Instagram, Facebook, and Google Business Profile takes five to seven working days. This includes professional imagery leveraging the Rochester heritage context, optimised profiles, branded templates, and a content framework. High Street businesses may benefit from additional photography capturing the streetscape setting."}, {"question": "Do you manage Rochester social media ongoing or just set it up?", "answer": "Our core service is professional setup with a content framework that makes ongoing management achievable. We also offer full management for businesses that prefer to hand off posting entirely. Many Rochester clients find the heritage calendar provides natural content hooks that make self-management straightforward with our templates."}]',
  'trust'
)
ON CONFLICT (service_slug, town_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  local_context = EXCLUDED.local_context,
  competition_landscape = EXCLUDED.competition_landscape,
  success_approach = EXCLUDED.success_approach,
  local_stats = EXCLUDED.local_stats,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs,
  layout_variant = EXCLUDED.layout_variant;

-- 7. Rochester × Digital Marketing
INSERT INTO public.local_content (service_slug, town_slug, intro_paragraph, local_context, competition_landscape, success_approach, local_stats, pain_points, solutions, faqs, layout_variant)
VALUES (
  'digital-marketing',
  'rochester',
  'Rochester occupies a unique position for digital marketing. The city''s heritage profile generates significant organic online interest, the Medway Towns population of over 270,000 provides a substantial local market, and the proximity to London via the High Speed train link brings a day-trip audience within reach of targeted digital campaigns. Yet most Rochester businesses invest nothing in digital marketing, relying entirely on heritage footfall and local reputation. This leaves substantial revenue on the table. The Medway resident who searches online for a local service and finds a Canterbury or Maidstone provider instead. The heritage tourist who visits Rochester Castle but eats lunch in Chatham because they did not discover your High Street restaurant digitally. The antique collector in London who would visit your Rochester gallery monthly if they knew it existed. Digital marketing closes these gaps, putting your Rochester business in front of the specific audiences most likely to become customers.',
  'Rochester''s digital marketing audience operates on three levels. The immediate Medway Towns population provides consistent local service demand that can be reached through targeted search and social advertising. Heritage tourists searching for Rochester Castle, the cathedral, and the Dickens Festival represent a high-intent visitor audience. The London corridor, accessible via the High Speed train, offers a premium day-trip audience for hospitality, antiques, and experiential businesses. Each level requires different channels, messaging, and conversion strategies.',
  'Digital marketing competition in Rochester is low for most business categories. Heritage tourism marketing is handled largely by institutional bodies like English Heritage and Visit Kent. Few local businesses run paid campaigns, email marketing, or structured content strategies. Some Chatham and wider Medway businesses capture Rochester traffic through broader campaigns. This low competition means advertising costs are favourable and organic opportunities are plentiful.',
  'Our Rochester digital marketing strategy works across all three audience levels. Local Medway campaigns target residents with service-focused messaging. Heritage corridor campaigns reach visitors planning castle, cathedral, and Dickens Festival trips with commercial offers. London day-trip campaigns target the High Speed train audience with discovery and experience messaging. Every campaign is tracked to measurable commercial results.',
  '{"population": 30000, "wider_area": "Medway Towns (270,000+)", "key_areas": ["High Street", "Castle area", "Cathedral precinct", "Creative quarter", "Corn Exchange"], "marketing_opportunity": "heritage profile, Medway population, London High Speed link"}',
  '[{"title": "Rochester heritage footfall dropping during off-peak with no digital marketing to sustain demand", "description": "Rochester businesses that rely on heritage tourism footfall experience significant revenue drops during winter months and between major events. Without digital marketing to the Medway residential audience and targeted campaigns encouraging off-peak visits, these businesses accept seasonal troughs as inevitable when they are in fact addressable."}, {"title": "Medway residents choosing out-of-area businesses because Rochester options are invisible online", "description": "A Medway resident searches for a service provider and finds options in Maidstone, Canterbury, or London before any Rochester business appears. Without digital marketing presence, Rochester businesses lose their own residential catchment to competitors who simply invest more in online visibility."}, {"title": "London day-trip audience unreachable without targeted digital campaigns", "description": "The High Speed train puts Rochester within easy reach of millions of Londoners. Many already visit for the castle and cathedral. But without targeted digital marketing reaching this audience during their planning stage, Rochester businesses miss the opportunity to convert heritage awareness into commercial visits."}]',
  '[{"title": "Three-audience digital marketing strategy for Rochester", "description": "We build campaigns across three levels: Medway-targeted campaigns for local service businesses, heritage visitor campaigns reaching people planning Rochester Castle and cathedral trips, and London corridor campaigns targeting the High Speed train audience with experiential and discovery messaging. Each level has distinct channels, content, and conversion goals."}, {"title": "Heritage event marketing leveraging the Dickens Festival and castle calendar", "description": "We create digital campaigns around Rochester''s heritage events that drive commercial results for local businesses. Pre-event campaigns build anticipation and bookings. During-event campaigns capture real-time visitor attention. Post-event campaigns convert event attendees into repeat visitors. The Dickens Festival becomes a year-round marketing asset."}, {"title": "Full attribution tracking from Rochester campaign to paying customer", "description": "Every digital marketing campaign includes proper tracking so you know which channels, messages, and audiences generate actual business. For Rochester heritage businesses, we track the connection between tourism-targeted advertising and in-store or in-restaurant revenue, proving the commercial value of your marketing investment."}]',
  '[{"question": "Can digital marketing reach London visitors planning a Rochester trip?", "answer": "Yes. We target audiences along the London to Rochester High Speed corridor with campaigns timed to weekend planning patterns. Combined with remarketing to previous website visitors, this reaches people actively considering a Rochester day trip and puts your business in front of them before they arrive."}, {"question": "How much should a Rochester business spend on digital marketing?", "answer": "Rochester''s low competition means effective campaigns start from modest budgets. Local Medway service campaigns can begin at a few hundred pounds monthly. Heritage tourism campaigns targeting a broader geography need larger budgets. We recommend starting focused and scaling based on tracked returns."}, {"question": "Which channels work best for Rochester digital marketing?", "answer": "Google Ads captures high-intent searches from both Medway residents and heritage tourists. Instagram leverages Rochester''s visual appeal for awareness and discovery. Facebook reaches the established Medway community. Email marketing delivers the strongest return for businesses with captured contact lists. We build the right mix for your business."}, {"question": "How can digital marketing help during Rochester''s quiet winter months?", "answer": "Targeted campaigns to the Medway residential market maintain revenue during heritage tourism off-peaks. Seasonal offers and content targeting local audiences ensure your Rochester business does not depend entirely on tourist footfall. We build year-round strategies that smooth seasonal revenue fluctuations."}]',
  'lead-gen'
)
ON CONFLICT (service_slug, town_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  local_context = EXCLUDED.local_context,
  competition_landscape = EXCLUDED.competition_landscape,
  success_approach = EXCLUDED.success_approach,
  local_stats = EXCLUDED.local_stats,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs,
  layout_variant = EXCLUDED.layout_variant;

-- 8. Rochester × Workwear & Print
INSERT INTO public.local_content (service_slug, town_slug, intro_paragraph, local_context, competition_landscape, success_approach, local_stats, pain_points, solutions, faqs, layout_variant)
VALUES (
  'workwear-print',
  'rochester',
  'Rochester''s High Street is a stage. Every business front, every staff member, every piece of packaging is seen against the backdrop of a Norman castle and a medieval cathedral by visitors who have chosen to spend their day in one of England''s most atmospheric historic towns. In this context, your physical brand materials are not just functional; they are part of the visitor experience. Branded aprons on staff serving in view of the castle ruins. Printed menus that match the quality of the dining experience. Packaging from an antique dealer that reflects the care given to their stock. Workwear on a tradesperson that communicates professionalism to homeowners in Rochester''s period properties. The physical expression of your brand matters more in Rochester than in almost any other town because the visual environment raises expectations. We provide workwear and print that meet the standards Rochester''s heritage setting demands.',
  'Rochester''s physical brand environment is defined by the heritage High Street context. Signage, menus, and packaging are viewed against timber-framed and Georgian shop fronts in a conservation area. Staff workwear is seen by heritage tourists with high visual expectations. Vehicle livery moves through the compact historic core where repeat exposure is guaranteed. The Guildhall Museum, Corn Exchange, and castle grounds host events where branded materials make impressions on engaged audiences. Beyond the High Street, tradespeople and service businesses operate across the Medway Towns where vehicle branding is the primary visual touchpoint.',
  'Branded materials quality on Rochester High Street is mixed. Some heritage hospitality venues have invested in materials that complement the historic setting, but many businesses use generic or cheaply produced items that look out of place on one of Kent''s finest high streets. The antique quarter has a few beautifully branded dealers alongside many with no consistent physical brand presence. Trade and service businesses across Medway rarely invest in professional workwear or vehicle livery.',
  'We provide Rochester businesses with branded materials that respect the heritage High Street context while expressing contemporary brand identities. For castle-and-cathedral-corridor businesses, we produce materials that look appropriate against the historic architecture. For antique dealers, we create packaging and stationery befitting high-value transactions. For Medway service businesses, we supply workwear and vehicle livery that builds professional recognition across the wider area.',
  '{"population": 30000, "wider_area": "Medway Towns (270,000+)", "key_areas": ["High Street", "Castle area", "Cathedral precinct", "Creative quarter", "Corn Exchange"], "brand_environment": "heritage High Street, conservation area, high visitor expectations"}',
  '[{"title": "Rochester High Street businesses with materials that clash with the heritage setting", "description": "A business on Rochester''s historic High Street displays brightly coloured plastic signage, hands out flimsy flyers, and dresses staff in unbranded high-street clothing. Against the backdrop of the castle and cathedral, these materials look cheap and incongruous, creating an impression at odds with the premium expectations heritage visitors bring."}, {"title": "Antique dealers handling valuable stock with unprofessional packaging", "description": "A Rochester antique dealer wraps a valuable purchase in newspaper and places it in a supermarket carrier bag. The collector who has just spent hundreds of pounds receives their acquisition in packaging that communicates zero care. Professional branded wrapping and bags would reinforce the value of the purchase and the dealer''s credibility."}, {"title": "Medway tradespeople losing jobs to competitors who simply look more professional", "description": "A Rochester tradesperson quotes for a job at a period property near the cathedral. The homeowner answers the door to see an unmarked van and unbranded clothing. The next tradesperson arrives in branded workwear from a sign-written van. Before any work is assessed, the second tradesperson has already won on perceived professionalism."}]',
  '[{"title": "Heritage-appropriate branded materials for Rochester High Street businesses", "description": "We produce branded workwear, menus, packaging, and signage that complement Rochester''s conservation area context. Materials are designed to look professional and appropriate against the historic High Street architecture. For hospitality venues near the castle, this means quality that matches the setting your visitors have chosen to spend their day in."}, {"title": "Collector-grade packaging for Rochester''s antique and creative quarter", "description": "We design and produce branded packaging, wrapping, bags, and certificates that reflect the value of high-end antique and art transactions. For Rochester''s creative quarter dealers, professional packaging reinforces the care and expertise behind every item and encourages collector loyalty."}, {"title": "Professional workwear and vehicle livery for Medway-wide service businesses", "description": "For trades and service businesses based in Rochester serving the Medway Towns, we supply branded workwear and vehicle livery that builds recognition and trust across every job. Your van and uniform communicate professionalism before you say a word, giving you an edge over unbranded competitors."}]',
  '[{"question": "Can you produce materials that suit Rochester''s conservation area?", "answer": "Yes. We design signage and external materials with awareness of conservation area guidelines and the visual expectations of the heritage High Street. Materials are produced in finishes and styles that complement the historic architecture rather than competing with it."}, {"question": "What workwear suits Rochester hospitality businesses near the castle?", "answer": "We supply branded aprons, shirts, and outerwear in styles and colours appropriate to the heritage setting. Quality fabrics with discreet branding communicate professionalism without looking corporate. Every item is branded consistently and produced to withstand daily commercial use."}, {"question": "How quickly can branded materials be delivered to Rochester?", "answer": "Standard turnaround is seven to ten working days from artwork approval. Rush orders can be accommodated in five working days for most items. We recommend ordering well ahead of the Dickens Festival and peak heritage tourism periods when your materials will have maximum impact."}, {"question": "Do you handle vehicle livery for Medway area trade businesses?", "answer": "Yes. We design and coordinate production of vehicle livery that makes your brand visible across Rochester, Chatham, Strood, and the wider Medway area. For Rochester-based tradespeople, consistent vehicle branding builds recognition in the compact community where your van is seen repeatedly by potential customers."}]',
  'operational'
)
ON CONFLICT (service_slug, town_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  local_context = EXCLUDED.local_context,
  competition_landscape = EXCLUDED.competition_landscape,
  success_approach = EXCLUDED.success_approach,
  local_stats = EXCLUDED.local_stats,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs,
  layout_variant = EXCLUDED.layout_variant;

-- 9. Rochester × AI Chatbots
INSERT INTO public.local_content (service_slug, town_slug, intro_paragraph, local_context, competition_landscape, success_approach, local_stats, pain_points, solutions, faqs, layout_variant)
VALUES (
  'ai-chatbots',
  'rochester',
  'Rochester businesses face a communication challenge amplified by the city''s heritage tourism economy. Heritage visitors plan trips in the evenings and at weekends, searching for dining near Rochester Castle, opening hours for High Street shops, or parking information for cathedral visits. They message businesses through Instagram, email enquiry forms, or Facebook Messenger and expect prompt responses. But the owner of a High Street restaurant is in the kitchen during service. The antique dealer is with a customer. The service provider is on a job in Chatham. By the time they respond, the visitor has made other plans. AI chatbots solve this by providing instant, knowledgeable responses to the repetitive questions that consume Rochester business owners'' time, while capturing details of complex enquiries for personal follow-up. The chatbot knows your Rochester business: your menu, your stock categories, your service area across Medway, your opening hours, and the directions from the castle.',
  'Rochester''s customer enquiry patterns are shaped by the heritage tourism calendar. Castle and cathedral visiting hours drive enquiry timing. The Dickens Festival generates intensive short-term communication surges. Weekend heritage visitors plan during weekday evenings when businesses are closed. Medway residents contact service businesses outside working hours. The High Street''s concentration of businesses means customers often enquire about multiple businesses simultaneously, and the first to respond captures the trade.',
  'AI chatbot adoption in Rochester is non-existent. No local businesses use trained AI for customer communication. Basic auto-reply messages are rare even among the more digitally active High Street businesses. The heritage tourism sector, which would benefit enormously from instant multilingual responses and twenty-four-hour availability, has no automated communication capability. First movers will differentiate dramatically.',
  'We build AI chatbots for Rochester businesses trained on your specific offerings, location context, and common customer queries. The chatbot understands the castle-to-cathedral visitor journey and can provide location-specific guidance. It handles booking enquiries for High Street hospitality, stock questions for antique dealers, and service queries for Medway businesses, responding instantly at any hour.',
  '{"population": 30000, "wider_area": "Medway Towns (270,000+)", "key_areas": ["High Street", "Castle area", "Cathedral precinct", "Creative quarter", "Corn Exchange"], "chatbot_adoption": "zero"}',
  '[{"title": "Rochester restaurant owners missing booking enquiries during service", "description": "A High Street restaurant receives an Instagram DM asking about availability for Saturday evening while the owner is plating food during a busy Friday service. The message sits unread until midnight. By Saturday morning, the potential diners have booked a Chatham restaurant that responded within minutes via automated chat."}, {"title": "Heritage visitors unable to get answers when planning Rochester trips", "description": "A London family planning a Rochester day trip sends enquiries to three High Street businesses on a Wednesday evening. They want to know about parking near the castle, children''s menus, and opening hours. No response arrives until Thursday afternoon. By then, they have chosen Canterbury instead, where a business replied immediately."}, {"title": "Antique dealers missing enquiries from serious collectors", "description": "A collector messages a Rochester antique dealer about a piece they saw on Instagram. The dealer is attending a fair and does not respond for two days. The collector, who was ready to make a significant purchase, has moved on. For high-value businesses where individual enquiries represent substantial revenue, slow response costs real money."}]',
  '[{"title": "Heritage-visitor-aware AI chatbot for Rochester businesses", "description": "We build chatbots that understand Rochester''s heritage context. The AI provides directions from the castle, parking information for cathedral visitors, and recommendations tailored to the tourist journey. It handles the repetitive planning questions that heritage visitors ask, freeing your team to focus on in-person service."}, {"title": "Booking-integrated chatbot for Rochester High Street hospitality", "description": "For Rochester restaurants and cafes, we connect the chatbot to your booking system. It checks availability, suggests alternatives for full time slots, and confirms reservations instantly. The Friday evening DM that would have gone unanswered until midnight is now converted into a confirmed booking within seconds."}, {"title": "Specialist enquiry handling for Rochester''s antique and creative quarter", "description": "For antique dealers and galleries, we build chatbots that can discuss stock categories, answer questions about specific pieces, and capture serious buyer enquiries with full context. The chatbot qualifies collector interest and flags high-value opportunities for your immediate personal attention."}]',
  '[{"question": "Will a chatbot work for a heritage-focused Rochester business?", "answer": "Perfectly. Heritage visitors are among the most likely to benefit from instant responses to planning questions. The chatbot provides helpful, knowledgeable answers about directions from the castle, parking options, opening hours, and your specific offerings. It feels like a welcoming, well-informed guide rather than a corporate robot."}, {"question": "Can the chatbot handle questions about Rochester Castle and the cathedral?", "answer": "We train it on local knowledge relevant to your customers'' experience: directions from the castle and cathedral, parking options, walking routes along the High Street, and your specific services and offerings. The chatbot sounds like someone who knows Rochester and can help visitors make the most of their trip."}, {"question": "How does the chatbot handle high-value antique enquiries?", "answer": "For Rochester antique and specialist businesses, the chatbot captures detailed enquiry information, establishes the collector''s interest area, and immediately flags significant opportunities for your personal follow-up. The customer receives an instant, helpful acknowledgement while you get a complete brief to work from."}, {"question": "How quickly can a chatbot be set up for my Rochester business?", "answer": "Most Rochester implementations are live within two weeks. The first week covers learning your business and training the AI on your offerings, Rochester-specific knowledge, and common questions. The second week involves testing and refinement before launch."}]',
  'authority'
)
ON CONFLICT (service_slug, town_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  local_context = EXCLUDED.local_context,
  competition_landscape = EXCLUDED.competition_landscape,
  success_approach = EXCLUDED.success_approach,
  local_stats = EXCLUDED.local_stats,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs,
  layout_variant = EXCLUDED.layout_variant;

-- 10. Rochester × AI Content
INSERT INTO public.local_content (service_slug, town_slug, intro_paragraph, local_context, competition_landscape, success_approach, local_stats, pain_points, solutions, faqs, layout_variant)
VALUES (
  'ai-content',
  'rochester',
  'Rochester possesses more content material per square metre than almost any town in Kent. A Norman castle with nine centuries of military history. England''s second oldest cathedral. Charles Dickens setting multiple novels in the city''s streets and buildings. The Guildhall Museum housing centuries of Medway artefacts. The annual Dickens Festival transforming the High Street into a Victorian spectacle. An antique and creative quarter with stories behind every piece of stock. This is content gold, yet Rochester''s businesses publish almost none of it. Their blogs are empty, their social media sporadic, and their email lists dormant. The problem is not a lack of material but a lack of time. The restaurant owner who should be writing about Rochester''s food heritage is in the kitchen. The antique dealer who could be publishing collector content is attending fairs. AI-powered content creation solves this by producing locally authentic, brand-consistent content from Rochester''s extraordinary material, keeping your digital presence active without consuming the time you need for running your business.',
  'Rochester''s content landscape is uniquely rich. The castle provides military history content spanning from the Norman Conquest to the present. The cathedral offers ecclesiastical, architectural, and community content year-round. Dickens connections provide literary tourism content with global audience appeal. The Guildhall Museum and Corn Exchange generate cultural and events content. The antique quarter offers specialist content for collector audiences. The Medway Towns context provides local community and service content. Seasonal events including the Dickens Festival, Christmas markets, and heritage weekends create intensive content moments throughout the year.',
  'Content marketing from Rochester businesses is sparse despite the rich material available. Very few businesses maintain active blogs, consistent social media, or email newsletter programmes. The heritage institutions produce strong content, but local businesses do not create complementary commercial content that captures the search traffic these institutions generate. This vacuum means enormous content marketing opportunities exist for any Rochester business willing to publish consistently.',
  'We build AI content systems for Rochester businesses that draw on the city''s extraordinary heritage material to produce content that is both locally authentic and commercially effective. The AI is trained on your brand voice and Rochester''s specific context: the castle, cathedral, Dickens legacy, and High Street character. Every piece is reviewed for accuracy and relevance before publication.',
  '{"population": 30000, "wider_area": "Medway Towns (270,000+)", "key_areas": ["High Street", "Castle area", "Cathedral precinct", "Creative quarter", "Corn Exchange", "Dickens connections"], "content_competition": "very low despite rich material"}',
  '[{"title": "Rochester''s extraordinary content material going completely untapped", "description": "A High Street restaurant operates a hundred metres from Rochester Castle and within sight of the cathedral, surrounded by Dickensian history. They have never published a single piece of content connecting their business to this rich heritage. The content that could build national search visibility and social media engagement sits unused because the owner has no time to write it."}, {"title": "Heritage institutions creating search demand that Rochester businesses fail to capture", "description": "English Heritage, Rochester Cathedral, and Dickens Festival organisers publish content that generates thousands of searches related to Rochester. Local businesses could capture this traffic with complementary commercial content, such as dining near Rochester Castle or shopping during the Dickens Festival, but nobody is creating it."}, {"title": "Inconsistent publishing destroying audience growth for Rochester businesses", "description": "A Rochester business posts enthusiastically around the Dickens Festival, goes silent for months, then resurfaces briefly at Christmas. The audience built during active periods dissipates during silence. Without consistent content production, Rochester businesses cannot build the sustained visibility that drives year-round commercial results."}]',
  '[{"title": "AI content system trained on Rochester''s heritage material and your brand voice", "description": "We build content generation systems that understand Rochester Castle, the cathedral, Dickens connections, the Guildhall Museum, and the High Street character. Content references this heritage naturally because the AI is trained on Rochester''s specific context. Output sounds like your business, enriched with the stories that make your city extraordinary."}, {"title": "Heritage calendar content strategy for Rochester businesses", "description": "We create publishing schedules aligned with Rochester''s heritage calendar: Dickens Festival build-up, castle event seasons, cathedral programme highlights, and community events. The AI produces content ahead of schedule so your business maintains presence through every heritage moment without manual effort."}, {"title": "Multi-format Rochester content from single briefings", "description": "One content brief generates blog posts targeting Rochester and Medway searches, social media posts for Instagram and Facebook, email newsletter content, and Google Business Profile updates. Each format is optimised for its platform while maintaining your brand voice and Rochester heritage context."}]',
  '[{"question": "Can AI content capture the character of Rochester''s heritage?", "answer": "Yes. We train the system on Rochester''s specific history, landmarks, and cultural context. The AI produces content that references the castle, cathedral, Dickens connections, and High Street character naturally because these are part of its knowledge base. Every piece is reviewed for historical accuracy and brand alignment."}, {"question": "How does Rochester heritage content help my business rank in search?", "answer": "Regular content connecting your business to Rochester landmarks and events builds topical authority that Google rewards. A restaurant publishing content about dining near Rochester Castle captures searches that generic restaurant content never would. In Rochester''s low-competition content landscape, consistent publishing delivers rapid ranking improvements."}, {"question": "How much content can the AI produce for my Rochester business?", "answer": "A typical monthly output includes four blog posts, sixteen social media posts, two email newsletters, and regular Google Business Profile updates. Volume is adjustable. Given the richness of Rochester''s content material, the system rarely struggles for topics. The heritage calendar alone provides enough material for years of consistent publishing."}, {"question": "Can I review content before it goes live?", "answer": "Absolutely. Every piece is available for your review and approval before publication. Given Rochester''s heritage sensitivity, we are particularly careful about historical accuracy and appropriate tone. Most clients find the AI output requires minimal editing, but you always have final approval."}]',
  'authority'
)
ON CONFLICT (service_slug, town_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  local_context = EXCLUDED.local_context,
  competition_landscape = EXCLUDED.competition_landscape,
  success_approach = EXCLUDED.success_approach,
  local_stats = EXCLUDED.local_stats,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs,
  layout_variant = EXCLUDED.layout_variant;

-- 11. Rochester × AI Automation
INSERT INTO public.local_content (service_slug, town_slug, intro_paragraph, local_context, competition_landscape, success_approach, local_stats, pain_points, solutions, faqs, layout_variant)
VALUES (
  'ai-automation',
  'rochester',
  'AI automation offers Rochester businesses the ability to learn from the patterns hidden in their own operations and improve continuously without hiring analysts or consultants. A High Street restaurant''s AI learns which heritage events predict full bookings and adjusts staffing recommendations before the Dickens Festival even begins. An antique dealer''s AI identifies which collector segments respond to which types of communication and personalises outreach automatically. A Medway service business''s AI learns from twelve months of quoting data to predict which jobs are most likely to convert and prioritises follow-up accordingly. Rochester''s heritage economy creates particularly rich patterns: the correlation between castle visitor numbers and High Street spending, the impact of cathedral events on nearby hospitality, the predictable rhythms of the Dickens Festival and heritage weekends. AI automation turns these patterns from invisible background noise into actionable operational intelligence.',
  'Rochester''s business data contains uniquely learnable patterns shaped by the heritage economy. Castle visitor numbers correlate with High Street footfall in predictable ways. Cathedral service schedules and event programmes affect surrounding business demand. The Dickens Festival creates quantifiable ripple effects across hospitality, retail, and services. Weather conditions affect heritage visitor behaviour differently from regular shopping patterns. Seasonal transitions between peak heritage tourism and quieter Medway-focused trading follow consistent yearly cycles.',
  'AI automation adoption in Rochester is non-existent. No local businesses use AI-enhanced workflows. Traditional automation itself is uncommon. The heritage sector, which generates the most predictable data patterns, has not explored AI applications. This creates a significant first-mover advantage for Rochester businesses willing to implement AI systems that learn from their operational data.',
  'We implement AI automation for Rochester businesses by identifying the data patterns most relevant to each business type. For heritage-adjacent hospitality, we focus on demand prediction aligned to the castle, cathedral, and Dickens Festival calendar. For antique dealers, we build customer intelligence and stock matching systems. For Medway service businesses, we create scheduling optimisation and conversion prediction tools. Every implementation starts focused and grows smarter with data.',
  '{"population": 30000, "wider_area": "Medway Towns (270,000+)", "key_areas": ["High Street", "Castle area", "Cathedral precinct", "Creative quarter", "Corn Exchange"], "ai_adoption": "zero"}',
  '[{"title": "Rochester businesses failing to anticipate predictable heritage event demand", "description": "Every Dickens Festival catches the same businesses unprepared. Every bank holiday heritage weekend creates the same staffing crunch. Without AI learning from historical patterns, Rochester businesses react to the same predictable surges year after year instead of preparing with data-driven precision."}, {"title": "Antique dealers with collector data they never analyse", "description": "A Rochester antique dealer has years of transaction records, collector communications, and browsing patterns from their website. This data contains clear signals about which collectors are ready to buy, which are lapsing, and which categories generate the most interest. None of it is being analysed."}, {"title": "Manual decision-making limiting Rochester business efficiency", "description": "Every staffing decision, pricing choice, and stock order in a typical Rochester business flows through the owner''s personal judgement. During a busy Saturday when the castle is full and the High Street is packed, the owner is making reactive decisions that data-driven AI could have anticipated and prepared for days in advance."}]',
  '[{"title": "Heritage event demand prediction for Rochester businesses", "description": "We build AI that learns from castle visitor data, cathedral event schedules, Dickens Festival patterns, and historical trading data to predict demand for your Rochester business. Staffing, stock, and preparation are informed by intelligent forecasting rather than last-minute scrambles during heritage peaks."}, {"title": "Collector intelligence AI for Rochester''s antique quarter", "description": "For antique dealers and specialist retailers, we implement AI that analyses collector behaviour, purchasing patterns, and engagement data. The system identifies active buyers, predicts lapsing relationships, and recommends personalised communication that converts browsing collectors into loyal customers."}, {"title": "Continuously improving operations from Rochester business data", "description": "Every transaction, booking, and customer interaction generates data that makes the AI smarter. Over time, the system identifies optimisation opportunities in scheduling, pricing, inventory, and customer engagement that would be invisible to manual analysis, creating a compounding advantage for your Rochester business."}]',
  '[{"question": "Does my Rochester business generate enough data for AI automation?", "answer": "Most Rochester businesses have sufficient data in their existing systems. Booking records, sales data, customer communications, and website analytics all provide inputs for AI learning. A High Street restaurant with six months of trading data has enough for meaningful demand prediction. We assess your specific data during the initial consultation."}, {"question": "How does AI automation connect to Rochester''s heritage tourism patterns?", "answer": "We integrate publicly available data about castle events, cathedral programmes, and festival schedules with your own business data. The AI learns the specific correlations between heritage activity and your commercial patterns, producing forecasts and recommendations that account for Rochester''s unique cultural calendar."}, {"question": "How long before AI automation shows results for my Rochester business?", "answer": "Automation efficiency gains are immediate from day one. The AI learning component typically needs two to three months of data to produce reliable predictions and recommendations. By month three, most Rochester businesses see measurable improvements in demand management and operational decision-making."}, {"question": "Is AI automation suitable for a small Rochester independent?", "answer": "Yes. We scale implementations to match your business size. Even basic AI automation delivers efficiency gains that exceed the investment for most Rochester independents. We start with a single high-impact workflow and expand as the system proves its value. You do not need to be a large business to benefit from intelligent automation."}]',
  'authority'
)
ON CONFLICT (service_slug, town_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  local_context = EXCLUDED.local_context,
  competition_landscape = EXCLUDED.competition_landscape,
  success_approach = EXCLUDED.success_approach,
  local_stats = EXCLUDED.local_stats,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs,
  layout_variant = EXCLUDED.layout_variant;
