-- ============================================================
-- seed-industry-content-plumbers.sql
-- Industry content for Plumbers across all 11 services
-- Safe to re-run: uses ON CONFLICT ... DO UPDATE
-- ============================================================

-- 1. Plumbers × Web Design
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'plumbers',
  'web-design',
  'When a pipe bursts at midnight or a boiler fails in January, the homeowner''s first action is a frantic Google search followed by a snap judgement about whichever plumber''s website they land on. Your website has roughly five seconds to communicate three things: you are qualified, you are available, and you can be contacted instantly. Most plumbing websites fail this test — phone numbers are buried in contact pages, Gas Safe registration numbers are hidden in footer text, and there is no indication of whether you handle emergencies, boiler installations, or bathroom fitting. A plumbing website must serve two distinct audiences simultaneously: the panicked homeowner with water pouring through their ceiling who needs a number to call right now, and the considered buyer researching a new boiler or bathroom renovation who needs to see credentials, completed projects, and transparent pricing guides. We build plumbing websites that convert both emergency callers and planned-project researchers with a design that puts trust signals and contact methods exactly where each audience needs them.',
  'Plumbing is a trust-critical trade — customers are inviting you into their homes to work on systems that, if done incorrectly, risk water damage, gas leaks, or both. Your website must immediately establish credibility through visible Gas Safe registration, insurance details, and manufacturer accreditations. Without these trust signals presented prominently, homeowners choose the competitor whose site makes them feel safest. Emergency callers who cannot find your number in two seconds call someone else.',
  'We design around the split nature of plumbing work: emergency callouts needing instant mobile contact, and planned projects needing detailed service pages. A persistent click-to-call emergency banner sits above the fold on every mobile page. Planned service sections cover boiler installations, bathroom fitting, and central heating with manufacturer logos, completed project galleries, and transparent pricing guidance.',
  '[{"title": "Emergency callers cannot find your phone number fast enough", "description": "When water is flooding a kitchen or a boiler has stopped working in freezing temperatures, homeowners will not navigate menus or scroll through service descriptions. If your phone number is not visible and tappable within two seconds on mobile, they hit the back button and call the next plumber Google shows them."}, {"title": "Gas Safe and manufacturer accreditations not prominently displayed", "description": "Gas Safe registration is a legal requirement for gas work and the most important trust signal for boiler installations. Most plumbing websites either bury the registration number in small footer text or display no accreditation at all, losing customers to competitors who make their qualifications impossible to miss."}, {"title": "No separation between emergency services and planned projects", "description": "A homeowner researching a bathroom renovation has completely different needs from someone with a burst pipe. When both audiences land on the same generic services page, neither finds what they need quickly enough. Emergency callers cannot find the phone number, and renovation researchers cannot find the portfolio or pricing information they need."}]',
  '[{"title": "Emergency-first mobile design with persistent click-to-call", "description": "A high-contrast emergency banner with your phone number visible on every page without scrolling. On mobile, a single tap initiates the call. After-hours messaging confirms emergency availability. This captures the urgent callout work that generates the highest per-hour revenue in plumbing."}, {"title": "Trust-forward Gas Safe and manufacturer accreditation display", "description": "Your Gas Safe registration number with a direct verification link, manufacturer accreditation logos for brands like Worcester Bosch, Vaillant, and Baxi, and public liability insurance details are displayed prominently across the site. This independent verification converts cautious homeowners who are comparing plumbers on trust."}, {"title": "Dual-pathway design for emergencies and planned work", "description": "Clear visual separation between emergency services and planned projects. Emergency visitors see immediate contact options and service coverage. Planned-project visitors find detailed boiler installation guides, bathroom fitting portfolios, and central heating service pages with pricing guidance and booking forms."}]',
  '[{"question": "How do you make a plumbing website generate emergency callout work?", "answer": "Emergency design prioritises speed and visibility. We place a clickable phone number in a high-contrast banner visible without scrolling on every mobile page. Schema markup tells Google your business handles emergency plumbing, and after-hours messaging confirms you take urgent calls. This captures the highest-value work in plumbing."}, {"question": "Can customers verify my Gas Safe registration through the website?", "answer": "Yes. We display your Gas Safe registration number with a direct link to the Gas Safe Register verification page. Visitors can confirm your registration status independently, which builds far more trust than simply stating you are registered. Manufacturer accreditation logos are displayed alongside with links to their approved installer directories."}, {"question": "Should I show pricing on my plumbing website?", "answer": "We recommend indicative pricing ranges or starting-from prices for common services like boiler installations, power flush treatments, and bathroom fitting. This sets expectations, reduces tyre-kicker enquiries, and attracts customers who are serious about proceeding at your price point. Exact quotes still require a site visit."}, {"question": "Will the website work well on mobile phones?", "answer": "Over seventy percent of plumbing enquiries come from mobile devices, and for emergencies that figure is even higher. Every site we build is mobile-first with fast loading times, tap-to-call functionality, and forms designed for thumb-friendly completion. Emergency features are specifically designed for panicked, one-handed phone use."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 2. Plumbers × SEO
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'plumbers',
  'seo',
  'Plumbing generates some of the most commercially valuable local search traffic of any trade. Emergency searches like "emergency plumber near me" and "burst pipe plumber" represent customers willing to pay premium callout rates immediately. Planned searches like "boiler installation cost" and "bathroom fitter Kent" represent projects worth thousands of pounds. Yet the majority of plumbers have no SEO strategy whatsoever, relying on word of mouth, Checkatrade profiles, and paid Google Ads that disappear the moment the budget runs out. The plumbing trade has a natural SEO advantage: the breadth of services creates dozens of targetable keyword clusters. Boiler installations, central heating repairs, bathroom fitting, drain unblocking, leak detection, power flushing, and emergency callouts each represent separate search categories with distinct intent and competition levels. We build plumbing SEO campaigns that systematically capture traffic across every service you offer, prioritising the high-value emergency and boiler installation searches that deliver the greatest return on your investment.',
  'Emergency plumbing searches have among the highest conversion rates of any local service query. A homeowner with water pouring through their ceiling will call the first credible plumber they find. If your business is invisible for these searches, you are surrendering premium-rate callout work to whoever ranks above you. Beyond emergencies, boiler installation searches represent the single highest-value keyword cluster in domestic plumbing, often worth several thousand pounds per converted enquiry.',
  'We prioritise the searches that generate the most revenue per click: emergency plumbing terms with 24/7 schema markup, boiler installation keywords targeting specific manufacturers and fuel types, and bathroom fitting searches in your service area. Each service gets a dedicated landing page. Google Business Profile optimisation features completed project photos and a systematic review programme.',
  '[{"title": "Invisible for emergency plumbing searches in your area", "description": "Emergency plumbing searches spike at evenings, weekends, and during cold snaps when pipes freeze and boilers fail. The plumbers appearing in the Map Pack and top organic results for these searches capture work at premium callout rates. Without emergency-focused SEO, your business is invisible at the exact moments when customers will pay the most for immediate help."}, {"title": "Boiler installation searches dominated by national companies and directories", "description": "Searches like boiler installation cost and new boiler quotes are targeted aggressively by national heating companies like British Gas, and by Checkatrade and MyBuilder. Without dedicated, locally-optimised boiler content, your business is buried beneath these well-funded competitors for the highest-value planned work in plumbing."}, {"title": "No content targeting specific plumbing services beyond generic terms", "description": "A single services page listing everything from dripping taps to full central heating installations cannot rank for any specific search term. Customers searching for power flush, underfloor heating installation, or unvented cylinder fitting find competitors who have dedicated pages addressing those exact requirements."}]',
  '[{"title": "Emergency plumbing SEO with 24/7 schema markup", "description": "Dedicated emergency pages targeting burst pipe plumber, no hot water emergency, and leak repair urgent searches. LocalBusiness schema markup declares 24/7 availability, emergency service capability, and average response times. Google Business Profile optimisation ensures Map Pack visibility for after-hours urgent searches across your coverage area."}, {"title": "Boiler installation content targeting manufacturer and fuel-type searches", "description": "Comprehensive landing pages for boiler installations segmented by manufacturer — Worcester Bosch, Vaillant, Baxi, Ideal — and by fuel type and property type. Cost guides, efficiency comparisons, and grant eligibility information target the informational searches that precede high-value boiler purchase decisions."}, {"title": "Service-specific landing pages for every plumbing discipline", "description": "Individual optimised pages for bathroom fitting, central heating installation, power flushing, drain unblocking, leak detection, underfloor heating, unvented cylinders, and every other service you offer. Each page targets the specific terms homeowners search for that service, capturing traffic a generic page cannot."}]',
  '[{"question": "How quickly can I rank for emergency plumber searches?", "answer": "Google Business Profile optimisation can improve Map Pack visibility for emergency searches within four to six weeks. Organic rankings for emergency plumber plus your location typically require three to six months. We prioritise emergency visibility because it delivers the highest immediate revenue — a single captured emergency callout can cover months of SEO investment."}, {"question": "Is it worth targeting boiler installation keywords against British Gas?", "answer": "Yes. While you cannot outspend national companies on broad terms, local SEO targeting specific towns and postcodes is highly effective. Homeowners increasingly prefer local Gas Safe registered installers over national companies, and dedicated local content outranks generic national pages for location-specific searches."}, {"question": "How many Google reviews do I need to appear in the Map Pack?", "answer": "Consistency matters more than a specific number. We implement automated review request workflows triggered after each completed job. Most plumbers see meaningful Map Pack improvements after accumulating fifteen to twenty recent, detailed reviews. The recency and specificity of reviews matters as much as the total count."}, {"question": "Can SEO reduce my spend on Google Ads?", "answer": "Yes. As organic rankings and Map Pack visibility improve, direct enquiries increase and your reliance on paid advertising decreases. Most plumbing clients maintain a small Ads budget for emergency terms during the early months, then gradually reduce it as organic visibility strengthens. The long-term cost per lead from SEO is significantly lower than paid advertising."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 3. Plumbers × Lead Capture
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'plumbers',
  'lead-capture',
  'Plumbing websites typically only capture visitors who are ready to call or fill in a contact form right now — and that represents a small fraction of total traffic. The homeowner researching boiler replacements three months before their current system fails, the landlord comparing plumbers for a property portfolio, and the couple browsing bathroom fitting ideas are all high-value prospects who visit your site and leave without a trace. Effective lead capture for plumbers means offering tools that provide genuine value at every stage of the buying journey: a boiler replacement cost calculator for the researcher, a landlord property maintenance checklist for the portfolio owner, and a bathroom project planner for the couple designing their renovation. Each tool captures contact details and project specifications in exchange for information the visitor actually wants, transforming anonymous browsers into named prospects with defined requirements. We build lead capture systems for plumbing businesses that convert casual researchers into booked consultations and repeat maintenance customers.',
  'Plumbing projects range from emergency callouts requiring no lead capture to boiler installations and bathroom renovations involving weeks of research. For these considered purchases, customers visit multiple plumber websites before choosing. Without capturing their details during the research phase, you lose every prospect who does not call on their first visit. A structured lead capture system ensures you have their contact information and project requirements, allowing proactive follow-up through the decision period.',
  'We build plumbing-specific lead magnets: boiler replacement cost calculators asking about property size, current system type, and fuel preferences; bathroom project planners collecting room dimensions and design preferences; and landlord gas safety compliance checklists. Each tool captures details and feeds into an automated follow-up sequence.',
  '[{"title": "Boiler replacement researchers leaving without making contact", "description": "A homeowner researching new boilers visits an average of four to five plumber websites before requesting a quote. Without a compelling reason to share their details — like a personalised cost estimate — these high-value prospects remain anonymous. You cannot follow up, and they choose whichever plumber they remember or find again when ready."}, {"title": "Landlords comparing plumbers with no way to capture their details", "description": "Landlords managing multiple properties represent the most valuable long-term plumbing customers, generating recurring gas safety checks, boiler servicing, and emergency callout work. Without lead magnets addressing landlord-specific concerns — compliance deadlines, portfolio management, preferred contractor arrangements — these prospects slip away to competitors."}, {"title": "Generic contact forms collecting insufficient project information", "description": "A contact form asking for name, email, and message produces vague enquiries that require extensive back-and-forth before you can provide a meaningful quote. Without knowing the property type, current boiler model, number of radiators, or bathroom dimensions, every initial response is a generic request for more information."}]',
  '[{"title": "Boiler replacement cost calculator", "description": "An interactive tool asking about property type, number of bedrooms and bathrooms, current boiler type, preferred fuel source, and any hot water requirements. Homeowners receive an indicative cost range for their specific situation. You receive their full contact details alongside detailed property and heating specifications ready for a site survey booking."}, {"title": "Landlord gas safety and compliance toolkit", "description": "A downloadable compliance checklist covering gas safety certificate deadlines, boiler servicing schedules, and legal obligations captures email addresses from landlords. A follow-up sequence positions your business as their preferred gas engineer, offering annual service contracts and priority emergency callout arrangements for their portfolio."}, {"title": "Bathroom project planner with design preferences", "description": "An interactive planner collecting room dimensions, fixture preferences, accessibility requirements, and budget range captures comprehensive project details from homeowners planning renovations. They receive a project summary document. You receive a fully qualified lead with specifications detailed enough to prepare a meaningful estimate before the site visit."}]',
  '[{"question": "What is the best lead magnet for a plumbing business?", "answer": "A boiler replacement cost calculator consistently generates the highest volume of qualified leads for plumbers. Homeowners are naturally curious about replacement costs, and the calculator provides personalised estimates that feel valuable. For businesses focused on bathroom fitting, a project planner with design preference collection performs equally well."}, {"question": "How does the boiler cost calculator work without committing me to a price?", "answer": "The calculator provides indicative ranges based on property type, boiler specifications, and complexity factors. Clear disclaimers explain that final pricing requires a site survey to assess pipework, flue routing, and installation access. The purpose is to give homeowners useful guidance while capturing their property details for your follow-up."}, {"question": "Can lead capture help me win landlord maintenance contracts?", "answer": "Yes. Landlord compliance toolkits and gas safety checklists capture details from property owners who need ongoing plumbing support. The automated follow-up sequence positions your business for annual gas safety inspections, boiler servicing contracts, and preferred contractor arrangements that generate reliable recurring revenue."}, {"question": "How do captured leads get delivered to me?", "answer": "Every lead generates an instant notification via email, SMS, or both with full project details. We integrate with CRM systems, Google Sheets, or whatever tools you already use. Each lead includes the prospect''s contact information, property details, project specifications, and any preferences they indicated."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 4. Plumbers × Business Automation
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'plumbers',
  'business-automation',
  'Plumbers spend their days under sinks, in loft spaces, and behind boilers — not sitting at desks managing admin. Yet the administrative demands of a plumbing business are relentless: quote requests arrive while you are elbow-deep in a repair, sent quotes go unfollowed because you are already on the next job, boiler service reminders need sending to hundreds of customers, gas safety certificate renewals need tracking across landlord portfolios, and completed jobs generate no reviews because you never got around to asking. Business automation for plumbers creates workflows that handle these repetitive tasks without your involvement. A new enquiry receives an instant acknowledgement with your availability. A sent quote triggers follow-up messages at forty-eight hours and one week. A completed boiler installation triggers a review request and schedules the first annual service reminder. Landlord customers receive automatic gas safety certificate renewal reminders sixty days before expiry. These are practical, trade-focused automations that keep your business running professionally while you focus on the work that generates revenue.',
  'Plumbers lose significant revenue annually to forgotten quote follow-ups, missed service renewal reminders, and uncollected reviews. When every working hour is spent on-site, admin tasks get pushed to late evenings and inevitably fall through the cracks. Automation ensures every enquiry gets an instant response, every quote gets chased, every boiler installation triggers a service reminder chain, and every completed job generates a review request. It transforms a busy sole trader into a professionally managed operation.',
  'We automate the plumbing business cycle: instant enquiry acknowledgements, quote follow-up sequences, job booking confirmations, post-completion review requests, annual boiler service reminders, gas safety certificate renewal tracking for landlord clients, and seasonal heating system check campaigns before winter.',
  '[{"title": "Quotes sent but never followed up while on the next job", "description": "A plumber sends a boiler installation quote on Monday, starts an emergency repair on Tuesday, and by Friday the quote has gone cold because no follow-up was sent. The customer, who was genuinely interested, chose the competitor who sent a polite check-in message on Wednesday. This pattern repeats weekly, costing thousands in lost revenue."}, {"title": "Boiler service reminders not sent to existing customers", "description": "Annual boiler servicing is a reliable revenue stream, but most plumbers have no system for reminding customers when their service is due. Without automated reminders, customers either forget about servicing entirely or search Google and find a different engineer when they do remember — losing you recurring income."}, {"title": "Gas safety certificate renewals missed for landlord clients", "description": "Landlords rely on their gas engineer to remind them when certificates are due for renewal. Tracking expiry dates across multiple properties using memory or spreadsheets inevitably leads to missed renewals, putting landlords at legal risk and damaging the trust that underpins your most valuable ongoing customer relationships."}]',
  '[{"title": "Automated quote follow-up sequences", "description": "Every sent quote triggers a timed sequence: a friendly check-in after forty-eight hours, a reminder after one week with a link to your reviews, and a final availability message after two weeks. Each message references the specific job details. Quote conversion rates typically improve by thirty to forty percent with consistent follow-up."}, {"title": "Boiler service and annual maintenance reminders", "description": "Every boiler installation and service automatically schedules a reminder for the following year. Customers receive a personalised message when their service is due, with a direct booking link. A follow-up reminder goes out if they do not respond within two weeks. This systematically generates recurring revenue from your existing customer base."}, {"title": "Gas safety certificate tracking for landlord portfolios", "description": "Every landlord property''s gas safety certificate expiry date is tracked automatically. Reminders go to both you and the landlord sixty days before expiry, with a booking link for the renewal visit. This protects landlords from legal non-compliance, demonstrates professional management, and secures your position as their preferred gas engineer."}]',
  '[{"question": "What plumbing business tasks can be automated?", "answer": "The highest-impact automations are enquiry acknowledgements, quote follow-ups, job booking confirmations, post-completion review requests, annual boiler service reminders, gas safety certificate renewal tracking, and seasonal heating check campaigns. We also automate appointment reminders, payment follow-ups, and warranty registration for new boiler installations."}, {"question": "How do gas safety certificate reminders work for my landlord clients?", "answer": "We record the expiry date for every gas safety certificate you issue. The system automatically sends reminders to both you and the landlord sixty days and thirty days before expiry. If no booking is made, escalation reminders follow. This ensures no certificate lapses, protecting your landlords from prosecution and securing your annual renewal visits."}, {"question": "Will automated quote follow-ups feel pushy to customers?", "answer": "No. Messages are personalised with the customer''s name and specific job details, timed at natural intervals, and written in a helpful rather than pressuring tone. Most customers appreciate the follow-up — it often prompts questions they had forgotten to ask and demonstrates a professional, attentive approach."}, {"question": "Can automations connect to tools I already use?", "answer": "Yes. We integrate with common tools plumbers use including Google Calendar, QuickBooks, Xero, ServiceM8, and Tradify. If you track jobs in a spreadsheet or notebook, we can build automations around that too. The goal is to enhance your existing workflow without forcing you to learn new software."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 5. Plumbers × Branding
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'plumbers',
  'branding',
  'Plumbing is one of the few trades where customers routinely let a stranger into their home to access their most private spaces — bathrooms, kitchens, bedrooms with en-suites. Trust is not just important; it is the prerequisite for every job. Your brand is the first signal of trustworthiness, and it is judged in multiple contexts: the van parked on the driveway, the uniform worn at the front door, the quote document emailed after a site visit, and the Google listing seen during the initial search. Most plumbing businesses operate with a clip-art logo featuring a spanner or dripping tap, inconsistent colours across their van and website, and quotes sent as plain text emails. This generic, unprofessional presentation makes it impossible to differentiate from dozens of other plumbers in the area and undermines the trust needed for customers to hand over their house keys for a boiler installation lasting several days. We create complete brand identities for plumbing businesses that communicate reliability, technical competence, and professionalism across every customer touchpoint from the first Google search to the final invoice.',
  'Customers choose plumbers based on perceived trustworthiness more than any other factor. A cohesive, professional brand — consistent across your van, website, workwear, and documentation — immediately distinguishes your business from the majority of plumbers running mismatched visuals. Strong branding also supports premium pricing for high-value work like boiler installations and bathroom fitting, where customers associate visual professionalism with quality workmanship and reliability.',
  'We design plumbing brands that project technical competence and reliability — clean, confident design systems using strong, trust-associated colour palettes. No clip-art spanners or cartoon water drops. Every brand system is tested across van livery, workwear embroidery, Gas Safe branded documentation, and digital assets before finalisation.',
  '[{"title": "Generic branding indistinguishable from every other plumber", "description": "Clip-art spanners, cartoon water drops, and blue-and-white colour schemes dominate plumbing branding. When every plumber in the area looks identical, customers cannot differentiate based on brand impression and default to choosing on price alone — undermining the premium positioning that quality workmanship deserves."}, {"title": "Van livery failing to build trust on residential driveways", "description": "A plumber''s van parked on a customer''s driveway is visible to every neighbour. Cheap vinyl lettering, faded wraps, and cluttered designs fail to project the professionalism that generates referral enquiries from neighbours watching through their windows. The van is your most visible marketing asset, and most plumbing vans waste it."}, {"title": "Quote documents that undermine the value of technical expertise", "description": "Plumbers quoting thousands of pounds for boiler installations or bathroom renovations often send plain text emails or handwritten estimates. Without a professionally designed quote template reflecting your Gas Safe accreditation, manufacturer certifications, and the technical scope of the work, customers struggle to see the value behind the price."}]',
  '[{"title": "Trust-first brand identity system", "description": "We design brand identities built around trust signals: strong, authoritative colour palettes, clean modern typography, and design elements that communicate technical competence and reliability. The brand system works cohesively across digital and physical formats, creating a consistent professional impression at every customer interaction."}, {"title": "Professional van livery designed for residential trust", "description": "Van designs that project competence and reliability on residential driveways: clean layouts, legible contact details, Gas Safe registration displayed prominently, and a design that stands apart from the generic plumbing vans parked on every street. The livery builds trust with the customer and generates enquiries from neighbours."}, {"title": "Branded technical documentation and quote templates", "description": "Professional quote and estimate templates featuring your brand identity, Gas Safe registration, manufacturer accreditations, detailed scope of work breakdowns, and warranty information. These documents elevate the sales process for high-value work like boiler installations and bathroom fitting, justifying premium pricing through professional presentation."}]',
  '[{"question": "What should a plumbing brand communicate?", "answer": "Reliability, technical competence, and trustworthiness. The most effective plumbing brands use strong, confident colour palettes — deep blues, charcoal greys, or teals — combined with clean modern typography. The brand should feel professional and established rather than generic or gimmicky, reflecting the serious nature of gas and water work."}, {"question": "Do you design van livery for plumbers?", "answer": "Yes. Van livery is a central component of our plumbing branding packages. We create wrap or vinyl designs optimised for your vehicle type, prominently displaying your Gas Safe registration, phone number, and services. The design is clean, professional, and distinct from the generic plumbing van aesthetic."}, {"question": "Can professional branding really help me charge more?", "answer": "Yes. For considered purchases like boiler installations and bathroom renovations, customers use visual cues to assess quality before speaking to you. Consistent branding across your van, website, workwear, and quotes positions you as an established professional, making customers more comfortable with higher pricing than they would accept from an unbranded sole trader."}, {"question": "How long does a plumbing brand identity take to complete?", "answer": "A complete brand identity including logo, colour system, typography, van livery design, workwear specifications, documentation templates, and brand guidelines takes three to four weeks from initial brief to final delivery. We present concepts after week one, refine based on your feedback, and deliver all production-ready files and specifications."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 6. Plumbers × Social Media Setup
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'plumbers',
  'social-media-setup',
  'Plumbing might not seem like natural social media content, but the reality is that behind-the-scenes plumbing work generates genuine fascination and engagement. Timelapse boiler installations, before-and-after bathroom transformations, drain camera footage revealing what caused a blockage, and seasonal heating tips all perform well on platforms like Instagram and Facebook. The problem is that most plumbers either have no social presence or post occasionally with no consistency, branding, or strategy. Setting up social media properly for a plumbing business means creating branded profiles that communicate Gas Safe credentials, establishing content categories that showcase different aspects of your work, and building a documentation system that makes capturing content on-site genuinely effortless alongside a physically demanding work schedule. A well-maintained social presence demonstrates active trading, builds trust through visible completed work, and generates referrals when satisfied customers share your posts with friends facing similar plumbing issues. We set up social media for plumbers with branded templates, content calendars, and capture systems designed for tradespeople who work with pipes, not pixels.',
  'Homeowners and landlords increasingly check social media before hiring a plumber, looking for evidence of recent work, professional presentation, and customer satisfaction. A plumber with no social presence raises questions about trading status and reliability. Regular posts showing completed boiler installations, bathroom projects, and satisfied customers build the social proof that converts cautious prospects into booked jobs, particularly for high-value planned work.',
  'We set up plumbing social accounts with project documentation templates for boiler installations and bathroom renovations, quick-capture formats for emergency callout stories, and seasonal content calendars aligned to heating demand cycles. Photo guidelines ensure your team can document work on-site in thirty seconds between tasks.',
  '[{"title": "No social media presence despite completing impressive work daily", "description": "Plumbers complete boiler installations, bathroom renovations, and complex pipework modifications every week, but none of this work reaches social media. These projects — particularly bathroom before-and-after transformations — generate strong engagement and build trust with prospective customers who never see evidence of your capabilities."}, {"title": "Sporadic posting creating an impression of inactivity", "description": "A Facebook page with the last post from four months ago looks worse than having no social presence at all. Potential customers assume the business is struggling or no longer trading. Without a sustainable posting system, social media becomes an inconsistent liability rather than a consistent marketing asset."}, {"title": "No time or system for capturing content while working", "description": "Plumbers work physically demanding schedules in cramped, dark spaces with dirty hands. Without an extremely simple, fast system for documenting work on-site, social media content never gets captured and the marketing opportunity of every completed job is permanently lost."}]',
  '[{"title": "Professionally branded plumbing social profiles", "description": "We set up Instagram, Facebook, and Google Business profiles with consistent branding, Gas Safe credentials displayed prominently, and bios highlighting your key services and coverage area. Organised highlights showcase bathroom projects, boiler installations, and customer testimonials in easily browsable categories."}, {"title": "Thirty-second on-site capture system", "description": "A practical documentation system designed for the realities of plumbing work: quick photo angles for before-and-after bathroom shots, boiler installation progress documentation, and a shared folder that makes uploading from a dirty phone on-site effortless. The system generates a steady content stream without disrupting your work schedule."}, {"title": "Seasonal content calendar aligned to heating demand", "description": "A twelve-month content plan timed to plumbing demand cycles: boiler service reminders before autumn, heating efficiency tips in winter, bathroom renovation inspiration in spring, and outdoor tap and drainage content in summer. Each season''s content is prepared with branded templates so posting takes minutes."}]',
  '[{"question": "Which social media platforms work best for plumbers?", "answer": "Facebook is the strongest platform for plumbers due to its community group reach and the demographic of homeowners making plumbing decisions. Instagram works well for bathroom renovation showcases and boiler installation timelapses. We set up both platforms with consistent branding and content strategies tailored to each."}, {"question": "What kind of plumbing content performs well on social media?", "answer": "Bathroom before-and-after transformations consistently generate the highest engagement. Boiler installation timelapses, drain camera footage, and heating system explanations also perform well. Seasonal tips like preparing pipes for winter or boiler servicing reminders generate shares and position you as a helpful expert."}, {"question": "How often should a plumber post on social media?", "answer": "Three posts per week is effective: one project showcase such as a bathroom reveal or boiler installation, one educational or seasonal tip, and one behind-the-scenes or customer testimonial post. Our template system makes creating each post a five-minute task rather than a creative exercise."}, {"question": "Can I manage social media myself after the initial setup?", "answer": "Yes. Our setup includes branded templates, a content calendar, and a quick-capture guide specifically designed for tradespeople. Most plumbers find they can maintain their social presence in under twenty minutes per week once the system and templates are in place. We train you on the process during handover."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 7. Plumbers × Digital Marketing
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'plumbers',
  'digital-marketing',
  'Digital marketing for plumbing businesses must account for two fundamentally different customer journeys: the emergency caller who needs a plumber in the next hour, and the homeowner planning a boiler replacement or bathroom renovation over the coming weeks. Most plumbing digital marketing either focuses entirely on emergency Google Ads — burning through budget on competitive clicks — or takes a generic "post on Facebook and hope" approach that generates minimal return. An effective plumbing digital marketing strategy coordinates multiple channels with distinct objectives: Google Ads for emergency callout visibility during off-peak organic ranking periods, remarketing campaigns targeting boiler quote page visitors who did not convert, email marketing to existing customers for annual service reminders, and social media campaigns timed to seasonal heating demand. Each channel serves a specific commercial purpose with measurable outcomes. We build integrated digital marketing strategies for plumbers that capture emergency demand, nurture planned-project researchers through to booking, and reactivate past customers for recurring service revenue.',
  'Relying on a single marketing channel — whether that is word of mouth, Checkatrade, or Google Ads alone — leaves your plumbing business vulnerable to fluctuations you cannot control. Checkatrade raises fees, Google Ads costs increase during winter demand spikes, and word of mouth slows during quiet periods. A diversified digital marketing strategy across search, social, email, and remarketing creates multiple revenue streams, smoothing seasonal demand and reducing dependency on any single source.',
  'We build plumbing marketing strategies around revenue priorities: emergency callout campaigns on Google targeting after-hours searches, boiler installation remarketing for quote page visitors, email campaigns to existing customers timed to annual service cycles, and seasonal social media campaigns ahead of winter heating demand. Every channel is measured against cost per enquiry.',
  '[{"title": "Google Ads spending generating calls but poor return on investment", "description": "Many plumbers run Google Ads targeting broad terms like plumber near me and pay premium rates per click during competitive periods. Without proper call tracking, negative keyword management, and landing page optimisation, a significant portion of ad spend generates irrelevant calls — tenants calling about landlord responsibilities, DIY advice seekers, or locations outside your service area."}, {"title": "No marketing strategy for high-value planned work", "description": "Boiler installations and bathroom renovations are the most profitable plumbing services, yet most marketing efforts focus on emergency callout visibility. Without dedicated campaigns targeting homeowners researching these considered purchases — through content, remarketing, and email nurture — you compete solely on price for the highest-value work."}, {"title": "Seasonal demand swings with no proactive marketing", "description": "Plumbing demand peaks in winter with heating failures and frozen pipes, then drops through summer. Without proactive marketing — promoting boiler servicing before autumn, bathroom renovations during quieter months, and outdoor plumbing work in summer — your revenue follows the same seasonal rollercoaster without any smoothing."}]',
  '[{"title": "Emergency Google Ads with call tracking and optimisation", "description": "Targeted Google Ads campaigns for emergency plumbing searches with proper call tracking, negative keyword exclusions for irrelevant searches, and landing pages designed for instant conversion. We optimise based on which keywords generate genuine paying callouts rather than just phone calls, improving your cost per actual job."}, {"title": "Boiler installation remarketing campaigns", "description": "Visitors who view your boiler installation or bathroom fitting pages but do not convert see targeted remarketing ads across Google and Facebook over the following thirty days. These campaigns keep your business visible during the consideration period and recapture prospects who were comparing multiple plumbers before making a decision."}, {"title": "Seasonal email and social campaigns timed to plumbing demand", "description": "Pre-winter boiler service campaigns to existing customers, spring bathroom renovation promotions, and autumn heating system health-check offers are coordinated across email and social media. These proactive campaigns smooth seasonal demand, generate recurring service revenue, and reactivate past customers before they search for a competitor."}]',
  '[{"question": "How much should a plumber spend on digital marketing?", "answer": "Most plumbing businesses see strong returns from a monthly investment of five hundred to fifteen hundred pounds across Google Ads, social media, and email marketing. We recommend starting with Google Ads for emergency and boiler installation terms, then expanding to remarketing and email as your enquiry pipeline develops. Every pound is tracked against actual jobs generated."}, {"question": "Should I use Google Ads or SEO for emergency plumbing searches?", "answer": "Both, with different timeframes. Google Ads provide immediate visibility for emergency searches while SEO builds long-term organic positioning. We typically run both in parallel, with Ads covering competitive terms while SEO gains traction. As organic rankings strengthen, we reduce ad spend on terms where you already rank well."}, {"question": "Can digital marketing help during the quieter summer months?", "answer": "Yes. Summer campaigns promoting bathroom renovations, outdoor tap installations, and boiler replacement planning ahead of winter capture work during your quietest period. Email campaigns to existing customers about annual boiler servicing and power flush offers generate revenue from your established base during seasonal lulls."}, {"question": "How do you measure whether plumbing marketing is working?", "answer": "We track cost per enquiry and cost per booked job for every channel. Call tracking identifies which campaigns generate phone calls, form tracking attributes online enquiries to specific ads or content, and revenue tracking calculates your return on investment per channel. Monthly reports show exactly what each marketing pound produces."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 8. Plumbers × Workwear & Print
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'plumbers',
  'workwear-print',
  'A plumber''s workwear is seen by every customer who opens their front door, every neighbour watching from across the street, and every merchant at the trade counter. It is your most personal brand touchpoint — the moment a homeowner decides whether they feel comfortable letting you into their home. Branded workwear for plumbers serves both a trust function and a marketing function: a clean, professionally embroidered polo shirt or softshell jacket immediately signals that this is an established business rather than an unknown individual, while the visible branding reinforces your name and phone number with everyone who sees you throughout the working day. Beyond workwear, printed materials complete the professional impression: branded business cards left after a quote visit, magnetic vehicle signs for personal vehicles used on weekends, invoice pads with Gas Safe registration details, and customer care cards explaining what to do if they have issues. We supply branded workwear and printed materials for plumbing businesses that build trust at the doorstep and keep your details in customers'' hands long after the job is finished.',
  'Plumbers enter customers'' most private spaces — bathrooms, bedrooms, kitchens — and homeowners make instant judgements about trustworthiness based on appearance. Branded workwear immediately elevates perception from "stranger at the door" to "professional from an established business." Printed materials — business cards, care cards, invoice books — extend that professional impression beyond the visit, keeping your details accessible when the customer recommends you or needs further work.',
  'We supply plumbing workwear designed for the physical demands of the trade: embroidered polo shirts for customer-facing work, branded softshell jackets for outdoor and loft work, and printed hi-vis vests for commercial sites. Printed materials include Gas Safe branded business cards, magnetic vehicle signs, customer care cards, and professional invoice pads.',
  '[{"title": "Arriving at customer properties in unbranded clothing", "description": "A plumber arriving in a plain t-shirt and jeans is immediately less trusted than one wearing a branded, clean uniform. Homeowners opening their front door make a split-second assessment of professionalism, and unbranded clothing offers no reassurance that this person represents an established, accountable business."}, {"title": "No business cards or leave-behind materials after quote visits", "description": "After visiting a property to quote a boiler installation or bathroom renovation, leaving nothing behind means the customer has no physical reminder of your business. When they compare quotes days later, the plumber who left a professional business card with Gas Safe registration details has a tangible advantage."}, {"title": "Workwear that does not withstand the physical demands of plumbing", "description": "Cheap promotional clothing that rips, fades, or stains after a few days of plumbing work wastes money and damages your brand appearance. Plumbers need workwear that withstands crawling through loft spaces, kneeling on hard floors, and exposure to water and chemicals while maintaining a professional appearance."}]',
  '[{"title": "Trade-grade branded workwear for plumbing professionals", "description": "Embroidered polo shirts, softshell jackets, and fleeces in your brand colours using trade-grade fabrics that withstand the physical demands of plumbing work. Reinforced stitching, stain-resistant treatments, and durable embroidery ensure your branding looks professional after months of daily wear in challenging conditions."}, {"title": "Gas Safe branded business cards and leave-behind materials", "description": "Professional business cards displaying your Gas Safe registration number, services offered, emergency contact details, and a QR code linking to your website. Customer care cards explaining post-installation guidance and warranty details provide genuine value while keeping your contact information in the customer''s home."}, {"title": "Magnetic vehicle signs and printed documentation", "description": "Magnetic vehicle signs for personal vehicles used on evening and weekend callouts, branded invoice pads with Gas Safe details and payment terms, and vehicle window stickers displaying your registration and contact information. These materials ensure consistent branding whether you are in the branded van or a personal vehicle."}]',
  '[{"question": "What workwear do you recommend for plumbers?", "answer": "We recommend embroidered polo shirts for customer-facing visits, branded softshell jackets for outdoor and loft work, and printed hi-vis vests for commercial sites. All garments use trade-grade fabrics with reinforced stitching and stain-resistant treatments designed to maintain a professional appearance through the physical demands of daily plumbing work."}, {"question": "Can you include my Gas Safe registration on business cards?", "answer": "Yes. Gas Safe registration displayed on business cards is a powerful trust signal. We include your registration number, the Gas Safe logo subject to their branding guidelines, your services, emergency contact number, and a QR code linking to your website or Gas Safe verification page."}, {"question": "How long does branded plumbing workwear last?", "answer": "Our trade-grade workwear is selected for durability in demanding conditions. Polo shirts typically last six to twelve months of daily wear before replacement, while softshell jackets and fleeces last considerably longer. Embroidery is more durable than printing and maintains a professional appearance through repeated washing."}, {"question": "Can I order small quantities of workwear?", "answer": "Yes. We cater to sole traders and small plumbing teams, with minimum orders typically starting at five to ten garments. Business cards, vehicle magnetics, and other printed materials have similarly accessible minimum quantities. We stock your brand specifications for easy reordering as workwear needs replacing."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 9. Plumbers × AI Chatbots
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'plumbers',
  'ai-chatbots',
  'Plumbing enquiries arrive at the worst possible times — a boiler failure at ten at night, a leak discovered on a Saturday morning, a burst pipe while you are already on a job with your hands full. Every missed call is a lost customer, because emergency plumbing callers do not leave voicemails; they call the next number on Google. An AI chatbot built for a plumbing business does not just answer frequently asked questions — it performs emergency triage, distinguishing a genuine burst pipe requiring immediate callout from a dripping tap that can be scheduled for next week. It collects critical information: the nature of the problem, whether water is actively flowing, whether the stopcock has been located and turned off, and the customer''s address and contact details. For non-emergency enquiries, the chatbot gathers boiler model details, describes symptoms, estimates property size for heating work, and books consultation slots directly into your calendar. The result is that emergency callers receive instant guidance and you receive a prioritised alert, while planned-work enquiries are qualified and scheduled without you lifting a finger. We build AI chatbots for plumbers that triage emergencies intelligently, capture every enquiry around the clock, and ensure no job is lost to a missed call.',
  'Plumbing businesses lose their most valuable leads — emergency callouts paying premium rates — to missed calls during working hours and after-hours downtime. An AI chatbot ensures every visitor to your website receives an instant response at any hour. Emergency situations are triaged with immediate safety guidance while alerting you to the callout. Non-urgent enquiries are fully qualified with problem details, property information, and preferred scheduling — ready for you to review when you finish the current job.',
  'We build plumbing chatbots with emergency triage logic: identifying active leaks, gas smells, and flooding situations that need immediate response versus routine repairs and planned installations. The chatbot walks emergency callers through safety steps like locating the stopcock, then sends you a priority alert. Non-emergency interactions collect boiler details, symptom descriptions, and schedule consultations automatically.',
  '[{"title": "Emergency calls missed while working on other jobs", "description": "A plumber cannot answer the phone while brazing a pipe joint or working in a confined loft space. Every unanswered call during a genuine emergency — a burst pipe, a gas smell, a boiler failure in freezing weather — sends a premium-paying customer directly to a competitor. These are the highest-value leads in plumbing, and they are the most likely to be missed."}, {"title": "After-hours enquiries lost entirely", "description": "Boiler failures and leaks do not respect working hours. Website visitors at eleven at night who cannot reach you will not fill in a contact form and wait — they need help now. Without an AI chatbot providing instant interaction, triaging their emergency, and offering safety guidance, these after-hours visitors call the first competitor with a visible phone number."}, {"title": "Time wasted qualifying non-emergency enquiries by phone", "description": "Routine calls about boiler servicing, radiator additions, and bathroom quotes consume valuable time when you are between jobs. Each call requires asking the same qualifying questions: property type, boiler model, number of radiators, symptoms. An AI chatbot collects all of this information before you are involved, letting you review fully qualified enquiries at your convenience."}]',
  '[{"title": "Emergency triage with safety guidance and priority alerting", "description": "The chatbot identifies emergency situations through targeted questions: Is water actively flowing? Can you smell gas? Is the property losing heating in freezing conditions? Emergency callers receive immediate safety instructions — locate and turn off the stopcock, open windows for gas smells, use the emergency gas number for suspected leaks — while you receive a priority SMS alert with the customer''s details and situation summary."}, {"title": "Instant boiler and heating enquiry qualification", "description": "For non-emergency heating enquiries, the chatbot collects boiler make, model, and age; describes symptoms; asks about property size and radiator count; and captures the customer''s budget expectations and timeline. You receive a fully qualified lead with all the technical details needed to prepare an accurate estimate before contacting the customer."}, {"title": "Automated callout and consultation booking", "description": "The chatbot accesses your calendar availability and allows customers to book emergency callout windows or planned consultation slots directly. Emergency bookings trigger immediate notifications. Planned consultations are confirmed automatically with address details, access instructions, and a reminder sent the day before."}]',
  '[{"question": "Can an AI chatbot really handle plumbing emergency triage?", "answer": "Yes. We programme the chatbot with a structured triage flow that identifies emergency indicators: active water leaks, gas smells, complete heating failure in cold weather, and flooding. The chatbot provides immediate safety guidance appropriate to each situation while simultaneously alerting you with the customer''s details and a priority classification."}, {"question": "What happens when the chatbot identifies a genuine emergency?", "answer": "You receive an immediate SMS and email alert with the customer''s name, address, phone number, and a summary of the emergency — for example, ''active leak from upstairs bathroom, stopcock located and turned off, ceiling showing water damage.'' This gives you everything needed to call back or dispatch within minutes."}, {"question": "Can the chatbot book callouts directly into my calendar?", "answer": "Yes. The chatbot integrates with Google Calendar, Calendly, or your preferred scheduling system. Customers can book available time slots for consultations and non-emergency visits. Emergency requests bypass normal scheduling and trigger immediate alerts, but the customer is informed of your typical response time."}, {"question": "Will customers be frustrated talking to a chatbot instead of a real plumber?", "answer": "The chatbot is designed to be genuinely helpful — providing safety guidance during emergencies, collecting information efficiently, and offering real appointment booking. Most customers prefer instant interaction over leaving a voicemail and waiting for a callback. The chatbot handles the initial interaction, and you follow up personally for complex discussions."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 10. Plumbers × AI Content
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'plumbers',
  'ai-content',
  'Content marketing for plumbers faces a unique challenge: the topics that drive the most valuable search traffic — boiler installation guides, central heating troubleshooting, emergency plumbing advice — require genuine technical accuracy. Generic content written by someone who has never bled a radiator or replaced a flue terminal reads as obviously inauthentic to both Google and customers. AI content creation for plumbers combines the efficiency of artificial intelligence with your real-world technical knowledge to produce content that is both search-optimised and technically credible. We use AI tools trained on plumbing industry knowledge to draft content that covers the technical details homeowners search for: boiler error codes and their meanings, the difference between combi and system boilers, how to identify a leaking pressure relief valve, and when to call a Gas Safe engineer versus attempting a fix themselves. Your expertise shapes and validates every piece, ensuring accuracy and authenticity. The result is a consistent stream of technically sound content that drives organic traffic, demonstrates your expertise, and generates enquiries from homeowners who trust your knowledge before they ever meet you.',
  'Plumbing businesses that publish regular, technically accurate content dominate local search results because Google rewards demonstrated expertise. But producing quality content requires time that working plumbers do not have. AI content tools bridge this gap, generating draft articles and service page copy that you refine with your practical knowledge. The result is a consistent publishing schedule that builds search authority without consuming your evenings writing blog posts.',
  'We use AI to draft technically focused plumbing content — boiler comparison guides, fault diagnosis articles, heating system explainers — then refine each piece with industry-specific accuracy checks. Your real-world experience validates every claim. Content is optimised for the specific search terms homeowners use when researching plumbing services and problems.',
  '[{"title": "No time to write content despite having valuable expertise", "description": "Plumbers possess exactly the technical knowledge that homeowners search for — boiler fault diagnosis, heating system advice, emergency plumbing guidance — but spend their entire working day on-site with no time to write articles. This expertise remains locked in your head while competitors who publish content consistently outrank you."}, {"title": "Generic content that lacks technical credibility", "description": "Content written by marketing agencies without plumbing knowledge is often technically inaccurate or superficial. Articles that confuse combi and system boilers, misidentify common fault codes, or give dangerous advice about gas appliances damage your credibility and can create legal liability."}, {"title": "Inconsistent publishing undermining SEO momentum", "description": "Plumbing businesses that publish a few articles and then stop see initial ranking improvements that plateau and decline. Search engines reward consistent content publication, and competitors who maintain a regular schedule steadily overtake businesses that publish sporadically."}]',
  '[{"title": "AI-drafted technical content validated by your expertise", "description": "We use AI tools to draft comprehensive plumbing content — boiler buying guides, fault diagnosis articles, heating efficiency tips, emergency response guides — then work with you to validate technical accuracy. A fifteen-minute review call per article ensures every piece reflects real-world plumbing knowledge while AI handles the time-consuming writing."}, {"title": "Boiler and heating system content targeting high-value searches", "description": "Targeted content covering boiler error codes for specific manufacturers, combi versus system boiler comparisons, and central heating troubleshooting guides. These articles attract homeowners actively researching heating decisions worth thousands of pounds, positioning your business as the knowledgeable expert they contact for installation or repair."}, {"title": "Consistent monthly publishing schedule building search authority", "description": "A managed content calendar delivers four to eight optimised articles per month covering seasonal plumbing topics, technical guides, and local service content. Consistent publication builds the topical authority that Google rewards with higher rankings across all your service pages, not just the individual articles."}]',
  '[{"question": "How does AI content creation work for a plumbing business?", "answer": "We use AI tools to draft content based on the search terms homeowners use when researching plumbing services. Each draft covers the technical details accurately but is then reviewed with you — typically in a fifteen-minute call — to add your real-world insights, correct any technical nuances, and ensure the content reflects your genuine expertise."}, {"question": "Will AI-generated content sound authentic to plumbing customers?", "answer": "Yes, because every piece is validated by your real-world experience. We add your practical insights, real examples from your work, and the technical details that only a working plumber would know. The AI handles structure and SEO optimisation; your expertise provides the authenticity that resonates with readers and search engines."}, {"question": "What plumbing topics generate the most valuable search traffic?", "answer": "Boiler installation guides, boiler error code explainers, heating system comparisons, and emergency plumbing advice generate the highest-value traffic. Homeowners reading boiler replacement guides are researching purchases worth several thousand pounds. Those searching for error codes often need urgent professional help. Both represent high-value leads."}, {"question": "How many articles per month should a plumber publish?", "answer": "Four to eight articles per month delivers strong SEO results for plumbing businesses. We balance evergreen technical content like boiler buying guides with seasonal topics like preparing pipes for winter and timely pieces responding to regulatory changes. This mix builds sustained search visibility while capturing seasonal demand."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 11. Plumbers × AI Automation
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'plumbers',
  'ai-automation',
  'AI automation for plumbing businesses goes beyond simple task scheduling into intelligent decision-making that adapts to the realities of trade work. Traditional automation sends a follow-up email on a timer; AI automation reads an incoming enquiry, determines whether it describes an emergency or a planned project, extracts the relevant technical details — boiler model, fault symptoms, property type — and routes it appropriately. An emergency description triggers an instant priority alert to your phone with a triage summary. A boiler replacement enquiry is automatically enriched with manufacturer warranty status checks and typical replacement costs for that model before you even see it. Quote follow-ups are timed intelligently based on the type and value of the work quoted — a twenty-thousand-pound bathroom renovation gets a different follow-up cadence than a three-hundred-pound radiator replacement. AI automation transforms a plumbing business from reactive to predictive, anticipating customer needs, prioritising your time toward the highest-value opportunities, and handling routine operational decisions that currently rely on you remembering to act. We build AI-powered automation systems for plumbers that think about your business while you focus on the work.',
  'Plumbing businesses generate a constant stream of decisions: which enquiry to respond to first, when to follow up a quote, which boiler service reminder to send, whether an incoming message describes an emergency. AI automation makes these decisions intelligently and instantly, ensuring emergency callers get immediate attention, high-value quotes get timely follow-up, and routine operations run without your involvement.',
  'We build AI automations that understand plumbing context: classifying enquiries by urgency and value, extracting technical details from customer messages, routing emergencies for instant response, enriching boiler enquiries with model-specific data, and intelligently timing follow-ups based on job type. Every automation learns from your preferences and improves over time.',
  '[{"title": "Emergency enquiries buried among routine messages", "description": "A message describing an active ceiling leak arrives alongside three boiler service requests and a bathroom quote enquiry. Without intelligent classification, the emergency sits in the same queue as everything else, and the customer calls a competitor while you work through messages in order. AI automation identifies emergencies instantly and escalates them."}, {"title": "One-size-fits-all follow-up timing losing high-value work", "description": "Following up a ten-thousand-pound boiler and heating system quote with the same timing as a two-hundred-pound tap replacement is commercially naive. High-value work requires more considered, strategically timed follow-up with additional supporting materials, while small repairs benefit from quick, simple reminders."}, {"title": "Manual processing of every enquiry consuming valuable time", "description": "Reading every incoming message, extracting the relevant details, classifying the urgency, and deciding on next steps consumes time that a plumber does not have during a busy working day. By the time you process the morning''s messages in the evening, the most urgent ones are hours old and the customers have found another plumber."}]',
  '[{"title": "Intelligent enquiry classification and emergency routing", "description": "AI reads every incoming enquiry — from website forms, emails, and chatbot conversations — and classifies it by urgency and commercial value. Descriptions mentioning active leaks, gas smells, or heating failure trigger instant priority alerts to your phone. Planned work enquiries are categorised, enriched with relevant details, and queued for your review."}, {"title": "Quote follow-up sequences tailored to job value and type", "description": "AI determines the appropriate follow-up cadence based on the type and value of quoted work. Boiler installation quotes receive a structured sequence with manufacturer information, finance options, and efficiency comparisons. Bathroom renovation quotes include design inspiration and project timeline reassurance. Small repair quotes get quick, simple reminders."}, {"title": "Predictive service reminders and customer lifecycle management", "description": "AI tracks every customer interaction and predicts when they will need your services next — annual boiler servicing, gas safety certificate renewals, and estimated timelines for replacement based on boiler age and service history. Proactive outreach reaches customers before they start searching for another plumber, securing repeat business automatically."}]',
  '[{"question": "How does AI automation differ from regular automation for plumbers?", "answer": "Regular automation follows fixed rules — send a follow-up after forty-eight hours regardless of context. AI automation understands context: it reads enquiry details, classifies urgency, extracts technical information, and adapts its responses and timing accordingly. An emergency gets instant escalation; a boiler quote gets a value-appropriate follow-up sequence with relevant supporting content."}, {"question": "Can AI really tell the difference between a plumbing emergency and a routine enquiry?", "answer": "Yes. The AI is trained to identify emergency indicators in customer messages: mentions of active leaks, water damage, gas smells, complete heating failure, and flooding. It distinguishes between a dripping tap that can wait and a burst pipe that needs immediate attention, routing each appropriately with the correct urgency level."}, {"question": "Will AI automation replace the need for me to handle customer enquiries personally?", "answer": "No. AI handles the initial classification, information extraction, and routing. Emergency alerts still come to you for personal response. High-value quotes are prepared with enriched information for you to review and personalise. The AI removes the administrative burden of processing enquiries, allowing you to focus your personal attention where it matters most."}, {"question": "How does AI improve over time for my plumbing business?", "answer": "The system learns from your feedback and actions. When you override a classification or adjust a follow-up timing, the AI incorporates this preference into future decisions. Over months, it develops an increasingly accurate understanding of your business priorities, customer base, and preferred working patterns."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;
