-- ============================================================
-- seed-industry-content-landscapers.sql
-- Industry content for Landscapers across all 11 services
-- Safe to re-run: uses ON CONFLICT ... DO UPDATE
-- ============================================================

-- 1. Landscapers × Web Design
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'landscapers',
  'web-design',
  'Landscaping is a visual trade, and your website needs to sell the transformation before a single spade hits the ground. Homeowners deciding between landscapers do not read paragraphs of text — they scroll through project galleries, looking for evidence that you can turn their tired patio or overgrown garden into something worth showing off. A landscaping website must showcase before-and-after transformations, present seasonal service pages that match what customers are searching for right now, and make it effortless to request a site visit. Generic template sites with stock images of manicured lawns actively undermine credibility, because every potential customer knows those are not your gardens. We build bespoke websites for Kent landscapers that put your real project portfolio front and centre, with design visualisation tools and clear calls to action that convert browsers into booked consultations.',
  'Homeowners spend hours researching landscapers online before making contact, and your website is where that decision is made. Without a professional site featuring genuine project galleries, garden design visualisations, and seasonal service breakdowns, you are losing jobs to competitors who present their work more effectively. A purpose-built landscaping website turns your completed projects into your most powerful sales tool, working around the clock to generate consultation requests even during your busiest season.',
  'We photograph or source your actual completed projects and build immersive portfolio galleries with filtering by project type — patios, planting schemes, water features, full garden redesigns. Seasonal service pages rotate prominence based on the time of year, and every page funnels visitors toward a site visit booking form with calendar integration.',
  '[{"title": "No project portfolio to showcase completed work", "description": "Most landscaper websites either have no gallery at all or display a handful of poorly lit phone photos. Homeowners comparing three or four landscapers will choose the one whose website proves they can deliver quality work through professional before-and-after project imagery."}, {"title": "Generic templates that look identical to competitors", "description": "Template websites with stock photography of perfect lawns immediately signal to customers that this is not a serious operation. When every landscaper in Kent uses the same Wix or Squarespace template, none of them stand out, and homeowners default to choosing on price alone."}, {"title": "No seasonal service pages matching current search intent", "description": "Customers search for ''garden clearance'' in autumn, ''patio laying'' in spring, and ''fence repair'' after winter storms. Without dedicated seasonal service pages, your site misses the specific searches happening right now and loses those jobs to competitors who have them."}]',
  '[{"title": "Immersive before-and-after project galleries", "description": "We build filterable portfolio galleries that let homeowners browse your completed projects by type — patios, planting, water features, driveways, full redesigns. Each project includes before-and-after sliders, scope description, and approximate timelines, giving prospects confidence in your capabilities."}, {"title": "Seasonal service pages with dynamic prominence", "description": "Dedicated pages for spring planting, summer maintenance, autumn clearance, and winter hardscaping rotate in visibility based on the calendar. Each page targets the exact search terms customers use at that time of year, capturing seasonal demand your competitors miss."}, {"title": "Site visit booking with calendar integration", "description": "Every page drives visitors toward a consultation request form connected to your actual availability calendar. Customers select their preferred date and describe their project, and you receive a structured enquiry ready for follow-up — no phone tag, no missed messages."}]',
  '[{"question": "Can you photograph my completed landscaping projects for the website?", "answer": "Yes. We coordinate project photography for completed gardens, patios, and outdoor spaces. We also work with any existing photos you have, professionally editing and presenting them in before-and-after formats that showcase the transformation."}, {"question": "How do seasonal service pages work on a landscaping website?", "answer": "We create dedicated pages for each seasonal service you offer — spring planting, patio installation, autumn clearance, winter maintenance. These pages are optimised for the search terms customers use during each season and are given greater prominence on your homepage as the relevant period approaches."}, {"question": "Will the website work on mobile for customers browsing in their gardens?", "answer": "Absolutely. Many homeowners browse landscaping websites while standing in the garden they want transformed. Every site we build is fully responsive with fast-loading images, touch-friendly galleries, and tap-to-call functionality so they can contact you instantly."}, {"question": "Can customers see estimated costs on the website?", "answer": "We can include indicative price ranges or project-size guides if you prefer, without committing you to fixed quotes. Many landscapers find that showing approximate starting prices for common services like patio laying or turfing reduces tyre-kicker enquiries and attracts serious customers."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 2. Landscapers × SEO
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'landscapers',
  'seo',
  'When a homeowner searches "landscaper near me" or "patio installation Kent," the businesses appearing in the top three Google results capture the vast majority of enquiries. For landscapers, seasonal search patterns create predictable waves of demand — garden design peaks in spring, fence and paving work surges after winter, and maintenance contracts are researched year-round. Yet most landscaping businesses have no SEO strategy, relying entirely on word of mouth while competitors quietly claim the search visibility that drives consistent new work. A landscaping SEO campaign must target service-specific keywords tied to seasonal intent, dominate the Google Map Pack for your service radius, and build content authority around the types of projects you want to win. We build SEO strategies specifically for landscapers that align your search visibility with the seasonal rhythms of outdoor trade work.',
  'Word of mouth alone cannot sustain consistent growth for a landscaping business. Seasonal demand fluctuations mean you need a steady pipeline of new enquiries to fill gaps between referrals. SEO positions your business in front of homeowners actively searching for the services you offer, precisely when they need them. Without deliberate search optimisation, you are invisible to the customers who are ready to spend money on their gardens right now.',
  'We map landscaping search terms against seasonal demand curves — targeting patio and hardscaping keywords as spring approaches, garden maintenance terms in summer, and clearance services in autumn. Google Business Profile optimisation includes project photos categorised by service type, driving Map Pack visibility for your core service area.',
  '[{"title": "Invisible for seasonal landscaping searches", "description": "Landscaping demand follows predictable seasonal patterns, but without SEO targeting spring garden design, summer maintenance, and autumn clearance terms at the right time, your business misses the peak search windows when homeowners are actively looking to hire."}, {"title": "Google Map Pack dominated by competitors with more reviews", "description": "The Map Pack results for landscaping searches are heavily influenced by review quantity and recency. Competitors who actively collect Google reviews after every completed project push your business below the fold, making you invisible to the highest-intent local searchers."}, {"title": "Directory sites outranking your business for your own services", "description": "Checkatrade, Bark, and MyBuilder aggressively target landscaping keywords across Kent. Without a deliberate SEO strategy, your own website is buried beneath these platforms, forcing you to pay commission for leads that should have come to you directly."}]',
  '[{"title": "Seasonal keyword targeting aligned to landscaping demand", "description": "We build content calendars that publish and promote service pages ahead of seasonal demand peaks. Patio installation pages gain authority before spring, garden maintenance content ranks for summer, and clearance service pages are ready for autumn — capturing each wave of search intent."}, {"title": "Review generation programme for Map Pack dominance", "description": "We implement automated review request workflows triggered after project completion. Consistent, recent five-star reviews with project-specific details push your Google Business Profile into the top three Map Pack positions for landscaping searches in your service area."}, {"title": "Service-area pages targeting specific towns and postcodes", "description": "We create dedicated landing pages for each town and postcode area you serve, targeting long-tail searches like ''patio landscaper in Maidstone'' or ''garden design Tonbridge.'' These pages outrank national directories by demonstrating genuine local relevance and service specificity."}]',
  '[{"question": "How long before SEO generates landscaping enquiries?", "answer": "Most landscaping clients see ranking improvements within eight to twelve weeks for targeted service-plus-location terms. Seasonal terms often move faster when we begin optimisation ahead of the demand peak, as competition for upcoming seasonal keywords is lower during the off-season."}, {"question": "Can SEO help during the quieter winter months?", "answer": "Yes. We target winter-specific searches such as fence repair, drainage work, and garden clearance, as well as forward-planning searches from homeowners researching spring projects. This smooths out the seasonal dip and keeps your enquiry pipeline active year-round."}, {"question": "Should I stop advertising on Checkatrade if I invest in SEO?", "answer": "Not immediately. SEO builds compounding visibility over time, so we recommend maintaining directory listings during the first few months. As organic rankings strengthen and direct enquiries increase, you can gradually reduce paid directory spend and keep more profit per job."}, {"question": "Do you optimise for specific landscaping services or just general terms?", "answer": "Both, but service-specific terms convert better. We target individual services like patio installation, garden design, turfing, fencing, and water features with dedicated optimised pages. These specific searches indicate strong buying intent and generate higher-quality enquiries than generic landscaper searches."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 3. Landscapers × Lead Capture
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'landscapers',
  'lead-capture',
  'Most landscaping websites lose the majority of their visitors without capturing any contact details. A homeowner visits your site, browses your gallery, and then leaves to check two more landscapers — and you never hear from them. Effective lead capture for landscapers means giving visitors a compelling reason to share their details before they leave: a garden project planner, an instant rough estimate calculator, or a downloadable seasonal maintenance guide. These tools transform anonymous browsers into named, contactable prospects with defined project requirements. For a trade where the average job value ranges from hundreds to thousands of pounds, capturing even a handful of additional leads each month represents significant revenue. We build lead capture systems designed specifically for landscaping businesses that convert casual browsers into consultation-ready prospects.',
  'Landscaping projects involve significant consideration time. Homeowners research multiple businesses, compare portfolios, and often delay for weeks before making contact. Without lead capture mechanisms, you lose everyone who does not call or email on their first visit. A structured lead capture system ensures you have their details and project requirements, allowing you to follow up proactively and stay front of mind through the decision period.',
  'We build landscaping-specific lead magnets: garden project planners that ask about garden size, style preferences, and budget range; seasonal maintenance checklists homeowners actually want; and quick-quote forms that collect project details in exchange for an approximate cost range. Every form feeds directly into your CRM or email system.',
  '[{"title": "Website visitors leave without making contact", "description": "The typical landscaping website converts fewer than two percent of visitors into enquiries. The other ninety-eight percent browse your gallery, perhaps compare your work to a competitor, and disappear without leaving any way for you to follow up or remind them you exist."}, {"title": "No way to capture early-stage researchers", "description": "Many homeowners start researching landscapers months before they are ready to commit. Without a lead magnet offering value at this early stage — like a project planning guide or seasonal maintenance tips — you miss the chance to nurture these prospects through to booking."}, {"title": "Enquiry forms collect insufficient project details", "description": "Generic contact forms with just a name, email, and message field give you no qualifying information. You cannot prioritise large patio installation enquiries over simple lawn-mowing requests when both arrive as identical one-line messages."}]',
  '[{"title": "Garden project planner as a lead magnet", "description": "We create an interactive project planner that asks homeowners about their garden size, desired features, preferred style, and indicative budget. In exchange for their email, they receive a personalised project summary — and you receive a fully qualified lead with detailed project requirements."}, {"title": "Quick-quote calculator for common services", "description": "An approximate cost calculator for popular services like patio laying, turfing, or fencing captures leads by offering instant value. Homeowners enter dimensions and materials preferences, receive a rough estimate, and you receive their contact details alongside the exact project specifications."}, {"title": "Seasonal maintenance guide with email nurture sequence", "description": "A downloadable seasonal garden care guide captures email addresses from homeowners not yet ready for a major project. An automated email sequence delivers genuine maintenance tips over the following weeks, keeping your business top of mind until they are ready to commission work."}]',
  '[{"question": "What is a lead magnet for a landscaping business?", "answer": "A lead magnet is a free resource or tool offered in exchange for contact details. For landscapers, effective lead magnets include garden project planners, seasonal maintenance guides, rough cost calculators, and design inspiration lookbooks. They capture the details of visitors who are interested but not yet ready to call."}, {"question": "Will a cost calculator commit me to specific pricing?", "answer": "No. The calculator provides approximate ranges based on typical project sizes and materials. It includes clear disclaimers that final pricing requires a site visit. The purpose is to give homeowners enough information to stay engaged while capturing their project details for your follow-up."}, {"question": "How do captured leads get sent to me?", "answer": "Leads are delivered instantly via email notification with full project details. We can also integrate with CRM systems, Google Sheets, or project management tools. Each lead includes the homeowner''s contact details, project type, garden dimensions, and any other information collected by the form."}, {"question": "How many extra leads can I expect per month?", "answer": "Results depend on your website traffic, but most landscaping clients see a three to five times increase in lead capture rates after implementing project planners and quick-quote tools. For a site receiving 500 monthly visitors, that typically translates to fifteen to twenty-five additional contactable leads per month."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 4. Landscapers × Business Automation
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'landscapers',
  'business-automation',
  'Running a landscaping business means spending your evenings writing quotes, chasing customers for approvals, sending appointment reminders, and requesting reviews after completed jobs. These repetitive admin tasks eat into the hours you should be spending on site or planning new projects. Business automation for landscapers eliminates the manual follow-up cycle by creating workflows that trigger automatically: a new enquiry receives an instant acknowledgement, a sent quote gets an automated follow-up after forty-eight hours, a completed project triggers a review request, and a seasonal maintenance reminder goes out before each customer''s garden needs attention. These are not complex enterprise systems — they are practical, trade-focused automations that save landscapers hours every week and ensure no lead, quote, or follow-up opportunity falls through the cracks.',
  'Landscapers lose thousands of pounds in revenue annually to forgotten quote follow-ups and missed review opportunities. When you are on site five days a week, administrative tasks get pushed to evenings and weekends, and things inevitably slip. Automation ensures every enquiry gets an instant response, every quote gets followed up, every completed job generates a review request, and every past customer receives seasonal reminders. It is the difference between a busy tradesperson and a professionally run business.',
  'We build automations around the landscaping workflow: enquiry acknowledgement, quote generation prompts, follow-up sequences for unanswered quotes, booking confirmations with weather-contingency messaging, post-completion review requests, and seasonal maintenance reminders to past customers for recurring revenue.',
  '[{"title": "Quotes sent but never followed up", "description": "Landscapers typically send quotes after a site visit and then wait for the customer to respond. Without systematic follow-up, a significant percentage of viable quotes go cold. Customers who were genuinely interested simply chose the competitor who followed up first."}, {"title": "No system for generating reviews after completed work", "description": "Landscaping projects produce visually impressive results that photograph well and generate enthusiastic reviews — but only if you ask. Without automated review requests sent at the moment of peak satisfaction, completed projects rarely translate into the Google reviews that drive future enquiries."}, {"title": "Past customers forgotten until they call someone else", "description": "A customer who had their garden landscaped two years ago is a prime candidate for maintenance, seasonal planting, or new feature additions. Without automated seasonal reminders, these past customers forget about you and search Google when they need further work — often finding a competitor."}]',
  '[{"title": "Automated quote follow-up sequences", "description": "When you send a quote, an automated sequence sends a follow-up after forty-eight hours, a gentle reminder after one week, and a final check-in after two weeks. Each message is personalised with the customer''s project details, dramatically increasing your quote-to-job conversion rate."}, {"title": "Post-completion review and referral requests", "description": "Automated review requests trigger two days after project completion, when customer satisfaction is highest. The message includes a direct link to your Google Business Profile and a simple referral prompt, systematically building the review count that drives your search visibility."}, {"title": "Seasonal maintenance reminders to past customers", "description": "Automated campaigns contact past customers before each season with relevant maintenance offers — spring planting preparation, summer lawn care packages, autumn clearance, and winter protection. These reminders generate recurring revenue from your existing customer base with zero manual effort."}]',
  '[{"question": "What landscaping tasks can be automated?", "answer": "The most impactful automations for landscapers are enquiry acknowledgements, quote follow-ups, booking confirmations, post-completion review requests, and seasonal maintenance reminders to past customers. We can also automate appointment reminders, weather delay notifications, and annual check-in messages."}, {"question": "Will automated messages feel impersonal to my customers?", "answer": "No. Every message is personalised with the customer''s name, project details, and specific service information. The tone matches your brand voice, and messages are timed to feel natural rather than robotic. Customers experience faster, more professional communication — not cold automation."}, {"question": "How does weather-contingency messaging work?", "answer": "When weather is likely to affect scheduled outdoor work, automated messages notify affected customers about potential delays, offer rescheduling options, and confirm revised dates once conditions improve. This reduces no-show frustrations and demonstrates professional communication."}, {"question": "Can automations connect to the tools I already use?", "answer": "Yes. We integrate with common tools landscapers use including Google Calendar, QuickBooks, Xero, and email platforms. If you track jobs in a spreadsheet, we can build automations around that too. The goal is to enhance your existing workflow, not replace it entirely."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 5. Landscapers × Branding
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'landscapers',
  'branding',
  'Your landscaping brand is judged long before anyone visits your website. It starts with the van parked on a residential street, the business card left after a site visit, the logo on your quote template, and the workwear your team wears on site. In a trade where customers invite you onto their property and trust you with thousands of pounds of work, visual professionalism signals reliability. Yet most landscapers operate with a logo designed by a mate, inconsistent colours across their van, website, and uniforms, and no cohesive brand identity whatsoever. A properly designed landscaping brand draws on nature-inspired aesthetics — earthy tones, organic shapes, botanical elements — while projecting the commercial professionalism that justifies premium pricing. We create complete brand identities for landscapers that look exceptional on van livery, workwear, project proposals, and every customer touchpoint.',
  'Landscaping is a competitive market where customers often choose based on perceived professionalism rather than actual skill differences. A cohesive brand identity — consistent across your van, website, uniforms, quotes, and business cards — immediately elevates your business above competitors running mismatched visuals. Strong branding also justifies premium pricing by positioning you as an established, professional operation rather than a sole trader with a mower.',
  'We design landscaping brands rooted in nature-inspired palettes and organic design language — earthy greens, warm stone tones, botanical line work — that feel authentic to the trade without looking amateurish. Every brand system is tested across van livery mockups, workwear embroidery, and printed proposal templates before finalisation.',
  '[{"title": "Logo designed years ago with no brand system behind it", "description": "Many landscapers have a logo created cheaply when they first started but no consistent colours, fonts, or visual style applied across their van, website, quotes, and uniforms. This inconsistency makes the business look disorganised and undermines customer confidence during the sales process."}, {"title": "Van livery that fails to generate enquiries", "description": "A landscaping van parked on a residential street is a mobile billboard seen by every neighbour. Poor van design with cluttered text, illegible phone numbers, or cheap vinyl fails to generate the kerb-side enquiries that a well-branded vehicle consistently produces."}, {"title": "Branding does not justify premium pricing", "description": "Landscapers trying to move into higher-value garden design and hardscaping projects need branding that matches the investment their clients are making. A hand-drawn logo and inconsistent visual identity make it difficult to present proposals for projects costing thousands of pounds."}]',
  '[{"title": "Nature-inspired brand identity system", "description": "We design complete brand identities drawing on botanical illustration, earthy colour palettes, and organic typography that feel authentically connected to the landscaping trade. The result is a sophisticated visual identity that works across every format from social media avatars to A-board signage."}, {"title": "Van livery design optimised for residential streets", "description": "Your van is your most visible marketing asset. We design livery with bold, clean branding that is legible from across a street, includes a memorable phone number and website, and creates the professional impression that prompts neighbours to note down your details while you work on their street."}, {"title": "Branded proposal templates for premium projects", "description": "We design professional quote and proposal templates featuring your brand identity, project visualisations, and structured pricing breakdowns. These documents elevate the sales process and justify premium pricing by presenting your business as an established, design-led operation."}]',
  '[{"question": "What should a landscaping brand look like?", "answer": "The most effective landscaping brands use nature-inspired colour palettes — deep greens, warm earth tones, stone greys — combined with clean modern typography and subtle botanical elements. The brand should feel premium and professional while remaining authentic to outdoor trade work."}, {"question": "Do you design van livery for landscapers?", "answer": "Yes. Van livery design is a core part of our landscaping branding packages. We create wrap or vinyl cut designs optimised for your specific vehicle type, ensuring your branding is legible from distance, memorable to passers-by, and consistent with your website and printed materials."}, {"question": "Can branding really help me charge higher prices?", "answer": "Absolutely. Customers use visual cues to assess the quality and professionalism of a business before they ever speak to you. Consistent, high-quality branding across your van, website, quotes, and uniforms positions you as a premium operator, making customers more comfortable with higher pricing."}, {"question": "How long does a full landscaping rebrand take?", "answer": "A complete brand identity including logo, colour system, typography, van livery design, workwear specifications, and branded templates typically takes three to four weeks from initial brief to final delivery. We present concepts after week one and refine based on your feedback."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 6. Landscapers × Social Media Setup
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'landscapers',
  'social-media-setup',
  'Landscaping is one of the most visually rewarding trades on social media. Before-and-after garden transformations, timelapse project videos, and seasonal planting content generate genuine engagement and enquiries on platforms like Instagram and Facebook. Yet most landscapers either have no social media presence or have abandoned accounts with sporadic posts and no consistent branding. Setting up social media properly for a landscaping business means creating professionally branded profiles, establishing content categories that showcase your work effectively, and building a posting framework you can actually maintain alongside running a busy outdoor trade. A well-structured Instagram grid of completed projects becomes a living portfolio that customers browse before making contact. We set up and optimise social media profiles for landscapers with branded templates, content plans, and posting systems designed for tradespeople who work with their hands, not their phones.',
  'Homeowners increasingly check social media before hiring a landscaper, using Instagram and Facebook as visual portfolios. A professional social presence with consistent project photography builds trust and demonstrates active, ongoing work. Without it, potential customers question whether you are still trading or capable of the quality they expect. Social media also drives referrals when satisfied customers share your posts with neighbours considering similar work.',
  'We set up landscaping social accounts with project showcase templates, before-and-after post formats, and seasonal content calendars. Photo capture guidelines ensure your team can document projects on-site with minimal disruption, and branded story templates let you share work-in-progress updates effortlessly.',
  '[{"title": "No social media presence despite visually stunning work", "description": "Landscapers create dramatic visual transformations every week but rarely document them for social media. Without a social presence, these powerful marketing assets go completely to waste while competitors with inferior work but better social skills attract more enquiries."}, {"title": "Abandoned or inconsistent social accounts", "description": "Many landscapers created Facebook or Instagram accounts but stopped posting after a few weeks. Dormant accounts with posts from months ago look worse than having no social presence at all — customers assume the business is inactive or struggling for work."}, {"title": "No time or knowledge to manage social media", "description": "Landscapers work physically demanding outdoor schedules with little energy left for content creation in the evenings. Without simple systems and templates that make posting quick and effortless, social media becomes an unsustainable burden that gets abandoned."}]',
  '[{"title": "Professionally branded social profiles", "description": "We set up and optimise your Instagram, Facebook, and Google Business profiles with consistent branding, compelling bios highlighting your specialisms, and organised highlights or albums showcasing your best project categories — from patios and planting to water features and full garden redesigns."}, {"title": "Project documentation system for on-site capture", "description": "We provide your team with simple photo and video capture guidelines: specific angles for before shots, progress documentation points, and final reveal framing. A shared folder or app makes uploading effortless, giving you a steady stream of content without disrupting your work schedule."}, {"title": "Content calendar with seasonal posting framework", "description": "A twelve-month content calendar maps post types to seasons: spring transformation reveals, summer maintenance tips, autumn planting guides, and winter planning content. Branded templates for each post type mean creating content takes minutes rather than hours."}]',
  '[{"question": "Which social media platforms work best for landscapers?", "answer": "Instagram is the strongest platform for landscapers due to its visual focus — before-and-after grids and reels generate excellent engagement. Facebook remains important for local community groups and older demographics. We set up both platforms with consistent branding and a content strategy tailored to each."}, {"question": "How often should a landscaper post on social media?", "answer": "Three to four posts per week is ideal, but consistency matters more than frequency. We design a system where two project showcase posts and one or two tips or behind-the-scenes posts per week is achievable alongside a full working schedule."}, {"question": "Can I manage social media myself after setup?", "answer": "Yes. Our setup includes branded templates, a content calendar, and photo capture guidelines specifically designed for tradespeople. We train you or a team member to create and schedule posts efficiently. Most landscapers find they can maintain their social presence in under thirty minutes per week."}, {"question": "Do before-and-after posts actually generate enquiries?", "answer": "Before-and-after garden transformations are among the highest-engagement content types on Instagram and Facebook. They demonstrate your capability visually, generate shares from satisfied customers to their friends and neighbours, and create a portfolio effect that builds trust with potential clients browsing your profile."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 7. Landscapers × Digital Marketing
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'landscapers',
  'digital-marketing',
  'Digital marketing for landscapers requires a fundamentally different approach from other trades because demand is intensely seasonal and project values vary enormously. A Facebook ad campaign that works brilliantly for patio installations in March will waste budget promoting the same service in November. An effective landscaping digital marketing strategy aligns ad spend, content promotion, and email campaigns with the seasonal rhythms of outdoor work — pushing garden design and hardscaping when homeowners are planning, promoting maintenance packages during summer, and targeting clearance and preparation services through autumn and winter. It also segments your audience by project value, ensuring premium garden design clients see different messaging than customers seeking basic lawn care. We build and manage digital marketing campaigns for landscapers that maximise return by matching the right message to the right audience at the right time of year.',
  'Word of mouth and organic search alone cannot provide the consistent, predictable enquiry flow a landscaping business needs to grow. Digital marketing puts your services in front of homeowners actively considering outdoor projects, at precisely the moment their intent is highest. Seasonal paid campaigns fill pipeline gaps during slower periods, retargeting keeps your business visible to researchers who are not yet ready to commit, and email marketing to past customers generates repeat business without acquisition costs.',
  'We run landscaping campaigns on a seasonal calendar: spring and early summer budgets weighted toward garden design, patio, and planting services; late summer promoting maintenance contracts; autumn driving clearance bookings. Ad creative uses your real project photography, and audience targeting focuses on homeowner demographics within your service radius.',
  '[{"title": "Ad budget wasted on poorly timed campaigns", "description": "Landscapers running the same Google or Facebook ads year-round burn budget promoting services when demand is low. Patio installation ads in December and garden clearance ads in June generate clicks from unready prospects who never convert, draining your marketing budget without delivering jobs."}, {"title": "No strategy to fill seasonal demand gaps", "description": "Most landscapers are overwhelmed with work from April through September but struggle through quieter winter months. Without targeted digital marketing promoting winter-appropriate services — drainage, fencing, hard landscaping, garden clearance — these revenue gaps persist year after year."}, {"title": "Generic ad messaging that fails to differentiate", "description": "Landscaping ads that say ''quality landscaping services'' with a stock image of a green lawn look identical to every competitor. Without compelling creative featuring real project transformations and specific service messaging, your ads fail to stand out in crowded social media feeds."}]',
  '[{"title": "Seasonal campaign calendar maximising ROI", "description": "We plan and execute digital marketing campaigns on a twelve-month calendar aligned to landscaping demand patterns. Budget allocation shifts monthly — heavier spend during peak planning periods, targeted niche campaigns during quieter months — ensuring every pound works hardest when customer intent is highest."}, {"title": "Real project creative that stops the scroll", "description": "Ad campaigns feature your actual completed projects — dramatic before-and-after transformations, timelapse videos, and aerial garden photography. Real work outperforms stock imagery by significant margins in click-through and enquiry conversion rates for landscaping businesses."}, {"title": "Retargeting campaigns for long-consideration projects", "description": "Homeowners researching major garden projects take weeks or months to decide. Our retargeting campaigns keep your business visible throughout this consideration period, showing relevant project examples and testimonials to website visitors who did not enquire on their first visit."}]',
  '[{"question": "How much should a landscaper spend on digital marketing?", "answer": "Most landscaping businesses see strong returns from an initial monthly budget of three hundred to eight hundred pounds, depending on service area size and target project values. We recommend starting conservatively, proving ROI on your highest-margin services, and scaling spend based on measurable results."}, {"question": "Which platforms work best for landscaping advertising?", "answer": "Facebook and Instagram are typically the highest-performing platforms for landscapers because visual project content drives strong engagement. Google Ads captures high-intent searches for specific services. We usually recommend a combination, with budget split adjusted seasonally based on performance."}, {"question": "Can digital marketing help during the quieter winter months?", "answer": "Absolutely. Targeted campaigns promoting winter-appropriate services — hard landscaping, drainage, fencing, garden clearance, and early spring planning consultations — generate work during traditionally slow periods. Many of our landscaping clients now maintain steady enquiry flow year-round through seasonal campaign planning."}, {"question": "How do you measure return on landscaping marketing spend?", "answer": "We track every enquiry back to its source: which ad, which platform, which campaign generated each lead. Monthly reports show cost per enquiry, cost per booked job, and return on ad spend. You see exactly how much revenue your marketing investment produces each month."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 8. Landscapers × Workwear & Print
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'landscapers',
  'workwear-print',
  'Landscapers work in full public view on residential streets, and every job is an opportunity to generate the next one. Branded workwear, vehicle signage, and printed leave-behind materials turn every project into a marketing event. When your team is working on a front garden in a residential estate, every passing neighbour and dog walker sees your brand. Professional workwear signals quality and trustworthiness — critical when you are working on someone''s property — while well-designed business cards and project postcards left with nearby homes convert that visibility into enquiries. Yet most landscaping teams work in unmarked clothes, drive partially branded vans, and leave nothing behind for curious neighbours to find. We provide complete branded workwear, van livery installation, printed marketing materials, and leave-behind cards designed specifically for landscaping businesses to maximise every job''s marketing potential.',
  'Every landscaping job is a public demonstration of your work happening in real time on a visible residential street. Branded workwear, vehicle signage, and printed materials ensure that this natural advertising generates maximum return. Professional presentation also builds customer confidence — homeowners feel more comfortable with a uniformed team on their property, and neighbours are more likely to approach a clearly identified business about their own garden.',
  'We supply durable outdoor workwear — embroidered polos, softshell jackets, and high-vis options — designed to withstand landscaping conditions while maintaining brand consistency. Printed materials include door-drop postcards with before-and-after project images for neighbouring properties and appointment cards for follow-up visits.',
  '[{"title": "Team working on residential streets with no branding visible", "description": "A landscaping crew working on a front garden is seen by dozens of neighbours daily. Without branded workwear and clear vehicle signage, this free marketing exposure is entirely wasted. Neighbours who might have enquired have no idea who you are or how to contact you."}, {"title": "Cheap workwear that degrades after weeks of outdoor work", "description": "Landscaping is tough on clothing — mud, thorns, rain, and constant physical movement destroy low-quality embroidered polos and printed t-shirts within weeks. Faded, torn branded workwear looks worse than no branding at all, actively damaging your professional image."}, {"title": "No leave-behind materials for neighbouring properties", "description": "After completing a garden transformation, most landscapers pack up and leave without any marketing materials for the surrounding homes. Neighbours who admired the work have no card, flyer, or postcard to prompt them into making contact about their own garden."}]',
  '[{"title": "Durable outdoor-grade branded workwear", "description": "We supply landscaping-appropriate workwear — reinforced embroidered polos, waterproof softshell jackets, branded beanies, and high-vis options — made from materials that withstand outdoor trade conditions. Embroidery and print methods are chosen for durability through repeated washing and daily wear."}, {"title": "Neighbour door-drop postcards with project photography", "description": "After each project, branded postcards featuring before-and-after photographs of the completed garden are dropped through letterboxes on the surrounding streets. Each card includes a compelling introductory offer and your contact details, converting nearby visibility into direct enquiries."}, {"title": "Vehicle signage designed for residential street visibility", "description": "Van wraps and magnetic signage designed for maximum legibility from across a residential street. Bold branding, a memorable phone number, and your website address ensure that every minute your van is parked outside a job site generates potential customer awareness and contact."}]',
  '[{"question": "What workwear is best for landscaping teams?", "answer": "We recommend embroidered polo shirts for warm weather, branded softshell jackets for cooler conditions, and embroidered beanies for winter. All items are selected for durability in outdoor conditions. We also offer high-visibility options for roadside and commercial site work."}, {"question": "How do door-drop postcards work after a landscaping job?", "answer": "After completing a project, you or your team distribute branded postcards to nearby homes — typically twenty to fifty properties on the surrounding streets. Each postcard features before-and-after images of the completed work, your contact details, and an introductory offer. This consistently generates one to three enquiries per drop for our landscaping clients."}, {"question": "Can you design van wraps for different vehicle types?", "answer": "Yes. We design livery for vans, pickup trucks, and trailers commonly used by landscaping businesses. Each design is created for your specific vehicle dimensions and optimised for visibility when the vehicle is parked on a residential street during jobs."}, {"question": "How quickly can branded workwear be produced?", "answer": "Standard embroidered workwear orders are completed within seven to ten working days. Rush orders for smaller quantities can often be turned around in five days. We hold stock of core garments in common sizes to ensure fast turnaround for landscaping teams needing to kit out quickly."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 9. Landscapers × AI Chatbots
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'landscapers',
  'ai-chatbots',
  'Landscaping enquiries arrive at unpredictable times — a homeowner admiring their neighbour''s new patio at the weekend, someone researching garden redesigns on a weekday evening, or a property manager needing emergency tree work at short notice. When these potential customers visit your website and find no one available to respond, most leave and contact the next landscaper on their list. An AI chatbot built for landscaping businesses handles these conversations intelligently: qualifying the project type and scope, collecting property details and access requirements, providing approximate timelines for common services, and booking site visit consultations directly into your calendar. It understands the difference between a customer wanting a full garden redesign and someone needing a simple hedge trim, and responds appropriately to each. We build AI chatbots specifically trained on landscaping services that capture and qualify leads twenty-four hours a day without you lifting a finger.',
  'Landscapers spend their working hours on-site with no opportunity to answer phones or respond to website enquiries. By the time you check messages in the evening, motivated prospects have already contacted and potentially booked with a competitor. An AI chatbot engages every visitor instantly, qualifies their project requirements, and books consultations — ensuring you never lose a lead to slow response times while you are busy creating gardens.',
  'Our landscaping chatbots are trained on your specific service offerings, typical project timelines, and service area. They ask intelligent qualifying questions — garden size, project type, access requirements, preferred timing — and distinguish between high-value design projects and routine maintenance requests, prioritising accordingly.',
  '[{"title": "Enquiries lost while working on-site all day", "description": "Landscapers cannot answer phones or respond to web enquiries while operating machinery, laying patios, or managing planting projects. By evening, motivated prospects have already contacted two or three competitors and often committed to whichever business responded first."}, {"title": "No qualification of enquiries before site visits", "description": "Without pre-qualification, landscapers waste hours driving to site visits for projects that turn out to be far below their minimum job value, in areas outside their service radius, or for customers with unrealistic budget expectations. Each wasted visit costs time and fuel."}, {"title": "Weekend and evening enquiries going completely unanswered", "description": "Homeowners frequently research landscapers on Saturday mornings while looking at their garden or on weekday evenings after work. These peak research periods are outside business hours, meaning the highest-intent enquiries receive the slowest responses."}]',
  '[{"title": "Instant engagement with every website visitor", "description": "Your AI chatbot greets every visitor within seconds, asks about their project requirements, and guides them through a conversational qualification process. Whether they visit at midday on Tuesday or ten o''clock on Saturday evening, they receive an immediate, helpful response that keeps them on your site."}, {"title": "Intelligent project qualification and prioritisation", "description": "The chatbot asks targeted questions about garden size, desired features, timeline, and budget range. It distinguishes between a full garden redesign worth thousands and a simple lawn-mowing enquiry, flagging high-value projects for immediate follow-up while routing routine requests appropriately."}, {"title": "Automated site visit booking with calendar integration", "description": "Qualified prospects can book a site visit consultation directly through the chatbot, selecting from your available time slots. You receive a detailed brief — project type, garden dimensions, access notes, and customer expectations — before you arrive, making every consultation more productive."}]',
  '[{"question": "Can an AI chatbot understand different landscaping project types?", "answer": "Yes. We train the chatbot on your full service range — garden design, patio installation, planting schemes, fencing, water features, maintenance contracts, and any specialist services you offer. It asks relevant follow-up questions based on the project type identified and provides appropriate information for each."}, {"question": "What happens when the chatbot cannot answer a question?", "answer": "When the chatbot encounters a question outside its training, it acknowledges the query, captures the customer''s contact details and specific question, and notifies you for a personal follow-up. No visitor is left without a response, and complex enquiries are escalated appropriately."}, {"question": "Will customers know they are talking to a chatbot?", "answer": "The chatbot is transparent about being an AI assistant for your business. In practice, customers appreciate the instant response and structured qualification process. Many prefer it to leaving a voicemail, as they can describe their project in detail and receive helpful information immediately."}, {"question": "Can the chatbot provide rough cost estimates for landscaping work?", "answer": "If you wish, the chatbot can share indicative price ranges for common services like turfing per square metre, standard patio sizes, or fencing per metre run. These are presented as approximate guides with a clear note that a site visit is needed for accurate quotation."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 10. Landscapers × AI Content
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'landscapers',
  'ai-content',
  'Content marketing for landscapers means publishing the kind of expertise that homeowners search for before hiring: seasonal planting guides, patio material comparisons, garden design inspiration, drainage solutions, and maintenance advice. This content builds search visibility, demonstrates authority, and pre-sells your expertise to prospects who are researching before they commit. But writing blog posts, service descriptions, and social captions is the last thing a landscaper has time for after a physical day on-site. AI-powered content creation solves this by generating expert-level landscaping content calibrated to your services, service area, and the seasonal search patterns that drive gardening decisions. Every piece is grounded in genuine horticultural and trade knowledge, optimised for the search terms homeowners actually use, and structured to drive consultation bookings. We set up AI content systems for landscapers that produce a consistent stream of authoritative, SEO-optimised content without requiring you to write a single word.',
  'Landscaping customers research extensively before committing to projects costing hundreds or thousands of pounds. Businesses that publish helpful content — planting guides, material comparisons, design tips — build trust and capture search traffic from these research queries. Without regular content, your website remains static while competitors who publish consistently accumulate search authority and attract the customers doing their homework.',
  'Our AI content system is trained on horticultural knowledge, landscaping trade practices, and your specific services. It produces seasonal blog posts, service page content, and social media captions that reference real plants, materials, techniques, and Kent-specific growing conditions — not generic gardening fluff.',
  '[{"title": "No time to write content after physically demanding days", "description": "Landscapers finish work exhausted from outdoor manual labour and have zero energy for writing blog posts about patio materials or planting schemes. Content creation gets perpetually postponed, leaving the website static and invisible for the dozens of informational searches potential customers make before hiring."}, {"title": "Website content is thin and generic", "description": "Most landscaping websites have brief service descriptions that say little more than ''we do patios, planting, and fencing.'' Without detailed, expert content covering each service, specific materials, design approaches, and project processes, the site fails to demonstrate the expertise that justifies premium pricing."}, {"title": "Competitors publishing content are gaining search advantage", "description": "Landscaping businesses that regularly publish guides, case studies, and seasonal advice accumulate search authority month by month. Without matching this content output, your site falls progressively further behind in rankings for the informational and commercial search terms that drive landscaping enquiries."}]',
  '[{"title": "Seasonal content calendar with automated production", "description": "We create a twelve-month content calendar aligned to landscaping search trends: spring garden design inspiration, summer maintenance guides, autumn planting advice, and winter hardscaping features. AI generates each piece with genuine horticultural accuracy, ready for your review and publication."}, {"title": "Service-specific deep content for every offering", "description": "Detailed pages covering each landscaping service — materials comparisons for patios, planting scheme options for different soil types, fence style guides, water feature installation processes — demonstrate expertise that generic competitors cannot match and capture long-tail search traffic."}, {"title": "Social media captions and project descriptions", "description": "AI generates engaging captions for your completed project photographs, seasonal tips for social media posting, and Google Business Profile updates. This content is tailored to your voice and brand, maintaining a consistent social presence without the time investment of writing from scratch."}]',
  '[{"question": "Will AI content sound authentic for a landscaping business?", "answer": "Yes. Our AI content system is trained on genuine horticultural knowledge, landscaping trade terminology, and your specific services and approach. Content references real plant species, actual materials and techniques, and Kent-specific growing conditions. Every piece is reviewed for accuracy before publication."}, {"question": "What types of content does the AI produce for landscapers?", "answer": "Blog posts covering seasonal topics, detailed service pages, project case study write-ups, social media captions for completed work, Google Business Profile posts, and email newsletter content. The system produces whatever content types deliver the most value for your specific marketing strategy."}, {"question": "How often will new content be published?", "answer": "We typically produce two to four blog posts per month plus ongoing social captions and service page updates. This frequency is enough to build meaningful search authority while maintaining quality. The exact volume is adjusted based on your competitive landscape and growth targets."}, {"question": "Do I need to review the content before it goes live?", "answer": "We recommend a brief review to ensure accuracy and alignment with your preferences. Most landscaping clients spend ten to fifteen minutes per week reviewing AI-generated content. We can also handle publication directly if you prefer a fully managed service."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 11. Landscapers × AI Automation
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'landscapers',
  'ai-automation',
  'AI automation for landscapers goes beyond simple email sequences — it introduces intelligent decision-making into your business operations. An AI system can analyse incoming enquiries and automatically route high-value garden design requests for priority follow-up while scheduling routine maintenance enquiries for batch processing. It can monitor weather forecasts and proactively notify affected customers about potential schedule changes before they chase you for updates. It can analyse your completed project photography, generate optimised descriptions, and post them to your social channels and Google Business Profile without manual intervention. For landscaping businesses handling dozens of enquiries, multiple active projects, and seasonal demand fluctuations simultaneously, AI automation transforms reactive firefighting into proactive, systematised operations. We build AI automation systems for landscapers that handle the intelligent admin tasks that currently consume your evenings and weekends.',
  'Landscaping businesses generate enormous amounts of repetitive administrative work — enquiry responses, quote preparation, scheduling coordination, customer updates, review collection, and seasonal marketing. As the business grows, this admin burden grows faster than revenue, forcing owners to choose between time on-site earning money and time at a desk managing operations. AI automation handles the intelligent repetitive tasks that currently bottleneck your growth.',
  'We build AI automations specific to landscaping workflows: intelligent enquiry triage that prioritises by project value, weather-aware schedule management that proactively communicates delays, automated project photography processing for social media, and smart seasonal campaign triggers based on local weather and calendar data.',
  '[{"title": "Evenings consumed by admin instead of rest or family", "description": "Landscaping business owners routinely spend two to three hours every evening processing enquiries, writing quotes, chasing approvals, and updating customers on project schedules. This unsustainable workload leads to burnout and forces a choice between business growth and personal wellbeing."}, {"title": "Weather disruptions creating communication chaos", "description": "Rain, frost, and wind regularly disrupt outdoor project schedules. Manually contacting every affected customer, rescheduling appointments, and coordinating revised timelines consumes hours of reactive admin that could be eliminated with proactive automated communication."}, {"title": "Growing enquiry volume impossible to manage manually", "description": "As marketing efforts increase enquiry flow, manually triaging, qualifying, and responding to every lead becomes unsustainable. High-value garden design enquiries get the same delayed response as simple hedge-trimming requests, and premium prospects hire the competitor who responded faster."}]',
  '[{"title": "Intelligent enquiry triage and priority routing", "description": "AI analyses incoming enquiries and automatically categorises them by project type, estimated value, and urgency. High-value garden design and hardscaping requests are flagged for immediate personal follow-up, while routine maintenance enquiries receive automated responses and scheduling — ensuring your time is spent on the most profitable conversations."}, {"title": "Weather-aware schedule management and customer communication", "description": "AI monitors local weather forecasts and automatically identifies projects likely to be affected by rain, frost, or high winds. Proactive notifications are sent to affected customers with revised timelines and rescheduling options, eliminating reactive communication and demonstrating professional project management."}, {"title": "Automated project content creation and distribution", "description": "When you upload completed project photos to a shared folder, AI generates optimised descriptions, creates before-and-after social media posts, updates your Google Business Profile, and adds the project to your website portfolio. A task that previously took thirty minutes per project happens automatically."}]',
  '[{"question": "How does AI triage landscaping enquiries?", "answer": "The AI analyses enquiry content for project indicators — garden size mentions, specific services requested, budget references, and timeline urgency. It assigns a priority score and routes high-value prospects for immediate personal response while sending automated acknowledgements and qualification questions to lower-priority enquiries."}, {"question": "Can AI automation handle weather-related schedule changes?", "answer": "Yes. The system monitors local weather forecasts and cross-references them with your project schedule. When weather is likely to affect outdoor work, it automatically notifies affected customers with delay explanations and rescheduling options, then updates your calendar when customers confirm new dates."}, {"question": "Will AI automation replace the personal touch with my customers?", "answer": "No. AI handles the repetitive administrative tasks — initial responses, qualification questions, scheduling logistics, review requests — freeing you to spend more personal time on site visits, design consultations, and the high-value interactions where your expertise and personality matter most."}, {"question": "What does AI automation cost for a landscaping business?", "answer": "AI automation systems are built to match your business scale and needs. Most landscaping businesses start with enquiry triage and quote follow-up automation, then expand to weather management and content distribution as they see results. The investment typically pays for itself within the first month through recovered leads and time savings."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;
