-- seed-industry-hub-content.sql
-- Adds hub-page content columns and seeds all 16 industries with unique, industry-specific copy.

-- ============================================================
-- 1. Schema changes
-- ============================================================

ALTER TABLE industries ADD COLUMN IF NOT EXISTS overview_text TEXT;
ALTER TABLE industries ADD COLUMN IF NOT EXISTS strategy_text TEXT;
ALTER TABLE industries ADD COLUMN IF NOT EXISTS opportunity_seo TEXT;
ALTER TABLE industries ADD COLUMN IF NOT EXISTS opportunity_automation TEXT;
ALTER TABLE industries ADD COLUMN IF NOT EXISTS industry_stats JSONB DEFAULT '{}';

-- ============================================================
-- 2. Industry content updates
-- ============================================================

-- ── ACCOUNTANTS ─────────────────────────────────────────────
UPDATE industries SET
  overview_text = 'The accountancy sector in Kent is navigating a seismic shift driven by HMRC''s Making Tax Digital mandate, which now extends to Income Tax Self Assessment from April 2026. Firms across Maidstone, Canterbury, and the Medway Towns face dual pressure: retaining existing clients who expect seamless digital filing while attracting new SMEs searching online for MTD-compliant advisors. Many Kent practices still rely on word-of-mouth referrals and outdated brochure-style websites that fail to communicate expertise in cloud accounting platforms like Xero, QuickBooks, or FreeAgent. With over 2,800 registered accountancy firms operating in the South East, differentiation hinges on demonstrating specialist sector knowledge, transparent pricing, and genuine thought leadership rather than generic service listings.',
  strategy_text = 'An accountancy website must function as a trust engine. Qualification badges — ACCA, ICAEW, AAT — belong above the fold alongside Google review ratings. Service pages need to address specific pain points: MTD migration, year-end filing deadlines, R&D tax credit claims. A fee calculator or transparent pricing table dramatically reduces enquiry friction. Blog content should target calendar-driven queries — "When is the self-assessment deadline" peaks every January. Client portal integration signals modernity, and case studies showing tangible tax savings convert better than any testimonial.',
  opportunity_seo = 'Accountancy searches are high-intent and locality-driven. "Accountant near me" converts at roughly three times the rate of generic service queries because searchers have already decided they need professional help. Ranking for niche terms like "contractor accountant Kent" or "R&D tax credits Maidstone" captures prospects with specific needs and higher lifetime value. Seasonal content targeting self-assessment and corporation tax deadlines generates predictable annual traffic spikes that compound year on year.',
  opportunity_automation = 'Automation transforms accountancy onboarding from weeks to hours. A structured intake form that captures company type, turnover band, and current software feeds directly into a CRM workflow, triggering engagement letters and ID verification requests automatically. Automated appointment scheduling with calendar sync eliminates the back-and-forth emails that delay new client setup. Deadline reminder sequences — for VAT returns, payroll submissions, and confirmation statements — reduce missed filings and strengthen client retention.',
  industry_stats = '{"stat1": "Making Tax Digital for ITSA affects 4.2M UK sole traders and landlords from April 2026", "stat2": "73% of UK SMEs now search online when choosing a new accountant", "stat3": "Average accountancy client lifetime value exceeds £3,200 per annum"}'::jsonb
WHERE slug = 'accountants';

-- ── BUILDERS ────────────────────────────────────────────────
UPDATE industries SET
  overview_text = 'Kent''s construction sector is buoyed by sustained housing demand across the Thames Gateway corridor, ongoing regeneration in Ebbsfleet and Ashford, and a steady pipeline of loft conversions and extensions driven by stamp duty economics. Yet most local builders still win work through word-of-mouth and Checkatrade listings, surrendering margin to platform commissions and competing on price rather than reputation. The digital gap is stark: homeowners planning a £40K extension will research extensively online, but the majority of Kent builders present little more than a phone number and a Facebook page. Building regulations, planning permission complexity, and insurance requirements like public liability and structural warranties all create content opportunities that few firms exploit.',
  strategy_text = 'A builder''s website must bridge the trust gap inherent in high-value projects. A portfolio organised by project type — extensions, new builds, renovations — with before-and-after photography and stated budgets reassures prospects. Displaying FMB membership, NHBC registration, and TrustMark accreditation signals professionalism. An integrated project enquiry form that captures property type, project scope, and budget range qualifies leads before the first phone call. Embedding planning permission guides and build-cost calculators positions the firm as an authority rather than just another contractor.',
  opportunity_seo = 'Builder searches skew heavily toward project types: "loft conversion cost Kent," "house extension builder Maidstone," and "garage conversion near me" all carry strong purchase intent. Google''s local pack dominates these results, making Google Business Profile optimisation essential. Image search is underutilised — properly tagged project photos rank well and drive qualified traffic. Location-specific landing pages for Kent''s major towns capture long-tail searches that aggregator sites often miss.',
  opportunity_automation = 'Builders lose hours each week on quoting admin. An automated enquiry-to-estimate workflow that captures project details, attaches uploaded photos, and routes leads to the right project manager cuts response times dramatically. Automated follow-ups after initial site visits keep prospects warm during the long decision cycle typical of construction projects. Post-completion review request sequences, timed to coincide with project handover, build the Google review volume that drives future lead generation.',
  industry_stats = '{"stat1": "Average UK home extension costs £35,000–£70,000, making research-intensive buying cycles the norm", "stat2": "82% of homeowners shortlist builders based on online portfolio quality", "stat3": "Builders on Checkatrade pay up to £120+ per qualified lead in high-demand areas"}'::jsonb
WHERE slug = 'builders';

-- ── CARPENTERS ──────────────────────────────────────────────
UPDATE industries SET
  overview_text = 'Carpentry and joinery in Kent spans a broad spectrum — from heritage restoration work on the county''s wealth of listed buildings and oast houses to contemporary fitted furniture and bespoke kitchen installations. The challenge for Kent''s carpenters is visibility: most operate as sole traders or micro-businesses, relying on subcontract work from builders rather than marketing directly to homeowners. This leaves significant revenue on the table, particularly in affluent areas like Sevenoaks, Tunbridge Wells, and Whitstable where demand for bespoke joinery commands premium pricing. The visual nature of carpentry makes it inherently suited to digital marketing, yet most tradespeople in this sector lack even a basic website, let alone one that showcases their craft effectively.',
  strategy_text = 'A carpenter''s website is fundamentally a visual portfolio. High-resolution imagery of completed work — dovetail joints, fitted wardrobes, oak staircases — does the heavy lifting. Organising projects by category (kitchens, staircases, fitted furniture, restoration) helps visitors self-qualify. Material expertise should be front and centre: specialism in hardwoods, reclaimed timber, or specific techniques like steam bending differentiates craftspeople from general contractors. A measurement booking form with room dimension fields streamlines the quoting process, and integration with Instagram creates a living portfolio that updates automatically.',
  opportunity_seo = 'Carpentry searches divide into two distinct intent clusters: urgent repair queries like "broken door frame repair near me" and aspirational project searches like "bespoke fitted wardrobes Kent." The latter carry far higher project values and longer research cycles. Image search is particularly powerful for carpentry — well-optimised portfolio images with descriptive alt text rank prominently. Content targeting material comparisons ("oak vs walnut worktops") and design inspiration captures prospects at the top of the funnel.',
  opportunity_automation = 'Bespoke carpentry involves detailed specification gathering before any quote can be issued. An automated brief form that captures room dimensions, timber preferences, design references, and photo uploads eliminates the typical two or three pre-quote site visits. Automated project update emails with progress photos keep clients informed during longer commissions. A post-installation care guide sequence — covering timber maintenance, oiling schedules, and warranty terms — adds professional polish and prompts referrals.',
  industry_stats = '{"stat1": "Bespoke fitted furniture commands 40–60% premium over mass-produced alternatives", "stat2": "Kent has over 2,100 listed buildings requiring specialist joinery skills", "stat3": "85% of bespoke joinery clients request a portfolio viewing before commissioning work"}'::jsonb
WHERE slug = 'carpenters';

-- ── CLEANING COMPANIES ──────────────────────────────────────
UPDATE industries SET
  overview_text = 'The commercial and domestic cleaning sector in Kent is fiercely competitive, with low barriers to entry creating a saturated market where differentiation is everything. Post-pandemic hygiene expectations have permanently elevated standards — businesses now require documented cleaning protocols, COSHH compliance records, and staff DBS checks as baseline requirements. The Kent market splits clearly between domestic cleaning (regular house cleans, end-of-tenancy, and Airbnb turnovers) and commercial contracts (offices, medical facilities, schools). Most cleaning companies compete purely on hourly rates, creating a race to the bottom that erodes profitability. The firms that thrive online are those that segment their services clearly, display insurance and accreditation credentials, and make instant booking frictionless.',
  strategy_text = 'A cleaning company website must remove every barrier to booking. Instant quote calculators based on property size, room count, and service type convert at significantly higher rates than simple contact forms. Displaying DBS certification, public liability insurance amounts, and cleaning product credentials (eco-friendly, COSHH-compliant) builds trust in an industry plagued by unreliable operators. Service pages must be granular — end-of-tenancy cleaning has completely different requirements and pricing from regular domestic maintenance. Recurring booking options with frequency discounts encourage long-term client relationships over one-off transactions.',
  opportunity_seo = 'Cleaning searches are intensely local and often urgent: "end of tenancy cleaning Canterbury" or "office cleaning company Maidstone" signal immediate need with short decision cycles. Google''s local pack dominates results, making review volume and rating the primary ranking differentiator. Seasonal opportunities exist around spring cleaning, post-Christmas deep cleans, and the university letting cycle in Canterbury. Targeting commercial cleaning niches — dental surgery cleaning, school cleaning contracts — captures higher-value B2B clients.',
  opportunity_automation = 'Cleaning businesses live and die by scheduling efficiency. Automated booking systems that show real-time availability, calculate pricing by property parameters, and confirm appointments via SMS reduce no-shows and eliminate phone tag. Recurring clean reminders with one-click rebooking maintain client frequency. Automated quality follow-ups sent 24 hours after each clean capture satisfaction scores and prompt Google reviews. Staff roster integration ensures jobs are assigned based on location clusters, minimising travel dead time.',
  industry_stats = '{"stat1": "End-of-tenancy cleaning demand spikes 340% in June–July across Kent university towns", "stat2": "Cleaning companies with online booking convert 52% more enquiries than phone-only firms", "stat3": "Average domestic cleaning client retains for 14 months when automated rebooking is in place"}'::jsonb
WHERE slug = 'cleaning-companies';

-- ── DRIVEWAY INSTALLERS ─────────────────────────────────────
UPDATE industries SET
  overview_text = 'Driveway installation in Kent represents a high-value, visually-driven market where a single project typically ranges from £3,000 for a basic tarmac resurface to £15,000+ for a block-paved or resin-bound finish. Kent''s planning regulations add complexity — front garden paving over five square metres requires permeable materials or drainage to a permeable area under Permitted Development rules, yet many installers fail to communicate this clearly. The sector is plagued by rogue traders and substandard work, making trust signals absolutely critical for legitimate operators. Seasonal demand peaks sharply in spring and early autumn, with homeowners planning improvements around property sales, and the growing trend toward electric vehicle charging points is creating new driveway design considerations across the county.',
  strategy_text = 'A driveway installer''s website must lead with visual proof of quality. Side-by-side before-and-after galleries organised by material type — block paving, resin bound, tarmac, gravel, Indian sandstone — let prospects compare finishes instantly. An interactive driveway cost calculator based on area size and material choice dramatically increases engagement. Planning permission guidance content builds authority and trust. Displaying Marshall''s or Brett approved installer status, along with insurance-backed guarantees, separates professional firms from the cowboy operators that plague this sector. Postcode-specific case studies prove local experience.',
  opportunity_seo = 'Driveway searches are almost exclusively project-driven and carry high commercial value: "block paving driveway cost" and "resin bound driveway installer near me" indicate prospects who have already decided to proceed. Material comparison content — "resin bound vs block paving pros and cons" — captures research-phase traffic and positions the installer as an advisor. Local image search for "driveway ideas" drives significant top-of-funnel discovery. Winter and spring content targeting "driveway repair" and "pothole repair" captures maintenance-stage leads.',
  opportunity_automation = 'Driveway projects involve a predictable sequence: enquiry, site survey, quote, acceptance, scheduling, and installation. Automating this pipeline — from initial enquiry form capturing driveway dimensions and photos through to automated survey booking and quote follow-up — compresses the sales cycle. Automated weather-dependent scheduling notifications keep clients informed about installation timing. Post-installation sequences delivering a maintenance guide and requesting reviews at the optimal moment maximise referral potential from every completed project.',
  industry_stats = '{"stat1": "Average UK driveway project value: £4,800 for block paving, £6,200 for resin bound", "stat2": "91% of driveway enquiries originate from Google search rather than social media", "stat3": "Permeable paving regulations affect an estimated 4.8M UK properties with paved front gardens"}'::jsonb
WHERE slug = 'driveway-installers';

-- ── ELECTRICIANS ────────────────────────────────────────────
UPDATE industries SET
  overview_text = 'Electrical contractors in Kent operate within one of the most heavily regulated trade sectors, where Part P Building Regulations compliance, 18th Edition Wiring Regulations (BS 7671), and registration with a competent person scheme such as NICEIC, NAPIT, or ELECSA are non-negotiable requirements. The market divides between domestic work — rewires, consumer unit upgrades, EV charger installations — and commercial contracts covering offices, retail, and industrial premises. The rapid growth of EV charging infrastructure and solar panel installations is creating substantial new revenue streams, yet many Kent electricians still rely entirely on word-of-mouth and fail to capitalise on these high-value, search-driven opportunities. With electrical safety certificates required for all rental properties under the 2020 regulations, the landlord market represents another significant and recurring revenue channel.',
  strategy_text = 'An electrician''s website must immediately communicate safety and compliance. NICEIC or NAPIT registration logos, Part P compliance statements, and public liability insurance details belong in the header. Service pages should separate domestic, commercial, and specialist services (EV charging, solar, fire alarm systems). Emergency callout availability needs prominent display with click-to-call functionality. An EICR booking system for landlords — capturing property address, number of circuits, and preferred dates — streamlines the fastest-growing segment. Displaying pricing bands for common jobs (socket additions, consumer unit upgrades) reduces enquiry friction for price-sensitive domestic customers.',
  opportunity_seo = 'Electrical searches split between emergency queries ("electrician near me now," "no power in house") demanding immediate response, and planned project searches ("EV charger installation Kent," "house rewire cost") with longer decision cycles. Emergency terms are dominated by Google''s local pack, where response time and review recency determine ranking. EV charger installation is a rapidly growing search category with relatively low competition — early ranking positions in this niche deliver outsized returns. EICR-related terms capture the landlord compliance market.',
  opportunity_automation = 'Emergency electrical work demands instant response — an automated triage system that captures fault description, property type, and urgency level, then routes to the nearest available engineer with SMS confirmation, can mean the difference between winning and losing a job. For planned work, automated EICR reminder sequences sent to landlord clients before certificate expiry dates generate predictable recurring revenue. Quote follow-up sequences with educational content about electrical safety regulations nurture prospects through the decision process for larger rewiring projects.',
  industry_stats = '{"stat1": "EV charger installation searches have grown 280% in Kent since 2022", "stat2": "EICR regulations require certificates for all rental properties, affecting 180,000+ Kent landlords", "stat3": "76% of emergency electrical callouts are booked via smartphone within 30 minutes of the fault"}'::jsonb
WHERE slug = 'electricians';

-- ── GARDEN SERVICES ─────────────────────────────────────────
UPDATE industries SET
  overview_text = 'Garden maintenance services in Kent benefit from the county''s favourable growing climate and high proportion of detached and semi-detached properties with substantial gardens. The market encompasses regular lawn care, hedge trimming, seasonal planting, green waste removal, and increasingly, ongoing garden management contracts for time-poor professionals. Kent''s ageing population also drives demand, with many older homeowners needing reliable help maintaining established gardens they can no longer manage themselves. The sector is characterised by extreme seasonality — demand surges from March through October and drops sharply in winter, making client retention and year-round service diversification critical challenges. Most garden maintenance operators lack any web presence, operating through leaflet drops and local Facebook groups.',
  strategy_text = 'A garden services website should emphasise reliability and regular availability over one-off project work. Subscription-based service packages (fortnightly lawn care, monthly full maintenance) with clear pricing convert better than vague "call for a quote" prompts. Seasonal service calendars showing what gardens need month-by-month position the business as knowledgeable and proactive. Before-and-after garden transformation galleries prove capability, while a simple postcode checker confirming coverage area prevents wasted enquiries. Displaying waste carrier licence details and insurance credentials builds trust in a sector with minimal regulation.',
  opportunity_seo = 'Garden service searches are highly seasonal and emphatically local: "gardener near me" peaks sharply in March and April as homeowners confront overgrown winter gardens. "Garden clearance" and "hedge cutting service" are high-volume action queries with strong conversion rates. Content targeting seasonal advice — "when to scarify a lawn," "best time to trim a privet hedge" — builds organic authority and captures recurring traffic. Service area pages targeting specific Kent towns with population-appropriate content outperform generic county-wide pages.',
  opportunity_automation = 'Garden maintenance is inherently recurring, making it ideal for automated scheduling. A booking system offering fortnightly or monthly slots with automatic calendar population and SMS reminders the day before each visit reduces no-access visits. Seasonal upsell sequences — autumn leaf clearance in October, spring lawn treatment in March — maximise revenue per client. Automated invoicing triggered by job completion, with integrated card payment links, eliminates the cash-in-hand culture that undermines professional operators.',
  industry_stats = '{"stat1": "Garden maintenance searches increase 215% between February and April each year", "stat2": "Subscription-based garden services report 72% client retention at 12 months vs 28% for ad-hoc", "stat3": "Kent has 620,000+ residential properties, of which 68% have private gardens"}'::jsonb
WHERE slug = 'garden-services';

-- ── HOLIDAY LETS ────────────────────────────────────────────
UPDATE industries SET
  overview_text = 'Kent''s holiday let market has expanded dramatically, driven by the post-pandemic staycation surge and the county''s strategic position offering both coastal retreats (Whitstable, Broadstairs, Deal) and countryside escapes (Weald, Downs, Romney Marsh). Property owners face a complex operating environment: Airbnb and Booking.com deliver bookings but extract 15–20% in combined host and guest fees, council tax versus business rates classification creates tax planning opportunities, and new short-term let registration requirements are on the horizon. The most successful Kent holiday let operators are those reducing platform dependency by driving direct bookings through their own websites — retaining the full nightly rate while building a guest database they actually own. With average occupancy rates for well-managed Kent coastal properties reaching 75%+ in peak season, the revenue case for professional digital presence is compelling.',
  strategy_text = 'A holiday let website must be gallery-first — large hero images, virtual tours, and honest photography that sets accurate expectations. An integrated availability calendar with real-time sync to Airbnb, Booking.com, and VRBO via channel manager API prevents double bookings. Direct booking with secure payment processing (Stripe) and instant confirmation must be seamless enough to compete with platform convenience. Guest reviews imported from multiple platforms build social proof. Area guides covering local restaurants, beaches, walks, and attractions add genuine value and improve SEO. Clear house rules, check-in procedures, and cancellation policies reduce pre-booking friction.',
  opportunity_seo = 'Holiday let searches are destination-specific and seasonal: "holiday cottage Whitstable," "dog friendly holiday let Deal," "coastal cottage Kent half term" all carry strong booking intent. Google now surfaces direct booking options more prominently in travel searches, creating a genuine opportunity to compete with OTA listings. Content targeting specific experiences — "best walks near Broadstairs," "things to do in Whitstable with kids" — drives discovery traffic. Schema markup for lodging businesses enables rich results with pricing, availability, and ratings directly in search.',
  opportunity_automation = 'Holiday let management involves repetitive operational sequences that are prime automation candidates. Automated guest communication workflows — booking confirmation, pre-arrival information pack, check-in instructions timed to arrival day, mid-stay check-in message, check-out reminder with review request — create a professional guest experience without manual intervention. Channel manager synchronisation keeps availability consistent across all platforms. Automated cleaner notification triggered by each checkout, with task checklists and photo verification, ensures turnover quality. Dynamic pricing rules that adjust rates based on demand, season, and local events maximise revenue per available night.',
  industry_stats = '{"stat1": "Direct bookings save holiday let owners 15–20% versus OTA commission structures", "stat2": "Kent coastal holiday lets average 75% occupancy May–September, dropping to 35% in winter", "stat3": "Properties with professional photography receive 40% more booking enquiries than phone-shot listings"}'::jsonb
WHERE slug = 'holiday-lets';

-- ── LANDSCAPERS ─────────────────────────────────────────────
UPDATE industries SET
  overview_text = 'Landscaping in Kent is a project-driven sector where individual commissions routinely range from £5,000 for a patio and planting scheme to £50,000+ for comprehensive garden redesigns. The county''s diverse geology — from chalk downland to Wealden clay — demands genuine horticultural knowledge and material selection expertise that distinguishes qualified landscapers from general builders who lay a few slabs. Kent''s affluent commuter belt areas (Sevenoaks, Tunbridge Wells, Cranbrook) sustain premium demand, while coastal towns generate steady work in low-maintenance, wind-resistant garden design. The sector increasingly intersects with sustainable drainage (SuDS) requirements, wildlife-friendly planting trends, and outdoor living space design incorporating kitchens, fire pits, and garden rooms — all of which command premium pricing.',
  strategy_text = 'A landscaping website must function as a design portfolio and project gallery. Case studies structured around the brief, design process, materials chosen, and final result demonstrate capability far more effectively than simple photo galleries. Organising work by project type — patios, planting, water features, garden rooms, driveways — helps prospects find relevant inspiration. Displaying BALI membership, APL accreditation, or City & Guilds qualifications signals professional standards. A design consultation booking form capturing garden dimensions, aspect, soil type, and style preferences pre-qualifies leads and demonstrates expertise from the first interaction.',
  opportunity_seo = 'Landscaping searches are split between inspiration-seeking ("garden design ideas," "small garden makeover") and project-ready ("landscaper near me," "patio installation Kent") intent. Image search drives substantial discovery traffic — properly optimised project photography with descriptive filenames and alt text ranks prominently for visual queries. Long-tail material queries like "Indian sandstone patio Kent" or "composite decking installer near me" capture prospects who have progressed past the inspiration phase. Seasonal content targeting "garden design" peaks in January–March as homeowners plan spring projects.',
  opportunity_automation = 'Landscaping projects involve extended design-to-build timelines, making automated nurture sequences essential. An initial enquiry form capturing garden photos, measurements, and inspiration images feeds into a design consultation booking workflow. Automated follow-ups after consultations — sharing mood boards, material samples, and phased pricing options — keep prospects engaged during the typically 4–8 week decision period. Post-project sequences requesting reviews, offering seasonal maintenance plans, and sharing planting care guides extend the client relationship beyond the initial build.',
  industry_stats = '{"stat1": "Average UK landscaping project value: £8,500 for residential, £22,000+ for premium garden redesigns", "stat2": "Garden renovation projects take an average of 6 weeks from first enquiry to contract signing", "stat3": "BALI-registered landscapers command 25–35% higher project fees than unaccredited competitors"}'::jsonb
WHERE slug = 'landscapers';

-- ── LETTING AGENTS ──────────────────────────────────────────
UPDATE industries SET
  overview_text = 'Kent''s rental market is shaped by distinct geographic dynamics: the Medway Towns and Thanet offer high yields on lower-value stock, Canterbury is dominated by student and young professional demand, and the London commuter belt commands premium rents driven by HS1 connectivity. Letting agents face a regulatory environment that has intensified significantly — the Tenant Fees Act 2019, mandatory client money protection, Electrical Safety Standards, and the looming Renters'' Reform Bill all create compliance burdens that favour professional operators over casual landlord self-management. Yet the sector''s online presence often lags behind its sophistication: many Kent agents still rely on Rightmove and Zoopla as their primary marketing channels, paying substantial portal fees while neglecting their own websites as lead generation assets.',
  strategy_text = 'A letting agent''s website must serve two distinct audiences: tenants searching for properties and landlords evaluating management services. A property search function with map integration, filtering by bedrooms, price, and area is table stakes. For landlord acquisition — the higher-value conversion — dedicated landing pages addressing rental yield calculations, regulatory compliance support, and fee transparency convert more effectively than generic "landlord services" pages. Instant online valuation tools using postcode data generate landlord leads at scale. Displaying ARLA Propertymark membership, client money protection certification, and redress scheme registration builds regulatory credibility.',
  opportunity_seo = 'Letting agent searches divide sharply by audience: tenants search "flats to rent in Canterbury" (high volume, low conversion for the agent) while landlords search "letting agent fees Maidstone" or "property management company Kent" (lower volume, vastly higher lifetime value). Optimising for landlord acquisition terms delivers superior ROI. Content targeting regulatory changes — Renters'' Reform Bill implications, EPC requirement updates, deposit protection rules — captures landlords actively seeking compliant management solutions. Area guide content for each Kent town improves both tenant and landlord SEO.',
  opportunity_automation = 'Letting agents handle enormous administrative volume across tenant enquiries, viewings, referencing, maintenance, and compliance. Automated viewing booking systems with calendar sync and SMS reminders reduce no-show rates, which typically run at 30–40% in the sector. Tenant onboarding workflows that trigger referencing, right-to-rent checks, and tenancy agreement generation compress move-in timelines. Automated maintenance request triage — capturing photos, categorising urgency, and routing to approved contractors — transforms a major operational bottleneck. Rent arrears escalation sequences triggered by missed payment dates ensure consistent, documented follow-up.',
  industry_stats = '{"stat1": "Kent has approximately 180,000 privately rented properties, growing 12% since 2019", "stat2": "Letting agents with online viewing booking report 35% fewer no-shows than phone-only booking", "stat3": "Average landlord client retention: 4.7 years, representing £9,400+ in cumulative management fees"}'::jsonb
WHERE slug = 'letting-agents';

-- ── PAINTERS AND DECORATORS ─────────────────────────────────
UPDATE industries SET
  overview_text = 'Painting and decorating in Kent encompasses everything from single-room refreshes to full exterior repaints on period properties, with the county''s extensive stock of Victorian terraces, Edwardian villas, and listed buildings creating demand for specialist knowledge in lime wash, heritage colour matching, and lead paint management. The sector suffers from particularly low digital adoption — most painters rely on van signage, business cards, and word-of-mouth, leaving a significant online gap. This is paradoxical given that decorating decisions are intensely visual and ideally suited to digital showcasing. The trend toward premium finishes — Farrow & Ball, Little Greene, specialist wallpapers — means clients increasingly research specific paint brands and techniques online before selecting a decorator.',
  strategy_text = 'A painter and decorator''s website needs to lead with colour and finish quality. Room transformation galleries with identified paint brands and colour names attract style-conscious clients willing to pay premium rates. Organising portfolios by room type (kitchens, bedrooms, exteriors) and technique (wallpapering, spray finishing, heritage restoration) helps visitors find relevant examples. Displaying Dulux Select Decorator or PDA membership status signals professionalism. A quote request form capturing room count, ceiling height, current wall condition, and finish preference (matt, eggshell, specialist) qualifies leads efficiently. Content exploring colour trends and paint comparisons attracts research-phase traffic.',
  opportunity_seo = 'Decorating searches are often project-triggered: "painter and decorator near me" spikes around bank holidays and school summer breaks when homeowners plan improvement projects. Higher-value searches target specific services — "exterior house painter Kent," "wallpaper hanger Canterbury," "spray painter for kitchen cabinets" — each representing a distinct job type. Content targeting brand-specific queries ("Farrow & Ball painter Kent") captures affluent clients who have already chosen premium materials and are seeking skilled application. Portfolio images optimised for "room makeover" and "before and after" queries drive visual search traffic.',
  opportunity_automation = 'Decorating quotes require room-specific details that an automated intake form handles more efficiently than site visits. Capturing room dimensions, photos of current condition, chosen colours or finishes, and access requirements (scaffolding, ceiling height) enables accurate remote quoting for straightforward jobs. Automated scheduling with weather-dependent notifications for exterior work prevents wasted journeys. Post-completion sequences requesting reviews and offering seasonal maintenance reminders — exterior touch-ups, annual refresh suggestions — generate repeat business in a trade that naturally recurs every 3–5 years.',
  industry_stats = '{"stat1": "63% of homeowners research paint colours and finishes online before contacting a decorator", "stat2": "Exterior painting demand increases 180% between April and September in South East England", "stat3": "Decorators specialising in heritage and period properties charge 30–50% more than standard residential rates"}'::jsonb
WHERE slug = 'painters-and-decorators';

-- ── PLUMBERS ────────────────────────────────────────────────
UPDATE industries SET
  overview_text = 'Plumbing in Kent serves both emergency and planned markets with fundamentally different customer behaviours. Emergency work — burst pipes, boiler breakdowns, blocked drains — demands instant response and converts within minutes of the initial search. Planned work — bathroom installations, boiler replacements, underfloor heating — involves research, comparison, and longer decision cycles. Kent''s housing stock diversity adds complexity: Victorian terraces in Rochester require different approaches than modern estates in Ebbsfleet. Gas Safe registration is legally required for any gas work, yet many Kent plumbing websites fail to display their registration number prominently. The 2025 boiler replacement incentive under the Boiler Upgrade Scheme, offering £7,500 toward heat pump installations, is creating a new market segment that forward-thinking plumbers are positioning to capture.',
  strategy_text = 'A plumber''s website must serve two modes: emergency and planned. For emergency work, a click-to-call button pinned to the top of every page, clear service area coverage, and "available now" indicators are essential — this visitor will leave within 10 seconds if they cannot call immediately. For planned work, detailed service pages covering bathroom installations, boiler replacements, and heating systems with indicative pricing guide comparison shoppers. Gas Safe registration number and logo must be displayed prominently. A boiler quote tool capturing property type, bedroom count, and current system type generates qualified leads for the highest-value plumbing work.',
  opportunity_seo = 'Plumbing emergency searches — "emergency plumber near me," "burst pipe plumber" — are the highest-converting local service queries in existence, with click-to-call rates exceeding 60% on mobile. However, planned work terms like "bathroom fitter Kent" and "boiler replacement cost" carry significantly higher project values. Ranking for both requires distinct content strategies: emergency pages optimised for speed and proximity signals, and project pages rich with specification detail and portfolio imagery. Heat pump installation queries are growing rapidly and represent an emerging SEO opportunity with limited competition.',
  opportunity_automation = 'Emergency plumbing demands the fastest possible response. An automated triage system that captures fault type, severity (e.g., water actively flowing vs slow drip), property type, and postcode, then instantly routes to the nearest available engineer with GPS-based dispatch, can compress response times to under 15 minutes. For boiler replacements, an automated survey booking system with pre-visit questionnaire captures existing system details and eliminates wasted survey visits. Annual boiler service reminder sequences sent to previous customers generate predictable recurring revenue and maintain Gas Safe compliance records.',
  industry_stats = '{"stat1": "78% of emergency plumbing searches happen on mobile devices, with 60%+ resulting in a call within 2 minutes", "stat2": "The Boiler Upgrade Scheme offers £7,500 grants for heat pump installations, driving new demand", "stat3": "Average UK boiler replacement costs £2,500–£4,500, making it the highest-value routine plumbing job"}'::jsonb
WHERE slug = 'plumbers';

-- ── PROPERTY MAINTENANCE ────────────────────────────────────
UPDATE industries SET
  overview_text = 'Property maintenance companies in Kent serve a market shaped by the county''s large private rental sector, growing build-to-rent developments, and commercial property portfolios requiring ongoing upkeep. The sector bridges multiple trades — plumbing, electrical, carpentry, decorating, general repairs — offering a single point of contact for property managers and landlords who need responsive, multi-skilled service without managing separate contractors. Kent''s regulatory environment intensifies demand: EICR inspections, gas safety certificates, EPC compliance, smoke and carbon monoxide alarm regulations, and Homes Act fitness standards all create recurring compliance-driven workload. The most successful property maintenance firms operate on retained contracts with letting agents, housing associations, and commercial property managers, providing guaranteed income streams that smooth out seasonal demand fluctuations.',
  strategy_text = 'A property maintenance website must communicate breadth of capability and speed of response simultaneously. Service listings should cover the full spectrum — plumbing, electrical, locks, glazing, decorating, guttering, damp treatment — while emphasising single-contact convenience. Dedicated sections for landlords, letting agents, and commercial clients address each audience''s specific needs. An online maintenance request portal with categorised fault reporting, photo upload, and priority tagging demonstrates the operational sophistication that property managers expect. SLA commitments (emergency response within 2 hours, routine within 48 hours) and displaying relevant trade certifications across all disciplines build multi-trade credibility.',
  opportunity_seo = 'Property maintenance searches skew heavily toward the professional client segment: "property maintenance company Kent," "landlord maintenance service," and "commercial building maintenance" signal ongoing contract potential rather than one-off jobs. Compliance-driven content targeting "landlord legal requirements 2026," "EICR requirements for landlords," and "rental property safety regulations" captures landlords and agents actively seeking compliant maintenance solutions. Service area pages optimised for each Kent district capture local searches that national facilities management companies typically neglect.',
  opportunity_automation = 'Property maintenance companies managing multiple properties benefit enormously from automated workflows. A tenant maintenance request portal that categorises faults (plumbing, electrical, structural, cosmetic), assesses urgency, and automatically dispatches the appropriate tradesperson transforms a chaotic phone-and-email process into a structured system. Automated compliance tracking — alerting property managers 60 days before gas safety certificates, EICRs, and EPC certificates expire — generates recurring work and prevents regulatory breaches. Job completion reports with time-stamped photos, sent automatically to property managers, create audit trails and build trust.',
  industry_stats = '{"stat1": "Landlords managing 3+ properties are 4x more likely to use a maintenance company than manage repairs directly", "stat2": "Average property maintenance contract value: £1,800–£3,600 per property per year for portfolio clients", "stat3": "Compliance-driven maintenance (gas, electrical, fire safety) accounts for 40% of property maintenance revenue"}'::jsonb
WHERE slug = 'property-maintenance';

-- ── REMOVAL COMPANIES ───────────────────────────────────────
UPDATE industries SET
  overview_text = 'Removal companies in Kent operate in a market uniquely shaped by the county''s geography — proximity to London drives high volumes of relocations along the M20 and M2 corridors, while Dover and Folkestone position Kent firms for European removals via Channel crossings. The sector is intensely seasonal, with demand peaking sharply between June and September when families relocate around school terms and completions cluster. Price comparison is aggressive: homeowners typically request three or more quotes, and the cost of an average three-bedroom house move (£800–£1,500 locally, £2,000+ for long-distance) makes price transparency a key conversion factor. BAR (British Association of Removers) membership and goods-in-transit insurance are important trust differentiators in a sector where horror stories of damaged belongings and no-show operators circulate widely online.',
  strategy_text = 'A removal company''s website must make quoting instant and effortless. An online survey form capturing current property size, destination, move date, access issues (stairs, parking restrictions), and special items (pianos, antiques) generates qualified leads with enough detail for accurate pricing. Video survey booking — increasingly expected by consumers — signals professionalism and accuracy. Displaying BAR membership, goods-in-transit insurance values, and public liability coverage addresses anxiety about belonging safety. Dedicated pages for house removals, office relocations, storage solutions, and European moves capture distinct search intents. Packing service upsells and storage facility details increase average order value.',
  opportunity_seo = 'Removal searches are overwhelmingly triggered by confirmed property transactions, creating high-intent traffic: "removal company near me" and "house removals Kent" convert strongly because the move date is already set. Long-distance route-specific terms — "removals Kent to Scotland," "international removals Dover" — capture higher-value jobs with less local competition. Content targeting "moving house checklist," "how to pack fragile items," and "change of address guide" draws prospects at the planning stage and establishes authority. Google''s local pack dominance means review volume and rating are critical ranking factors.',
  opportunity_automation = 'The removal quotation process involves significant information gathering that automation streamlines dramatically. An online room-by-room inventory builder that calculates estimated volume and generates indicative pricing pre-qualifies leads and reduces survey no-shows. Automated pre-move communication sequences — sending packing tips two weeks out, confirming details three days before, and sharing arrival time on moving day — reduce the anxiety-driven phone calls that consume office hours. Post-move review requests timed for two days after delivery (when relief is highest) maximise positive Google review capture.',
  industry_stats = '{"stat1": "Average three-bedroom house removal costs £1,200 locally and £2,400+ for long-distance in the South East", "stat2": "89% of people moving house request at least three removal quotes before booking", "stat3": "BAR-member removal companies report 55% higher average order values than non-members"}'::jsonb
WHERE slug = 'removal-companies';

-- ── ROOFERS ─────────────────────────────────────────────────
UPDATE industries SET
  overview_text = 'Roofing in Kent faces weather-driven demand cycles and a housing stock that ranges from medieval timber-framed buildings with peg tile roofs to modern housing estates with concrete interlocking tiles. Storm damage creates surge demand that overwhelms local capacity — every significant weather event triggers a flood of emergency searches that test the response capability of Kent''s roofing firms. Beyond storm work, the planned roofing market covers full re-roofs, flat roof conversions (felt to GRP fibreglass), lead work on churches and heritage buildings, and the growing solar panel integration market. The sector has a particularly acute trust problem: insurance-led storm damage work attracts rogue operators, and homeowners frequently cannot inspect roof work themselves, making verifiable credentials and photographic evidence especially important.',
  strategy_text = 'A roofer''s website must communicate both emergency responsiveness and long-term reliability. Storm damage and emergency leak repair content needs a prominent, permanently visible call-to-action with phone number. For planned work, project galleries organised by roof type (pitched tile, flat, slate, lead, GRP) with identified materials and stated guarantees demonstrate capability. Drone photography of completed work provides proof that homeowners cannot verify from ground level. Displaying Competent Roofer, NFRC, or TrustMark registration alongside insurance-backed guarantee information combats the industry''s trust deficit. Roof survey booking forms with aerial imagery upload (Google Earth screenshots) help assess jobs before site visits.',
  opportunity_seo = 'Roofing searches spike dramatically around storm events, creating unpredictable but extremely high-converting traffic. "Emergency roofer near me" and "roof leak repair" are crisis-driven searches where ranking position directly determines call volume. Planned roofing terms — "roof replacement cost Kent," "flat roof conversion," "GRP fibreglass roof" — carry high project values (£5,000–£15,000+). Content targeting specific roof problems ("sagging roof," "missing ridge tiles," "valley gutter leaking") captures diagnostic searches from homeowners trying to understand their issue before calling. Image optimisation for roof types and materials drives visual search discovery.',
  opportunity_automation = 'Storm events create volume spikes that overwhelm manual processes. An automated emergency triage form capturing damage type, photos, insurance claim status, and address enables rapid prioritisation — genuine emergencies (water entering property) versus non-urgent repairs (missing tiles, cosmetic damage). Automated insurance claim support workflows, generating photo documentation reports formatted for insurer submission, add significant value. For planned work, annual roof inspection reminder sequences sent to previous customers generate recurring survey bookings and identify maintenance needs before they become emergencies.',
  industry_stats = '{"stat1": "Emergency roofing searches increase up to 800% during major storm events in the South East", "stat2": "Average full roof replacement costs £7,500–£15,000 depending on property size and material choice", "stat3": "72% of homeowners cannot visually inspect their own roof, making photographic evidence the primary trust signal"}'::jsonb
WHERE slug = 'roofers';

-- ── SOLICITORS ──────────────────────────────────────────────
UPDATE industries SET
  overview_text = 'The legal services market in Kent is shaped by distinct geographic specialisms: conveyancing demand driven by active property markets in Maidstone, Ashford, and the Medway Towns; family law concentrated around the county''s Crown and Family Courts; and commercial law serving the business clusters along the M20 corridor and in Canterbury. The Solicitors Regulation Authority (SRA) mandates price transparency for certain services since 2018, yet many Kent firms still present opaque "contact us for a quote" approaches that frustrate comparison shoppers. The sector faces growing competition from licensed conveyancers, direct-access barristers, and legal technology platforms like Farewill and Settled, all targeting the most commoditised practice areas. Firms that differentiate through specialist expertise, transparent pricing, and genuine client accessibility will capture the growing proportion of legal services research that begins online.',
  strategy_text = 'A solicitor''s website must balance accessibility with authority. SRA-mandated price transparency pages for conveyancing, probate, and employment tribunal work should feature calculators rather than static fee tables. Practice area pages need depth — a conveyancing page should address leasehold vs freehold differences, search timelines, and Help to Buy complications. Solicitor profile pages with genuine biographies, specialisms, and direct contact details humanise the firm. Displaying SRA registration, Lexcel accreditation, and Law Society panels (conveyancing quality scheme, family law panel) builds institutional trust. Client testimonials are particularly powerful in legal services where anxiety about outcomes runs high.',
  opportunity_seo = 'Legal searches are highly specific and intent-rich: "divorce solicitor Canterbury" or "conveyancing solicitor Maidstone" signal active need with willingness to instruct. Practice area content targeting procedural queries — "how long does probate take," "what happens at a family court hearing," "commercial lease break clause" — captures prospects researching their specific situation. Local competition analysis reveals significant gaps: many Kent firms rank poorly for their own practice area terms due to thin, duplicated content across service pages. Google''s E-E-A-T signals (Experience, Expertise, Authoritativeness, Trustworthiness) are weighted heavily in legal search results.',
  opportunity_automation = 'Legal client onboarding involves extensive document gathering and compliance checks (AML verification, conflict checks, ID verification) that automation transforms. An automated intake form capturing matter type, key dates, opposing parties, and document uploads triggers conflict searches and AML checks before the first consultation. Conveyancing milestone updates — search results received, mortgage offer confirmed, exchange date set — sent automatically to clients reduce the "any news?" phone calls that consume fee-earner time. Automated review requests timed to matter completion capture testimonials when client satisfaction peaks.',
  industry_stats = '{"stat1": "SRA price transparency rules require published pricing for conveyancing, probate, and employment tribunal work", "stat2": "67% of people seeking legal advice now begin their search online rather than through personal recommendations", "stat3": "Average conveyancing matter value in Kent: £1,200–£2,500 in fees, with 8–12 week completion timelines"}'::jsonb
WHERE slug = 'solicitors';
