-- ============================================================
-- seed-industry-content-solicitors.sql
-- Industry content for Solicitors across all 11 services
-- Safe to re-run: uses ON CONFLICT ... DO UPDATE
-- ============================================================

-- 1. Solicitors × Web Design
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'solicitors',
  'web-design',
  'When someone needs a solicitor, they are typically dealing with one of the most significant events of their life: buying a home, going through a divorce, writing a will, defending against criminal charges, or pursuing compensation for an injury. They are anxious, often confused about the legal process, and acutely aware that choosing the wrong solicitor could have life-altering consequences. Your website must communicate competence, trustworthiness, and approachability simultaneously, which is a balance most law firm websites fail to achieve. The majority of solicitor websites fall into two traps: either they are stuffed with impenetrable legal jargon that intimidates potential clients, or they are so generic that a conveyancing firm looks identical to a criminal defence practice. A purpose-built solicitor website organises your practice areas into clear, accessible pages that explain what you do in language clients actually understand. It displays your SRA registration and regulatory compliance prominently, provides transparent fee information that the SRA now expects, showcases testimonials from clients in similar situations, and makes it effortless to book an initial consultation. We build law firm websites that satisfy SRA regulatory requirements for digital transparency while converting anxious visitors into booked consultations through clear practice area presentation, fee transparency, and trust signals that address the specific concerns of people navigating legal processes for the first time.',
  'The legal profession faces increasing pressure from the SRA to provide transparent pricing and accessible information online. The 2018 Transparency Rules require many law firms to publish pricing, service descriptions, and regulatory information on their websites. Beyond compliance, the practical reality is that potential clients now research solicitors online before making contact. A firm with a dated, uninformative website loses enquiries to competitors who present their services clearly and transparently, regardless of their actual legal expertise.',
  'We design solicitor websites around practice areas with SRA compliance built in. Each practice area page explains the legal process in accessible language, displays published fee information where required, and includes testimonials relevant to that service. SRA registration numbers, complaints procedures, and professional indemnity information are displayed as required by regulatory guidance.',
  '[{"title": "Practice area pages written in jargon that intimidates potential clients", "description": "Most people seeking a solicitor have never engaged one before. When they land on a practice area page written in dense legal terminology, they cannot understand what you actually do for them, how the process works, or what outcome they can expect. Confused visitors do not enquire; they leave and find a firm that explains things in plain English."}, {"title": "No fee transparency despite SRA regulatory expectations", "description": "The SRA Transparency Rules require many law firms to publish pricing information for specific services including conveyancing, probate, employment tribunals, and motoring offences. Firms that fail to publish this information are not only non-compliant but also lose potential clients who expect to understand costs before making contact. Fee opacity drives visitors to competitors who provide the pricing clarity they demand."}, {"title": "SRA registration and regulatory compliance information missing or hidden", "description": "Solicitors are required to display their SRA registration number, provide a link to the SRA register, include a complaints procedure, and publish details of their professional indemnity insurance. Many law firm websites either omit these details or bury them in footer text. Non-compliance risks regulatory action and misses the trust-building opportunity that visible regulation provides."}]',
  '[{"title": "Practice area pages with accessible language and clear process explanation", "description": "Every practice area has a dedicated page explaining the legal service in language clients understand. Conveyancing pages walk through the buying or selling process step by step. Divorce pages explain the timeline and what to expect. Each page addresses the emotional context of the client''s situation and provides the clarity that converts anxious visitors into consultation bookings."}, {"title": "SRA-compliant fee transparency and pricing display", "description": "Published fee information for services covered by the SRA Transparency Rules, presented in clear, accessible formats. Fixed fee services display total costs including disbursements and VAT. Hourly rate services provide realistic cost ranges and factors that affect pricing. This transparency satisfies regulatory requirements while building client trust through pricing honesty."}, {"title": "Regulatory compliance display and trust signal integration", "description": "SRA registration numbers with direct links to the SRA register are displayed prominently. Complaints procedures, professional indemnity details, and regulatory body logos are presented clearly without being hidden in footer text. Client testimonials, accreditation badges, and team qualification displays provide additional trust signals that reassure potential clients."}]',
  '[{"question": "How do you handle SRA Transparency Rules on a solicitor website?", "answer": "We build fee information displays that meet SRA requirements for the regulated services where pricing publication is mandatory. For conveyancing, probate, employment tribunal, motoring offences, immigration, and debt recovery, we create clear pricing sections with total costs, disbursement breakdowns, and realistic timescales. These displays are reviewed against current SRA guidance."}, {"question": "How do you make legal services accessible to people who have never used a solicitor?", "answer": "Every practice area page is written in plain English, explaining the legal process from the client''s perspective. We describe what happens at each stage, how long it takes, what the client needs to do, and what outcome they can expect. Legal terminology is explained in context. The goal is that someone with no legal knowledge understands exactly what you offer."}, {"question": "Can the website handle multiple practice areas without looking cluttered?", "answer": "Yes. We use clear navigation architecture that groups practice areas logically: property, family, wills and probate, personal injury, criminal defence, commercial, and employment. Each area has its own landing page with individual service pages beneath. Visitors find the specific legal service they need without navigating through irrelevant practice areas."}, {"question": "How important are client testimonials for a solicitor website?", "answer": "Extremely. People choosing a solicitor for a stressful legal matter want to know that others in their situation had a positive experience. Testimonials specific to each practice area provide this reassurance. A divorce client reading a testimonial from another divorce client builds confidence in a way that generic reviews cannot match."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 2. Solicitors × SEO
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'solicitors',
  'seo',
  'Legal searches represent some of the most valuable local search traffic available. When someone searches for divorce solicitor near me, conveyancing solicitor Kent, or criminal defence lawyer Maidstone, they are actively seeking legal representation and will instruct a solicitor within days or weeks. The lifetime value of a single legal client can be substantial: a conveyancing instruction leads to wills, then probate, then perhaps family law referrals. Yet the legal SEO landscape is fiercely competitive, with national comparison directories, legal aid finders, and large multi-office firms dominating many search results. Local and regional law firms can compete by exploiting geographic specificity, practice area depth, and the local knowledge that national directories cannot replicate. Our SEO campaigns for solicitors target every practice area, every geographic modifier, and every client question that generates search volume in your area. We build authority through legal guides that demonstrate expertise, practice area pages optimised for specific service searches, and local content that establishes your firm as the definitive legal resource in your region. The compound effect of ranking across multiple practice areas creates a dominating local presence that national directories cannot match for firms committed to long-term SEO investment.',
  'The first page of Google results for solicitor searches is dominated by directories, comparison sites, and the largest law firms with dedicated marketing teams. Local firms without an SEO strategy are invisible to the majority of potential clients who search online before choosing a solicitor. Given that a single new client instruction can be worth hundreds or thousands of pounds in fees, and that clients often return for multiple legal matters over their lifetime, the revenue impact of poor search visibility is substantial.',
  'We build legal SEO campaigns around practice areas and geographic modifiers. Every service your firm offers gets dedicated, optimised content targeting the specific searches potential clients use. Legal guide content builds topical authority that improves rankings across all practice areas. Local pages target town and area-specific searches where your physical presence gives you a ranking advantage.',
  '[{"title": "Invisible for practice-area-specific searches in your local area", "description": "When a potential client searches for family solicitor Maidstone or conveyancing lawyer Canterbury, the firms appearing on page one capture the enquiry. Most local law firms have a single generic services page that fails to rank for any specific practice area plus location search. Each practice area you offer represents a distinct keyword cluster that requires dedicated content to rank."}, {"title": "Legal directories and comparison sites outranking your firm''s website", "description": "The Law Society, Solicitors.info, and legal comparison platforms invest heavily in SEO and dominate many general legal search terms. As a local firm, you cannot outspend these platforms nationally, but you can outrank them for specific local practice area searches where your dedicated, locally-focused content provides more relevant, detailed information."}, {"title": "No legal guide content building authority and capturing research-phase searches", "description": "Potential clients research legal processes extensively before choosing a solicitor. Searches like how long does conveyancing take, what happens during divorce proceedings, and how to contest a will represent people in the early stages of their legal journey. Without guide content targeting these research searches, you miss the opportunity to establish your firm as the trusted expert before the client starts comparing solicitors."}]',
  '[{"title": "Practice area landing pages optimised for local legal searches", "description": "Dedicated, optimised pages for every practice area your firm covers, each targeting location-specific search terms. Conveyancing, family law, wills and probate, personal injury, criminal defence, commercial law, and employment each receive comprehensive pages targeting their distinct search queries. This creates multiple ranking opportunities across your full service range."}, {"title": "Legal guide content building topical authority across practice areas", "description": "In-depth legal guides covering the processes, timescales, costs, and frequently asked questions for each practice area. Conveyancing process guides, divorce timeline explanations, and probate procedure walkthroughs attract research-phase traffic and build the topical authority that improves rankings across all your pages. Each guide positions your firm as knowledgeable local experts."}, {"title": "Google Business Profile optimisation for local Map Pack visibility", "description": "Your Google Business Profile optimised with accurate practice area categories, service area coverage, professional photography, and a review generation strategy. Legal searches heavily feature the Map Pack, and firms appearing in these three positions capture significant call volume. Regular Google Business posts maintain profile activity and signal relevance to the algorithm."}]',
  '[{"question": "How competitive is SEO for solicitors in Kent?", "answer": "General terms like solicitors near me are highly competitive, but practice-area-specific searches with location modifiers are achievable. A dedicated page targeting conveyancing solicitor Tunbridge Wells faces far less competition than a generic solicitor page. We build rankings across dozens of specific practice area and location combinations, creating cumulative visibility that generic approaches cannot match."}, {"question": "Should we create content explaining legal processes to potential clients?", "answer": "Absolutely. Legal guide content serves three purposes: it attracts research-phase traffic from people who will need a solicitor within weeks, it builds topical authority that improves rankings across all your pages, and it demonstrates the expertise that potential clients are looking for in their solicitor. A comprehensive conveyancing guide can rank for years and continuously attract your ideal clients."}, {"question": "How long before SEO generates new client instructions?", "answer": "Google Business Profile improvements can increase local visibility within four to six weeks. Practice area landing pages typically begin ranking within two to four months. Legal guide content builds compounding authority over six to twelve months. Most law firms see meaningful enquiry increases within three to four months, with sustained growth over the first year."}, {"question": "Can SEO help us compete with national legal directories for local searches?", "answer": "Yes. National directories produce generic content that cannot match the local detail, practice area depth, and client-specific information of a dedicated local firm''s website. By building comprehensive content for every practice area with local specificity, you establish relevance and authority that generic directory listings cannot replicate for your specific service area."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 3. Solicitors × Lead Capture
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'solicitors',
  'lead-capture',
  'People contacting a solicitor are often in emotionally charged situations. A homeowner whose property chain is at risk of collapsing needs urgent conveyancing support. Someone served with divorce papers needs immediate family law guidance. A business owner facing an employment tribunal needs to understand their position quickly. These potential clients are anxious, time-sensitive, and evaluating whether your firm can help them based on how easily and quickly they can make initial contact. Most solicitor websites offer a phone number and a generic contact form that asks for a name, email, and message. This approach fails because it provides no structure for the visitor to explain their situation, no immediate response confirming their enquiry has been received, and no indication of what happens next. Lead capture for solicitors must provide practice-area-specific enquiry pathways that capture the relevant details for each legal matter, deliver immediate automated responses that acknowledge the enquiry and set expectations for response time, and route each enquiry to the appropriate fee earner based on practice area. A conveyancing enquiry should capture property details, transaction type, and timeline. A family law enquiry should capture the nature of the matter and urgency level. Each pathway provides the right experience for each client type.',
  'Law firms lose potential clients at the first contact stage more than any other point in the client journey. An enquiry that receives no response for twenty-four hours is often an enquiry lost to a competitor. A generic response that fails to acknowledge the client''s specific legal matter feels impersonal and undermines trust. The first interaction with your firm shapes the entire client relationship, and a slow or impersonal response starts that relationship poorly.',
  'We build practice-area-specific lead capture that guides potential clients through an appropriate initial enquiry process. Conveyancing forms capture property and transaction details. Family law forms assess matter type and urgency. Commercial enquiries identify business size and legal need. Automated responses are tailored to each practice area with relevant next-step information.',
  '[{"title": "Generic contact forms providing no structure for legal enquiries", "description": "A form asking for name, email, and message gives an anxious potential client no framework for explaining their situation. They either write an essay that your team must decode, or they write three words that tell you nothing. Neither outcome leads to an efficient first interaction. Without practice-area-specific forms, every enquiry requires a manual qualification conversation."}, {"title": "No automated acknowledgement leaving potential clients anxious about whether you received their message", "description": "Someone who has just been served with divorce papers or received a threatening letter sends an enquiry to your firm and hears nothing. For hours, they do not know if you received their message, if you handle their type of matter, or when someone will contact them. This silence creates anxiety that drives them to contact additional firms, reducing your conversion rate."}, {"title": "Enquiries not routed to the appropriate fee earner based on practice area", "description": "When all enquiries land in a shared inbox, a conveyancing matter sits alongside a criminal defence enquiry and a commercial dispute. The receptionist or office manager must read each one, determine the appropriate practice area, and forward it to the right solicitor. This manual triage adds delay and risks enquiries being misrouted or overlooked during busy periods."}]',
  '[{"title": "Practice-area-specific enquiry forms capturing relevant case details", "description": "Separate enquiry pathways for each practice area capture the information relevant to that legal matter. Conveyancing forms collect property address, transaction type, chain status, and mortgage position. Family law forms identify the matter type, urgency, and whether children are involved. Each form provides the relevant fee earner with enough information to prepare a meaningful initial response."}, {"title": "Immediate automated responses tailored to each practice area", "description": "Every enquiry receives an instant acknowledgement specific to their practice area. A conveyancing enquiry receives information about your conveyancing process and typical timescales. A family law enquiry receives guidance about initial consultation arrangements and what to bring. This practice-specific response demonstrates competence and care before any human interaction occurs."}, {"title": "Intelligent routing to fee earners with urgency-based prioritisation", "description": "Enquiries are automatically routed to the appropriate department or fee earner based on practice area. Urgency indicators within the form trigger priority flagging. Criminal matters, urgent family applications, and time-sensitive commercial disputes are escalated immediately. This ensures every enquiry reaches the right person quickly without manual triage."}]',
  '[{"question": "Can the forms be specific enough for different legal matters?", "answer": "Yes. Each practice area has its own form pathway with questions tailored to that legal service. Conveyancing forms capture different information from family law forms, which capture different details from commercial dispute forms. This specificity ensures you receive the relevant details for each matter type without requiring a preliminary phone call."}, {"question": "How do the automated responses work for different practice areas?", "answer": "Each practice area has a tailored automated response that acknowledges the enquiry and provides relevant initial information. A conveyancing response outlines your process and typical timescales. A family law response explains initial consultation arrangements. A commercial response confirms your team will review their matter. Each response feels personal and practice-specific rather than generic."}, {"question": "Can the system book initial consultation appointments directly?", "answer": "Yes. For practice areas where you offer initial consultations, the form can include appointment booking functionality integrated with your fee earners'' diaries. Potential clients select available consultation slots, receive confirmation, and arrive prepared with the information gathered during the form process. This accelerates the client onboarding journey."}, {"question": "How does urgency-based routing work?", "answer": "Form questions include urgency indicators relevant to each practice area. Criminal matters with court dates, family matters involving immediate safeguarding concerns, and commercial disputes with filing deadlines are flagged as urgent. These enquiries bypass standard routing and are delivered directly to the relevant fee earner with priority notification."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 4. Solicitors × Business Automation
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'solicitors',
  'business-automation',
  'Law firms operate under regulatory requirements that create administrative demands unlike any other professional service. SRA compliance obligations include client account management, complaints handling procedures, continuing competence requirements, and transparency reporting. Anti-money-laundering regulations demand identity verification, source of funds checks, and risk assessments for every new client matter. GDPR imposes data protection obligations across every client file. And between managing compliance, fee earners are drowning in client onboarding paperwork, file opening procedures, correspondence management, and billing administration that erodes the time available for fee-earning work. Business automation for solicitors systematises the repeatable processes that consume your administrative capacity. New client onboarding workflows guide clients through identity verification, engagement letter signing, and initial information gathering without manual chasing. Matter milestones trigger automated client updates at key stages. AML check processes are standardised and documented. Time recording reminders ensure fee earners capture every billable unit. File review dates and limitation periods are tracked automatically. The compliance burden that currently requires dedicated administrative staff is handled systematically, reducing risk while freeing fee earners to focus on the legal work that generates revenue.',
  'Solicitors typically spend twenty to thirty percent of their working week on administration rather than billable work. For a fee earner charging two hundred pounds per hour, that represents thousands of pounds in unbilled time every month. Beyond the financial cost, manual compliance processes create risk: a missed AML check, a forgotten limitation date, or an overdue file review can trigger SRA intervention. Automation reduces both the financial cost and the compliance risk simultaneously.',
  'We automate around the specific regulatory and operational requirements of legal practice. Client onboarding workflows incorporate AML identity verification, engagement letter distribution, and initial document collection. Matter stage milestones trigger client update communications. SRA compliance tracking ensures transparency obligations, complaints procedures, and competence requirements are met systematically.',
  '[{"title": "Client onboarding consuming hours of manual administration per new matter", "description": "Opening a new client matter involves identity verification, source of funds documentation, conflict checks, engagement letter preparation and signing, initial information gathering, and file creation. Each step requires manual chasing, and a single new matter can take your support staff several hours of administrative work before the fee earner has even begun the legal work."}, {"title": "AML compliance processes inconsistent and poorly documented across fee earners", "description": "Anti-money-laundering regulations require documented identity verification, source of funds evidence, and risk assessments for every client. When each fee earner handles AML checks differently, with varying levels of documentation and different thresholds for enhanced due diligence, the firm''s compliance position is inconsistent and vulnerable to regulatory scrutiny."}, {"title": "Client updates falling behind because fee earners are focused on legal work", "description": "Clients expect regular updates about their matter, and the SRA expects firms to communicate effectively with clients. But when fee earners are absorbed in casework, client update calls and emails drop to the bottom of the priority list. Clients who feel uninformed become unhappy clients, and unhappy clients generate complaints that consume more time than proactive updates would have required."}]',
  '[{"title": "Automated client onboarding with integrated AML verification", "description": "New client workflows guide clients through identity verification via digital document submission, engagement letter e-signing, initial questionnaire completion, and key document upload. AML checks follow a standardised process with documented evidence collection and risk assessment scoring. The entire onboarding process runs with minimal manual intervention while maintaining full compliance documentation."}, {"title": "Matter milestone communications keeping clients informed automatically", "description": "Key stages in each matter type trigger automated client updates. Conveyancing clients receive updates when searches are ordered, when results return, and when exchange approaches. Family law clients receive stage updates as proceedings progress. These communications keep clients informed without fee earners manually writing routine update emails at every milestone."}, {"title": "SRA compliance tracking and regulatory obligation management", "description": "Automated tracking of SRA transparency requirements, complaints handling timelines, file review schedules, and continuing competence obligations. The system monitors compliance deadlines across the firm, alerts responsible individuals when action is required, and maintains an audit trail demonstrating systematic regulatory compliance. This reduces the risk of compliance oversights that trigger SRA intervention."}]',
  '[{"question": "Can automation handle the client identification and AML process?", "answer": "Yes. The system guides clients through digital identity document submission, captures source of funds declarations, and applies standardised risk assessment criteria. Enhanced due diligence triggers are built into the workflow based on matter type and risk indicators. Every step is documented and stored against the client file, providing a clear compliance audit trail."}, {"question": "How do automated client updates work for different practice areas?", "answer": "Each practice area has defined milestones that trigger client communications. Conveyancing milestones include search orders, search results, draft contracts, exchange, and completion. Family law milestones track petition filing, acknowledgement, and decree stages. The communications are tailored to each stage and practice area, providing relevant information without generic messaging."}, {"question": "Can the system track SRA compliance obligations across the whole firm?", "answer": "Yes. The system monitors transparency rule compliance, complaints handling timelines, annual renewal requirements, and continuing competence obligations for individual solicitors. Dashboard views show firm-wide compliance status. Alerts are triggered when deadlines approach or actions are overdue, providing the practice manager with oversight without manual diary tracking."}, {"question": "Will automation integrate with our existing case management system?", "answer": "We integrate with popular legal case management platforms including Clio, Leap, PracticePanther, and others. Where integration APIs are available, automation workflows connect to your existing system so client data, matter stages, and document management flow between the automation layer and your case management system without double entry."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 5. Solicitors × Branding
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'solicitors',
  'branding',
  'The legal profession exists in a branding paradox: solicitors must project authority and expertise while simultaneously being approachable to people who may be intimidated by the legal process. A brand that is too corporate and formal feels inaccessible to the divorcing parent, the first-time homebuyer, or the injured worker who needs legal help but is nervous about engaging a solicitor. A brand that is too casual undermines the gravitas expected of professionals handling matters with life-changing consequences. Most law firm branding defaults to conservative navy blue, serif fonts, and stock imagery of scales of justice and courtroom gavels. This generic legal aesthetic makes one firm visually indistinguishable from another, which means clients choose based on proximity or price rather than trust and affinity. Your brand should reflect the specific character of your firm: whether you are a high-street practice serving the local community or a specialist firm focused on particular practice areas. It should communicate competence without intimidation, tradition without stuffiness, and professionalism without coldness. We create brand identities for solicitors that establish the right tone for your firm, work across physical offices, digital platforms, and client-facing documentation, and differentiate your practice in a sector where visual conformity is the norm.',
  'Potential clients judge law firms on perceived competence and approachability before they ever speak to a solicitor. Your brand shapes that perception across every touchpoint: your website, your office frontage, your business cards, your correspondence, and your social media presence. In a profession where firms offer similar services at similar rates, brand perception is often the deciding factor. A distinctive, appropriate brand identity attracts clients who feel that your firm understands their situation.',
  'We design law firm brands that balance authority with approachability. Typography communicates professionalism without feeling corporate. Colour palettes differentiate your firm from the generic legal navy. Office signage, stationery, and digital assets create a cohesive identity. Client-facing document templates maintain brand standards across every interaction.',
  '[{"title": "Brand identity indistinguishable from every other local law firm", "description": "Navy blue colour scheme, serif typeface, and a generic scales-of-justice icon. This describes the majority of law firm branding in any town. When every firm looks identical, potential clients have no visual basis for differentiation. Your choice of solicitor feels arbitrary because no firm has established a distinctive identity that communicates their specific character and values."}, {"title": "Office presentation not matching the quality of legal service delivered", "description": "A law firm with excellent solicitors but dated signage, worn reception furniture, and inconsistent interior branding creates a disconnect between service quality and perceived quality. Clients visiting your office for the first time form impressions that shape their entire relationship with your firm. An office that looks outdated suggests a practice that has not kept pace."}, {"title": "Client-facing documents lacking professional brand consistency", "description": "Engagement letters, advice letters, cost estimates, and invoices that use different formatting, inconsistent logos, and varying styles undermine the professional image your brand should reinforce at every interaction. When a client receives five documents from your firm and each looks slightly different, it suggests an organisational inconsistency that erodes confidence."}]',
  '[{"title": "Distinctive brand identity balancing legal authority with approachability", "description": "A brand identity designed specifically for your firm''s character and target client base. Colour palettes that differentiate you from generic legal branding while maintaining professional gravitas. Typography that communicates competence without feeling intimidating. Visual elements that reflect your firm''s personality whether that is traditional and established or modern and progressive."}, {"title": "Office signage and interior branding creating a consistent client experience", "description": "External signage reflecting your brand identity and visible to local foot traffic. Reception area branding with consistent colours, materials, and presentation. Meeting room branding that provides a professional backdrop for client consultations. The physical environment reinforces the same brand qualities communicated by your website and documentation."}, {"title": "Client-facing document templates maintaining brand standards", "description": "Branded templates for every document type: engagement letters, advice letters, cost estimates, invoices, completion statements, and client care letters. Each template maintains your brand standards while meeting SRA requirements for content and presentation. Document consistency reinforces the professional, organised image that builds client confidence throughout their matter."}]',
  '[{"question": "How do you make a solicitor brand approachable without losing professionalism?", "answer": "The balance comes from design choices: warmer colour accents alongside authoritative base tones, modern typefaces that are clean and readable rather than stiff and traditional, and imagery that features real people and situations rather than legal cliches. The brand should feel like a confident, knowledgeable professional who also happens to be a genuinely helpful human being."}, {"question": "Should our branding look different depending on our practice areas?", "answer": "Your core brand identity should be consistent, but the expression can adapt across practice areas. A family law section might use warmer, more empathetic imagery while a commercial department uses more structured, corporate presentation. The colour palette, typography, and core identity remain consistent while the tone adapts to each audience''s expectations."}, {"question": "How important is office branding for a solicitor practice?", "answer": "Very. Clients visit your office during significant life events and form lasting impressions. A professionally branded reception, meeting room, and office environment reinforces the competence and attention to detail they expect from their solicitor. The physical experience should match the quality of your digital presence and the service your fee earners deliver."}, {"question": "Can you design branded templates that meet SRA documentation requirements?", "answer": "Yes. All document templates incorporate required SRA information including firm authorisation details, complaints procedures, and regulatory information while maintaining your brand standards. The templates ensure every letter, email, and document that leaves your firm is both compliant and professionally branded."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 6. Solicitors × Social Media Setup
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'solicitors',
  'social-media-setup',
  'Social media for solicitors operates under constraints that most industries do not face. SRA regulations, client confidentiality obligations, and professional conduct rules mean you cannot simply post about cases, share client outcomes, or make claims about your legal expertise without careful consideration. Yet social media provides one of the most effective ways to humanise a profession that many people find intimidating, demonstrate expertise on legal topics that affect your community, and maintain visibility with the local audience who will eventually need legal services. When someone is thinking about making a will, they do not search for a solicitor immediately. But if they have been following a local solicitor''s social media posts about inheritance tax changes, will validity requirements, and power of attorney benefits over recent months, that solicitor is the first person they think of when they decide to act. Social media for solicitors is about sustained, compliant visibility that builds familiarity and trust over time, so that when a legal need arises, your firm is already established in the potential client''s mind as the knowledgeable, approachable local practice they want to call.',
  'The legal profession is increasingly competitive at the local level, with firms fighting for visibility in the same communities. Social media provides a channel to demonstrate expertise, build community familiarity, and maintain top-of-mind awareness that static advertising cannot achieve. A firm that regularly shares helpful legal information builds a reputation for knowledge and approachability that generates referrals and direct enquiries from an audience that already trusts them.',
  'We create social media frameworks that demonstrate legal expertise within SRA compliance boundaries. Content focuses on legal education, legislative changes, and practical guidance rather than case specifics. Templates ensure every post is reviewed against professional conduct considerations. LinkedIn content targets professional referral networks alongside client-facing Facebook content.',
  '[{"title": "No social presence despite clients checking online before choosing a solicitor", "description": "Potential clients researching solicitors check social media profiles as part of their evaluation. An empty or abandoned LinkedIn page and no Facebook presence suggest a firm that is either too small to maintain a professional image or too outdated to engage with modern communication channels. This absence undermines the credibility that your qualifications and experience have earned."}, {"title": "Uncertainty about what solicitors can and cannot post on social media", "description": "Fear of SRA compliance issues prevents many law firms from engaging with social media at all. The concern about inadvertently breaching client confidentiality, making misleading claims, or posting content that could constitute unsolicited approaches paralyses firms into inaction. This caution, while understandable, surrenders the entire channel to competitors who have navigated these boundaries successfully."}, {"title": "No LinkedIn presence for professional referral network building", "description": "Solicitors receive a significant proportion of their work through professional referrals: estate agents referring conveyancing, IFAs referring wills and probate, accountants referring commercial matters. LinkedIn is where these professional relationships are maintained and developed. Without an active LinkedIn presence, you are invisible to the professional referral network that feeds your practice."}]',
  '[{"title": "SRA-compliant content framework for legal social media", "description": "Pre-approved content templates covering legal education, legislative changes, team updates, community engagement, and practice area explainers. Every template is designed within SRA professional conduct boundaries, avoiding case-specific content, misleading claims, and unsolicited approaches. The framework gives your team confidence to post regularly without compliance anxiety."}, {"title": "LinkedIn professional referral network strategy", "description": "LinkedIn profiles for the firm and individual fee earners set up to connect with professional referral sources: estate agents, financial advisers, accountants, and other professionals who refer legal work. Content targeting these professional audiences demonstrates practice area expertise and maintains the relationships that generate referral instructions."}, {"title": "Facebook community engagement with legal education content", "description": "A Facebook page positioned as a local legal information resource. Regular posts about legal topics affecting your community: property buying tips, employment rights updates, family law process explanations, and seasonal legal reminders. This educational approach builds familiarity and trust with the local audience who will eventually need legal services."}]',
  '[{"question": "What can solicitors post on social media without breaching SRA rules?", "answer": "Solicitors can share general legal education, legislative updates, team and firm news, community involvement, and practice area explanations. The key restrictions are around client confidentiality, misleading claims about expertise or outcomes, and content that could be perceived as unsolicited approaches to individuals in vulnerable situations. Our content frameworks are designed within these boundaries."}, {"question": "Is LinkedIn important for a local solicitor practice?", "answer": "Yes. LinkedIn is where professional referral relationships are maintained. Estate agents, financial advisers, accountants, and other solicitors who refer work connect and engage on LinkedIn. An active presence with practice area content keeps your firm visible to these referral sources. Many firms receive a significant proportion of their instructions through professional networks that LinkedIn strengthens."}, {"question": "How much time will social media require from our fee earners?", "answer": "Minimal. We create content frameworks and templates that your marketing assistant or office manager can execute with minimal input from fee earners. Where solicitor expertise is needed for a specific legal topic, a five-minute conversation provides enough material for several posts. The system is designed to maintain consistent presence without consuming billable hours."}, {"question": "Can we use client testimonials on social media?", "answer": "Client testimonials can be shared on social media with appropriate client consent and within SRA guidance. Testimonials should reflect genuine client experiences without making misleading claims about outcomes. We help you collect and present testimonials that are both compliant and compelling, providing social proof that builds confidence in your firm."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 7. Solicitors × Digital Marketing
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'solicitors',
  'digital-marketing',
  'Digital marketing for solicitors must navigate the tension between the need to grow the practice and the professional conduct obligations that restrict how legal services can be promoted. SRA rules prohibit misleading advertising, restrict unsolicited approaches, and require transparency in all communications. Within these boundaries, however, substantial marketing opportunity exists. Google Ads for solicitors is exceptionally effective because legal searches have the highest commercial intent and the highest click values in almost any local market. Someone searching for conveyancing solicitor or divorce lawyer is actively seeking to instruct a firm and represents immediate revenue potential. Social media advertising targeting local audiences with legal education content builds awareness and trust within your community. Retargeting campaigns keep your firm visible to website visitors through their research and comparison phase. Email marketing nurtures referral relationships with estate agents, IFAs, and other professional sources. Our digital marketing campaigns for solicitors combine paid search capturing high-intent legal queries, social advertising building local brand awareness, retargeting maintaining visibility during decision-making, and professional referral marketing strengthening the relationships that generate instructions. Every campaign element operates within SRA advertising guidelines while maximising your firm''s visibility to potential clients at the moment they need legal help.',
  'Law firms that rely solely on reputation, high street presence, and word of mouth are losing market share to competitors who invest in digital visibility. The younger generations of homebuyers, divorcing couples, and business owners search online first when they need a solicitor. Without digital marketing, your firm is invisible to a growing proportion of the legal market. The firms investing in digital marketing now are building the client pipelines that will define the competitive landscape for the next decade.',
  'We build legal marketing campaigns within SRA advertising guidelines. Google Ads capture high-intent practice area searches with compliant ad copy. Social media advertising builds local awareness through educational content rather than promotional messaging. Professional referral campaigns target estate agents, IFAs, and accountants who generate instructions. All campaigns are reviewed for regulatory compliance.',
  '[{"title": "No paid visibility for high-value practice area searches in your area", "description": "Google Ads for legal searches are expensive per click but deliver exceptional return because the client instruction value is high. A single conveyancing instruction from a Google Ad costing thirty pounds generates hundreds or thousands in fees. Without paid search, you are invisible for these high-intent queries and surrendering immediate-revenue enquiries to competitors whose ads appear above your organic listings."}, {"title": "Professional referral network not being marketed to systematically", "description": "Estate agents, financial advisers, and accountants refer legal work to solicitors they know and trust. Most firms rely on personal relationships for these referrals without any systematic marketing to the broader professional community. A targeted campaign reaching every estate agent and IFA in your area with your practice capabilities generates referral instructions from professionals you have never personally met."}, {"title": "Marketing activity not tracked to client instructions and fee revenue", "description": "Many law firms spend money on directories, sponsorships, and advertising without knowing which sources generate actual client instructions. When you cannot connect marketing spend to fee revenue, you cannot optimise your budget. Money continues flowing to underperforming channels while effective opportunities remain unfunded."}]',
  '[{"title": "Practice-area Google Ads capturing high-intent legal searches", "description": "Targeted campaigns for each practice area your firm covers, with ad copy and landing pages specific to conveyancing, family law, wills and probate, personal injury, and other services. Ads comply with SRA advertising requirements while presenting compelling reasons for potential clients to choose your firm. Budget allocation reflects practice area profitability and growth priorities."}, {"title": "Professional referral marketing targeting estate agents, IFAs, and accountants", "description": "LinkedIn campaigns and targeted communications reaching professional referral sources in your area. Practice area capability content demonstrates your expertise to the professionals who recommend solicitors to their clients. This systematic approach extends your referral network beyond personal contacts to every potential referral source in your region."}, {"title": "Full attribution tracking from marketing spend to client instruction", "description": "Conversion tracking across all channels connecting enquiries to their marketing source. Integration with your practice management system tracks which marketing channels generate actual client instructions and fee revenue. Monthly reporting shows cost per enquiry and cost per instruction for every campaign, enabling data-driven budget allocation."}]',
  '[{"question": "Are Google Ads expensive for solicitors?", "answer": "Legal clicks are among the most expensive in any industry because the client value is high. However, cost per acquisition is what matters. If a conveyancing Google Ad click costs thirty pounds but one in ten clicks becomes a client paying fifteen hundred in fees, the return is substantial. We optimise campaigns to minimise cost per instruction rather than cost per click."}, {"question": "How do you ensure our advertising complies with SRA rules?", "answer": "All ad copy and marketing content is reviewed against SRA advertising requirements. We avoid misleading claims, ensure transparent pricing is included where required, and maintain the professional tone expected of regulated legal services. Landing pages include all required regulatory information. We stay updated on SRA guidance changes that affect legal marketing."}, {"question": "Can you track which marketing generates actual client instructions?", "answer": "Yes. We implement conversion tracking that follows enquiries from their marketing source through to instruction. Where integration with your practice management system is possible, we track through to fee revenue. This closed-loop reporting shows exactly which campaigns generate profitable instructions and which are not delivering return on investment."}, {"question": "Should we market to estate agents and financial advisers?", "answer": "Absolutely. Professional referrals represent some of the highest-quality instructions for conveyancing, wills and probate, and commercial matters. A targeted campaign reaching every estate agent and IFA in your area with your practice capabilities generates referral relationships that provide steady instruction volume. The lifetime value of a strong professional referral relationship is substantial."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 8. Solicitors × Workwear & Print
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'solicitors',
  'workwear-print',
  'The legal profession communicates through documentation more than almost any other industry. Engagement letters, advice letters, court bundles, completion statements, cost estimates, invoices, and client care letters flow constantly from your firm to clients, courts, other solicitors, and professional contacts. Every document that leaves your office carries your brand and shapes the recipient''s perception of your firm''s professionalism and attention to detail. Beyond documentation, your physical presence at networking events, professional development seminars, and community activities creates opportunities for branded materials that maintain your firm''s visibility. For solicitors, workwear extends to professional accessories rather than traditional trade clothing: branded notebooks, pen sets, and document folders for client meetings, conference materials, and professional gifts. Printed materials for law firms serve both practical and marketing functions. Business cards remain essential for professional networking. Branded stationery communicates establishment and professionalism. Client welcome packs create positive first impressions. Practice area brochures provide tangible material for referral partners to share. Every printed touchpoint is an opportunity to reinforce your firm''s brand identity and demonstrate the attention to detail that clients expect from their legal advisers.',
  'Solicitors operate in a profession where attention to detail is the core competency clients are paying for. When a client receives a letter on misaligned, poorly printed stationery, or a completion statement in an unbranded generic document, it subtly undermines confidence in the firm''s attention to detail. Professional printed materials and branded accessories communicate that your firm applies the same standards to its presentation as it does to its legal work.',
  'We supply branded materials designed for the professional standards of legal practice. Stationery including letterheads, compliment slips, and envelopes maintains brand consistency across all correspondence. Client meeting accessories like branded folders and notebooks create professional impressions. Practice area materials support referral partner distribution.',
  '[{"title": "Documentation leaving the firm with inconsistent branding and formatting", "description": "When different fee earners use different letter templates, format invoices differently, and present documents with varying levels of brand adherence, the firm''s professional image is inconsistent. A client receiving five documents from your practice that each look slightly different questions the organisational coherence of the firm handling their legal matter."}, {"title": "No branded materials for client meetings and networking events", "description": "Fee earners attending client meetings with plain notepads and generic pens miss an opportunity to reinforce the firm''s brand. At networking events, the absence of professional business cards or branded materials makes your representatives indistinguishable from any other attendee. These small details contribute to the overall impression of your firm''s professionalism."}, {"title": "No physical materials for referral partners to share with potential clients", "description": "Estate agents, financial advisers, and other referral sources recommend your firm verbally but have nothing tangible to give their clients. A practice area brochure or branded information card gives referral partners something physical to hand over, making it easier for them to recommend you and more likely that the referred client will follow through and make contact."}]',
  '[{"title": "Professional stationery suite with SRA-compliant information", "description": "Branded letterheads, compliment slips, envelopes, and continuation sheets incorporating all required SRA regulatory information. Digital letterhead templates for electronic correspondence maintaining the same brand standards. Every piece of correspondence leaving your firm presents a consistent, professional, and compliant brand image."}, {"title": "Client meeting accessories and professional branded items", "description": "Branded document folders for presenting advice documents and completion statements. Meeting notebooks and pen sets for fee earner use during client consultations. These accessories create a professional meeting environment and provide clients with branded materials they take home, maintaining your firm''s visibility after the meeting ends."}, {"title": "Practice area brochures and referral partner materials", "description": "Concise, professionally designed brochures for each practice area explaining your services, fee structures, and the team involved. Branded information cards and referral packs for estate agents, IFAs, and other professional contacts. These materials equip your referral network with tangible items to share when recommending your firm to their clients."}]',
  '[{"question": "Can your stationery templates include all SRA-required information?", "answer": "Yes. All stationery templates incorporate SRA authorisation details, firm registration numbers, complaints procedure information, and any other regulatory text required by current guidance. These elements are integrated into the design so they are present and legible without dominating the visual presentation."}, {"question": "Do you supply digital letterhead templates as well as printed stationery?", "answer": "Absolutely. Most legal correspondence is now sent electronically. We supply digital letterhead templates compatible with common word processing platforms and practice management systems. These templates maintain the same brand standards and regulatory information as printed stationery, ensuring consistency across both physical and digital correspondence."}, {"question": "What branded materials are most useful for solicitor networking events?", "answer": "Professional business cards remain essential. Beyond that, branded notebooks and quality pen sets make practical impressions. Pocket-sized practice area cards provide a portable summary of your services that contacts keep. For larger events, pull-up banners and display materials maintain brand visibility. The key is quality that reflects the professional standards of your practice."}, {"question": "How do referral partner materials help generate instructions?", "answer": "When an estate agent recommends your conveyancing service, handing the client a professional practice area brochure with your contact details, fee information, and team profiles makes the referral tangible. The client is significantly more likely to contact you than if they received only a verbal recommendation. The brochure does the selling when you are not in the room."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 9. Solicitors × AI Chatbots
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'solicitors',
  'ai-chatbots',
  'People needing a solicitor often reach the point of making contact outside office hours. The homeowner who discovers a boundary dispute browses solicitor websites in the evening. The employee who receives a disciplinary letter researches employment lawyers at midnight. The couple who finally decide to proceed with their divorce have the conversation on a Sunday afternoon and want to take action before the resolve fades. When these potential clients visit your website and find no way to engage beyond a phone number that will not be answered until Monday morning, they either contact another firm with better availability or lose the impetus to act at all. An AI chatbot for solicitors provides immediate, twenty-four-hour engagement that guides potential clients through an initial assessment of their legal matter, answers common questions about processes, timescales, and costs, and captures their details for fee earner follow-up. The chatbot operates within professional conduct boundaries, avoiding the provision of specific legal advice while providing the general guidance and procedural information that potential clients need to feel confident about engaging your firm. It qualifies enquiries by practice area, assesses urgency, and routes captured leads to the appropriate fee earner with all relevant information, ensuring that Monday morning begins with a queue of qualified, pre-assessed enquiries rather than an overflowing voicemail.',
  'Law firm enquiry peaks often occur outside standard office hours because the life events that drive legal need do not follow a nine-to-five schedule. Family crises happen at weekends. Employment disputes arise during evenings. Property concerns surface when homeowners are at home. A chatbot ensures every potential client receives immediate engagement regardless of when they visit your website, capturing enquiries that would otherwise be lost to competitors or abandoned entirely.',
  'We build solicitor chatbots that provide general legal guidance within SRA professional conduct boundaries. The chatbot explains legal processes, typical timescales, and indicative costs without providing specific legal advice. Practice-area-specific conversation flows qualify the enquiry and capture relevant details. Urgent matters are flagged for priority response when the office opens.',
  '[{"title": "Potential clients visiting outside office hours and leaving without engaging", "description": "A significant proportion of initial legal research happens in the evenings and at weekends when people have time to think about their situation. A family law prospect browsing at nine pm on a Wednesday finds your website, reads about your services, but cannot get answers to their immediate questions. They bookmark the page intending to call on Monday, but by then three other firms have their attention."}, {"title": "Reception team unable to triage legal enquiries effectively", "description": "When all calls come through your reception, the team must determine which practice area the enquiry relates to, whether it is urgent, and which fee earner should handle it. Receptionists are not legally trained and may route enquiries incorrectly or fail to identify urgent matters. A chatbot captures structured information that enables accurate routing without relying on reception-level triage."}, {"title": "Repetitive initial enquiry questions consuming fee earner time", "description": "Potential clients ask the same questions repeatedly: how much does conveyancing cost, how long does divorce take, what is involved in making a will, do I need a solicitor for probate. Fee earners answering these questions during initial calls spend time on information that could be provided automatically, reserving their expertise for the legal assessment that actually requires their qualification."}]',
  '[{"title": "Practice-area-specific chatbot conversations within SRA boundaries", "description": "The chatbot presents different conversation flows for each practice area. Conveyancing conversations capture property details, transaction status, and timeline. Family law conversations assess the matter type and urgency. Employment conversations identify whether the visitor is an employer or employee and the nature of the issue. Each flow captures the relevant details while staying within general guidance rather than specific legal advice."}, {"title": "Intelligent triage with urgency assessment and fee earner routing", "description": "The chatbot assesses urgency based on practice-area-specific indicators: court deadlines, limitation periods approaching, emergency family situations, and time-sensitive commercial matters. Urgent enquiries are flagged for priority response. All captured leads are routed to the appropriate fee earner with the full conversation history, qualifying information, and urgency assessment attached."}, {"title": "Initial consultation booking with calendar integration", "description": "After qualifying the enquiry and capturing relevant details, the chatbot offers available consultation appointment slots. Potential clients book directly into fee earner diaries. Appointment confirmations include information about what to bring and what to expect, preparing the client for a productive first meeting. The fee earner receives all captured details before the consultation."}]',
  '[{"question": "Can an AI chatbot operate within SRA professional conduct rules?", "answer": "Yes. The chatbot is designed to provide general procedural information and guidance rather than specific legal advice. It explains typical processes, timescales, and cost structures without advising on individual legal positions. This distinction between general information and specific advice is clearly maintained throughout all chatbot conversations."}, {"question": "How does the chatbot handle sensitive legal matters like family law?", "answer": "Family law conversations use empathetic, non-judgemental language appropriate to the emotional context. The chatbot captures the type of matter, whether children are involved, urgency indicators, and preferred communication methods. Sensitive details are handled with appropriate discretion. The conversation is designed to make the visitor feel heard and supported while capturing the information your family team needs."}, {"question": "Can the chatbot provide cost information for legal services?", "answer": "Yes. The chatbot can share your published fee information for services covered by SRA Transparency Rules and provide indicative cost ranges for other services. These are presented as general guides subject to individual assessment, consistent with how fee information would be discussed in an initial telephone enquiry. Specific quotes require fee earner review of the individual matter."}, {"question": "What happens with enquiries captured outside office hours?", "answer": "Every enquiry is logged with full conversation details, practice area classification, urgency assessment, and client contact information. When your office opens, fee earners receive their allocated enquiries with all captured information. Urgent matters are flagged prominently. The client receives an automated acknowledgement with expected response time, so they know their enquiry has been received and will be addressed."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 10. Solicitors × AI Content
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'solicitors',
  'ai-content',
  'People facing legal matters research extensively before instructing a solicitor. They search for how conveyancing works, what to expect during divorce proceedings, how to contest a will, and whether they need a solicitor for their employment dispute. This research phase represents the most important content opportunity for law firms because every helpful answer you provide establishes your firm as the knowledgeable, trustworthy practice the searcher should instruct when they are ready to act. Legal content marketing is exceptionally effective because the subject matter is complex, the stakes are high, and people genuinely need expert guidance. A comprehensive guide about the conveyancing process does not just attract traffic; it reduces the anxiety that prevents people from taking the first step toward instructing a solicitor. The challenge is that producing accurate legal content requires genuine expertise, awareness of current legislation and case law, and the ability to explain complex legal concepts in accessible language. Fee earners have the knowledge but not the time. Marketing assistants have the time but not the legal knowledge. AI-powered content creation bridges this gap, producing legally informed, SEO-optimised content across every practice area your firm covers. Each piece is crafted to explain legal concepts clearly, target the search terms potential clients use, and guide readers toward instructing your firm.',
  'Legal content has the longest effective lifespan of almost any content category because legal processes change slowly and the fundamental questions remain consistent year after year. A comprehensive conveyancing guide published today will attract traffic for years with only periodic updates for legislative changes. This compounding return makes legal content one of the highest-ROI marketing investments available to solicitors.',
  'Our AI content system produces legally informed content across every practice area, written in accessible language that demystifies legal processes for potential clients. Each piece targets specific search terms used by people researching legal matters and includes appropriate caveats about seeking specific legal advice. Legislative change content is published promptly to capture search spikes.',
  '[{"title": "Practice area pages with no supporting content to rank in search results", "description": "A single page listing conveyancing, family law, wills and probate, and employment law cannot rank for any specific legal search against competitors with comprehensive guides and articles for each practice area. Without depth of content behind your service pages, Google has no basis to rank your firm above competitors who demonstrate expertise through comprehensive legal information."}, {"title": "Legislative changes creating search spikes with no content to capture them", "description": "When legislation changes, search volume spikes as affected people seek information. Changes to inheritance tax thresholds, divorce law reforms, employment regulation updates, and property law amendments all create surges of search traffic. Firms that publish explanatory content quickly capture this traffic. Firms without content miss the spike entirely and the associated client instructions."}, {"title": "Fee earner expertise trapped in their heads rather than published on your website", "description": "Your solicitors possess decades of combined expertise across multiple practice areas, yet almost none of this knowledge appears on your website. The advice they give clients daily about processes, timelines, costs, and common pitfalls would be invaluable as website content attracting new clients. But fee earners understandably prioritise billable work over writing articles."}]',
  '[{"title": "Practice area guide content targeting research-phase legal searches", "description": "Comprehensive guides for every practice area covering processes, timescales, costs, and frequently asked questions. Conveyancing process walkthroughs, divorce timeline guides, probate procedure explanations, and employment rights overviews. Each guide targets the specific search terms potential clients use and provides the helpful information that builds trust before instruction."}, {"title": "Legislative change content published promptly to capture search spikes", "description": "When legislation affecting your practice areas changes, content explaining the implications is produced and published quickly to capture the resulting search traffic spike. Budget announcements affecting inheritance tax, employment law updates, property regulation changes, and family law reforms all generate content opportunities that position your firm as the informed, responsive practice to instruct."}, {"title": "Practice area FAQ content addressing specific client questions", "description": "Content targeting the exact questions potential clients ask: how long does conveyancing take, how much does a divorce cost, do I need probate if there is a will, and can I claim unfair dismissal. Each answer is optimised for the specific search query and includes a clear path to contacting your firm when the reader is ready to discuss their individual situation."}]',
  '[{"question": "Can AI content be accurate enough for legal topics?", "answer": "Our AI content system produces legally informed content covering processes, timescales, and general guidance. Content includes appropriate caveats about seeking specific legal advice for individual circumstances. All content is reviewed for accuracy before publication. Legislative change content is verified against the actual legislative text to ensure accuracy."}, {"question": "How does legal content help generate new client instructions?", "answer": "Content targets people researching legal matters before they instruct a solicitor. By providing helpful, accurate information, your firm becomes the trusted resource they turn to when ready to proceed. Every piece includes clear calls to action guiding readers to your consultation booking or enquiry form. The content educates, builds trust, and converts in a single journey."}, {"question": "What legal topics generate the most search traffic?", "answer": "Cost and process questions generate the highest volume: how much does conveyancing cost, how long does divorce take, and do I need a solicitor for probate. Legislative change content generates spikes. Guides explaining complex processes like the conveyancing chain, contested probate, and unfair dismissal attract high-intent traffic from people actively planning legal action."}, {"question": "How often should a law firm publish new content?", "answer": "We recommend four to eight pieces monthly distributed across your practice areas, with additional content published promptly when relevant legislation changes. A consistent publishing schedule builds topical authority across all practice areas. Over twelve months, a comprehensive legal content library becomes a significant asset generating compounding organic traffic and enquiries."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 11. Solicitors × AI Automation
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'solicitors',
  'ai-automation',
  'Law firms generate and process enormous volumes of documentation, and the intelligence required to manage this documentation effectively goes beyond simple rule-based automation. AI automation for solicitors applies intelligent analysis to the operational and compliance challenges that define legal practice. Document analysis algorithms review incoming correspondence, identify action items, and flag deadlines that require attention. Client communication intelligence determines when clients need updates based on matter progress patterns rather than arbitrary schedules. Compliance monitoring analyses firm-wide activity against SRA requirements, identifying potential issues before they become regulatory problems. Conflict checking uses intelligent matching that goes beyond name searches to identify related entities, connected matters, and potential commercial conflicts. The difference between standard automation and AI automation in a law firm is the difference between a system that sends a diary reminder and a system that reads an opposing solicitor''s letter, identifies three action points with deadlines, logs them against the file, and alerts the responsible fee earner. AI handles the cognitive administrative tasks that currently consume junior solicitor and paralegal time, allowing qualified staff to focus on the legal analysis and client advisory work that generates fees and builds the practice.',
  'The administrative burden on law firms is increasing as regulatory requirements expand and client expectations for communication and transparency grow. Hiring additional support staff addresses capacity but not efficiency. AI automation makes existing staff dramatically more productive by handling the cognitive administrative tasks that fall between simple automation and qualified legal work. The result is more client matters handled per fee earner, more consistent compliance, and better client service.',
  'We implement AI systems that bring intelligent document analysis, predictive compliance monitoring, and smart client communication to legal practice. Document intake analysis identifies action items and deadlines. Communication intelligence ensures client updates happen at the right time. Compliance analytics monitor firm-wide SRA adherence and flag potential issues proactively.',
  '[{"title": "Incoming correspondence requiring manual reading, categorisation, and action identification", "description": "Every letter, email, and document received by your firm must be read, categorised, filed against the correct matter, and assessed for action items and deadlines. This manual triage consumes significant paralegal and support staff time. Delays in processing incoming post mean action items are identified late, deadlines are missed, and fee earners work from an incomplete picture of their matter."}, {"title": "Conflict checking limited to basic name matching", "description": "Standard conflict checks search for matching client names, but genuine conflicts can exist between related entities, associated individuals, and commercially connected matters that a name search does not reveal. A thorough conflict check requires understanding the relationships between parties, which manual checks may miss when the connections are not immediately obvious."}, {"title": "Compliance monitoring reactive rather than proactive across the firm", "description": "Most law firms discover compliance issues when something goes wrong: a missed file review, an expired insurance certificate, a complaints handling deadline breached. Without proactive monitoring, the firm''s compliance position is unknown until an audit or an incident reveals the gaps. Reactive compliance is expensive, stressful, and carries genuine regulatory risk."}]',
  '[{"title": "Intelligent document analysis with automated action identification", "description": "AI analyses incoming correspondence across all formats, identifies the relevant matter, extracts action items and deadlines, and logs them against the appropriate file. Fee earners receive a structured summary of actions required rather than a stack of unprocessed correspondence. Deadline-critical items are flagged with appropriate urgency and added to the firm''s diary system automatically."}, {"title": "Enhanced conflict checking with relationship and entity intelligence", "description": "AI conflict checking goes beyond name matching to analyse corporate structures, known associations, and matter relationships. When a new client instruction is opened, the system checks not just the named parties but their directors, associated companies, and related individuals against your existing client base. This intelligent matching identifies conflicts that basic name searches would miss."}, {"title": "Proactive compliance analytics with SRA requirement monitoring", "description": "AI monitors firm-wide activity against SRA compliance requirements, including file review schedules, complaints handling timelines, transparency rule adherence, and continuing competence obligations. Dashboard views show real-time compliance status across the firm. Predictive alerts flag matters or processes that are trending toward non-compliance before deadlines are actually breached."}]',
  '[{"question": "How does AI document analysis work in practice?", "answer": "Incoming correspondence is scanned and analysed by the AI system. It identifies the relevant matter, extracts key information including dates, monetary amounts, and required actions, and presents a structured summary to the fee earner. Action items are logged against the file with deadlines. The fee earner reviews the AI''s analysis rather than reading and manually processing every document."}, {"question": "Can AI conflict checking really identify conflicts that name searches miss?", "answer": "Yes. AI analyses corporate structures, directorship connections, and known associations between entities. When checking a new instruction, the system maps the relationships around the named parties and checks these against your existing client base. This catches conflicts involving connected companies, family members of existing clients, and commercial relationships that basic name matching cannot identify."}, {"question": "How does proactive compliance monitoring reduce SRA risk?", "answer": "The system continuously monitors compliance-relevant activity across the firm: file review completion rates, complaints handling timelines, transparency rule adherence, and individual continuing competence records. When metrics trend toward non-compliance, alerts are triggered before actual breaches occur. This shifts compliance from reactive crisis management to proactive risk prevention."}, {"question": "What is the difference between AI automation and standard automation for a law firm?", "answer": "Standard automation follows rules: send a client update email on day thirty of a matter. AI automation makes intelligent decisions: analyse this incoming letter, identify three action items with deadlines, and alert the fee earner to the most time-critical one. AI handles cognitive tasks that require understanding, categorisation, and judgement, not just rule-following."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;
