-- ============================================================
-- seed-local-content-dover.sql
-- Local content for Dover across all 11 services
-- Safe to re-run: uses ON CONFLICT ... DO UPDATE
-- ============================================================

-- ==========================================================
-- DOVER (11 services)
-- ==========================================================

-- 1. Dover × Web Design
INSERT INTO public.local_content (service_slug, town_slug, intro_paragraph, local_context, competition_landscape, success_approach, local_stats, pain_points, solutions, faqs, layout_variant)
VALUES (
  'web-design',
  'dover',
  'Dover occupies a unique position in Kent as both an ancient historic town and the busiest passenger port in the United Kingdom. Every year, millions of travellers pass through the Port of Dover on their way to and from mainland Europe, yet the town itself has struggled to retain that footfall and convert passing visitors into local customers. With a population of around thirty-five thousand in the town and over one hundred and seventeen thousand across the district, Dover businesses serve a mix of residents, tourists drawn to Dover Castle and the White Cliffs, and the logistics and transport workforce that keeps the port running. A professionally built website is essential for capturing these diverse audiences. We design conversion-focused websites for Dover businesses that speak to tourists researching visits, residents searching for local services, and commercial clients across the port and transport sector.',
  'Dover''s commercial geography is shaped by its port and heritage. The town centre around Market Square and the High Street serves as the retail core, while the seafront and De Bradelei Wharf attract tourist footfall. Dover Castle and the White Cliffs draw hundreds of thousands of visitors annually, generating demand for hospitality, dining, and retail. The A2 and A20 corridors connect Dover to London and the M25, making the town a gateway for continental logistics. Dover Priory station links to London St Pancras via high-speed rail. The Western Heights and Connaught Park add residential character to the hillside areas above the town centre.',
  'Dover''s web design market is underserved. Many businesses around Market Square and the High Street operate with dated websites that fail to capture the tourist audience effectively. Port-related logistics firms often have functional but visually uninspiring sites. Tourism operators near the Castle and White Cliffs vary significantly in digital quality. London agencies rarely target Dover specifically, leaving a gap between cheap template builders and genuine quality.',
  'Our approach for Dover starts with understanding the three distinct audiences every business here must consider: local residents, tourists and visitors, and the port and logistics sector. We build sites that serve each audience with clear navigation paths, whether someone is a local searching for a plumber on Market Square, a tourist planning a White Cliffs walk, or a shipping company evaluating a logistics partner. Speed and mobile optimisation are critical for the tourist audience browsing on mobile data.',
  '{"population": 35000, "district_population": 117000, "business_districts": ["Market Square", "High Street", "De Bradelei Wharf", "Port of Dover", "Dover Priory area"], "key_fact": "Busiest passenger port in the UK with millions of annual travellers"}',
  '[{"title": "Tourist traffic not converting into local business online", "description": "Hundreds of thousands of visitors come to Dover Castle and the White Cliffs each year. They search for restaurants, shops, and experiences on their phones while visiting. Dover businesses with outdated, slow websites lose these visitors to the handful of competitors who present a polished digital experience."}, {"title": "Dated websites failing to compete across three audiences", "description": "Dover businesses must appeal to residents, tourists, and the port logistics sector simultaneously. Most existing websites were built for one audience and ignore the others entirely. A restaurant near Market Square needs to attract both locals and Castle visitors, but its five-year-old site does neither effectively."}, {"title": "Port and logistics firms lacking professional digital presence", "description": "The transport and logistics sector around the Port of Dover is substantial, yet many firms operate with basic brochure websites that do not convey the scale or professionalism of their operations. When international clients search for Dover-based logistics partners, a substandard website costs contracts."}]',
  '[{"title": "Multi-audience websites designed for Dover''s unique market", "description": "We build Dover websites with distinct user journeys for each audience. Tourists get prominent booking and visiting information with stunning White Cliffs imagery. Local residents get clear service pages and easy contact methods. Commercial clients get professional capability presentations. One site, three conversion paths."}, {"title": "Mobile-first design for on-the-go tourist visitors", "description": "Visitors walking along the White Cliffs or queuing at the port browse exclusively on mobile. We build Dover sites with sub-two-second mobile load times, thumb-friendly navigation, and prominent click-to-call buttons. Your site works flawlessly on patchy mobile signal near the clifftops."}, {"title": "Professional websites that match Dover''s heritage significance", "description": "Dover is a town of genuine historic importance, from the Castle to St Edmund''s Chapel to the Western Heights. We design sites that reflect this heritage credibility without feeling dated. Your business benefits from Dover''s prestige through design that communicates permanence and trustworthiness."}]',
  '[{"question": "How long does a new website take for a Dover business?", "answer": "Most Dover projects launch within four to six weeks. We begin with a strategy session understanding your position in the local market, whether you serve tourists near the Castle, residents around Market Square, or commercial clients linked to the port. Design, development, and testing follow a structured timeline."}, {"question": "Will my site attract both tourists and local customers?", "answer": "Yes. We design Dover websites with separate user journeys for different audiences. A restaurant might have a tourist landing page highlighting proximity to the Castle and White Cliffs alongside a locals page featuring weekly menus and booking. Each audience sees content relevant to their needs."}, {"question": "Can you help my logistics business look more professional online?", "answer": "Absolutely. We work with several Dover businesses in the port and transport sector. We build websites that project the operational scale and professionalism international clients expect, with case studies, fleet information, and capability presentations that win contracts."}, {"question": "Do you work with businesses outside Dover town centre?", "answer": "Yes. We serve businesses across the Dover district including Deal, Sandwich, and surrounding villages. Our local SEO approach ensures your site reaches customers across the A2 and A20 corridors and the wider east Kent area."}]',
  'lead-gen'
)
ON CONFLICT (service_slug, town_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  local_context = EXCLUDED.local_context,
  competition_landscape = EXCLUDED.competition_landscape,
  success_approach = EXCLUDED.success_approach,
  local_stats = EXCLUDED.local_stats,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs,
  layout_variant = EXCLUDED.layout_variant;

-- 2. Dover × SEO
INSERT INTO public.local_content (service_slug, town_slug, intro_paragraph, local_context, competition_landscape, success_approach, local_stats, pain_points, solutions, faqs, layout_variant)
VALUES (
  'seo',
  'dover',
  'Dover has a search profile unlike any other town in Kent. Alongside the standard local service queries that every town generates, Dover attracts enormous search volume from tourists researching visits to the White Cliffs, Dover Castle, and the port crossings. This creates a dual opportunity for local businesses: capturing the residents who need everyday services and intercepting the visitor traffic that is actively searching for things to do, places to eat, and places to stay. Yet most Dover businesses have no SEO strategy whatsoever. They are invisible for the tourist-related searches happening on their doorstep and losing ground to competitors for basic local service terms. Our SEO campaigns are engineered specifically for Dover''s unusual search landscape, targeting both residential intent and the high-volume visitor queries that could transform your revenue.',
  'Dover''s search landscape splits into three distinct channels. Local residential searches follow standard patterns for trades, professional services, and retail. Tourist and visitor searches spike seasonally, with enormous volumes around Dover Castle, White Cliffs walks, port parking, and Channel crossing information. Commercial searches relate to the port logistics sector, freight forwarding, and transport services. Dover Priory station and the A2/A20 corridors generate additional transit-related search intent. The Dover Museum, St Edmund''s Chapel, and Connaught Park contribute to heritage and leisure search volume.',
  'SEO competition in Dover is moderate for residential terms but highly contested for tourist-related keywords. National tourism platforms, English Heritage, and the National Trust dominate the top positions for Castle and Cliffs searches. Local hospitality businesses compete fiercely for restaurant and accommodation queries. For trade and service keywords, competition is lower than in larger Kent towns, presenting quick-win opportunities for businesses willing to invest.',
  'We approach Dover SEO by building two parallel strategies: a local residential campaign targeting service-specific terms across the Dover district, and a visitor-capture campaign intercepting tourist searches with content that drives footfall. A Dover restaurant ranks for both takeaway near Dover Priory and best restaurant near Dover Castle as separate, optimised content paths. Google Business Profile optimisation is critical here, as tourists rely heavily on map results.',
  '{"population": 35000, "district_population": 117000, "business_districts": ["Market Square", "High Street", "Port of Dover", "De Bradelei Wharf"], "key_fact": "Dual search landscape combining residential intent and massive tourist volume"}',
  '[{"title": "Tourist search volume going entirely to national platforms", "description": "Millions of people search for Dover Castle, White Cliffs, and port-related information annually. National platforms like English Heritage, TripAdvisor, and the National Trust capture almost all of this traffic. Local Dover businesses that could benefit from visitor footfall are invisible in these searches."}, {"title": "Local service searches lost to competitors with basic SEO", "description": "When a Dover resident searches for a plumber, electrician, or accountant, Google serves results based on proximity, reviews, and optimisation. Businesses with incomplete Google Business Profiles and no local content lose every time to competitors who have invested even minimally in search visibility."}, {"title": "Seasonal fluctuations devastating unprepared Dover businesses", "description": "Tourist-dependent Dover businesses experience dramatic seasonal swings. Without SEO capturing year-round residential searches and building authority during quieter months, these businesses face cash flow crises every winter while competitors with diversified search strategies maintain steady enquiry flow."}]',
  '[{"title": "Dual-intent SEO capturing residents and visitors", "description": "We build Dover SEO campaigns with two distinct keyword strategies. Residential targeting captures local service searches across the district. Visitor targeting intercepts tourist queries for dining, activities, and accommodation near the Castle, White Cliffs, and port. Two revenue streams from one optimised presence."}, {"title": "Google Business Profile domination for Dover map results", "description": "Tourists searching near Dover Castle or the port rely overwhelmingly on Google Maps results. We fully optimise your Google Business Profile with Dover-specific categories, professional imagery, and a review generation strategy that builds the social proof visitors need to choose your business over alternatives."}, {"title": "Seasonal SEO strategy smoothing Dover''s revenue cycles", "description": "We build content calendars that capture tourist searches during peak season while strengthening residential search positions year-round. Pre-season content goes live before tourist volume spikes, ensuring your Dover business is visible when visitors start planning. Off-season campaigns maintain local enquiry flow."}]',
  '[{"question": "Can SEO really help my Dover business attract tourists?", "answer": "Absolutely. Tourist searches for dining, activities, and services near Dover Castle and the White Cliffs are enormous. Most local businesses are invisible for these terms because they have never optimised for visitor intent. We build content specifically targeting what tourists search for when visiting Dover."}, {"question": "How competitive is SEO in Dover compared to larger Kent towns?", "answer": "For local residential service terms, Dover is less competitive than Maidstone or Canterbury, meaning faster results are achievable. Tourist-related terms are more competitive due to national platforms, but there are significant opportunities in long-tail visitor queries that larger platforms ignore."}, {"question": "How do you handle seasonal search patterns in Dover?", "answer": "We plan content and optimisation around Dover''s seasonal calendar. Tourist-focused content is built and indexed before peak season so it ranks when volume arrives. Year-round local service content ensures your business maintains enquiry flow during quieter winter months when visitor numbers drop."}, {"question": "Do you optimise for port and logistics related searches?", "answer": "Yes. The port and transport sector is a significant part of Dover''s economy. We build SEO strategies for logistics firms, freight forwarders, and port service providers targeting commercial search terms. B2B SEO in this sector focuses on capability pages, industry content, and professional directory citations."}]',
  'authority'
)
ON CONFLICT (service_slug, town_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  local_context = EXCLUDED.local_context,
  competition_landscape = EXCLUDED.competition_landscape,
  success_approach = EXCLUDED.success_approach,
  local_stats = EXCLUDED.local_stats,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs,
  layout_variant = EXCLUDED.layout_variant;

-- 3. Dover × Lead Capture
INSERT INTO public.local_content (service_slug, town_slug, intro_paragraph, local_context, competition_landscape, success_approach, local_stats, pain_points, solutions, faqs, layout_variant)
VALUES (
  'lead-capture',
  'dover',
  'Dover businesses face a challenge that most Kent towns do not: a constant stream of transient visitors who browse, consider, and leave without making contact. A tourist walking along the White Cliffs searches for a restaurant, visits your website, then gets distracted by the next attraction. A port worker checks your services during a break but does not have time to call. A resident near Dover Priory browses your site on the train home but forgets to follow up. Every one of these people was a potential customer, and without a lead capture system, they disappear entirely. Our lead capture solutions are built specifically for Dover''s mixed audience, using smart forms, instant response tools, and automated follow-up sequences that convert passing interest into actionable leads before your visitors move on to the next search result.',
  'Dover''s lead generation environment is defined by its transient traffic patterns. Tourist visitors browse local business websites for short sessions on mobile devices, often while walking or waiting for ferries. Port and logistics workers have limited browsing windows during shifts. Residential customers around Market Square and the wider district follow standard evening browsing patterns. The A2 and A20 corridors bring pass-through traffic searching for services on the move. Each audience requires a different capture strategy matched to their browsing behaviour and attention span.',
  'Lead capture sophistication among Dover businesses is minimal. Tourism operators occasionally use booking widgets, but few have proper lead capture for enquiries that fall outside immediate bookings. Trades and service businesses rely almost entirely on phone calls and basic contact forms. The businesses that do implement proper capture systems report a significant increase in enquiries simply because they make it easy for Dover''s time-pressed visitors to leave their details quickly.',
  'We design lead capture for Dover around the concept of time-constrained audiences. A tourist gets a one-tap booking enquiry form that takes ten seconds to complete. A port worker sees a rapid quote request tool optimised for mobile. A residential customer browsing in the evening gets an exit-intent offer with a callback scheduler. Every form is designed to capture the minimum viable information needed to start a conversation, removing the friction that loses Dover''s impatient visitors.',
  '{"population": 35000, "district_population": 117000, "business_districts": ["Market Square", "High Street", "Port of Dover", "De Bradelei Wharf"], "key_fact": "Transient tourist and port traffic requires fast, frictionless capture methods"}',
  '[{"title": "Tourist visitors browsing and leaving without trace", "description": "Visitors to Dover Castle and the White Cliffs search for local restaurants, shops, and experiences on their phones. They visit your website for thirty seconds, find no easy way to make a quick enquiry, and tap back to Google. That visitor is gone permanently, choosing the competitor who made contact effortless."}, {"title": "Port workers and logistics staff with no time to call", "description": "The transport sector workforce around the Port of Dover operates on tight schedules. A driver or logistics coordinator might check your services on a phone during a break but cannot make a phone call. Without a rapid mobile enquiry form, these potential commercial leads vanish when their break ends."}, {"title": "Evening residential browsers forgetting to follow up", "description": "Dover residents researching local services after work visit multiple websites in a single session. By morning, they remember the business that sent a confirmation email, not the one with only a phone number. Without capturing details and sending instant automated responses, your enquiry is lost to the business that did."}]',
  '[{"title": "Ten-second tourist capture forms for mobile visitors", "description": "We build ultra-lightweight enquiry forms designed for Dover''s tourist audience. Three fields maximum, one-tap submission, and an instant confirmation with your location and directions. Visitors near the Castle or White Cliffs can enquire about your restaurant, shop, or service without breaking stride."}, {"title": "Rapid quote tools for Dover''s commercial sector", "description": "Port and logistics businesses get custom quote request forms that capture job specifics in under thirty seconds on mobile. Drivers and coordinators can submit requirements between tasks, and your team receives structured enquiry data ready for quoting. No phone tag, no missed connections."}, {"title": "Automated follow-up converting evening browsers into morning customers", "description": "Every lead captured from your Dover website triggers an instant personalised response followed by a timed email sequence. A resident who enquired at nine in the evening receives professional communication within seconds. By morning, your business is the one they remember and respond to."}]',
  '[{"question": "What type of lead capture works best for Dover tourism businesses?", "answer": "For Dover tourism operators, we recommend lightweight booking enquiry forms with minimal fields, prominent click-to-call buttons, and location-based prompts showing proximity to the Castle or White Cliffs. The key is speed: tourist visitors have short attention spans and will not complete lengthy forms."}, {"question": "Can lead capture help my logistics business near the port?", "answer": "Absolutely. We build structured quote request forms that capture job specifications, timeline, and contact details in a format your operations team can action immediately. For port-related businesses, we integrate with existing quoting and dispatch systems where possible."}, {"question": "How many more leads can I expect from better capture systems?", "answer": "Most Dover clients see a two to four times increase in monthly enquiries within the first month. The leads were always there as website visitors. Lead capture simply gives them a fast, easy way to make contact instead of leaving your site to try a competitor."}, {"question": "Will lead capture forms slow down my website?", "answer": "No. We build lightweight forms that add negligible load time to your Dover site. Speed is critical for the tourist audience browsing on mobile data near the Cliffs and Castle. Our forms load in under half a second and are fully optimised for low-bandwidth mobile connections."}]',
  'lead-gen'
)
ON CONFLICT (service_slug, town_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  local_context = EXCLUDED.local_context,
  competition_landscape = EXCLUDED.competition_landscape,
  success_approach = EXCLUDED.success_approach,
  local_stats = EXCLUDED.local_stats,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs,
  layout_variant = EXCLUDED.layout_variant;

-- 4. Dover × Business Automation
INSERT INTO public.local_content (service_slug, town_slug, intro_paragraph, local_context, competition_landscape, success_approach, local_stats, pain_points, solutions, faqs, layout_variant)
VALUES (
  'business-automation',
  'dover',
  'Dover''s economy runs on movement. The Port of Dover processes millions of passengers and vast quantities of freight annually, and the businesses that support this ecosystem operate under constant time pressure. Logistics coordinators juggle bookings manually. Guest houses near the White Cliffs handle reservation confirmations by hand. Trades serving the wider district spend evenings writing quotes instead of resting. The transport and tourism sectors that define Dover''s economy are particularly vulnerable to administrative bottlenecks because demand fluctuates dramatically with seasons, ferry schedules, and crossing delays. Our business automation solutions connect fragmented processes into seamless workflows that handle the administrative load automatically, giving Dover business owners back the hours they are currently losing to repetitive tasks that machines should be doing.',
  'Dover''s business environment is uniquely shaped by the port and tourism cycle. Hospitality businesses near the Castle and White Cliffs experience extreme seasonal demand swings requiring flexible booking and staffing systems. Logistics and transport firms operate around ferry schedules and customs procedures that generate enormous paperwork. Trades and service businesses across the wider district face the same quoting and invoicing challenges as elsewhere in Kent, compounded by the geographic spread from Dover to Deal and the surrounding villages along the A2 and A20 corridors.',
  'Automation adoption among Dover businesses is extremely low, even by Kent standards. The port logistics sector relies heavily on manual processes despite the volume of transactions. Tourism operators handle bookings through a patchwork of phone calls, emails, and third-party platforms with no integration. Trades operate with paper-based quoting. The few businesses that have automated key processes report significant competitive advantages in response time and operational capacity.',
  'We start every Dover automation project by mapping the specific workflows that consume the most time. A guest house near the Castle gets automated booking confirmations, review requests, and seasonal pricing adjustments. A logistics firm near the port gets customs document preparation workflows and automated scheduling. A tradesperson covering the district gets enquiry-to-invoice automation. Every system is built around how Dover businesses actually operate, not generic templates.',
  '{"population": 35000, "district_population": 117000, "business_districts": ["Port of Dover", "Market Square", "High Street", "De Bradelei Wharf"], "key_fact": "Port operations and tourism create high-volume, time-sensitive administrative demands"}',
  '[{"title": "Seasonal demand overwhelming Dover hospitality operations", "description": "Guest houses, restaurants, and tour operators near Dover Castle and the White Cliffs face enormous seasonal swings. During peak summer months, manual booking management becomes impossible. Overbookings, missed confirmations, and slow responses to enquiries cost revenue and damage reputations during the most critical trading period."}, {"title": "Port logistics firms drowning in manual paperwork", "description": "The transport and logistics sector around the Port of Dover generates vast quantities of documentation for every crossing, shipment, and customs declaration. Manual processing creates delays, errors, and bottlenecks that compound during busy periods. Staff spend hours on data entry that should flow automatically between systems."}, {"title": "Dover trades losing evenings to admin across a wide service area", "description": "Tradespeople covering the Dover district from the town centre to Deal and the surrounding villages spend hours each evening writing quotes, chasing invoices, and scheduling jobs. The geographic spread of their work adds travel planning and route management to an already overwhelming administrative burden."}]',
  '[{"title": "Seasonal-smart automation for Dover hospitality", "description": "We build booking management systems that handle peak season automatically. Confirmation emails, availability updates, pricing adjustments, and review requests all trigger without manual intervention. Your Dover guest house or restaurant handles three times the volume without additional staff during the Castle and Cliffs tourist season."}, {"title": "Document and workflow automation for port logistics", "description": "We connect your booking, scheduling, and documentation systems into seamless workflows. Customs paperwork populates automatically from booking data. Scheduling updates trigger client notifications. Invoice generation follows job completion. The manual data entry that bogs down Dover logistics operations is eliminated."}, {"title": "Enquiry-to-invoice automation for Dover district trades", "description": "From the moment a prospect contacts your Dover business, automation handles the administrative chain. Enquiry acknowledgement, quote generation from templates, follow-up reminders, job scheduling, completion confirmation, and invoice dispatch all flow automatically. You focus on the work while the system handles the paperwork."}]',
  '[{"question": "Can automation handle the seasonal peaks my Dover business experiences?", "answer": "That is precisely what automation excels at. We build systems that scale effortlessly during peak tourist season. When enquiry volume triples around Dover Castle and the White Cliffs in summer, automated responses, booking confirmations, and follow-ups handle the load without additional staff or overtime."}, {"question": "What systems do you integrate with for Dover logistics businesses?", "answer": "We work with common logistics platforms including fleet management systems, customs documentation tools, and accounting software like Xero and QuickBooks. For Dover port-related businesses, we build custom integrations where standard connectors do not exist, ensuring your specific workflow is automated end to end."}, {"question": "How long does automation setup take for a Dover business?", "answer": "A core automation stack covering enquiry management, booking confirmations, and invoicing typically takes two to three weeks. More complex workflows involving customs documentation, multi-system integration, or seasonal pricing logic may take four to six weeks. We prioritise the automations that save you the most time first."}, {"question": "I am not very technical. Will I be able to manage the automations?", "answer": "You will not need to manage them. The automations run invisibly in the background using the tools you already know. When something needs adjusting, such as seasonal pricing or new service offerings, we handle the changes. We also provide simple documentation for any routine adjustments you want to make yourself."}]',
  'operational'
)
ON CONFLICT (service_slug, town_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  local_context = EXCLUDED.local_context,
  competition_landscape = EXCLUDED.competition_landscape,
  success_approach = EXCLUDED.success_approach,
  local_stats = EXCLUDED.local_stats,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs,
  layout_variant = EXCLUDED.layout_variant;

-- 5. Dover × Branding
INSERT INTO public.local_content (service_slug, town_slug, intro_paragraph, local_context, competition_landscape, success_approach, local_stats, pain_points, solutions, faqs, layout_variant)
VALUES (
  'branding',
  'dover',
  'Dover carries a weight of identity that few Kent towns can match. The White Cliffs are an iconic symbol of Britain itself. Dover Castle has guarded the English Channel for nearly a thousand years. The port connects the country to an entire continent. Yet for all this heritage significance, many Dover businesses present themselves with generic branding that could belong to any town in the country. A restaurant near Market Square with a clipart logo and inconsistent colours fails to benefit from the prestige of its location. A logistics firm operating from the busiest passenger port in the UK with an amateur website and plain van livery undersells its operational credibility. We create brand identities for Dover businesses that draw on the town''s genuine heritage and significance, building visual credibility that converts the prestige of your location into customer trust and higher perceived value.',
  'Dover''s visual identity is dominated by its heritage landmarks. The White Cliffs, the Castle, and the port create a dramatic backdrop that shapes how visitors and residents perceive the town. Market Square and the High Street have seen regeneration efforts, but the overall aesthetic remains a mix of historic charm and functional port infrastructure. De Bradelei Wharf brings a retail dimension to the waterfront. Connaught Park and the Western Heights add green space and Victorian character. St Edmund''s Chapel and the Dover Museum contribute to the town''s deep historical layering.',
  'Brand quality among Dover businesses is heavily polarised. Tourism operators near the Castle and Cliffs tend to have decent visual identities, influenced by English Heritage standards. But the wider business community, particularly trades, retail around Market Square, and port-adjacent firms, largely operates with dated or amateur branding. This creates a striking disconnect between Dover''s heritage significance and the visual presentation of its business community.',
  'Our branding approach for Dover starts with the question of heritage alignment. Every business here operates in the shadow of genuine British icons. We create brand identities that respect this context without resorting to cliched cliff imagery. A logistics firm gets branding that projects the scale and reliability of its port operations. A restaurant near Market Square gets an identity that feels established and trustworthy. The goal is always to ensure your brand borrows credibility from Dover''s significance rather than diminishing it.',
  '{"population": 35000, "district_population": 117000, "business_districts": ["Market Square", "High Street", "De Bradelei Wharf", "Port of Dover"], "key_fact": "Iconic heritage location creating unique branding opportunities for local businesses"}',
  '[{"title": "Generic branding wasting Dover''s heritage advantage", "description": "Operating a business in one of Britain''s most iconic locations while using a clipart logo and inconsistent colours is a missed opportunity of enormous proportions. Tourists expect businesses near Dover Castle and the White Cliffs to reflect the quality and significance of their surroundings. Generic branding actively undermines this expectation."}, {"title": "Port logistics firms projecting amateur image to international clients", "description": "Companies operating from the busiest passenger port in the UK should project operational scale and professional credibility. Instead, many Dover logistics firms have plain vans, basic business cards, and websites that look like they were built in a weekend. International clients judge capability by presentation."}, {"title": "Inconsistent visual identity across Dover business touchpoints", "description": "A Dover business might have one look on its Market Square shopfront, another on its website, and yet another on its vehicles. This fragmented identity confuses customers and prevents the brand recognition that drives repeat business and referrals in a town where word of mouth matters enormously."}]',
  '[{"title": "Heritage-conscious branding for Dover businesses", "description": "We create brand identities that draw on Dover''s significance without cliche. Colour palettes inspired by the chalk cliffs, the harbour, and the Castle stone. Typography that feels established and permanent. Visual systems that make your Dover business feel like a natural part of the town''s prestigious landscape."}, {"title": "Professional identity for Dover''s commercial and logistics sector", "description": "For port-adjacent and logistics businesses, we design brands that project the operational scale their clients expect. Fleet livery, documentation design, corporate presentations, and digital presence all unified under a brand system that says this is a serious, capable operation worthy of the UK''s premier port."}, {"title": "Unified brand systems across every Dover touchpoint", "description": "From your Market Square signage to your website, from van livery to workwear, from social media to invoice headers. We deliver a complete brand system with guidelines ensuring perfect consistency. Every customer encounter reinforces the same professional, trustworthy image of your Dover business."}]',
  '[{"question": "Should my Dover brand reference the White Cliffs or Castle?", "answer": "It depends on your business. We avoid literal cliff or castle imagery as it often feels generic. Instead, we draw subtle inspiration from Dover''s visual environment: the chalk whites, harbour blues, and heritage stone tones create sophisticated palettes that feel distinctly Dover without resorting to tourist postcard cliches."}, {"question": "How long does a full brand identity take for a Dover business?", "answer": "A complete brand identity including logo, colour system, typography, brand guidelines, and primary applications typically takes three to four weeks. We begin with a strategy session exploring your position in the Dover market and develop concepts that differentiate you from competitors."}, {"question": "Can you rebrand my logistics business near the port?", "answer": "Yes. We have experience branding commercial and logistics firms where projecting operational credibility is essential. We design complete identity systems covering fleet livery, corporate documentation, digital presence, and physical signage that position your Dover business as a professional, trustworthy partner."}, {"question": "Do you design vehicle livery for Dover businesses?", "answer": "Absolutely. Vehicle branding is particularly impactful in Dover where vans are visible throughout the town centre, along the A2 and A20, and at customer premises across the district. We design livery and work with local wrap specialists to ensure your brand translates perfectly from screen to vehicle."}]',
  'trust'
)
ON CONFLICT (service_slug, town_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  local_context = EXCLUDED.local_context,
  competition_landscape = EXCLUDED.competition_landscape,
  success_approach = EXCLUDED.success_approach,
  local_stats = EXCLUDED.local_stats,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs,
  layout_variant = EXCLUDED.layout_variant;

-- 6. Dover × Social Media Setup
INSERT INTO public.local_content (service_slug, town_slug, intro_paragraph, local_context, competition_landscape, success_approach, local_stats, pain_points, solutions, faqs, layout_variant)
VALUES (
  'social-media-setup',
  'dover',
  'Social media in Dover operates on two distinct levels. The local community discusses businesses, recommends tradespeople, and shares experiences in Dover-specific Facebook groups. Simultaneously, visitors and tourists post about the White Cliffs, Dover Castle, and port crossings across Instagram, TripAdvisor, and Facebook, generating enormous volumes of Dover-related content that local businesses could leverage but almost never do. A restaurant near Market Square that is tagged in a tourist''s White Cliffs Instagram post gains exposure to hundreds of potential visitors, but only if its profile is properly set up, branded, and active. We build and optimise social media profiles for Dover businesses that capture both the local community conversation and the visitor-driven content that makes this town unique.',
  'Dover''s social media landscape combines strong local community engagement with high-volume tourist content. Facebook groups for Dover residents are active forums for recommendations and reviews. Instagram sees significant Dover content driven by the White Cliffs and Castle, with visitor photos generating thousands of impressions daily. TripAdvisor is heavily used for Dover hospitality businesses given the tourist footfall. Google reviews influence both local search rankings and tourist decision-making. The port generates its own social conversation around crossing times, delays, and travel experiences.',
  'Social media quality among Dover businesses is inconsistent. Tourism-facing businesses near the Castle tend to have active Instagram presences, but most other Dover businesses either have dormant Facebook pages or no social media at all. Few businesses engage with the tourist content being created about Dover daily. The gap between businesses with professional social media and those without is widening as customers increasingly check social profiles before making purchasing decisions.',
  'We set up Dover social media profiles based on audience behaviour. Hospitality and tourism businesses get Instagram-first strategies to intercept visitor content. Trades and local services get Facebook profiles optimised for community group engagement. Port and logistics firms get LinkedIn pages built for commercial credibility. Every profile is branded consistently and includes Dover-specific local information that improves discoverability.',
  '{"population": 35000, "district_population": 117000, "business_districts": ["Market Square", "High Street", "De Bradelei Wharf", "Dover Castle area"], "key_fact": "High-volume tourist social content creates unique engagement opportunities"}',
  '[{"title": "Tourist social content going unmonetised by Dover businesses", "description": "Visitors to the White Cliffs and Dover Castle post hundreds of photos and reviews daily across Instagram, Facebook, and TripAdvisor. Local businesses that could benefit from this exposure either have no social media presence or fail to engage with visitor content, missing an enormous free marketing opportunity."}, {"title": "Dormant Dover Facebook pages damaging business credibility", "description": "A potential customer searches for your Dover business on Facebook and finds a page last updated two years ago with inconsistent branding and no recent activity. This dormant presence is worse than no presence at all, actively signalling that the business may no longer be operating or does not care about its public image."}, {"title": "No social presence for community recommendation requests", "description": "Dover Facebook groups see daily posts asking for tradesperson recommendations, restaurant suggestions, and service provider referrals. Businesses without active, professional social media profiles cannot benefit from these recommendations because there is nothing credible for potential customers to check when they see your name mentioned."}]',
  '[{"title": "Tourist-intercepting social profiles for Dover hospitality", "description": "We set up and optimise Instagram and Facebook profiles designed to appear when visitors tag Dover locations. Proper hashtag strategy, location tagging, and content templates ensure your hospitality business benefits from the enormous volume of tourist content created around the White Cliffs and Castle daily."}, {"title": "Community-ready Facebook presence for Dover services", "description": "For trades and service businesses, we build Facebook profiles optimised for the Dover community conversation. Professional branding, complete service information, prominent reviews, and ready-to-share content that looks credible when someone recommends you in a local group and the prospect clicks through to check."}, {"title": "Branded, consistent profiles across every Dover-relevant platform", "description": "Facebook, Instagram, Google Business Profile, and LinkedIn where appropriate. Every profile carries consistent Dover-specific branding, complete business information, and platform-appropriate content. No orphaned profiles, no outdated information, no branding mismatches across platforms."}]',
  '[{"question": "Which social media platforms matter most for Dover businesses?", "answer": "It depends on your audience. Tourism and hospitality businesses benefit most from Instagram and TripAdvisor. Local service businesses need strong Facebook and Google Business Profiles for community engagement. B2B and logistics firms benefit from LinkedIn. We set up the platforms that match your specific Dover customer base."}, {"question": "Can social media really attract tourists to my Dover business?", "answer": "Yes. Visitors actively search Dover hashtags and location tags on Instagram and check Google reviews before choosing restaurants and activities. A professionally set up profile with strong visuals and positive reviews directly influences tourist spending. We have seen Dover hospitality clients significantly increase footfall through social presence alone."}, {"question": "How do I engage with tourist content about Dover?", "answer": "We set up monitoring for Dover-related hashtags, location tags, and mentions. When visitors post about the White Cliffs or Castle and tag nearby locations, your business can engage with that content, building visibility with their followers. We provide templates and guidance for effective engagement."}, {"question": "I do not have time to post on social media regularly. Can you help?", "answer": "Our service focuses on the professional setup and optimisation of your profiles, giving you a strong foundation. We also provide content templates and scheduling guidance that make posting take minutes rather than hours. For ongoing management, we can discuss regular content packages."}]',
  'trust'
)
ON CONFLICT (service_slug, town_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  local_context = EXCLUDED.local_context,
  competition_landscape = EXCLUDED.competition_landscape,
  success_approach = EXCLUDED.success_approach,
  local_stats = EXCLUDED.local_stats,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs,
  layout_variant = EXCLUDED.layout_variant;

-- 7. Dover × Digital Marketing
INSERT INTO public.local_content (service_slug, town_slug, intro_paragraph, local_context, competition_landscape, success_approach, local_stats, pain_points, solutions, faqs, layout_variant)
VALUES (
  'digital-marketing',
  'dover',
  'Dover offers a marketing landscape that most digital agencies completely misunderstand. This is not simply a small Kent town with a local audience. It is the busiest passenger port in the United Kingdom, home to one of England''s most visited castles, and the location of the White Cliffs, one of Britain''s most recognisable landmarks. The marketing opportunity here is dual-natured: a resident population of thirty-five thousand who need everyday services, and millions of annual visitors who spend money on food, accommodation, retail, and experiences. Yet most Dover businesses market only to one of these audiences, or worse, to neither with any deliberate strategy. Our digital marketing campaigns are built specifically for Dover''s unique dual market, running targeted campaigns that capture local customers while intercepting the enormous visitor traffic that passes through this town every year.',
  'Dover''s digital marketing environment spans three distinct audiences. Local residents search for services, shop online, and respond to social media advertising in standard patterns. Tourists plan visits through Google, social media, and travel platforms, with decision-making often happening weeks before arrival. The port logistics and commercial sector operates through B2B channels including LinkedIn, industry directories, and trade publications. Dover Priory station, the A2/A20 corridors, and the ferry terminal create additional geographic targeting opportunities for reaching travellers at specific points in their journey.',
  'Digital marketing spend in Dover is concentrated among a small number of tourism operators and hospitality businesses running Google Ads and social campaigns. The broader business community invests minimally in paid digital channels. National tourism boards and ferry operators dominate the paid search landscape for crossing and visit-related terms. Local service businesses face moderate competition from regional competitors but very little from sophisticated local campaigns.',
  'We build Dover digital marketing campaigns around audience segmentation and timing. Tourist-targeted ads launch before peak booking periods with messaging tied to Castle visits, Cliffs walks, and port crossings. Local service campaigns run year-round targeting residents across the district. Remarketing captures website visitors who browsed but did not convert. Every campaign is measured against real business outcomes: enquiries, bookings, and revenue, not vanity metrics.',
  '{"population": 35000, "district_population": 117000, "business_districts": ["Market Square", "High Street", "Port of Dover", "De Bradelei Wharf"], "key_fact": "Dual market opportunity combining resident customers and millions of annual visitors"}',
  '[{"title": "Tourist marketing budget wasted on wrong timing and targeting", "description": "Dover hospitality businesses that run Google Ads or social campaigns often target broadly and year-round, burning budget during low-season periods and missing the critical pre-booking window when tourists decide where to eat, stay, and visit. Without seasonal campaign management, marketing spend generates far fewer bookings than it should."}, {"title": "Local service businesses invisible in Dover''s digital landscape", "description": "While tourism operators invest in some digital marketing, most Dover trades, professional services, and retailers do zero paid digital advertising. They rely entirely on word of mouth and organic search in a market where competitors in neighbouring towns are actively advertising to Dover residents."}, {"title": "No remarketing strategy for Dover website visitors who leave", "description": "A tourist visits your Dover restaurant website while planning a White Cliffs trip but does not book immediately. A resident checks your plumbing prices but gets distracted. Without remarketing campaigns that follow these visitors across the web and social media, you lose them permanently to the next search result."}]',
  '[{"title": "Seasonal tourism campaigns timed to Dover''s visitor calendar", "description": "We launch tourist-targeted campaigns before peak booking windows, not during them. Google Ads and social campaigns promoting your Dover business reach visitors while they are planning their White Cliffs walk, Castle visit, or port crossing. By the time they arrive, they have already chosen your business."}, {"title": "Year-round local campaigns for Dover''s resident market", "description": "Targeted Google Ads and social media campaigns reach Dover district residents searching for everyday services. Postcode-level targeting ensures your budget reaches the right audience across the town and surrounding areas. Campaign messaging reflects local knowledge, building trust that generic national advertisers cannot match."}, {"title": "Remarketing campaigns converting Dover browsers into customers", "description": "Visitors who browse your Dover website without converting see targeted follow-up ads across Google, Facebook, and Instagram. A tourist who checked your restaurant menu sees a booking prompt on their Facebook feed that evening. A resident who browsed your services sees a reminder ad the following day."}]',
  '[{"question": "How much should a Dover business spend on digital marketing?", "answer": "It depends on your audience and goals. A Dover restaurant targeting tourist traffic might invest heavily during spring and summer. A local trade business needs a steady year-round budget. We typically recommend starting with a focused budget of a few hundred pounds monthly, scaling based on measurable return on investment."}, {"question": "Can you run campaigns targeting tourists before they arrive in Dover?", "answer": "Absolutely. We target people searching for Dover Castle, White Cliffs walks, ferry crossings, and Dover accommodation in the weeks before peak tourist periods. By the time they arrive, they have already seen your business and formed a positive impression. This pre-arrival advertising is highly effective."}, {"question": "Which platforms work best for Dover digital marketing?", "answer": "Google Ads captures high-intent searches from both residents and tourists. Facebook and Instagram reach tourists during trip planning and residents during leisure browsing. For B2B and logistics, LinkedIn campaigns target commercial decision-makers. We recommend the platform mix that matches your specific audience."}, {"question": "How do I know if my Dover marketing campaigns are working?", "answer": "We provide monthly reporting showing exactly how many enquiries, bookings, or sales each campaign generated. No vanity metrics. You see which Dover campaigns drove real business outcomes, what each lead cost, and where to increase or reduce spend for maximum return on investment."}]',
  'lead-gen'
)
ON CONFLICT (service_slug, town_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  local_context = EXCLUDED.local_context,
  competition_landscape = EXCLUDED.competition_landscape,
  success_approach = EXCLUDED.success_approach,
  local_stats = EXCLUDED.local_stats,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs,
  layout_variant = EXCLUDED.layout_variant;

-- 8. Dover × Workwear & Print
INSERT INTO public.local_content (service_slug, town_slug, intro_paragraph, local_context, competition_landscape, success_approach, local_stats, pain_points, solutions, faqs, layout_variant)
VALUES (
  'workwear-print',
  'dover',
  'In Dover, your physical branding carries weight that extends beyond the usual small-town visibility. A branded polo shirt worn by a hospitality worker near Dover Castle is seen by hundreds of tourists daily. A liveried van parked at the Port of Dover is visible to thousands of passengers. Printed menus and signage around Market Square are photographed and shared on social media by visitors from around the world. Dover''s unique mix of local community, tourist footfall, and commercial port traffic means your printed materials and branded workwear reach audiences far beyond the town itself. We produce high-quality workwear, signage, print materials, and branded merchandise for Dover businesses that look professional in every context, from a White Cliffs tourist photograph to a port logistics client meeting.',
  'Dover''s physical branding environment is shaped by its three audiences. Tourist areas around the Castle, White Cliffs, and Market Square demand presentation-quality signage, menus, and branded materials that may be photographed and shared internationally. The port and logistics sector requires durable, professional workwear and fleet branding that projects operational credibility. Residential service businesses need van livery and workwear visible across the wider district from the town centre to Deal and the A2 corridor villages.',
  'Print and workwear quality in Dover varies significantly. Tourism operators near the Castle generally maintain reasonable presentation standards. However, many trades and service businesses operate with unbranded or poorly branded workwear and vehicles. The port logistics sector shows mixed standards, with some firms investing in professional fleet livery while others run plain white vans. Quality print materials are relatively uncommon among independent businesses around Market Square.',
  'We approach Dover workwear and print with an understanding of the visibility multiplier this town provides. Every piece of branded material has the potential to reach far beyond its immediate context. We source durable, professional workwear suited to Dover''s maritime climate, produce print materials that withstand the seafront conditions, and design everything to look as good in a tourist photograph as it does in a client presentation. Quality and durability are non-negotiable.',
  '{"population": 35000, "district_population": 117000, "business_districts": ["Market Square", "Port of Dover", "High Street", "De Bradelei Wharf"], "key_fact": "Tourist photography and port visibility give Dover branding an outsized audience reach"}',
  '[{"title": "Unbranded staff visible to hundreds of Dover tourists daily", "description": "Tourism and hospitality workers in Dover interact with hundreds of visitors daily near the Castle, White Cliffs, and Market Square. Staff in plain clothing or poorly branded uniforms miss the opportunity to reinforce your business identity with every tourist interaction. Your competitors with professional workwear look more established and trustworthy."}, {"title": "Port-area vehicles missing commercial branding opportunity", "description": "Vehicles operating around the Port of Dover are seen by thousands of passengers, drivers, and logistics professionals daily. A plain white van parked at the terminal is invisible. A professionally branded vehicle with clear contact details and service information generates enquiries passively from the enormous captive audience the port provides."}, {"title": "Print materials deteriorating in Dover''s maritime conditions", "description": "Dover''s coastal location means outdoor signage, A-boards, and printed materials face salt air, wind, and moisture that destroy cheap materials quickly. Faded, peeling, or damaged print materials around Market Square and the seafront actively damage your business image in front of tourist visitors."}]',
  '[{"title": "Tourism-grade workwear for Dover hospitality and service staff", "description": "We supply professionally branded workwear designed for Dover''s customer-facing environments. Embroidered polo shirts, branded aprons, and printed jackets that look sharp under the scrutiny of tourist visitors. Every piece reinforces your brand identity during the hundreds of daily customer interactions near the Castle and White Cliffs."}, {"title": "Durable fleet branding for Dover''s port and logistics sector", "description": "We design and produce vehicle livery that projects professional capability to the commercial audiences around the Port of Dover. Durable, weather-resistant wraps and decals that maintain their appearance in Dover''s maritime conditions. Your fleet becomes a mobile advertisement visible to thousands of port users daily."}, {"title": "Maritime-durable print materials for Dover''s seafront businesses", "description": "Signage, menus, A-boards, and promotional materials produced with materials specifically chosen to withstand Dover''s coastal conditions. UV-resistant inks, waterproof substrates, and durable finishes ensure your printed materials look professional through every season of salt air and channel weather."}]',
  '[{"question": "What workwear is best for Dover hospitality staff?", "answer": "For tourist-facing hospitality businesses near the Castle and Market Square, we recommend embroidered polo shirts and branded aprons as the foundation. These are durable enough for daily use while looking professional in the customer interactions that define your reputation. We source from suppliers offering comfort in both indoor and outdoor Dover environments."}, {"question": "Can you brand vehicles that operate from the Port of Dover?", "answer": "Yes. We design and produce vehicle livery for everything from single vans to entire commercial fleets operating from the port. We work with professional wrap installers and use materials rated for the maritime conditions Dover vehicles encounter. Full wraps, partial wraps, and vinyl decals are all available."}, {"question": "How do you ensure print materials survive Dover''s coastal weather?", "answer": "We specify materials designed for outdoor coastal use. UV-resistant inks prevent fading, waterproof substrates resist moisture, and durable lamination protects against salt air. For A-boards and outdoor signage near Market Square and the seafront, we use aluminium composite and marine-grade materials."}, {"question": "What is the typical turnaround for workwear orders?", "answer": "Standard embroidered workwear orders typically take seven to ten working days from approved artwork. Printed garments can be faster at five to seven days. Rush orders are available for an additional charge. We hold stock of popular base garments to minimise delays for repeat Dover business orders."}]',
  'operational'
)
ON CONFLICT (service_slug, town_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  local_context = EXCLUDED.local_context,
  competition_landscape = EXCLUDED.competition_landscape,
  success_approach = EXCLUDED.success_approach,
  local_stats = EXCLUDED.local_stats,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs,
  layout_variant = EXCLUDED.layout_variant;

-- 9. Dover × AI Chatbots
INSERT INTO public.local_content (service_slug, town_slug, intro_paragraph, local_context, competition_landscape, success_approach, local_stats, pain_points, solutions, faqs, layout_variant)
VALUES (
  'ai-chatbots',
  'dover',
  'Dover businesses face an enquiry pattern that human staff simply cannot cover efficiently. Tourists planning White Cliffs walks ask the same questions about opening times, parking, and directions repeatedly. Guest houses receive identical booking enquiries at all hours from travellers across different time zones planning Channel crossings. Port logistics firms field routine availability and pricing questions that interrupt operational staff from their core work. A tradesperson driving between jobs across the Dover district misses calls from prospects who need immediate answers. AI chatbots solve all of these problems simultaneously. We build intelligent conversational assistants for Dover businesses that handle routine enquiries instantly, twenty-four hours a day, in multiple languages where needed, freeing your team to focus on the work that actually requires human attention and judgement.',
  'Dover''s enquiry patterns are shaped by its tourist and port economy. Hospitality businesses receive waves of identical questions about availability, location, parking near the Castle, and crossing-related timing. The port logistics sector handles repetitive quote requests and availability checks. Trades and service businesses across the district miss calls during working hours. The international dimension of Dover''s visitor base means enquiries arrive in multiple languages and across all time zones, creating a genuine twenty-four-hour demand that no small team can staff manually.',
  'AI chatbot adoption among Dover businesses is virtually non-existent. A handful of larger tourism operators use basic FAQ bots, but the technology has not penetrated the wider business community. This creates a significant first-mover advantage for early adopters. The businesses that implement intelligent chatbots now will capture enquiries that competitors are losing to phone queues, slow email responses, and closed-hours voicemails.',
  'We build Dover chatbots trained on your specific business knowledge and customer patterns. A guest house chatbot knows your room availability, proximity to the Castle and Cliffs, parking options, and ferry connection timing. A logistics chatbot handles quote requests and availability checks. A trades chatbot qualifies enquiries and books callbacks. Every chatbot is trained to recognise when a question requires human intervention and escalates seamlessly.',
  '{"population": 35000, "district_population": 117000, "business_districts": ["Market Square", "Port of Dover", "High Street", "De Bradelei Wharf"], "key_fact": "International visitors and port traffic create genuine 24-hour enquiry demand"}',
  '[{"title": "Repetitive tourist questions consuming Dover hospitality staff time", "description": "Dover hospitality businesses answer the same questions hundreds of times each season. Where is the nearest parking for the White Cliffs? How far is Dover Castle? What time does the last ferry leave? Each question takes staff time away from serving guests. Multiplied across peak season, this repetition consumes enormous operational capacity."}, {"title": "International enquiries arriving outside business hours", "description": "Travellers from mainland Europe and beyond plan Dover visits and Channel crossings from different time zones. Enquiries arrive at midnight, three in the morning, and during weekends. A guest house that cannot respond until nine the next morning loses the booking to a competitor with round-the-clock response capability."}, {"title": "Missed calls costing Dover trades businesses revenue", "description": "A tradesperson working at a property near Connaught Park cannot answer the phone when a new prospect calls from the town centre. The prospect calls the next number on their list. Without an intelligent system that can handle the initial enquiry, qualify the lead, and schedule a callback, Dover trades lose revenue every working day."}]',
  '[{"title": "Multilingual chatbots for Dover''s international visitor market", "description": "We build AI chatbots that handle enquiries in English, French, German, and other languages relevant to Dover''s international visitor base. A French tourist planning a post-crossing dinner can interact with your restaurant chatbot in their own language, receiving instant recommendations, availability, and booking confirmation."}, {"title": "Knowledge-trained assistants for Dover hospitality businesses", "description": "Your chatbot is trained on everything a guest needs to know: room details, proximity to the Castle and White Cliffs, parking options, ferry timing, restaurant recommendations, and local attractions. It handles the repetitive questions that consume your staff''s time, providing instant accurate answers twenty-four hours a day."}, {"title": "Lead-qualifying chatbots for Dover trades and services", "description": "We build chatbots that do more than answer questions. They qualify enquiries by asking about job scope, location, timing, and budget. A qualified lead with full details is delivered to your phone or email, ready for a precise quote. Unqualified tyre-kickers are filtered out before they consume your time."}]',
  '[{"question": "Can a chatbot really handle tourist questions about Dover?", "answer": "Yes. We train your chatbot with detailed knowledge about your business, local attractions, parking, directions, ferry connections, and everything tourists commonly ask. The chatbot provides instant, accurate answers that match what your best staff member would say. When a question falls outside its knowledge, it escalates to your team."}, {"question": "Will a chatbot work for my Dover logistics business?", "answer": "Absolutely. We build chatbots for logistics firms that handle routine quote requests, availability checks, and service enquiries. The chatbot collects structured information that your operations team can action immediately, eliminating the back-and-forth that delays quoting and frustrates potential clients."}, {"question": "Can the chatbot handle enquiries in French and other languages?", "answer": "Yes. Given Dover''s proximity to France and the volume of international visitors through the port, multilingual capability is a core feature. We configure chatbots to detect visitor language preference and respond accordingly, covering French, German, Dutch, and other languages relevant to your customer base."}, {"question": "What happens when the chatbot cannot answer a question?", "answer": "The chatbot recognises when a question exceeds its training and smoothly hands over to your team. It collects the visitor''s contact details and question, then notifies you via email or text. The customer receives a message confirming a team member will follow up, ensuring no enquiry is lost."}]',
  'authority'
)
ON CONFLICT (service_slug, town_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  local_context = EXCLUDED.local_context,
  competition_landscape = EXCLUDED.competition_landscape,
  success_approach = EXCLUDED.success_approach,
  local_stats = EXCLUDED.local_stats,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs,
  layout_variant = EXCLUDED.layout_variant;

-- 10. Dover × AI Content
INSERT INTO public.local_content (service_slug, town_slug, intro_paragraph, local_context, competition_landscape, success_approach, local_stats, pain_points, solutions, faqs, layout_variant)
VALUES (
  'ai-content',
  'dover',
  'Content creation is a particular challenge for Dover businesses because generic content fails completely in a market defined by specific local context. A restaurant near Market Square needs content that references the White Cliffs walk, Castle visit parking, and ferry crossing timing, not generic hospitality copy that could apply anywhere. A logistics firm needs content demonstrating expertise in port operations and customs procedures, not vague business language. A guest house needs seasonal content aligned with Dover''s tourist calendar, not evergreen filler. AI-powered content generation, trained on Dover''s specific geography, demographics, and business environment, produces the locally relevant, search-optimised content these businesses need at a fraction of the time and cost of traditional copywriting. We deploy AI content systems that generate genuinely Dover-specific material for your website, social media, and marketing.',
  'Dover''s content landscape requires deep local knowledge. Tourism content must reference specific attractions, walking routes, parking locations, and seasonal events accurately. Port and logistics content demands familiarity with customs terminology, freight processes, and commercial shipping language. Local service content should reference the Dover district geography from Market Square to Deal, the A2 corridor, and the Western Heights. Seasonal variations are dramatic, with tourism content needs peaking in spring and summer while residential service content maintains year-round relevance.',
  'Content quality among Dover businesses is poor overall. Tourism operators produce some location-specific content, but most is superficial and SEO-weak. Trades and professional services use generic copy with Dover mentioned once or twice. Port logistics firms have minimal content beyond basic service descriptions. Very few Dover businesses produce regular blog posts, guides, or social content. The opportunity for AI-generated, locally authentic content to differentiate businesses here is substantial.',
  'We deploy AI content systems trained specifically on Dover''s geography, demographics, and business environment. The AI generates blog posts, service pages, social media content, and marketing copy that references real Dover locations, attractions, and local context accurately. Every piece is reviewed for factual accuracy and local authenticity before publication. The result is a consistent flow of genuinely Dover-specific content at a fraction of traditional copywriting costs.',
  '{"population": 35000, "district_population": 117000, "business_districts": ["Market Square", "Port of Dover", "High Street", "De Bradelei Wharf"], "key_fact": "Tourist, logistics, and residential audiences each require distinct content approaches"}',
  '[{"title": "Generic content failing Dover''s location-specific audience", "description": "A Dover restaurant using generic hospitality copy misses the opportunity to capture tourists searching for dining near the Castle or post-crossing meals near the port. Without content referencing real Dover locations, walking routes, and visitor experiences, your business is invisible for the specific searches tourists actually perform."}, {"title": "No capacity to produce regular Dover-specific content", "description": "Dover business owners are too busy running their operations to write weekly blog posts about local topics. The result is websites with static content that Google progressively devalues. Competitors who publish regular, locally relevant content gain search visibility while inactive sites slip further down the rankings."}, {"title": "Port and logistics firms lacking specialist content", "description": "The commercial shipping and logistics sector around the Port of Dover has complex, specialist content needs. Generic business content does not resonate with freight managers and shipping coordinators who need to see demonstrated expertise in customs procedures, port operations, and cross-channel logistics."}]',
  '[{"title": "AI-generated tourism content for Dover hospitality", "description": "We deploy content systems that produce visitor-focused articles, guides, and social posts referencing real Dover attractions, walking routes, seasonal events, and practical information. Your restaurant gets content about dining after a White Cliffs walk. Your guest house gets seasonal guides to Dover attractions. All factually accurate and search-optimised."}, {"title": "Consistent local content production without your time", "description": "Our AI content systems produce a steady stream of Dover-specific blog posts, social media content, and marketing copy. Seasonal topics, local event coverage, and evergreen service content keep your website fresh and your search visibility growing. You review and approve; the system does the heavy lifting."}, {"title": "Specialist content for Dover''s commercial and logistics sector", "description": "We train AI systems on logistics terminology, customs procedures, and port operations to generate content that demonstrates genuine expertise. White papers, case studies, service descriptions, and industry articles position your Dover logistics business as an authoritative voice in the cross-channel freight sector."}]',
  '[{"question": "Will AI content sound generic or actually mention Dover?", "answer": "Our content systems are trained specifically on Dover''s geography, attractions, and business environment. Generated content references the White Cliffs, Dover Castle, Market Square, the port, and local area details naturally. Every piece reads as if written by someone who genuinely knows Dover, because the AI has been trained on comprehensive local knowledge."}, {"question": "How do you ensure AI content is factually accurate about Dover?", "answer": "Every piece of AI-generated content goes through a review process checking local facts, attraction details, and geographic references. We maintain an up-to-date knowledge base of Dover information including seasonal events, business developments, and infrastructure changes. Nothing publishes without accuracy verification."}, {"question": "Can AI produce content about port logistics and customs?", "answer": "Yes. We train content systems on specialist terminology and current procedures relevant to the Port of Dover. The generated content demonstrates genuine expertise in freight forwarding, customs documentation, and cross-channel logistics, positioned to resonate with commercial decision-makers in the transport sector."}, {"question": "How much content can the AI produce monthly?", "answer": "Output scales to your needs. Most Dover clients start with four to eight blog posts and daily social media content monthly. Tourism businesses often increase output before peak season. The per-piece cost is a fraction of traditional copywriting, making it practical to publish the volume of content that search engines reward."}]',
  'authority'
)
ON CONFLICT (service_slug, town_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  local_context = EXCLUDED.local_context,
  competition_landscape = EXCLUDED.competition_landscape,
  success_approach = EXCLUDED.success_approach,
  local_stats = EXCLUDED.local_stats,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs,
  layout_variant = EXCLUDED.layout_variant;

-- 11. Dover × AI Automation
INSERT INTO public.local_content (service_slug, town_slug, intro_paragraph, local_context, competition_landscape, success_approach, local_stats, pain_points, solutions, faqs, layout_variant)
VALUES (
  'ai-automation',
  'dover',
  'The convergence of artificial intelligence and business automation creates opportunities for Dover businesses that would have been science fiction five years ago. A guest house near the White Cliffs can use AI to automatically adjust pricing based on ferry booking volumes and Castle event schedules. A logistics firm at the port can deploy AI to predict demand patterns, optimise routing, and generate customs documentation from booking data. A tradesperson covering the Dover district can use AI to automatically prioritise leads, generate quotes from site photos, and schedule jobs optimally across their geographic coverage area. These are not future possibilities; they are deployable now. We build AI-powered automation systems for Dover businesses that combine the efficiency of traditional automation with the intelligence of machine learning, creating workflows that improve themselves over time.',
  'Dover''s business environment presents specific AI automation opportunities shaped by the port, tourism, and geographic factors. The port generates enormous data volumes around crossing schedules, freight movements, and passenger flows that AI can analyse for business intelligence. Tourism seasonal patterns are predictable enough for AI pricing and staffing optimisation. The geographic spread of the Dover district from the town centre to Deal creates routing and scheduling optimisation opportunities for mobile service businesses. The international dimension adds translation and multi-currency processing needs.',
  'AI automation adoption in Dover is virtually zero outside of the largest port operators. This places every small and medium Dover business at an identical starting point, with no entrenched AI advantage among competitors. However, this will not last. National trends show AI automation adoption accelerating rapidly. The Dover businesses that implement AI automation now will establish operational advantages that competitors will find increasingly expensive to match.',
  'We build Dover AI automation by identifying the highest-impact opportunities first. For tourism businesses, dynamic pricing and demand forecasting based on Dover-specific signals like ferry bookings and Castle event schedules. For logistics, AI-powered document processing and route optimisation. For trades, intelligent lead scoring and automated quoting. Every system is designed to learn from your specific Dover business data, becoming more accurate and valuable over time.',
  '{"population": 35000, "district_population": 117000, "business_districts": ["Port of Dover", "Market Square", "High Street", "De Bradelei Wharf"], "key_fact": "Port data, tourism patterns, and geographic spread create ideal conditions for AI automation"}',
  '[{"title": "Manual pricing losing revenue for Dover tourism businesses", "description": "Dover guest houses and hospitality businesses set prices manually, often failing to respond to demand fluctuations driven by ferry schedules, Castle events, and seasonal patterns. A room that should be priced higher during a busy crossing weekend sits at the standard rate. Revenue is left on the table every week because humans cannot process these demand signals fast enough."}, {"title": "Logistics operations not leveraging available port data", "description": "The Port of Dover generates enormous data about crossing schedules, freight volumes, and traffic patterns. Logistics firms operating nearby make operational decisions based on experience and gut feeling rather than data analysis. Route planning, staffing, and capacity allocation happen manually when AI could optimise all three simultaneously."}, {"title": "Dover trades wasting time on unqualified leads", "description": "Tradespeople covering the Dover district spend time quoting jobs that never convert, visiting properties that do not match their service profile, and scheduling inefficiently across a wide geographic area. Without intelligent systems to score leads, estimate jobs, and optimise routes, productivity suffers daily."}]',
  '[{"title": "AI-powered dynamic pricing for Dover hospitality", "description": "We build pricing systems that analyse ferry booking volumes, Castle event schedules, weather forecasts, and historical demand patterns to recommend optimal pricing automatically. Your Dover guest house or restaurant adjusts prices in real time based on actual demand signals, capturing revenue that manual pricing leaves behind."}, {"title": "Intelligent document processing for port logistics", "description": "AI reads booking confirmations, extracts shipment details, and pre-populates customs documentation automatically. What previously required manual data entry from your Dover logistics team is handled in seconds with higher accuracy. The system learns your specific document formats and improves with every transaction processed."}, {"title": "AI lead scoring and route optimisation for Dover trades", "description": "Our AI systems analyse incoming enquiries to predict conversion likelihood based on job type, location, budget signals, and historical patterns. High-value leads get prioritised. Job scheduling is optimised to minimise travel time across the Dover district. The result is more revenue from fewer wasted hours."}]',
  '[{"question": "Is AI automation realistic for a small Dover business?", "answer": "Yes. Modern AI tools have made intelligent automation accessible at price points that work for small businesses. A Dover guest house can implement AI pricing for less than the revenue it recovers in the first month. We focus on high-impact, practical applications that deliver measurable returns quickly, not experimental technology."}, {"question": "How does AI pricing work for Dover hospitality businesses?", "answer": "The system monitors demand signals including ferry booking volumes, Castle event schedules, local accommodation availability, weather forecasts, and historical booking patterns. It recommends optimal pricing for each date, adjusting automatically as conditions change. You set minimum and maximum bounds, and the AI optimises within those parameters."}, {"question": "Can AI really help with customs documentation at the port?", "answer": "Absolutely. AI document processing extracts information from booking confirmations, shipping manifests, and client communications to pre-populate customs forms and logistics documentation. It handles the repetitive data entry that currently consumes your operations staff time, with accuracy that improves with every document processed."}, {"question": "How long does it take to see results from AI automation?", "answer": "Simple AI automations like lead scoring and document processing deliver results within the first week of deployment. More complex systems like dynamic pricing and demand forecasting improve over two to four weeks as they learn from your specific Dover business data. We prioritise quick-win implementations first."}]',
  'authority'
)
ON CONFLICT (service_slug, town_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  local_context = EXCLUDED.local_context,
  competition_landscape = EXCLUDED.competition_landscape,
  success_approach = EXCLUDED.success_approach,
  local_stats = EXCLUDED.local_stats,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs,
  layout_variant = EXCLUDED.layout_variant;
