-- ============================================================
-- seed-local-content-gravesend-other.sql
-- Local content for Gravesend across 4 remaining services:
-- branding, social-media-setup, digital-marketing, workwear-print.
-- Extracted verbatim from seed-local-content-gravesend.sql (sections 5-8),
-- which contained these rows but appears never to have been run against
-- production. Gravesend currently has rows for only 4 of 11 services live
-- (web-design, seo, lead-capture, business-automation). This file plus
-- seed-local-content-gravesend-ai.sql brings Gravesend up to all 11.
--
-- Safe to re-run: uses ON CONFLICT (service_slug, town_slug) DO UPDATE.
--
-- After running, verify with:
--   SELECT service_slug, length(intro_paragraph) AS chars
--   FROM local_content
--   WHERE town_slug = 'gravesend'
--   ORDER BY service_slug;
-- Expected: 11 rows total once both AI and Other seed files have run.
-- ============================================================

-- 5. Gravesend × Branding
INSERT INTO public.local_content (service_slug, town_slug, intro_paragraph, local_context, competition_landscape, success_approach, local_stats, pain_points, solutions, faqs, layout_variant)
VALUES (
  'branding',
  'gravesend',
  'Gravesend''s identity is evolving. The Thames riverside, historic pier, and Pocahontas heritage sit alongside a vibrant multicultural community, modern commuter culture, and a regenerating town centre. This is a town where a Sikh temple stands as one of the largest outside India, where Borough Market brings traditional and international flavours together, and where an Ebbsfleet commuter in a contemporary kitchen renovation expects the same brand standards as a London firm. Businesses that succeed in Gravesend must communicate credibility across these diverse contexts simultaneously. A one-dimensional brand identity cannot serve this multifaceted market. We create brand systems for Gravesend businesses that project professionalism, cultural awareness, and local authenticity, building the visual trust that converts Gravesend''s diverse population into loyal customers regardless of their background or expectations.',
  'Gravesend''s visual landscape blends Thames-side heritage with multicultural vibrancy. The riverside around Gravesend Pier and Gordon Promenade has a historic, maritime character. The High Street and Borough Market reflect the town''s diverse community through varied shopfronts and signage. Windmill Hill provides a green, residential backdrop. The Woodville theatre anchors the cultural offering. New development around Ebbsfleet brings contemporary architectural standards. The overall aesthetic is eclectic and evolving, requiring brands that feel authentic rather than borrowed from another context.',
  'Brand quality in Gravesend varies dramatically. The commuter-oriented professional services sector tends toward adequate branding. The diverse high street features both distinctive cultural businesses and generic-looking enterprises. Trades and residential services follow the typical low-quality pattern seen across Kent. The regenerating town centre is raising visual expectations. Businesses that invest in professional branding stand out significantly in this transitional market.',
  'Our branding approach for Gravesend embraces the town''s diversity rather than flattening it. We create brands that feel at home in this multicultural, riverside community while projecting the professionalism that the commuter demographic expects. A tradesperson gets bold, trustworthy branding visible on residential streets across the borough. A hospitality business near the riverside gets an identity reflecting the area''s evolving character. Every brand we build for Gravesend reflects the town as it is, not a sanitised version.',
  '{"population": 75000, "business_districts": ["Gravesend High Street", "Borough Market", "Riverside", "Ebbsfleet area"], "key_fact": "Culturally diverse community requiring brands that project professionalism across multiple audience contexts"}',
  '[{"title": "Brands failing to communicate across Gravesend''s diverse audiences", "description": "A Gravesend business with branding designed for a single demographic misses the town''s broader market. The commuter expects modern polish. The diverse local community values cultural authenticity. The riverside visitor looks for heritage character. One-dimensional branding serves one audience and alienates the others."}, {"title": "Commuter clients comparing Gravesend businesses against London standards", "description": "Ebbsfleet commuters interact with polished London brands daily. When they choose a local Gravesend business, they unconsciously compare the brand presentation against what they see in the capital. A tradesperson with a hand-painted van logo does not meet the standard this influential demographic expects."}, {"title": "Town centre regeneration raising brand expectations for all businesses", "description": "As Gravesend''s town centre modernises around Borough Market and the riverside, the visual standard is rising. New businesses arrive with contemporary branding. Established businesses with dated logos and inconsistent colours look increasingly out of place. The regeneration is creating a brand quality divide that widens monthly."}]',
  '[{"title": "Multi-audience brand identities for diverse Gravesend", "description": "We create brand systems that communicate effectively across Gravesend''s varied demographics. Professional enough for commuter clients, authentic enough for the diverse local community, and characterful enough for the riverside setting. Versatile identities that flex across contexts without losing consistency or credibility."}, {"title": "Contemporary branding matching Gravesend''s regeneration standards", "description": "As the town centre transforms, your brand should reflect the forward momentum. We design identities that feel current and confident, positioning your Gravesend business as part of the town''s positive evolution. Modern typography, sophisticated colour palettes, and clean design that belongs in a regenerating high street."}, {"title": "Complete brand systems for consistent Gravesend visibility", "description": "Logo, colour system, typography, vehicle livery, workwear, signage, social media templates, and brand guidelines. Every element works together to build recognition across Gravesend''s diverse touchpoints. A customer who sees your van in Northfleet recognises the same brand on the Borough Market high street and on Instagram."}]',
  '[{"question": "How do you create a brand that works for Gravesend''s diverse community?", "answer": "We research your specific customer demographics and design brand elements that communicate universally positive qualities: professionalism, reliability, and quality. Where culturally specific elements would strengthen your positioning with particular Gravesend communities, we incorporate them thoughtfully. The result is an inclusive brand that resonates broadly."}, {"question": "Should my Gravesend brand reference the riverside or Thames heritage?", "answer": "It depends on your business positioning. We avoid generic river imagery, but for businesses near the riverside or Borough Market, subtle references to the waterside setting can strengthen local identity. For trades and services covering the wider borough, broader Gravesend identity cues are more effective."}, {"question": "How long does a full brand identity take?", "answer": "A complete brand identity including logo, colour system, typography, and brand guidelines takes three to four weeks. Vehicle livery, workwear specifications, and additional applications add one to two weeks. We begin with a strategy session exploring your position in Gravesend''s evolving market."}, {"question": "Can you rebrand my business without losing existing Gravesend customers?", "answer": "Yes. Brand evolution preserves the elements your customers recognise while upgrading overall quality. We audit your current brand equity, identify what to retain, and build a refreshed identity that maintains continuity. The result feels like a natural maturation of your Gravesend business, not an unfamiliar replacement."}]',
  'trust'
)
ON CONFLICT (service_slug, town_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  local_context = EXCLUDED.local_context,
  competition_landscape = EXCLUDED.competition_landscape,
  success_approach = EXCLUDED.success_approach,
  local_stats = EXCLUDED.local_stats,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs,
  layout_variant = EXCLUDED.layout_variant;

-- 6. Gravesend × Social Media Setup
INSERT INTO public.local_content (service_slug, town_slug, intro_paragraph, local_context, competition_landscape, success_approach, local_stats, pain_points, solutions, faqs, layout_variant)
VALUES (
  'social-media-setup',
  'gravesend',
  'Gravesend''s social media landscape reflects the town''s diversity in ways that most businesses fail to leverage. Multiple community groups serve different demographics, from general Gravesend discussion forums to community-specific groups. Instagram captures the riverside''s visual appeal and the Borough Market food scene. Google reviews influence the commuter audience that relies on search to find local services. WhatsApp and other messaging platforms are primary communication channels for significant portions of the community. Yet most Gravesend businesses either have no social media presence or maintain a single, inactive Facebook page. In a town where different communities use different platforms and different engagement styles, a one-size-fits-all approach leaves most of your potential audience unreached. We set up and optimise social media profiles for Gravesend businesses across the platforms that actually reach your target customers.',
  'Gravesend''s social media ecosystem is more fragmented than most Kent towns due to its cultural diversity. Facebook groups serve the general community and specific demographic groups. Instagram is growing around the riverside, Borough Market food scene, and lifestyle content. Google reviews are particularly influential for the commuter audience. Community-specific messaging platforms and social networks serve various cultural communities. The Woodville theatre and local events generate social content that local businesses could leverage. Heritage interest around Pocahontas and the pier creates shareable content opportunities.',
  'Social media presence among Gravesend businesses is underdeveloped. The diversity of the community means no single platform dominates, and businesses that focus only on Facebook miss significant audience segments. Few businesses have adapted their social media approach to reflect Gravesend''s multicultural market. The opportunity for businesses willing to meet their audiences on the right platforms with culturally appropriate content is substantial.',
  'We set up Gravesend social media profiles based on where your specific customers spend their time. Residential services get Facebook and Google profiles optimised for the community recommendation culture. Hospitality businesses near Borough Market and the riverside get Instagram-first strategies showcasing food and location. Professional services targeting commuters get LinkedIn and Google Business Profile optimisation. Community-specific platforms are incorporated where they serve your target audience.',
  '{"population": 75000, "business_districts": ["Gravesend High Street", "Borough Market", "Riverside", "Ebbsfleet area"], "key_fact": "Culturally diverse social media landscape requiring multi-platform, community-aware approach"}',
  '[{"title": "Single Facebook page missing Gravesend''s diverse social audiences", "description": "A Gravesend business with only a Facebook page reaches one portion of the community. Significant segments of the diverse population use different platforms, different groups, and different communication styles. A single-platform approach leaves large portions of the Gravesend market completely unreached."}, {"title": "No Google review strategy for Gravesend''s commuter audience", "description": "Ebbsfleet commuters check Google reviews before choosing local services. They compare star ratings and review counts across options. Gravesend businesses without a systematic review generation strategy accumulate too few reviews to compete, losing the commuter audience to businesses that have prioritised their review profile."}, {"title": "Borough Market food scene not leveraged on Instagram", "description": "Gravesend''s Borough Market and riverside food scene generates Instagram-worthy content naturally. But most local food businesses either have no Instagram presence or post sporadically with poor-quality images. The visual platform that could drive significant footfall remains untapped by the businesses that would benefit most."}]',
  '[{"title": "Multi-platform profiles reaching Gravesend''s diverse community", "description": "We set up and optimise profiles on the platforms that reach your specific Gravesend audience. Facebook for community engagement, Instagram for visual appeal, Google for commuter trust, and community-specific platforms where relevant. Each profile is branded consistently but content is tailored to the platform audience."}, {"title": "Review generation system for Gravesend''s trust-driven market", "description": "We implement systematic Google and Facebook review generation that builds your review profile consistently. Automated post-service review requests, response templates for all feedback, and monitoring across platforms. For the commuter audience, a strong review profile is the primary trust signal that determines which business gets the call."}, {"title": "Instagram strategy for Gravesend hospitality and riverside businesses", "description": "We set up and optimise Instagram profiles with professional imagery showcasing your food, location, and atmosphere. Hashtag strategy targets Gravesend food explorers, riverside visitors, and the growing Instagram community documenting the town''s regeneration. Content templates make posting quick and consistent."}]',
  '[{"question": "Which social media platforms matter for my Gravesend business?", "answer": "It depends on your audience. Trades and services need strong Facebook and Google profiles. Hospitality and food businesses benefit from Instagram. Professional services targeting commuters need Google and LinkedIn. We audit your customer demographics and set up the platforms that will actually reach your Gravesend audience."}, {"question": "How do I reach Gravesend''s diverse community on social media?", "answer": "We research where different segments of Gravesend''s community engage online and tailor your presence accordingly. This may include multiple Facebook community groups, culturally appropriate content, and platform choices that match your target audience''s preferences. One-size-fits-all does not work in Gravesend''s diverse market."}, {"question": "How important are Google reviews for Gravesend businesses?", "answer": "Extremely, particularly for the commuter audience. Ebbsfleet commuters use Google as their primary tool for evaluating local services. A business with twenty positive reviews wins over one with three, regardless of actual quality. We set up systematic review generation so your satisfied Gravesend customers contribute to your online reputation."}, {"question": "Can social media drive footfall to my Borough Market business?", "answer": "Yes. Instagram in particular drives food and experience-seeking visitors to Gravesend. Professional food photography, consistent posting, and strategic hashtag use put your business in front of people actively seeking dining and market experiences. We have seen Borough Market area businesses increase footfall measurably through social media presence."}]',
  'trust'
)
ON CONFLICT (service_slug, town_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  local_context = EXCLUDED.local_context,
  competition_landscape = EXCLUDED.competition_landscape,
  success_approach = EXCLUDED.success_approach,
  local_stats = EXCLUDED.local_stats,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs,
  layout_variant = EXCLUDED.layout_variant;

-- 7. Gravesend × Digital Marketing
INSERT INTO public.local_content (service_slug, town_slug, intro_paragraph, local_context, competition_landscape, success_approach, local_stats, pain_points, solutions, faqs, layout_variant)
VALUES (
  'digital-marketing',
  'gravesend',
  'Gravesend sits at a marketing crossroads. With Ebbsfleet International connecting the town to London in seventeen minutes and a diverse population of seventy-five thousand, the local market is both larger and more complex than most Kent towns. Digital marketing campaigns here must navigate multiple audience segments: affluent commuters with London expectations, established local families, the diverse cultural community, and the growing number of new residents attracted by the town''s regeneration. A single campaign message cannot serve all of these audiences effectively. Yet most Gravesend businesses either do no digital marketing or run untargeted campaigns that waste budget on irrelevant audiences. We build segmented digital marketing campaigns that reach each of Gravesend''s distinct audience groups with messaging that resonates, on the platforms they actually use, at the times they are most receptive.',
  'Gravesend''s digital marketing landscape offers distinct audience segments. The Ebbsfleet commuter demographic is reachable through timed campaigns during travel hours and through LinkedIn and Google. The diverse community is accessible through culturally targeted social advertising and community-specific platforms. Borough Market and riverside visitors respond to food and lifestyle content across Instagram and Facebook. New residents arriving in the area are reachable through location-based advertising and targeted social campaigns. Each segment has different media habits, different responsiveness, and different messaging triggers.',
  'Digital marketing spend among Gravesend businesses is minimal. A small number of hospitality businesses run social campaigns, and some professional services invest in Google Ads, but the broader market is largely uncontested. The diverse community is almost completely untargeted by paid digital campaigns. Advertising costs in Gravesend remain lower than in nearby London-facing markets, creating strong return on investment for businesses willing to invest.',
  'We build Gravesend campaigns around audience segmentation. Commuter-targeted Google Ads run during travel hours with messaging about local convenience and quality. Social campaigns targeting the diverse community use culturally relevant creative and appropriate platform selection. Lifestyle campaigns showcase Borough Market and riverside experiences on Instagram. Every campaign is measured against real business outcomes: enquiries, footfall, and revenue.',
  '{"population": 75000, "business_districts": ["Gravesend High Street", "Borough Market", "Riverside", "Ebbsfleet area"], "key_fact": "Complex audience segmentation across commuters, diverse community, and new residents requiring tailored campaigns"}',
  '[{"title": "Untargeted Gravesend campaigns wasting budget on wrong audiences", "description": "A Gravesend business running generic Google Ads or Facebook campaigns without audience segmentation reaches everyone and resonates with no one. The commuter needs different messaging than the local family. The diverse community responds to different creative than new residents. Without segmentation, budget is spread thin across audiences with low relevance."}, {"title": "Diverse community completely untouched by paid digital marketing", "description": "Significant segments of Gravesend''s diverse population are not targeted by any local digital advertising. Businesses that could serve these communities profitably are invisible to them online. This represents one of the largest untapped advertising opportunities in north Kent."}, {"title": "No remarketing for Gravesend website visitors who browse but do not convert", "description": "Hundreds of Gravesend residents visit local business websites monthly without converting. A commuter researches during their Ebbsfleet journey but does not commit. Without remarketing campaigns following these visitors across Google and social media, every unconverted visitor is lost permanently to competitors."}]',
  '[{"title": "Audience-segmented campaigns for Gravesend''s diverse market", "description": "We build separate campaign streams for each Gravesend audience segment. Commuter-timed Google Ads with convenience messaging. Culturally targeted social campaigns reaching the diverse community. Lifestyle content campaigns for Borough Market visitors. Each segment receives tailored messaging on the platforms they use, maximising relevance and conversion."}, {"title": "Community-specific advertising reaching underserved Gravesend audiences", "description": "We research and target the specific online behaviours and platform preferences of Gravesend''s diverse community segments. Culturally appropriate creative, relevant language options, and platform selection that matches actual usage patterns. Your business becomes visible to audiences that no competitor is currently reaching."}, {"title": "Commuter-timed remarketing converting Ebbsfleet browsers", "description": "Website visitors who browsed during their commute see targeted follow-up ads on Facebook, Instagram, and Google. The tradesperson researched on the morning train appears in the commuter''s social feed that evening. Remarketing converts Gravesend''s concentrated browsing sessions into customers over the following days."}]',
  '[{"question": "How should I segment my Gravesend digital marketing?", "answer": "We recommend separating campaigns by audience: Ebbsfleet commuters, established local residents, diverse community segments, and new arrivals. Each receives different messaging, creative, and platform targeting. This segmentation ensures every pound of your marketing budget reaches someone likely to become a customer."}, {"question": "Can digital marketing reach Gravesend''s diverse communities?", "answer": "Absolutely. We research the online behaviour and platform preferences of specific community segments in Gravesend. Culturally appropriate social advertising, community-relevant messaging, and appropriate platform selection connect your business with audiences that mainstream marketing approaches miss entirely."}, {"question": "How much should I spend on digital marketing in Gravesend?", "answer": "Gravesend''s low advertising competition means budgets go further than in nearby London-adjacent markets. Most businesses start effectively with a few hundred pounds monthly. We optimise spending across audience segments based on performance, ensuring maximum return on your investment."}, {"question": "How do I know my Gravesend campaigns are working?", "answer": "We provide monthly reporting showing how many enquiries, customers, and revenue each campaign segment generated. No vanity metrics. You see which Gravesend audiences responded best, what each lead cost, and where to adjust spending for better results next month."}]',
  'lead-gen'
)
ON CONFLICT (service_slug, town_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  local_context = EXCLUDED.local_context,
  competition_landscape = EXCLUDED.competition_landscape,
  success_approach = EXCLUDED.success_approach,
  local_stats = EXCLUDED.local_stats,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs,
  layout_variant = EXCLUDED.layout_variant;

-- 8. Gravesend × Workwear & Print
INSERT INTO public.local_content (service_slug, town_slug, intro_paragraph, local_context, competition_landscape, success_approach, local_stats, pain_points, solutions, faqs, layout_variant)
VALUES (
  'workwear-print',
  'gravesend',
  'Gravesend''s diverse, growing community sees your physical branding in contexts that few other Kent towns replicate. A branded van parked in a residential street is seen by a multicultural neighbourhood. Workwear-clad staff near Borough Market interact with locals, commuters, and visitors. Printed menus in a riverside restaurant are read by heritage tourists and Ebbsfleet workers alike. Your physical branding must communicate quality and professionalism across all of these audiences simultaneously. In Gravesend''s evolving market, where town centre regeneration is raising visual standards and commuter clients carry London expectations, the quality of your workwear, signage, and printed materials directly influences whether a prospect trusts your business or moves to a competitor. We produce workwear, print, and branded materials for Gravesend businesses that project professionalism in every context this diverse town presents.',
  'Gravesend''s physical branding environment spans the heritage riverside, the regenerating town centre, the diverse high street, and the residential borough stretching to Northfleet and beyond. Borough Market demands quality presentation from food and hospitality businesses. The riverside setting near Gravesend Pier creates a visual context where quality materials matter. Residential streets across the borough provide daily exposure for service vehicle branding. The growing retail and hospitality scene requires signage and print materials that match rising town centre standards.',
  'Workwear and print quality in Gravesend follows a familiar pattern: the few businesses that invest in professional materials stand out dramatically against a low-quality majority. The town centre regeneration is beginning to raise expectations, with new businesses arriving with contemporary branding that highlights the dated appearance of longer-established enterprises. The commuter demographic''s exposure to London brand standards amplifies this expectation gap.',
  'We produce Gravesend workwear and print materials that communicate professionalism across the town''s varied contexts. Van livery designed for maximum visibility on residential streets across the borough. Workwear that projects quality at doorsteps from Northfleet to the riverside. Print materials that meet the rising standards of the regenerating town centre. Every piece is designed to help your Gravesend business present consistently well regardless of where a customer encounters you.',
  '{"population": 75000, "business_districts": ["Gravesend High Street", "Borough Market", "Riverside", "Northfleet", "Ebbsfleet area"], "key_fact": "Regenerating town with rising visual standards and commuter clients expecting London-quality presentation"}',
  '[{"title": "Unbranded Gravesend trades losing trust in a diversifying market", "description": "A tradesperson working across Gravesham''s diverse neighbourhoods builds trust partly through professional presentation. In communities where word of mouth and visual trust signals are paramount, unbranded workwear and plain vehicles communicate nothing about quality or reliability. Professional branding opens doors that unmarked businesses find closed."}, {"title": "Borough Market hospitality presentation below regeneration standards", "description": "As Gravesend''s town centre regenerates, the visual standard for hospitality and retail is rising. Businesses near Borough Market with cheap menus, inconsistent signage, and poor-quality print materials look increasingly out of place alongside the contemporary design arriving with new investment."}, {"title": "Print materials failing commuter clients'' quality expectations", "description": "Professional service firms in Gravesend serving Ebbsfleet commuters hand out business cards, proposals, and branded materials that are compared against the polished corporate materials clients encounter in London. A low-quality business card from a Gravesend accountant undermines credibility before the first meeting begins."}]',
  '[{"title": "Professional workwear building trust across Gravesend''s communities", "description": "We supply quality branded workwear that projects professionalism at every Gravesend doorstep. Embroidered polo shirts, branded jackets, and durable workwear in quality fabrics. Your team looks professional whether they are working in Northfleet, near the riverside, or across the wider Gravesham borough."}, {"title": "Regeneration-standard print for Borough Market businesses", "description": "Menus, signage, promotional materials, and business stationery produced to the standard Gravesend''s regenerating town centre demands. Quality stocks, professional design, and durable finishes ensure your print materials enhance your business image and match the rising visual quality of the Borough Market area."}, {"title": "Van livery for borough-wide visibility in Gravesend", "description": "We design vehicle graphics for maximum impact across Gravesham''s residential streets. Bold, professional design with clear contact details that generate passive enquiries from every street you park on. Durable materials ensure your fleet looks professional through all weather conditions across the borough."}]',
  '[{"question": "What workwear is best for Gravesend trades working across diverse areas?", "answer": "We recommend quality embroidered polo shirts and branded jackets as the foundation. Clean, professional appearance builds trust universally across Gravesend''s diverse communities. We source comfortable, durable garments suited to working conditions across the borough, from residential properties to commercial sites."}, {"question": "Can you produce menus for my Gravesend restaurant?", "answer": "Yes. We design and produce restaurant menus, signage, and promotional materials to the standard the regenerating Borough Market and riverside area demands. Options range from single-sheet seasonal menus to premium bound presentations. Quality materials and professional design enhance your dining experience."}, {"question": "How quickly can I get branded workwear for my Gravesend team?", "answer": "Standard embroidered workwear orders take seven to ten working days from approved artwork. We coordinate sizes across your team to ensure everyone is kitted simultaneously. Popular base garments are held in stock to minimise delays. Rush services are available when needed."}, {"question": "Do you design van livery for Gravesend service businesses?", "answer": "Yes. We design vehicle graphics for everything from single vans to multi-vehicle fleets operating across Gravesham. We work with professional wrap installers and use durable materials. Full wraps, partial wraps, and vinyl decals are available to match your budget and visibility goals."}]',
  'operational'
)
ON CONFLICT (service_slug, town_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  local_context = EXCLUDED.local_context,
  competition_landscape = EXCLUDED.competition_landscape,
  success_approach = EXCLUDED.success_approach,
  local_stats = EXCLUDED.local_stats,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs,
  layout_variant = EXCLUDED.layout_variant;
