-- ============================================================
-- seed-industry-content-letting-agents.sql
-- Industry content for Letting Agents across all 11 services
-- Safe to re-run: uses ON CONFLICT ... DO UPDATE
-- ============================================================

-- 1. Letting Agents × Web Design
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'letting-agents',
  'web-design',
  'Letting agents face a unique digital challenge: your website must serve two entirely different audiences simultaneously. Tenants need to browse available properties, book viewings, and submit applications seamlessly. Landlords need to see evidence of professional management, transparent fee structures, and compelling reasons to switch from their current agent or self-management. Most letting agent websites fail at both — clunky property search tools frustrate tenants, while generic "why choose us" sections fail to convince landlords that this agency will protect their investment and maximise yield. Meanwhile, Rightmove and Zoopla dominate property search, making your own website feel redundant unless it offers something the portals cannot. We build letting agent websites that convert landlords through compelling property management content and provide tenants with a frictionless search-to-viewing experience that complements your portal listings.',
  'Your website is the primary tool for landlord acquisition — the highest-value activity in any letting agency. When a landlord searches for local letting agents, your site must instantly communicate professionalism, local market knowledge, and management capability. For tenants, a smooth property search and viewing booking experience reduces your admin burden and fills vacancies faster. A purpose-built letting agent website serves both audiences without compromise.',
  'We design letting agent sites with distinct landlord and tenant journeys. Landlord-facing pages feature rental yield data, management service breakdowns, and free valuation tools. Tenant-facing sections integrate with your property management software for real-time availability, online viewing bookings, and application submissions.',
  '[{"title": "Website cannot compete with Rightmove and Zoopla for tenant traffic", "description": "Letting agents struggle to drive tenant traffic to their own websites when Rightmove and Zoopla dominate property search. Without a clear value proposition beyond the portals — such as early access listings, detailed neighbourhood guides, or seamless application processes — your website becomes an afterthought for property seekers."}, {"title": "No dedicated landlord acquisition journey on the website", "description": "Most letting agent websites bury landlord content behind a single ''Landlords'' tab with generic promises. Without dedicated landing pages addressing specific landlord concerns — void periods, legal compliance, rent guarantees, property maintenance — the site fails to convert the prospects who represent your highest-value revenue stream."}, {"title": "Property listings not synced with management software", "description": "Manually updating website listings when properties become available or are let creates delays and inaccuracies. Tenants encountering properties marked as available that are already let lose trust, and your team wastes hours maintaining duplicate listing systems."}]',
  '[{"title": "Dual-journey design for landlords and tenants", "description": "We build letting agent websites with clearly separated landlord and tenant experiences. Landlords see rental yield calculators, management service breakdowns, compliance assurance content, and prominent free valuation calls-to-action. Tenants access fast property search, viewing booking tools, and streamlined application forms."}, {"title": "Landlord acquisition landing pages with conversion focus", "description": "Dedicated pages targeting specific landlord segments — first-time landlords, portfolio landlords, landlords switching agents, and self-managing landlords considering professional management — each address the specific concerns and motivations of that audience with tailored content and calls to action."}, {"title": "Property management software integration", "description": "We integrate your website with property management platforms like Arthur, Reapit, or Street.co.uk for real-time listing synchronisation. Properties appear and disappear automatically as availability changes, viewing slots update in real time, and tenant applications feed directly into your management workflow."}]',
  '[{"question": "Should our letting agent website focus on landlords or tenants?", "answer": "Both, but with strategic priority. Landlord acquisition drives long-term revenue, so landlord-facing content receives prominent positioning and dedicated conversion paths. Tenant-facing property search and application tools reduce your operational workload and fill vacancies faster, supporting the service quality that retains landlords."}, {"question": "Can the website integrate with our property management software?", "answer": "Yes. We integrate with most major letting agent platforms including Arthur, Reapit, Street.co.uk, and others. Property listings sync automatically, viewing availability updates in real time, and tenant applications flow directly into your management system without manual data entry."}, {"question": "How do we compete with Rightmove and Zoopla for website traffic?", "answer": "Your website should not try to replace the portals for general property search. Instead, it should offer what they cannot: detailed neighbourhood guides, early access to new listings, landlord-focused content, and a seamless application process. This drives direct traffic from landlords and engaged tenants who value the enhanced experience."}, {"question": "Can tenants book viewings directly through the website?", "answer": "Yes. We build online viewing booking systems that display available time slots synced with your team''s calendars. Tenants select a property, choose a convenient slot, and receive automatic confirmation. This reduces phone calls, eliminates scheduling conflicts, and provides a professional tenant experience."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 2. Letting Agents × SEO
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'letting-agents',
  'seo',
  'SEO for letting agents is a battle on two fronts: ranking for tenant property searches against the enormous domain authority of Rightmove, Zoopla, and OnTheMarket, and ranking for landlord acquisition searches where the competition is other local agents. The landlord front is where SEO delivers the highest ROI. When a landlord searches "letting agents in Maidstone" or "property management fees Kent," appearing above your competitors directly generates the instructions that grow your portfolio. On the tenant side, local SEO and neighbourhood content can capture searches the portals handle poorly — "pet-friendly rentals Canterbury" or "best areas to rent in Medway." A letting agent SEO strategy must prioritise landlord acquisition keywords while building a content moat around local property market expertise that the national portals cannot replicate. We build SEO campaigns for letting agents that focus on the searches that actually grow your managed portfolio and fill your properties faster.',
  'Letting agents who rely solely on portal listings for tenant traffic and word of mouth for landlord acquisition are ceding control of their growth to third parties. SEO delivers a direct pipeline of landlords actively searching for management services and tenants seeking properties in your area. Ranking for "letting agent" plus your location terms captures landlords at their highest point of intent, while local property market content builds the authority that sustains those rankings long-term.',
  'We prioritise landlord acquisition keywords — "letting agent [location]," "property management [area]," "landlord services [town]" — because these searches directly drive portfolio growth. Tenant-facing SEO focuses on hyper-local neighbourhood content and niche property type searches that Rightmove handles poorly, capturing traffic the portals miss.',
  '[{"title": "Rightmove and Zoopla dominating property search rankings", "description": "National property portals have enormous domain authority and sophisticated SEO operations. Letting agents attempting to rank for generic property search terms like ''flats to rent in [town]'' face near-impossible competition. Without a strategy targeting searches the portals handle poorly, your organic property search traffic will remain negligible."}, {"title": "Invisible for landlord acquisition searches", "description": "When landlords search for letting agents or property management services, the agencies appearing on page one capture the majority of new instructions. Without deliberate SEO targeting these high-value searches, your agency is invisible to landlords actively looking to appoint a new managing agent."}, {"title": "No local property market content building authority", "description": "Letting agents who publish no content about local rental market conditions, yield data, or area guides miss the opportunity to build topical authority that Google rewards with higher rankings. Competitors publishing regular market commentary steadily outrank agencies with static, content-thin websites."}]',
  '[{"title": "Landlord acquisition keyword domination", "description": "We build dedicated, optimised pages targeting every variation of landlord acquisition search terms for your area — letting agents, property management, landlord services, rental management, portfolio management. Each page addresses specific landlord needs and drives toward free valuation or consultation requests."}, {"title": "Local rental market content strategy", "description": "Regular publication of local rental market analysis — average yields by area, demand trends, regulatory updates, and neighbourhood rental guides — builds the topical authority that Google rewards with higher rankings. This content also demonstrates the market expertise that convinces landlords to instruct your agency."}, {"title": "Niche property search pages targeting portal gaps", "description": "We create content targeting property searches that Rightmove handles poorly: pet-friendly rentals, specific neighbourhood guides, property type specialists, and long-term let specialists. These long-tail searches generate tenant traffic directly to your site, bypassing portal dependency for engaged, qualified applicants."}]',
  '[{"question": "Can a letting agent really outrank Rightmove for property searches?", "answer": "For broad terms like ''flats to rent,'' no. But for specific local and niche searches — neighbourhood-specific queries, pet-friendly properties, particular property types — a well-optimised local letting agent site can absolutely outrank the portals. We focus on these winnable searches rather than fighting unwinnable battles."}, {"question": "How does SEO help with landlord acquisition?", "answer": "When landlords search for letting agents or property management services in your area, SEO determines whether your agency appears on the first page. We optimise for every variation of these searches, ensuring your agency is visible to landlords actively looking to instruct a new agent — the highest-value leads in the letting industry."}, {"question": "What content should a letting agent publish for SEO?", "answer": "Local rental market updates, yield analysis by area, landlord guides covering legal compliance and regulations, neighbourhood rental guides, and tenant advice content. This mix targets both landlord and tenant search intent while building the topical authority that sustains rankings long-term."}, {"question": "How long before SEO generates new landlord instructions?", "answer": "Landlord acquisition keywords typically show ranking improvements within eight to twelve weeks, with first-page positions for less competitive location terms often achieved within four to six months. The compounding nature of SEO means that results accelerate over time as your site builds authority through consistent content publication."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 3. Letting Agents × Lead Capture
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'letting-agents',
  'lead-capture',
  'The most valuable visitor to a letting agent''s website is a landlord considering professional management — and most of these visitors leave without identifying themselves. They browse your fees page, read a service description, perhaps check a few property listings, and then disappear to research competitors. Without lead capture mechanisms designed specifically for the letting industry, you have no way to follow up with these high-value prospects. Effective lead capture for letting agents means offering genuinely useful tools that landlords want to engage with: instant online property valuations, rental yield calculators, free landlord compliance checklists, and downloadable guides on topics like Section 21 changes or EPC regulations. For tenant-facing capture, property alert sign-ups and application pre-qualification forms keep prospective tenants engaged when no suitable property is currently available. We build lead capture systems for letting agents that convert anonymous website visitors into identifiable, contactable landlord and tenant prospects.',
  'Landlord acquisition is the growth engine of any letting agency, and most landlord prospects visit your website multiple times before making contact. Lead capture tools — property valuations, yield calculators, compliance guides — give landlords a reason to share their details early in the research process, allowing you to nurture them through to instruction. Without these mechanisms, you rely entirely on landlords picking up the phone, losing the majority who prefer to research privately.',
  'We build landlord-specific lead magnets: instant online rental valuations powered by local market data, rental yield calculators for investment landlords, and downloadable compliance guides covering current legislation. Each tool captures the landlord''s property details and contact information, feeding qualified leads directly into your CRM.',
  '[{"title": "Landlord prospects researching but not making contact", "description": "Landlords considering switching agents or moving to professional management visit multiple agency websites before deciding. Without a compelling reason to share their details — like a free property valuation or yield calculation — these high-value prospects remain anonymous and uncontactable during their critical decision period."}, {"title": "No lead magnets addressing current landlord concerns", "description": "Legislative changes, EPC requirements, selective licensing, and Section 21 reform create genuine anxiety among landlords. Letting agents who offer no downloadable guides, checklists, or tools addressing these specific concerns miss the opportunity to capture leads from landlords actively seeking expert guidance."}, {"title": "Tenant enquiries lost when no suitable property is available", "description": "Tenants who search your listings and find nothing suitable leave your site permanently. Without property alert registration or waiting list sign-ups, you cannot reconnect with these qualified tenants when a matching property becomes available, forcing you to restart marketing for every vacancy."}]',
  '[{"title": "Instant online rental valuation tool", "description": "A property valuation form captures the landlord''s address, property type, bedrooms, and condition, then provides an estimated rental value based on comparable local data. The landlord receives a useful valuation; you receive a qualified lead with full property details and contact information ready for follow-up."}, {"title": "Landlord compliance checklist and regulatory guides", "description": "Downloadable guides covering current landlord obligations — EPC requirements, gas safety regulations, deposit protection, licensing requirements — capture email addresses from concerned landlords. A follow-up email sequence demonstrates your compliance expertise and positions your agency as the safe choice for professional management."}, {"title": "Tenant property alert registration", "description": "When no suitable property is currently listed, tenants register their requirements — location, bedrooms, budget, move-in date — and receive automatic notifications when matching properties become available. This builds a waiting list of qualified tenants, reducing void periods when new properties come under management."}]',
  '[{"question": "What is the best lead magnet for attracting landlords?", "answer": "An instant online rental valuation consistently generates the highest volume and quality of landlord leads. Landlords are naturally curious about their property''s rental value, and providing this information in exchange for contact details creates a natural opening for follow-up discussions about management services."}, {"question": "How does the rental valuation tool work?", "answer": "The landlord enters their property address, type, bedrooms, and condition. The tool calculates an estimated rental value based on comparable local market data. They receive the valuation via email, and you receive their full property details and contact information as a qualified lead in your CRM."}, {"question": "Can lead capture help reduce void periods?", "answer": "Yes. Tenant property alert registrations build a pre-qualified waiting list of tenants actively seeking rentals in your area. When a new property comes under management, you can immediately notify matching tenants, often securing viewings and applications before the property even hits the portals."}, {"question": "How do captured landlord leads get followed up?", "answer": "Leads feed directly into your CRM with full property and contact details. An automated email sequence delivers relevant content — local market data, management service information, client testimonials — over the following weeks. Your team receives instant notifications for high-priority leads flagged for personal follow-up."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 4. Letting Agents × Business Automation
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'letting-agents',
  'business-automation',
  'Letting agents drown in process-driven admin: tenant referencing workflows, maintenance request coordination, landlord monthly statements, tenancy renewal reminders, compliance certificate tracking, and inspection scheduling. Each process involves multiple steps, multiple parties, and strict deadlines — and when any step is missed, the consequences range from unhappy landlords to legal non-compliance. Business automation for letting agents systematises these repetitive workflows so that nothing falls through the cracks. Tenancy renewals trigger automatically sixty days before expiry with landlord consultation and tenant notification. Gas safety certificates approaching expiry generate contractor bookings and landlord notifications. Maintenance requests from tenants are automatically logged, categorised, and routed to approved contractors with landlord approval workflows. These are not optional efficiency gains — they are the operational backbone that allows an agency to scale its managed portfolio without proportionally scaling its team.',
  'Letting agency profitability depends on managing more properties per staff member without sacrificing service quality. Every manual process — chasing landlords for maintenance approvals, tracking certificate expiry dates, sending renewal letters — consumes staff time that could be spent on landlord acquisition and relationship management. Automation handles the repetitive operational tasks, enabling your team to manage a larger portfolio while delivering faster, more consistent service.',
  'We automate the core letting agency workflows: tenancy renewal pipelines with landlord and tenant communication, compliance certificate tracking with automatic contractor booking, maintenance request triage and contractor dispatch, landlord reporting, and tenant communication sequences for move-in, mid-tenancy, and move-out.',
  '[{"title": "Compliance certificate tracking relying on spreadsheets", "description": "Gas safety, EPC, EICR, and other compliance certificates each have different expiry dates across every managed property. Tracking these in spreadsheets or relying on diary reminders leaves the agency exposed to missed renewals, putting landlords at legal risk and the agency at liability for non-compliance."}, {"title": "Tenancy renewals requiring manual coordination", "description": "Each tenancy renewal involves consulting the landlord on rent review, issuing new terms to the tenant, processing signed agreements, and updating records. With dozens of renewals cycling through each month, manual handling creates delays, missed deadlines, and inconsistent communication."}, {"title": "Maintenance requests lost between tenant, landlord, and contractor", "description": "Tenant maintenance reports that require landlord approval before contractor dispatch create multi-party communication chains. Without automated tracking, requests get stuck waiting for landlord responses, contractors are not chased for completion dates, and tenants are left waiting without updates."}]',
  '[{"title": "Automated compliance tracking and contractor booking", "description": "Every managed property''s compliance certificates are tracked with automated alerts triggering sixty days before expiry. The system notifies the landlord, books the approved contractor, confirms the appointment with the tenant, and records the renewed certificate — eliminating the risk of missed compliance deadlines entirely."}, {"title": "Tenancy renewal pipeline automation", "description": "Automated workflows trigger the renewal process ninety days before tenancy expiry: landlord rent review consultation, tenant renewal offer with updated terms, agreement processing, and record updates. Each step progresses automatically with escalation alerts if responses are delayed, ensuring no renewal falls through the cracks."}, {"title": "Maintenance request workflow with approval routing", "description": "Tenant maintenance reports are automatically logged, categorised by urgency, and routed to the landlord for approval with recommended contractor quotes. Approved requests trigger contractor booking, tenant notification, and completion tracking. Emergency maintenance bypasses approval for immediate dispatch."}]',
  '[{"question": "What letting agency processes can be automated?", "answer": "The highest-impact automations are compliance certificate tracking, tenancy renewal workflows, maintenance request management, landlord monthly reporting, tenant communication sequences, inspection scheduling, and arrears notification. We prioritise based on which processes consume the most staff time in your specific agency."}, {"question": "Will automation work with our existing property management software?", "answer": "Yes. We integrate with major letting platforms including Arthur, Reapit, Street.co.uk, Goodlord, and others. Automations are built to enhance your existing system rather than replace it, triggering workflows based on data already in your property management software."}, {"question": "How does automated compliance tracking prevent legal risk?", "answer": "The system monitors every certificate expiry date across your portfolio and triggers renewal workflows well in advance. If a landlord is unresponsive or a contractor appointment falls through, escalation alerts ensure your team intervenes before any certificate expires. This systematic approach eliminates the human error risk inherent in spreadsheet tracking."}, {"question": "Can automation handle the landlord approval process for maintenance?", "answer": "Yes. When a maintenance request requires landlord approval, the system sends the request with contractor quotes and recommended action. The landlord approves or queries via email or a portal. Approved requests automatically trigger contractor booking and tenant notification. Overdue approvals generate chase reminders."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 5. Letting Agents × Branding
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'letting-agents',
  'branding',
  'In a market where landlords choose between dozens of local agents and tenants encounter your brand on property boards, portal listings, and printed particulars, a letting agency''s brand identity is a core commercial asset. Your brand must simultaneously communicate professionalism to landlords trusting you with six-figure assets and approachability to tenants who will interact with your team throughout their tenancy. Most letting agents operate with branding that was current a decade ago — dated colour schemes, clip-art-style logos, and inconsistent presentation across their office frontage, property boards, website, and portal profiles. In a sector where trust is the product, visual inconsistency signals operational inconsistency. We create modern, authoritative letting agent brand identities that build landlord confidence, stand out on property boards across residential streets, and present a cohesive, trustworthy image at every touchpoint from portal listings to tenancy agreements.',
  'Letting agent branding directly affects landlord acquisition and tenant perception. Landlords compare agencies visually before engaging, and an outdated or inconsistent brand undermines your credibility regardless of service quality. Property boards on residential streets are seen by thousands of potential landlord and tenant prospects. Portal listing branding affects click-through rates against competing agents. Every visual touchpoint either builds or erodes the trust that underpins your entire business.',
  'We design letting agent brands that balance authority with approachability — professional enough to reassure landlords entrusting valuable assets, modern enough to appeal to younger tenant demographics. Every brand system is tested across property boards, portal listing headers, office signage, and printed tenancy documentation.',
  '[{"title": "Outdated branding undermining landlord confidence", "description": "Landlords entrusting properties worth hundreds of thousands of pounds judge agency professionalism through visual presentation. A dated logo, inconsistent colours across your website and office, and poorly designed property particulars signal that the agency may be equally dated in its management practices."}, {"title": "Property boards failing to generate brand recognition", "description": "Property boards are the most visible form of letting agent advertising, seen daily by residents across entire streets and neighbourhoods. Boards with faded colours, cluttered text, or poor design fail to build the brand recognition that generates landlord enquiries when board viewers consider professional management."}, {"title": "Inconsistent branding across portals, website, and printed materials", "description": "When a landlord sees one version of your brand on Rightmove, another on your website, and a third on your office window, it creates an impression of disorganisation. Tenants encountering different visual styles across property particulars, emails, and signage question whether the agency is professionally run."}]',
  '[{"title": "Authoritative brand identity for landlord confidence", "description": "We design brand systems that communicate the professionalism, stability, and expertise landlords need to see before entrusting their property. Clean, modern aesthetics with a carefully chosen colour palette project contemporary management practices while maintaining the gravitas appropriate to significant property assets."}, {"title": "High-impact property board design", "description": "Property boards designed for maximum street-level visibility: bold brand colours, legible typography, prominent contact details, and a design that stands out against competing agent boards on the same street. Our board designs build cumulative brand recognition across every neighbourhood you operate in."}, {"title": "Unified brand application across all touchpoints", "description": "We deliver complete brand guidelines ensuring perfect consistency across your website, portal listings, property boards, office signage, printed particulars, tenancy agreements, email templates, and social media profiles. Every touchpoint reinforces the same professional impression, building compound trust over time."}]',
  '[{"question": "How important is branding for a letting agent?", "answer": "Branding directly influences landlord acquisition — the primary growth driver for any agency. Landlords compare agents visually before engaging, and a modern, consistent brand signals professional management. Property boards build awareness across residential streets, and portal listing appearance affects click-through rates. Every visual element either builds or undermines trust."}, {"question": "Do you design property boards for letting agents?", "answer": "Yes. Property board design is a central element of our letting agent branding packages. We create board designs optimised for street-level visibility that stand out against competing agent boards, build brand recognition across your operating area, and present a contemporary, professional image."}, {"question": "Can you rebrand our portal listings to match the new identity?", "answer": "Yes. We prepare all assets needed for consistent portal presence including Rightmove, Zoopla, and OnTheMarket header images, logo files, and brand guidelines for listing photography. This ensures landlords and tenants encounter the same professional brand across every platform."}, {"question": "How long does a letting agent rebrand take?", "answer": "A complete letting agent rebrand — from initial strategy through logo design, colour system, typography, and application across boards, signage, portal assets, and document templates — typically takes four to six weeks. We phase implementation to minimise operational disruption, starting with digital assets and rolling out printed materials on schedule."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 6. Letting Agents × Social Media Setup
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'letting-agents',
  'social-media-setup',
  'Social media for letting agents serves a dual commercial purpose that most agencies completely overlook. For tenant acquisition, platforms like Facebook and Instagram showcase available properties with walkthrough videos and lifestyle content about your operating areas. For landlord acquisition — the far more valuable objective — LinkedIn and local business networks position your agency as a market authority, while community Facebook posts demonstrate local expertise and active management. Yet most letting agents either have no social presence or post sporadically with generic property listings that generate zero engagement. Setting up social media properly for a letting agency means creating distinct content strategies for landlord and tenant audiences, establishing branded templates for property showcases and market updates, and building a sustainable posting framework that your team can maintain alongside day-to-day agency operations. We set up and optimise letting agent social media with clear audience segmentation and content systems that drive both landlord instructions and tenant enquiries.',
  'Landlords increasingly research letting agents on social media before making contact, looking for evidence of active management, market knowledge, and professional operations. An agency with no social presence or dormant accounts raises questions about its viability and commitment. Regular social content demonstrating local market expertise, successful lets, and tenant satisfaction builds the confidence that converts researching landlords into instructing clients.',
  'We set up letting agent social accounts with dual content streams: landlord-focused content on LinkedIn and Facebook featuring market data, regulatory updates, and portfolio highlights; tenant-focused content on Instagram and Facebook showcasing available properties, area guides, and moving tips. Branded templates make consistent posting achievable.',
  '[{"title": "No social media presence despite managing local properties", "description": "Letting agents managing dozens of properties across residential areas have zero social media presence. Every successful let, satisfied tenant, and market insight goes unshared, while competitors who post consistently build the online authority and visibility that attracts new landlord instructions."}, {"title": "Social posts that only list available properties with no engagement", "description": "Agencies that use social media solely to post property listings generate minimal engagement. Without market commentary, landlord-relevant content, area guides, and behind-the-scenes management insights, their social presence feels like an automated feed rather than an active, knowledgeable agency."}, {"title": "No LinkedIn strategy for landlord acquisition", "description": "LinkedIn is the most effective platform for reaching professional landlords and property investors, yet most letting agents have minimal or no LinkedIn presence. Without thought leadership content, market analysis posts, and professional networking activity, agencies miss the highest-value audience on social media."}]',
  '[{"title": "Dual-audience social media profiles", "description": "We set up Facebook and Instagram for tenant-facing property showcases and community engagement, and LinkedIn for landlord-focused market commentary and professional positioning. Each platform has distinct content strategies, branded templates, and posting schedules aligned to its primary audience."}, {"title": "Property showcase templates for consistent listings", "description": "Branded templates for Instagram carousels, Facebook property posts, and story walkthroughs ensure every listing looks professional and consistent. Photo guidelines and video frameworks enable your team to create compelling property content quickly using smartphone cameras during routine property visits."}, {"title": "Market insight content calendar for landlord audience", "description": "A twelve-month content calendar includes local rental market updates, regulatory change summaries, yield analysis by area, and landlord advice content. These posts position your agency as a knowledgeable market authority on LinkedIn and Facebook, building the credibility that drives landlord instructions."}]',
  '[{"question": "Which social platforms are most important for letting agents?", "answer": "Facebook and Instagram are essential for property showcases and local community engagement with both tenants and landlords. LinkedIn is critical for landlord acquisition, particularly for reaching professional landlords and property investors. We set up all three platforms with distinct strategies for each audience."}, {"question": "How can social media help attract new landlords?", "answer": "Regular posts demonstrating local market knowledge — rental yield data, demand trends, regulatory updates — position your agency as the informed, authoritative choice. Case studies of successful lets, portfolio growth updates, and client testimonials build confidence in your management capabilities and generate landlord enquiries."}, {"question": "How often should a letting agent post on social media?", "answer": "We recommend four to five posts per week across platforms: two to three property showcases on Instagram and Facebook, one market insight post on LinkedIn, and one community or behind-the-scenes post. Branded templates and scheduled content make this achievable in under an hour per week."}, {"question": "Can property listings be posted automatically to social media?", "answer": "We can set up workflows that generate social media draft posts when new properties are added to your management software. Your team reviews and approves each post before publication, ensuring brand consistency while dramatically reducing the time needed to maintain a regular property showcase presence."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 7. Letting Agents × Digital Marketing
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'letting-agents',
  'digital-marketing',
  'Digital marketing for letting agents must address the fundamental asymmetry in the business: tenants are plentiful but each generates modest revenue, while landlord instructions are scarce but each generates recurring income for years. Most letting agent marketing budgets are disproportionately spent on tenant-facing portal subscriptions and property advertising, while landlord acquisition — the activity that actually grows the business — receives almost no targeted marketing investment. A properly structured letting agent digital marketing strategy allocates budget weighted toward landlord acquisition: Google Ads targeting "letting agent" and "property management" searches, Facebook campaigns reaching property owners in your area, and retargeting that keeps your agency visible to landlords throughout their research period. Tenant-facing spend is strategic and targeted — filling specific hard-to-let properties rather than paying portal premiums for enquiries on popular listings that would fill themselves. We build and manage digital marketing campaigns for letting agents that prioritise the landlord instructions driving long-term portfolio growth.',
  'Relying on Rightmove and Zoopla for tenant traffic and word of mouth for landlord growth leaves a letting agency at the mercy of portal pricing and referral inconsistency. Targeted digital marketing provides a controllable, measurable pipeline of landlord prospects actively searching for management services. For tenants, strategic campaigns fill specific vacancies faster, reducing void periods and demonstrating the proactive marketing that retains landlord confidence.',
  'We weight letting agent marketing budgets toward landlord acquisition — typically sixty to seventy percent of spend — targeting Google searches for management services, Facebook audiences matching landlord demographics, and LinkedIn campaigns reaching property investors. Tenant-facing campaigns target specific hard-to-let properties and niche segments.',
  '[{"title": "Marketing budget consumed by portal subscriptions with declining ROI", "description": "Letting agents spend thousands annually on Rightmove and Zoopla premium listings while receiving diminishing returns as portal competition increases. This tenant-focused spend generates enquiries for properties that would likely fill through standard listings, while landlord acquisition receives virtually no marketing investment."}, {"title": "No targeted marketing for landlord acquisition", "description": "The highest-value activity in any letting agency — winning new landlord instructions — typically receives the least marketing attention. Agencies depend on referrals and property board visibility rather than running targeted campaigns to reach landlords actively considering professional management."}, {"title": "Unable to measure return on letting agency marketing spend", "description": "Without proper tracking and attribution, agencies cannot determine which marketing activities generate landlord instructions and which waste budget. Portal spending, social media activity, and local advertising all proceed without clear evidence of what actually delivers new managed properties."}]',
  '[{"title": "Landlord acquisition campaigns across Google and Facebook", "description": "We run Google Ads targeting landlords searching for letting agents, property management services, and related queries in your area. Facebook campaigns use demographic and interest targeting to reach property owners. Both channels drive prospects to dedicated landlord landing pages optimised for valuation request conversions."}, {"title": "Strategic void reduction campaigns for specific properties", "description": "Rather than blanket portal spending, we run targeted campaigns for hard-to-let properties — specific ads reaching the right tenant demographic for each vacancy. This reduces void periods for challenging properties while allowing popular listings to fill through standard channels, optimising overall marketing efficiency."}, {"title": "Full attribution tracking from ad click to landlord instruction", "description": "Every marketing channel is tracked from initial click through to landlord instruction. Monthly reports show cost per landlord lead, cost per instruction, and portfolio growth directly attributable to marketing spend. This data enables continuous budget optimisation toward the channels delivering the best landlord acquisition ROI."}]',
  '[{"question": "How much should a letting agent spend on digital marketing?", "answer": "Most letting agents see strong results from a monthly budget of five hundred to fifteen hundred pounds, with the majority allocated to landlord acquisition campaigns. Given that a single new landlord instruction generates recurring management fees for years, the return on investment is substantial even with modest monthly spend."}, {"question": "Should we reduce portal spending to fund digital marketing?", "answer": "We recommend shifting budget gradually rather than cutting portal spend immediately. As direct landlord acquisition campaigns prove ROI and tenant-facing strategies reduce dependence on premium portal features, you can strategically reduce portal investment while maintaining or growing your pipeline."}, {"question": "Can digital marketing specifically target landlords in our area?", "answer": "Yes. Google Ads captures landlords actively searching for management services. Facebook targeting reaches homeowners in specific postcodes with property investment interests. LinkedIn targets professional profiles matching landlord and investor demographics. Each platform offers precise audience targeting for landlord acquisition."}, {"question": "How do you measure landlord acquisition from digital marketing?", "answer": "We track every touchpoint: ad clicks, landing page visits, valuation requests, phone calls, and ultimately landlord instructions. Monthly reporting shows exactly which campaigns, keywords, and platforms generated each landlord lead, enabling continuous optimisation toward the lowest cost per instruction."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 8. Letting Agents × Workwear & Print
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'letting-agents',
  'workwear-print',
  'A letting agent''s physical presence extends far beyond the office: property viewings, inspections, landlord meetings, check-ins, and contractor supervision all place your team in the public eye across residential neighbourhoods. Branded workwear ensures that every property visit reinforces your professional image, while printed materials — property particulars, landlord information packs, tenant welcome folders, and business cards — shape the perception of your agency at critical decision-making moments. When a landlord receives a property valuation presentation in a branded folder with professionally designed particulars, they are experiencing your brand promise in physical form. When a tenant receives a branded welcome pack at check-in, they are forming their first impression of the management relationship. Most letting agents underinvest in these physical touchpoints, presenting proposals in generic folders and sending staff to viewings in unbranded clothing. We provide letting agents with complete branded workwear, printed materials, and physical marketing assets that reinforce professionalism at every in-person interaction.',
  'Letting agents conduct dozens of property visits, viewings, and meetings each week in residential areas. Every in-person interaction is an opportunity to reinforce brand professionalism — or undermine it through inconsistent presentation. Branded workwear identifies your staff as professional representatives, printed particulars and proposals demonstrate attention to detail, and leave-behind materials generate future enquiries. Physical touchpoints carry disproportionate weight in building the trust that drives landlord instructions.',
  'We supply letting agent teams with professional branded workwear suitable for property viewings and client meetings — polo shirts, oxford shirts, softshell jackets, and lanyards. Printed materials include property particulars templates, landlord valuation presentation folders, tenant welcome packs, and branded stationery.',
  '[{"title": "Staff attending viewings and meetings without branding", "description": "Letting agents sending staff to property viewings, landlord meetings, and inspections in unbranded clothing miss every opportunity to reinforce their professional identity. Landlords and tenants cannot distinguish your representative from any other visitor, and the agency appears less established than branded competitors."}, {"title": "Property particulars and proposals presented informally", "description": "Landlord valuation proposals printed on plain paper and property particulars without consistent branding undermine the professional image your agency depends on. When competing against agents who present polished, branded documents, informal presentation costs you instructions and lets."}, {"title": "No branded materials to leave behind after viewings and visits", "description": "After property viewings, inspections, and landlord meetings, your team leaves no branded material that reinforces your agency''s presence. Business cards are often generic, and there is no branded information for tenants or landlords to reference when making their decision."}]',
  '[{"title": "Professional branded workwear for property-facing staff", "description": "We supply branded polo shirts, oxford shirts, and softshell jackets for viewing agents, property managers, and maintenance coordinators. Branded lanyards and name badges add a further layer of professionalism. All items are comfortable for active property visits while maintaining a polished appearance for landlord meetings."}, {"title": "Branded property particulars and presentation materials", "description": "Professional property particular templates with your branding, high-quality photography layouts, and consistent formatting across every listing. Landlord valuation presentations are delivered in branded folders with market data, fee structures, and service breakdowns that demonstrate the quality of your agency''s operations."}, {"title": "Tenant welcome packs and landlord onboarding folders", "description": "Branded tenant welcome packs containing property information, maintenance reporting procedures, and agency contact details create a positive first impression at check-in. Landlord onboarding folders with management agreements, compliance documentation, and key contact details reinforce the professional relationship from instruction onwards."}]',
  '[{"question": "What workwear is appropriate for letting agent staff?", "answer": "We recommend branded polo shirts for routine property visits and inspections, oxford shirts for landlord meetings and formal viewings, and softshell jackets for outdoor work and cold-weather visits. Branded lanyards with ID badges add security credibility for property access. All items are designed for comfort during active property work."}, {"question": "Can you produce branded property particulars templates?", "answer": "Yes. We design property particular templates that your team can populate with photography and details for each listing. Templates maintain consistent branding across all properties while allowing customisation for individual listings. We provide these in editable formats compatible with your current design software or management system."}, {"question": "Do you supply tenant welcome packs?", "answer": "Yes. We design and print branded tenant welcome packs including property-specific information sheets, maintenance reporting guides, agency contact details, and move-in checklists. These create a professional first impression at check-in and provide tenants with essential information in a branded format."}, {"question": "How quickly can branded materials be produced?", "answer": "Workwear orders typically take seven to ten working days. Printed materials including property particulars, presentation folders, and welcome packs are produced within five to seven working days. Rush orders can often be accommodated for urgent requirements. We recommend keeping standard stock levels to avoid running out."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 9. Letting Agents × AI Chatbots
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'letting-agents',
  'ai-chatbots',
  'Letting agents handle a relentless volume of repetitive enquiries: tenants asking about property availability, viewing times, application requirements, and maintenance reporting; landlords asking about fees, services, market conditions, and their current property status. Each enquiry demands a timely response, and delayed replies cost you tenants to faster-responding agents and landlords to competitors who seem more attentive. An AI chatbot built for letting agents handles both audience types intelligently. For tenants, it answers property availability questions in real time, books viewings from your team''s calendar, explains application requirements, and captures details for the waiting list when no suitable property is listed. For landlords, it provides information about your management services, captures property details for free valuation requests, and answers preliminary questions about fees, compliance support, and management processes. We build AI chatbots specifically trained on letting agency operations that reduce your team''s repetitive workload while ensuring every visitor receives an instant, helpful response.',
  'Letting agents lose tenant leads to faster-responding competitors and landlord prospects to agencies that seem more attentive. An AI chatbot provides instant responses to both audiences around the clock: booking viewings for tenants at eleven o''clock at night and capturing landlord valuation requests on Sunday mornings. This responsiveness directly reduces void periods, accelerates landlord acquisition, and frees your team from the repetitive enquiries that consume their productive hours.',
  'Our letting agent chatbots handle dual audiences: tenant-facing conversations around property search, viewing bookings, and application guidance; landlord-facing conversations around services, fees, and valuation requests. The chatbot routes high-value landlord enquiries for priority follow-up while managing tenant interactions autonomously.',
  '[{"title": "Tenant enquiries overwhelming the team during office hours", "description": "Property availability questions, viewing requests, application queries, and maintenance reports flood letting agents during business hours. Staff spend the majority of their time answering repetitive questions rather than conducting viewings, managing properties, or acquiring new landlord instructions."}, {"title": "Landlord prospects visiting the website outside business hours", "description": "Landlords often research letting agents during evenings and weekends when your office is closed. Without an instant response mechanism, these high-value prospects move on to competitor websites, and by Monday morning they may have already booked valuations with rival agencies."}, {"title": "Slow response times losing tenants to competing agents", "description": "In a competitive rental market, tenants contact multiple agents simultaneously. The first agency to respond and book a viewing typically secures the application. Without instant response capability, your agency loses qualified tenants to competitors who reply faster, extending void periods and frustrating landlords."}]',
  '[{"title": "Instant tenant engagement with viewing booking", "description": "The chatbot answers property availability questions in real time using your current listings data, books viewings directly into your team''s calendar, explains application requirements and fees, and registers waiting list tenants when no suitable property is available — all without requiring staff intervention."}, {"title": "Landlord enquiry capture and qualification", "description": "Landlord visitors receive immediate information about your management services, fee structures, and approach. The chatbot captures property details for free valuation requests, asks qualifying questions about portfolio size and current management arrangements, and routes high-value prospects for priority personal follow-up."}, {"title": "Maintenance request logging and triage", "description": "Tenants can report maintenance issues through the chatbot at any time. The system captures details, photographs, and urgency level, logs the request in your management system, and provides the tenant with a reference number and expected response timeline — reducing phone calls and ensuring consistent documentation."}]',
  '[{"question": "Can the chatbot handle both tenant and landlord conversations?", "answer": "Yes. The chatbot identifies whether the visitor is a tenant or landlord based on their initial query and adjusts its responses accordingly. Tenant conversations focus on property search, viewings, and applications. Landlord conversations cover services, fees, and valuation requests. Each path is designed to maximise conversion for that audience."}, {"question": "Will the chatbot have access to our current property listings?", "answer": "Yes. We integrate the chatbot with your property management system so it can answer availability questions in real time, provide basic property details, and confirm whether specific properties are still available. This ensures tenants receive accurate, current information without staff involvement."}, {"question": "How does the chatbot handle emergency maintenance reports?", "answer": "The chatbot identifies emergency keywords — flood, leak, no heating, gas smell — and immediately provides relevant safety instructions while escalating the report to your emergency contact. Non-emergency maintenance is logged with full details and confirmation for standard response processing."}, {"question": "Can the chatbot book property viewings autonomously?", "answer": "Yes. The chatbot accesses your team''s viewing availability calendar and allows tenants to select convenient slots. Confirmation is sent to both the tenant and the viewing agent. If a viewing requires specific arrangements such as key collection, the chatbot includes these instructions automatically."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 10. Letting Agents × AI Content
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'letting-agents',
  'ai-content',
  'Letting agents need to publish two categories of content consistently: landlord-facing market analysis, regulatory updates, and investment guidance that demonstrates expertise and drives instructions; and tenant-facing area guides, renting advice, and property lifestyle content that builds search visibility and attracts applicants. Most agencies produce neither, because the team is consumed by day-to-day property management and has no time for content creation. AI-powered content creation for letting agents solves this by generating expert-level property market commentary, regulatory analysis, neighbourhood rental guides, and tenant advice — all calibrated to your local market, current legislation, and agency positioning. Every piece is optimised for the search terms landlords and tenants actually use, structured to drive conversions, and published consistently to build the content authority that compounds into lasting competitive advantage. We set up AI content systems for letting agents that maintain a steady stream of authoritative, locally relevant content without requiring your team to write a word.',
  'Content marketing for letting agents builds the topical authority that drives both landlord acquisition and tenant search visibility. Regular market commentary positions your agency as a knowledgeable local expert, attracting landlords who want informed management. Tenant-facing area guides and renting advice capture search traffic from prospective tenants researching locations. Without consistent content, your website stagnates while competitors publishing regularly accumulate the search authority that generates instructions and applications.',
  'Our AI content system produces letting-specific material: local rental yield analyses, legislative update summaries relevant to your landlords, neighbourhood guides with rental market context, and seasonal renting advice. Content references current regulations, local market data, and area-specific insights that demonstrate genuine letting expertise.',
  '[{"title": "No time for content creation alongside property management", "description": "Letting agency teams spend their days managing tenancies, conducting viewings, handling maintenance, and acquiring instructions. Writing blog posts about rental market trends or landlord regulations gets deprioritised indefinitely, leaving the website static and invisible for content-driven searches."}, {"title": "Competitor agencies building content authority", "description": "Forward-thinking letting agents publishing regular market analysis, regulatory updates, and area guides are accumulating search authority that compounds month by month. Without matching this output, your agency falls progressively behind in rankings for both landlord and tenant search terms."}, {"title": "Regulatory updates not being communicated to landlords", "description": "Frequent legislative changes — EPC requirements, Renters Reform Bill, deposit regulations, licensing changes — create opportunities to demonstrate expertise and add value to landlord relationships. Without content covering these updates, your agency misses the chance to position itself as an informed, proactive management partner."}]',
  '[{"title": "Local rental market analysis and commentary", "description": "AI generates monthly rental market reports for your operating area: average rents by property type, yield comparisons, demand trends, and forward-looking commentary. Published as blog posts and shared on social media, this content demonstrates the market knowledge that convinces landlords to trust your management recommendations."}, {"title": "Regulatory update content for landlord audience", "description": "When legislation changes affect landlords — EPC deadlines, licensing requirements, safety regulations, tenancy law updates — AI produces clear, practical summaries explaining the implications and your agency''s compliance support. This content builds trust, drives search traffic, and provides genuine value to your landlord client base."}, {"title": "Neighbourhood rental guides for tenant acquisition", "description": "Detailed area guides covering rental market conditions, local amenities, transport links, and lifestyle factors for each neighbourhood you operate in. These guides capture tenant search traffic, improve your site''s local search authority, and provide valuable content to share with prospective tenants during their property search."}]',
  '[{"question": "What types of content does AI produce for letting agents?", "answer": "Local rental market reports, landlord regulatory updates, neighbourhood guides, tenant advice articles, property listing descriptions, social media posts, email newsletter content, and Google Business Profile updates. The content mix is tailored to your primary business objectives — whether that is landlord acquisition, tenant attraction, or both."}, {"question": "Will AI content reflect current letting regulations accurately?", "answer": "Yes. The system is updated with current letting legislation and regulatory requirements. Content covering legal topics includes appropriate caveats and references to official guidance. We recommend a brief review of regulatory content before publication to ensure alignment with the most recent developments affecting your area."}, {"question": "How does content help with landlord acquisition specifically?", "answer": "Market analysis posts, yield data, and regulatory updates attract landlords searching for local market information. This content demonstrates the expertise that distinguishes a knowledgeable agency from a passive listing service. Landlords who read your market commentary before making contact arrive as warmer, more qualified prospects."}, {"question": "Can AI generate property listing descriptions?", "answer": "Yes. The AI produces compelling, unique property descriptions based on your property details, photographs, and area information. This saves considerable time compared to writing descriptions from scratch for each listing and ensures consistent quality across your entire portfolio."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;

-- 11. Letting Agents × AI Automation
INSERT INTO public.industry_content (industry_slug, service_slug, intro_paragraph, why_needed, approach_difference, pain_points, solutions, faqs)
VALUES (
  'letting-agents',
  'ai-automation',
  'Letting agency operations generate vast quantities of structured, repetitive decision-making: screening tenant applications against landlord criteria, categorising and routing maintenance requests by urgency and trade, generating rental market comparables for valuations, and producing landlord reports from management data. AI automation brings intelligent processing to these tasks, making decisions that currently require staff time but follow consistent, documentable logic. An AI system can pre-screen tenant applications against affordability ratios and landlord preferences before your team reviews them, categorise maintenance photographs to identify the correct trade and urgency level, generate comparative market analysis reports for landlord valuations in minutes rather than hours, and produce personalised monthly landlord reports summarising management activity, financial performance, and market conditions. These are not futuristic concepts — they are practical AI applications that transform letting agency efficiency today. We build AI automation systems for letting agents that handle the intelligent repetitive work consuming your team''s capacity.',
  'Letting agency profitability is constrained by the ratio of managed properties to staff members. Every hour spent on routine screening, categorisation, and reporting is an hour not spent on landlord acquisition, relationship management, and strategic growth. AI automation handles the high-volume intelligent tasks that bottleneck scaling — application screening, maintenance triage, market analysis, and reporting — enabling your team to manage a significantly larger portfolio without proportional headcount growth.',
  'We build AI automations for letting-specific workflows: tenant application pre-screening against landlord criteria, maintenance request image analysis for trade routing and urgency classification, automated comparable market analysis for rental valuations, and AI-generated monthly landlord management reports with portfolio performance insights.',
  '[{"title": "Tenant application screening consuming hours of staff time", "description": "Each tenant application requires verification of employment, income, references, and credit history against the landlord''s criteria. With multiple applications per property and dozens of properties turning over annually, manual screening consumes enormous staff hours that could be spent on higher-value activities."}, {"title": "Maintenance requests requiring manual categorisation and routing", "description": "Tenant maintenance reports arrive with varying levels of detail and urgency. Staff must interpret each request, identify the appropriate trade, assess urgency, and route to the correct contractor — a repetitive process that scales linearly with portfolio size and is prone to inconsistency."}, {"title": "Landlord reports generated manually each month", "description": "Monthly landlord statements and management reports require compiling financial data, maintenance summaries, market commentary, and property updates from multiple sources. Manual report generation for a portfolio of fifty or more properties consumes days of staff time each month."}]',
  '[{"title": "AI tenant application pre-screening", "description": "AI analyses tenant applications against landlord-specific criteria — income multiples, employment status, reference requirements — and provides a recommendation with supporting evidence. Your team reviews pre-screened applications with a clear summary, dramatically reducing screening time while maintaining thorough due diligence."}, {"title": "Intelligent maintenance request triage", "description": "AI analyses maintenance request descriptions and photographs to identify the required trade, assess urgency level, and route to the appropriate approved contractor. Emergency issues are flagged for immediate action, routine requests are batched for efficient processing, and tenants receive instant acknowledgement with expected timelines."}, {"title": "Automated landlord reporting with market context", "description": "AI compiles monthly landlord reports combining financial performance data, maintenance activity summaries, market condition commentary, and property-specific updates. Each report is personalised to the landlord''s portfolio and presented in a branded format — produced in minutes rather than hours for every property under management."}]',
  '[{"question": "Can AI really screen tenant applications accurately?", "answer": "AI pre-screening applies consistent criteria to every application — income verification against rent multiples, employment status checks, and reference requirement matching. It produces a recommendation with supporting evidence for your team to review, ensuring thorough screening while reducing processing time by up to seventy percent."}, {"question": "How does AI categorise maintenance requests?", "answer": "The system analyses the tenant''s description and any uploaded photographs to identify the maintenance category, required trade, and urgency level. A photograph of a dripping tap is identified as plumbing and non-urgent; a report of no heating in winter is flagged as heating and urgent. Accuracy improves continuously through use."}, {"question": "Will AI-generated landlord reports feel generic?", "answer": "No. Each report is personalised with the specific landlord''s property data, financial performance, maintenance history, and relevant market conditions for their property''s area. The AI generates unique commentary for each portfolio based on actual management data, creating reports that feel individually crafted."}, {"question": "What is the ROI of AI automation for a letting agency?", "answer": "Most agencies recover the investment within the first month through staff time savings alone. Application screening, maintenance routing, and report generation that previously consumed hours of staff time per week are reduced to minutes. The larger benefit is enabling portfolio growth without proportional headcount increases."}]'
)
ON CONFLICT (industry_slug, service_slug) DO UPDATE SET
  intro_paragraph = EXCLUDED.intro_paragraph,
  why_needed = EXCLUDED.why_needed,
  approach_difference = EXCLUDED.approach_difference,
  pain_points = EXCLUDED.pain_points,
  solutions = EXCLUDED.solutions,
  faqs = EXCLUDED.faqs;
